const names=['導入','グラフを見る','微分する','符号を調べる','増減表','2D / 3D','まとめ'];
const progress=document.querySelector('#progress'), cursor=document.querySelector('#cursor');
const tabs=document.querySelector('#tabs'), panels=[...document.querySelectorAll('.panel')]; let active=0,x=4;
names.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.onclick=()=>show(i);tabs.append(b)});
function show(i){active=i;panels.forEach((p,j)=>p.classList.toggle('active',i===j));[...tabs.children].forEach((b,j)=>b.classList.toggle('active',i===j));progress.style.width=`${i/(names.length-1)*100}%`;drawAll()};
document.querySelector('.next').onclick=()=>show(1);show(0);
const formulas=[['f(x) = x − 4√x','もとの関数を確認'],["f′(x) = 1 − 4· 1/(2√x)",'√x の微分公式を使う'],["f′(x) = 1 − 2/√x",'係数を整理する'],["f′(x) = (√x − 2)/√x",'通分して符号を見やすくする'],['√x > 0（x > 0）','符号は分子 √x−2 で決まる']];
const steps=document.querySelector('#steps');formulas.forEach((s,i)=>{let b=document.createElement('button');b.className='step'+(i===0?' active':'');b.innerHTML=`<b>0${i+1}</b><span class="formula">${s[0]}</span><small>${s[1]}</small>`;b.onclick=()=>{[...steps.children].forEach(e=>e.classList.remove('active'));b.classList.add('active')};steps.append(b)});
const range=document.querySelector('#xRange'), out=document.querySelector('#xOut');range.oninput=()=>{x=+range.value;update()};document.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{x=+b.dataset.x;range.value=x;update()});
const f=v=>v-4*Math.sqrt(v), d=v=>1-2/Math.sqrt(v); const sign=()=>Math.abs(x-4)<.015?0:x<4?-1:1;
function update(){out.value=x<.02?'0+':x.toFixed(2);let s=sign(),cls=s<0?'negative':s>0?'positive':'zero',word=s<0?'− 負':s>0?'＋ 正':'0';for(const id of ['numSign','allSign']){let e=document.querySelector('#'+id);e.className=cls;e.textContent=word}let st=document.querySelector('#state');st.className='state '+cls;st.textContent=s<0?"f′(x) < 0 → 減少中":s>0?"f′(x) > 0 → 増加中":"f′(x) = 0 → 停留点";cursor.style.left=`${x/25*100}%`;drawAll()}
function setup(c){const r=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==w*r||c.height!==h*r){c.width=w*r;c.height=h*r}let q=c.getContext('2d');q.setTransform(r,0,0,r,0,0);return[q,w,h]}
function graph(c){let[q,w,h]=setup(c),pad=42,X=v=>pad+v/25*(w-pad*1.5),Y=v=>h-pad-(v+5)/11*(h-pad*1.6);q.clearRect(0,0,w,h);q.strokeStyle='#29465d';q.lineWidth=1;for(let i=0;i<=25;i+=5){q.beginPath();q.moveTo(X(i),20);q.lineTo(X(i),h-pad);q.stroke();q.fillStyle='#7292a5';q.fillText(i,X(i)-4,h-18)}for(let y=-4;y<=6;y+=2){q.beginPath();q.moveTo(pad,Y(y));q.lineTo(w-20,Y(y));q.stroke();q.fillText(y,15,Y(y)+4)}q.strokeStyle='#62d9ff';q.lineWidth=3;q.shadowColor='#31caff';q.shadowBlur=12;q.beginPath();for(let v=0;v<=25;v+=.08)q[v?'lineTo':'moveTo'](X(v),Y(f(v)));q.stroke();q.shadowBlur=0;let tangent=d(x),y=f(x);q.strokeStyle=sign()<0?'#ff5874':sign()>0?'#39e69a':'#ffd45b';q.lineWidth=2;q.beginPath();q.moveTo(X(Math.max(0,x-4)),Y(y+tangent*(Math.max(0,x-4)-x)));q.lineTo(X(Math.min(25,x+4)),Y(y+tangent*(Math.min(25,x+4)-x)));q.stroke();point(4,'#4b8dff',7);point(0,'#ffd45b',6);point(25,'#ffd45b',6);point(x,'#fff',7);function point(v,color,r){q.fillStyle=color;q.shadowColor=color;q.shadowBlur=18;q.beginPath();q.arc(X(v),Y(f(v)),r,0,7);q.fill();q.shadowBlur=0}}
function drawAll(){document.querySelectorAll('.graph').forEach(graph);document.querySelectorAll('.meter').forEach(e=>{let derivative=x<.02?'定義されない':d(x).toFixed(3);e.innerHTML=`<small>現在の点</small><strong>(${x.toFixed(2)}, ${f(x).toFixed(2)})</strong><small>接線の傾き f′(x)</small><b class="derivative">${derivative}</b><div class="status ${sign()<0?'negative':sign()>0?'positive':'zero'}">${sign()<0?'右下がり・減少':sign()>0?'右上がり・増加':'水平・停留'}</div>`});draw3d()}
const tc=document.querySelector('#threeCanvas');let yaw=-.55,pitch=.45,zoom=1,drag=null,lastDist=0;
function draw3d(){if(tc.classList.contains('hidden'))return;let[q,w,h]=setup(tc);q.clearRect(0,0,w,h);const proj=(a,b,z)=>{a=(a-12.5)/13;b=(b+.5)/7;let xx=a*Math.cos(yaw)-z*Math.sin(yaw),zz=a*Math.sin(yaw)+z*Math.cos(yaw),yy=b*Math.cos(pitch)-zz*Math.sin(pitch);return[w/2+xx*240*zoom,h*.58-yy*190*zoom]};const line=(pts,color,width=2)=>{q.strokeStyle=color;q.lineWidth=width;q.shadowColor=color;q.shadowBlur=width>3?14:0;q.beginPath();pts.forEach((p,i)=>q[i?'lineTo':'moveTo'](...proj(...p)));q.stroke();q.shadowBlur=0};line([[0,-5,0],[25,-5,0]],'#ff5874',8);line([[4,-5,0],[25,-5,0]],'#39e69a',8);line([[4,-5,-.05],[4,-5,.05]],'#ffd45b',13);let pts=[];for(let v=0;v<=25;v+=.12)pts.push([v,f(v),0]);line(pts,'#56d8ff',3);line([[x,-5,0],[x,f(x),0]],'#fff',2);[[0,'#ffd45b'],[4,'#5f9cff'],[25,'#ffd45b'],[x,'#fff']].forEach(([v,c])=>{let [a,b]=proj(v,f(v),0);q.fillStyle=c;q.shadowColor=c;q.shadowBlur=18;q.beginPath();q.arc(a,b,v===4?7:5,0,7);q.fill()});q.shadowBlur=0;q.fillStyle='#b5ccda';q.fillText('床面：赤 f′<0　黄 f′=0　緑 f′>0',18,h-18)}
document.querySelectorAll('.view').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');let is3=b.dataset.view==='3d';document.querySelector('#vizCanvas').classList.toggle('hidden',is3);tc.classList.toggle('hidden',!is3);drawAll()});
tc.onpointerdown=e=>{drag=[e.clientX,e.clientY];tc.setPointerCapture(e.pointerId)};tc.onpointermove=e=>{if(drag){yaw+=(e.clientX-drag[0])*.008;pitch+=(e.clientY-drag[1])*.006;drag=[e.clientX,e.clientY];draw3d()}};tc.onpointerup=()=>drag=null;tc.onwheel=e=>{e.preventDefault();zoom=Math.max(.55,Math.min(1.8,zoom-e.deltaY*.001));draw3d()};tc.addEventListener('touchmove',e=>{if(e.touches.length===2){let d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(lastDist)zoom=Math.max(.55,Math.min(1.8,zoom*d/lastDist));lastDist=d;draw3d()}},{passive:false});tc.addEventListener('touchend',()=>lastDist=0);window.onresize=drawAll;update();
