import {Canvas} from '@react-three/fiber'
import {Grid,Line,OrbitControls} from '@react-three/drei'
import {useMemo,useState} from 'react'
import katex from 'katex'
import 'katex/dist/katex.min.css'
import {ChevronLeft,ChevronRight,Home,Lightbulb,RotateCcw} from 'lucide-react'
import {extrema,orderedTriangle,value,vertices,type Point} from './math'

const tabs=['問題を見る','3つの不等式','領域Dを作る','x²+y²=k の意味','円を動かす','最小値を探す','最大値を探す','数式で確認','3D解析','現実世界','自由探究','確認問題']
function M({children,block=false}:{children:string,block?:boolean}){return <span className={block?'math block':'math'} dangerouslySetInnerHTML={{__html:katex.renderToString(children,{throwOnError:false,displayMode:block})}}/>}
const sx=(x:number)=>70+(x+1)*68, sy=(y:number)=>440-(y+1)*68
function Dot({p,label,color,pulse=false}:{p:Point,label:string,color:string,pulse?:boolean}){return <g className={pulse?'pulse':''}><circle cx={sx(p.x)} cy={sy(p.y)} r="8" fill={color}/><text className="point-label" x={sx(p.x)+11} y={sy(p.y)-11}>{label}</text></g>}
function Graph({radius=0,showCircle=true,enabled=[true,true,true],showD=true,focus}:{radius?:number,showCircle?:boolean,enabled?:boolean[],showD?:boolean,focus?:'H'|'A'}){
 const A={x:2,y:4},B={x:4,y:0},C={x:0,y:2},H={x:.8,y:1.6}; const rpx=radius*68
 return <div className="graph-wrap"><svg viewBox="0 0 610 500" role="img" aria-label="3本の直線、三角形の領域D、原点中心の円"><defs><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><clipPath id="plot"><rect x="2" y="2" width="606" height="485"/></clipPath></defs><g clipPath="url(#plot)">
 <rect width="610" height="500" fill="#071522"/>{[-1,0,1,2,3,4,5,6].map(n=><g key={n}><path d={`M${sx(n)} 0V500 M0 ${sy(n)}H610`} className="grid"/><text x={sx(n)+4} y={sy(0)+17}>{n}</text><text x={sx(0)+6} y={sy(n)-5}>{n}</text></g>)}<path d={`M0 ${sy(0)}H610M${sx(0)} 0V500`} className="axis"/>
 {enabled[0]&&<polygon className="half red" points={`0,0 610,0 610,${sy(7)} 0,${sy(-1)}`}/>} {enabled[1]&&<polygon className="half blue" points={`0,${sy(8)} 610,${sy(-4)} 610,500 0,500`}/>} {enabled[2]&&<polygon className="half green" points={`0,${sy(2.5)} 610,${sy(-2)} 610,0 0,0`}/>} 
 <path d={`M${sx(-1)},${sy(1)} L${sx(6)},${sy(8)}`} className="boundary redline"/><path d={`M${sx(-1)},${sy(10)} L${sx(6)},${sy(-4)}`} className="boundary blueline"/><path d={`M${sx(-1)},${sy(2.5)} L${sx(6)},${sy(-1)}`} className="boundary greenline"/>
 {showD&&<polygon className="domain" points={`${sx(A.x)},${sy(A.y)} ${sx(B.x)},${sy(B.y)} ${sx(C.x)},${sy(C.y)}`}/>} {showCircle&&radius>0&&<circle className="radius-circle" cx={sx(0)} cy={sy(0)} r={rpx}/>}<Dot p={{x:0,y:0}} label="O" color="#ffe28a" pulse/><Dot p={A} label="A (2, 4)" color="#ff5570" pulse={focus==='A'}/><Dot p={B} label="B (4, 0)" color="#45aaff"/><Dot p={C} label="C (0, 2)" color="#36e4c2"/>
 {(focus==='H'||Math.abs(radius-4/Math.sqrt(5))<.06)&&<><path className="perp" d={`M${sx(0)},${sy(0)}L${sx(H.x)},${sy(H.y)}`}/><path className="right-angle" d={`M${sx(.62)},${sy(1.24)}l12,-6 6,12`}/><Dot p={H} label="H (4/5, 8/5)" color="#53f28f" pulse/></>}
 </g><text x="570" y={sy(0)-8}>x</text><text x={sx(0)+8} y="22">y</text></svg></div>
}
function Guide(){return <section className="guide"><h3>この図の見方</h3><div><span>🔴 赤い直線：<M>x-y+2=0</M></span><span>🔵 青い直線：<M>2x+y-8=0</M></span><span>🟢 緑の直線：<M>x+2y-4=0</M></span><span>🟨 金色部分：3条件の共通部分 D</span><span>🟣 紫の円：<M>x^2+y^2=k</M></span><span>O：円の中心　H：最初の接点　A：最遠点</span></div></section>}
function supportsWebGL(){try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}}
class MaterialErrorBoundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{
 state={failed:false}
 static getDerivedStateFromError(){return{failed:true}}
 componentDidCatch(error:unknown){console.error('region-circle-radius runtime error',error)}
 render(){return this.state.failed?<section className="runtime-fallback"><h3>表示を安全に停止しました</h3><p>この表示で描画エラーが起きました。上のタブから別の学習項目へ移動できます。</p><p>3Dの場合は、2D表示を使って同じ内容を確認してください。</p></section>:this.props.children}
}
function ThreeD(){const[webgl]=useState(()=>supportsWebGL());if(!webgl)return <div className="runtime-fallback"><h3>この端末では3D表示を開始できませんでした</h3><p>ブラックアウトさせず、2Dの「円を動かす」から学習を続けられます。</p><Graph radius={4/Math.sqrt(5)} focus="H"/></div>;const tri=orderedTriangle();const lifted=tri.map(p=>[p.x,value(p)/3,p.y] as [number,number,number]);return <div className="three"><Canvas camera={{position:[8,8,10],fov:48}}><color attach="background" args={['#071522']}/><ambientLight intensity={1.2}/><pointLight position={[5,10,5]} intensity={30}/><Grid args={[14,14]} cellColor="#24445e" sectionColor="#507595"/>{Array.from({length:22},(_,i)=>{const rad=i*.27;return <Line key={i} points={Array.from({length:49},(_,j)=>{const t=j*Math.PI*2/48;return [rad*Math.cos(t),rad*rad/3,rad*Math.sin(t)] as [number,number,number]})} color="#315c7b" transparent opacity={.6}/>})}<mesh><bufferGeometry><bufferAttribute attach="attributes-position" args={[new Float32Array(lifted.flat()),3]}/></bufferGeometry><meshBasicMaterial color="#ffd65c" transparent opacity={.6} side={2}/></mesh><Line points={[...lifted,lifted[0]]} color="#ffe477" lineWidth={4}/><Marker p={[.8,16/15,1.6]} color="#53f28f" label="H  z=16/5"/><Marker p={[2,20/3,4]} color="#ff5570" label="A  z=20"/><OrbitControls makeDefault minDistance={5} maxDistance={25}/></Canvas><div className="three-legend"><span className="legend-h">● H　z=16/5（最小）</span><span className="legend-a">● A　z=20（最大）</span></div><p>ドラッグ：回転　／　ホイール・ピンチ：拡大縮小</p></div>}
function Marker({p,color,label}:{p:[number,number,number],color:string,label:string}){return <group position={p} userData={{label}}><mesh><sphereGeometry args={[.16,20,20]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={3}/></mesh></group>}

const derivations=[['STEP 1','3直線の共通部分が三角形 D。'],['STEP 2',String.raw`x^2+y^2=k\ とおく。`],['STEP 3',String.raw`O(0,0),\quad r=\sqrt{k}`],['STEP 4','最大値は原点から最も遠い点を考える。'],['STEP 5',String.raw`A(2,4):\quad k=2^2+4^2=20`],['STEP 6','最小値は原点から領域 D への最短距離。'],['STEP 7',String.raw`OH=\frac{|0+0-4|}{\sqrt{1^2+2^2}}=\frac4{\sqrt5}`],['STEP 8',String.raw`k=\left(\frac4{\sqrt5}\right)^2=\frac{16}{5}`],['STEP 9',String.raw`H\left(\frac45,\frac85\right)`]]
const qs=[['x²+y²=k はどんな図形？','原点中心、半径 √k の円。'],['k が大きくなると？','半径 √k が大きくなり、円が広がる。'],['なぜ直線への距離を考える？','最初の接点では、半径が辺に垂直になるから。'],['A(2,4) での値は？','2²+4²=20。'],['原点を含む領域の最小値は？','原点で 0。']]
export default function App(){const[tab,setTab]=useState(0),[radius,setRadius]=useState(2),[on,setOn]=useState([true,true,true]),[reveal,setReveal]=useState(0),[step,setStep]=useState(0),[abc,setAbc]=useState({a:2,b:8,c:4}),[answer,setAnswer]=useState<number|null>(null);const ex=useMemo(()=>extrema(abc.a,abc.b,abc.c),[abc]);const vv=vertices(abc.a,abc.b,abc.c);const touching=Math.abs(radius-4/Math.sqrt(5))<.06;const maxing=Math.abs(radius-Math.sqrt(20))<.06
 const nav=(n:number)=>{setTab(Math.max(0,Math.min(11,n)));scrollTo({top:0,behavior:'smooth'})}
 let content=<></>
 if(tab===0)content=<Panel title="問題129" lead="この領域の中で、原点から最も近い点と最も遠い点はどこだろう？"><div className="problem"><M block>{String.raw`\begin{cases}x-y+2\geqq0\\2x+y-8\leqq0\\x+2y-4\geqq0\end{cases}`}</M><p>を満たす <M>x,y</M> に対して、<M>x^2+y^2</M> の最大値・最小値と、そのときの <M>x,y</M> を求めよ。</p></div></Panel>
 if(tab===1)content=<Panel title="3つの不等式" lead="スイッチを切り替え、各境界線のどちら側が条件を満たすか観察しよう。"><div className="workspace"><div><Graph enabled={on} showD={on.every(Boolean)} showCircle={false}/><div className="toggles">{[['① x−y+2 ≧ 0','red'],['② 2x+y−8 ≦ 0','blue'],['③ x+2y−4 ≧ 0','green']].map((x,i)=><button className={on[i]?`on ${x[1]}`:''} onClick={()=>setOn(v=>v.map((q,j)=>j===i?!q:q))} key={i}>{on[i]?'ON':'OFF'}　{x[0]}</button>)}</div><Guide/></div><aside><h3>半平面を重ねる</h3><p>境界線上の点も含むので実線です。3色すべてに入る場所を探してみよう。</p></aside></div></Panel>
 if(tab===2)content=<Panel title="領域 D を作る" lead="3つの半平面の共通部分が、金色に光る三角形です。"><div className="workspace"><div><Graph showCircle={false}/><Guide/></div><aside><button className="primary" onClick={()=>setReveal(Math.min(3,reveal+1))}>交点を1つ求める</button>{reveal>0&&<M block>{String.raw`①,②:\ A(2,4)`}</M>}{reveal>1&&<M block>{String.raw`②,③:\ B(4,0)`}</M>}{reveal>2&&<M block>{String.raw`③,①:\ C(0,2)`}</M>}<p>2本ずつを等式として連立すると頂点が得られます。</p></aside></div></Panel>
 if(tab===3)content=<Panel title="x²+y²=k の意味" lead="値 k を、図形の大きさとして読み替えます。"><div className="formula-hero"><M block>{String.raw`x^2+y^2=k`}</M><ChevronRight/><M block>{String.raw`x^2+y^2=(\sqrt{k})^2`}</M><p>中心 <b>O(0,0)</b>、半径 <M>\sqrt{k}</M> の円</p><div><M>{String.raw`r=\sqrt{k}`}</M><M>{String.raw`k=r^2`}</M></div></div><Graph radius={2.4}/><Guide/></Panel>
 if(tab===4)content=<Panel title="円を動かす" lead="つまみを連続ドラッグして、円が領域に触れる瞬間を探そう。"><RadiusGraph radius={radius} setRadius={setRadius}/>{touching&&<div className="discovery">最初に領域 D へ触れた！ <b>ここが最小値</b></div>}<Guide/></Panel>
 if(tab===5)content=<Panel title="最小値を探す" lead="最短距離 OH は、辺 BC に垂直です。"><div className="workspace"><div><Graph radius={4/Math.sqrt(5)} focus="H"/><Guide/></div><aside className="result green-result"><M block>{String.raw`OH=\frac{|0+0-4|}{\sqrt{1^2+2^2}}=\frac4{\sqrt5}`}</M><M block>{String.raw`\sqrt{k}=\frac4{\sqrt5}`}</M><M block>{String.raw`k=\left(\frac4{\sqrt5}\right)^2=\frac{16}{5}`}</M><h2>最小値 <M>{String.raw`\frac{16}{5}`}</M></h2><p>そのとき <M>{String.raw`(x,y)=(\frac45,\frac85)`}</M></p></aside></div></Panel>
 if(tab===6)content=<Panel title="最大値を探す" lead="円を各頂点まで広げ、距離の2乗を比較しよう。"><RadiusGraph radius={radius} setRadius={setRadius} focus={maxing?'A':undefined}/>{maxing&&<div className="discovery red-result">領域 D で原点から最も遠い点：A(2,4)</div>}<div className="compare"><M>{String.raw`OA^2=2^2+4^2=20`}</M><M>{String.raw`OB^2=4^2=16`}</M><M>{String.raw`OC^2=2^2=4`}</M></div><h2>最大値 20　そのとき (x,y)=(2,4)</h2></Panel>
 if(tab===7)content=<Panel title="数式で確認" lead="図で発見したことを、9段階の論証にしよう。"><div className="steps"><small>{derivations[step][0]}　{step+1}/9</small><div>{derivations[step][1].includes('\\')?<M block>{derivations[step][1]}</M>:derivations[step][1]}</div><div><button onClick={()=>setStep(Math.max(0,step-1))}><ChevronLeft/>戻る</button><button onClick={()=>setStep(0)}><RotateCcw/>最初から</button><button className="primary" onClick={()=>setStep(Math.min(8,step+1))}>次へ<ChevronRight/></button></div></div></Panel>
 if(tab===8)content=<Panel title="3D解析" lead="2Dの『半径』を、3Dでは『高さ』として見ます。"><ThreeD/><div className="compare"><div><b>2D</b><M block>{String.raw`x^2+y^2=k`}</M><p>等高線は円</p></div><ChevronRight/><div><b>3D</b><M block>{String.raw`z=x^2+y^2`}</M><p>原点を底とする放物面</p></div></div><p>三角形 D を <M>{String.raw`(x,y)\mapsto(x,y,x^2+y^2)`}</M> で曲面へ持ち上げると、H が最低、A が最高になります。</p><button onClick={()=>nav(4)}>2Dへ戻る</button></Panel>
 if(tab===9)content=<Panel title="現実世界：基地局 O と移動可能領域 D" lead="距離の問題として、同じ数学的構造を見てみよう。"><div className="world"><Graph radius={2.8}/><div><h2>📡 基地局 O　　🤖 移動ロボット</h2><p>三角形 D はロボットが動ける許可区域です。</p><h3>基地局から最も近い位置は？</h3><h3>基地局から最も遠い位置は？</h3><M block>{String.raw`d^2=x^2+y^2`}</M><p>距離 d の2乗の最小・最大が、元の問題そのものです。</p><small>※ 現実を完全に再現するものではなく、数学的構造を理解するための模式例です。</small></div></div></Panel>
 if(tab===10)content=<Panel title="自由探究" lead="a・b・c を動かすと、領域と極値はどう変わる？"><div className="workspace"><div className="explore-graph"><DynamicGraph abc={abc}/>{(['a','b','c'] as const).map(key=><label key={key}>{key} = {abc[key].toFixed(1)}<input type="range" min="-2" max="10" step=".1" value={abc[key]} onChange={e=>setAbc({...abc,[key]:+e.target.value})}/></label>)}</div><aside><M block>{String.raw`x-y+a\geqq0`}</M><M block>{String.raw`2x+y-b\leqq0`}</M><M block>{String.raw`x+2y-c\geqq0`}</M><p>最小点 ({ex.min.x.toFixed(2)}, {ex.min.y.toFixed(2)}) / k={value(ex.min).toFixed(2)}</p><p>最大点 ({ex.max.x.toFixed(2)}, {ex.max.y.toFixed(2)}) / k={value(ex.max).toFixed(2)}</p></aside></div><div className="questions">{['領域が原点を含むと最小値はどうなる？','最も遠い点は必ず頂点になる？','円が辺ではなく頂点に最初に触れることはある？','領域を動かすと最小点 H はどう変化する？'].map(q=><p><Lightbulb/>{q}</p>)}</div></Panel>
 if(tab===11)content=<Panel title="確認問題" lead="円と距離の見方を、自分の言葉で確かめよう。"><div className="quiz">{qs.map((q,i)=><article key={q[0]}><b>{i+1}. {q[0]}</b><div><button onClick={()=>setAnswer(answer===i?null:i)}>ヒント</button><button className="primary" onClick={()=>setAnswer(i)}>解答を見る</button><button onClick={()=>setAnswer(null)}>もう一度考える</button></div>{answer===i&&<p>{q[1]}</p>}</article>)}</div></Panel>
 return <div className="app"><header><a href="../../"><Home/>教材一覧</a><div><small>数学Ⅱ · 図形と方程式・領域</small><h1>領域と円の半径</h1></div><b>REGION × RADIUS</b></header><nav className="tabs" aria-label="学習ステップ">{tabs.map((t,i)=><button className={tab===i?'active':''} onClick={()=>nav(i)} key={t}><span>{i+1}</span>{t}</button>)}</nav><main><MaterialErrorBoundary key={tab}>{content}</MaterialErrorBoundary><footer><button disabled={tab===0} onClick={()=>nav(tab-1)}><ChevronLeft/>前へ</button><span>{tab+1} / 12</span><button disabled={tab===11} className="primary" onClick={()=>nav(tab+1)}>次へ<ChevronRight/></button></footer></main></div>
}
function Panel({title,lead,children}:{title:string,lead:string,children:React.ReactNode}){return <section className="panel"><small>DISCOVER WITH CIRCLES</small><h2>{title}</h2><p className="lead">{lead}</p>{children}</section>}
function RadiusGraph({radius,setRadius,focus}:{radius:number,setRadius:(x:number)=>void,focus?:'A'}){return <div><Graph radius={radius} focus={focus}/><div className="slider"><label>円の半径 r = <b>{radius.toFixed(2)}</b><input aria-label="円の半径 r" type="range" min="0" max="5.2" step=".01" value={radius} onChange={e=>setRadius(+e.target.value)}/></label><M>{`k=r^2=${(radius*radius).toFixed(2)}`}</M><button onClick={()=>setRadius(4/Math.sqrt(5))}>最小に合わせる</button><button onClick={()=>setRadius(Math.sqrt(20))}>最大に合わせる</button></div></div>}
function DynamicGraph({abc}:{abc:{a:number,b:number,c:number}}){const v=vertices(abc.a,abc.b,abc.c),e=extrema(abc.a,abc.b,abc.c);return <div className="graph-wrap"><svg viewBox="0 0 610 500"><rect width="610" height="500" fill="#071522"/><path d={`M0 ${sy(0)}H610M${sx(0)} 0V500`} className="axis"/>{e.valid?<><polygon className="domain" points={Object.values(v).map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')}/><circle className="radius-circle" cx={sx(0)} cy={sy(0)} r={Math.sqrt(value(e.min))*68}/><circle className="radius-circle maxcircle" cx={sx(0)} cy={sy(0)} r={Math.sqrt(value(e.max))*68}/>{Object.entries(v).map(([k,p])=><Dot key={k} p={p} label={k} color="#5bd9ff"/>)}<Dot p={e.min} label="最小点" color="#53f28f" pulse/><Dot p={e.max} label="最大点" color="#ff5570" pulse/></>:<text x="305" y="250" textAnchor="middle" className="invalid-region-svg">共通領域なし：a・b・c を調整してください</text>}</svg></div>}
