import {describe,it,expect} from 'vitest';
import {Playback,TAU,sine,sineDerivative,converge,eSequence,secantSlope,cubic,cubicDerivative,rightRiemann,rectangleCount,motion,harmonic,geometry} from './math.js';
import {scenes,links} from './scenes.js';
import {parameters} from './render.js';
import katex from 'katex';
it('every displayed equation parses and derivatives retain superscript primes',()=>{for(const s of scenes)expect(()=>katex.renderToString(s.formula,{throwOnError:true})).not.toThrow();expect(scenes[16].formula).toContain('f^{\\prime}(a)');expect(scenes[26].formula).toContain('F^{\\prime}(x)')});
describe('cinematic playback',()=>{
 it('plays all 30 scenes once, finishes, and never runs past the end',()=>{const p=new Playback(scenes),visited=new Set([p.locate().index]);p.playing=true;for(let i=0;i<630;i++){p.tick(1);visited.add(p.locate().index)}expect([...visited]).toEqual(Array.from({length:30},(_,i)=>i));expect(p.time).toBe(630);expect(p.playing).toBe(false);p.tick(100);expect(p.time).toBe(630)});
 it('respects pause, all six speeds, seeks and chapter boundaries',()=>{for(const speed of [.5,.75,1,1.25,1.5,2]){const p=new Playback(scenes);p.speed=speed;p.playing=true;p.tick(10);expect(p.time).toBe(10*speed);p.playing=false;p.tick(20);expect(p.time).toBe(10*speed)}const p=new Playback(scenes);p.jump(16);expect(p.time).toBe(336);expect(p.locate().index).toBe(16);p.seek(21);expect(p.locate().index).toBe(1);p.seek(-10);expect(p.locate().index).toBe(0);p.seek(900);expect(p.locate().index).toBe(29)});
 it('has a complete, bounded narrative with local scene metadata',()=>{expect(scenes).toHaveLength(30);expect(new Set(scenes.map(s=>s.kind)).size).toBe(30);for(const s of scenes){expect(s.duration).toBeGreaterThanOrEqual(15);expect(s.duration).toBeLessThanOrEqual(30);expect([s.title,s.caption,s.formula,s.connection].every(Boolean)).toBe(true)}expect(links.some(([a,b])=>a==='積分'&&b==='回転体')).toBe(true)});
});
describe('mathematical connections',()=>{
 it('unit-circle projections generate the same sine/cosine values and period',()=>{for(let i=0;i<=100;i++){const t=i/100,theta=parameters(scenes[6],t,false,.5).angle;expect(Math.sin(theta)**2+Math.cos(theta)**2).toBeCloseTo(1,12);expect(sine(theta)).toBe(Math.sin(theta));expect(sine(theta+TAU)).toBeCloseTo(sine(theta),12)}expect(sine(1.2,1.7,2.3,.4)).toBeCloseTo(sine(1.2+TAU/2.3,1.7,2.3,.4),12)});
 it('sequence and e values approach their stated limits',()=>{let oldError=Infinity;for(const n of [1,2,5,10,100,1000]){const error=Math.E-eSequence(n);expect(error).toBeGreaterThan(0);expect(error).toBeLessThan(oldError);oldError=error}expect(eSequence(1000)).toBeCloseTo(Math.E,2);expect(converge(1000)-2).toBeCloseTo(.001,12);for(const n of [4,8,16,32])expect(geometry.geometricSum(n)).toBeLessThan(1)});
 it('secants approach the tangent and critical-point signs match extrema',()=>{let error=Infinity;for(const h of [1,.5,.1,.01,.001]){const slope=secantSlope(.5,h);expect(Math.abs(slope-1)).toBeLessThan(error);error=Math.abs(slope-1)}expect(cubicDerivative(-1.01)).toBeGreaterThan(0);expect(cubicDerivative(-.99)).toBeLessThan(0);expect(cubicDerivative(.99)).toBeLessThan(0);expect(cubicDerivative(1.01)).toBeGreaterThan(0);expect(cubic(-1)).toBeCloseTo(2/3,12);expect(cubic(1)).toBeCloseTo(-2/3,12)});
 it('right endpoint sums converge from above to the exact integral 1/3',()=>{let previous=Infinity;for(const n of [4,8,16,32,64,128]){expect(rightRiemann(n)).toBeGreaterThan(1/3);expect(rightRiemann(n)).toBeLessThan(previous);previous=rightRiemann(n)}expect(rightRiemann(128)-1/3).toBeLessThan(.004);expect(rectangleCount(0)).toBe(4);expect(rectangleCount(1)).toBe(128);expect(geometry.rotationVolume(0,1)).toBeCloseTo(Math.PI/3,12)});
 it('position, velocity, acceleration and sine derivatives agree numerically',()=>{const h=1e-5;for(let i=0;i<=30;i++){const t=i/10,m=motion(t),s=harmonic(t,1.7,2.3,.4);expect((motion(t+h).position-motion(t-h).position)/(2*h)).toBeCloseTo(m.velocity,7);expect((motion(t+h).velocity-motion(t-h).velocity)/(2*h)).toBeCloseTo(m.acceleration,7);expect((harmonic(t+h,1.7,2.3,.4).position-harmonic(t-h,1.7,2.3,.4).position)/(2*h)).toBeCloseTo(s.velocity,7);expect((harmonic(t+h,1.7,2.3,.4).velocity-harmonic(t-h,1.7,2.3,.4).velocity)/(2*h)).toBeCloseTo(s.acceleration,7);expect(s.acceleration).toBeCloseTo(-(2.3**2)*s.position,12);expect((sine(t+h,1.7,2.3,.4)-sine(t-h,1.7,2.3,.4))/(2*h)).toBeCloseTo(sineDerivative(t,1.7,2.3,.4),7)}});
});
