import {TAU,clamp,mix,smooth,sine,sineDerivative,converge,eSequence,secantSlope,cubic,cubicDerivative,rightRiemann,rectangleCount,motion,harmonic} from './math.js';
export const C={cyan:'#70e2f0',gold:'#ffd58a',blue:'#79aaff',green:'#70e2b1',red:'#ff7795',orange:'#ffb47c',dim:'#263f51',white:'#f1f8ff'};
const cycle=(p,turns=1)=>p*TAU*turns;
export function parameters(scene,p,explore,u,frequency=1,phase=0){
 const t=explore?u:p,kind=scene.param;
 return {t,angle:cycle(t,explore?1:2),radius:3-2*smooth(t),amplitude:.3+1.7*t,frequency,phase,n:Math.max(1,Math.round(1+99*t)),eN:[1,2,5,10,100,1000][Math.min(5,Math.floor(t*6))],h:10**(-3*t),approach:Math.max(.001,.9*(1-smooth(t))),x:-2+4*t,time:4*t,rectangles:rectangleCount(t),integralX:t,kind};
}
export class Renderer{
 constructor(canvas){this.canvas=canvas;try{this.g=canvas.getContext('2d')}catch{this.g=null}this.width=1200;this.height=675;this.scale=1;this.offset=[0,0];this.nodes=[];this.low=matchMedia('(max-width:700px)').matches||navigator.hardwareConcurrency<=4;this.stars=Array.from({length:this.low?70:130},(_,i)=>({x:((i*719+89)%1200),y:((i*347+17)%675),r:.4+(i%4)*.3}));}
 resize(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,this.low?1.25:1.75);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.dpr=dpr;this.compact=r.height<340&&r.width>r.height*1.5;this.scale=Math.min(r.width/1200,r.height/675);this.offset=[(r.width-1200*this.scale)/2,(r.height-675*this.scale)/2];}
 logical(clientX,clientY){const r=this.canvas.getBoundingClientRect();return[(clientX-r.left-this.offset[0])/this.scale,(clientY-r.top-this.offset[1])/this.scale];}
 text(str,x,y,color=C.white,size=20,align='center'){if(this.compact&&y>=530)return;const g=this.g;g.save();g.shadowBlur=0;g.fillStyle=color;g.textAlign=align;g.font=`${size}px system-ui,sans-serif`;g.fillText(str,x,y);g.restore();}
 line(points,color=C.cyan,width=2,glow=10,dashed=false){if(!points.length)return;const g=this.g;g.save();g.strokeStyle=color;g.lineWidth=width;g.shadowColor=color;g.shadowBlur=this.low?glow*.35:glow;g.lineJoin='round';g.lineCap='round';if(dashed)g.setLineDash([7,9]);g.beginPath();points.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.stroke();g.restore();}
 point(x,y,color=C.gold,pulse=0,r=5){const g=this.g;g.save();g.fillStyle=color;g.shadowColor=color;g.shadowBlur=this.low?8:22;g.beginPath();g.arc(x,y,r,0,TAU);g.fill();g.shadowBlur=0;g.strokeStyle=color;g.globalAlpha=.25;g.lineWidth=1;g.beginPath();g.arc(x,y,r+9+4*Math.sin(pulse),0,TAU);g.stroke();g.restore();}
 arrow(a,b,color=C.gold,width=2){this.line([a,b],color,width,10);const t=Math.atan2(b[1]-a[1],b[0]-a[0]);this.line([[b[0]-10*Math.cos(t-.45),b[1]-10*Math.sin(t-.45)],b,[b[0]-10*Math.cos(t+.45),b[1]-10*Math.sin(t+.45)]],color,width,7);}
 axes(domain=[-2.5,2.5],range=[-1.8,2.8],box=[240,245,950,510],labels=['x','y']){const [l,t,r,b]=box,X=x=>mix(l,r,(x-domain[0])/(domain[1]-domain[0])),Y=y=>mix(b,t,(y-range[0])/(range[1]-range[0]));for(let i=0;i<=8;i++){const x=mix(l,r,i/8);this.line([[x,t],[x,b]],C.dim,.5,0)}for(let i=0;i<=4;i++){const y=mix(t,b,i/4);this.line([[l,y],[r,y]],C.dim,.5,0)}const yy=Y(clamp(0,range[0],range[1])),xx=X(clamp(0,domain[0],domain[1]));this.arrow([l,yy],[r+15,yy],'#7893a6',1);this.arrow([xx,b],[xx,t-12],'#7893a6',1);this.text(labels[0],r+34,yy+6,'#a3bccb',17);this.text(labels[1],xx-18,t-24,'#a3bccb',17);this.text('0',xx-15,yy+22,'#6a8ea0',14);return{X,Y,box,domain,range};}
 curve(axes,fn,color=C.cyan,reveal=1,width=3,sign=null){const points=[],N=this.low?130:230;for(let i=0;i<=N*clamp(reveal);i++){const x=mix(...axes.domain,i/N),y=fn(x);if(Number.isFinite(y))points.push([axes.X(x),axes.Y(y)]);}if(sign){for(let i=1;i<points.length;i++){const x=mix(...axes.domain,(i-.5)/N);this.line([points[i-1],points[i]],sign(x)>=0?C.green:C.red,width,8)}}else this.line(points,color,width,13);return points;}
 circle(cx,cy,r,angle=TAU,color=C.cyan){const count=Math.max(2,Math.round(90*angle/TAU));this.line(Array.from({length:count+1},(_,i)=>{const a=angle*i/count;return[cx+r*Math.cos(a),cy-r*Math.sin(a)]}),color,2.3,13);}
 frame(scene,p,options){const g=this.g;if(!g)return;g.setTransform(this.dpr,0,0,this.dpr,0,0);g.clearRect(0,0,this.canvas.width/this.dpr,this.canvas.height/this.dpr);g.translate(...this.offset);g.scale(this.scale,this.scale);this.nodes=[];for(const s of this.stars){g.globalAlpha=.15+.3*(.5+.5*Math.sin(options.time*.15+s.x));g.fillStyle='#9ed1e2';g.beginPath();g.arc(s.x,s.y,s.r,0,TAU);g.fill()}g.globalAlpha=1;
 const q=parameters(scene,p,options.explore,options.u,options.frequency,options.phase);const transition=options.next&&!options.explore?smooth((p-.9)/.1):0;
 g.save();const camera=options.reduced||options.explore?0:Math.sin(p*Math.PI)*.025;g.translate(600,365);g.scale(1+camera,1+camera);g.translate(-600,-365);g.globalAlpha=1-transition;const result=this.draw(scene,q,options);g.restore();
 if(transition>0){g.save();g.globalAlpha=transition;this.draw(options.next,parameters(options.next,0,false,.5),options);g.restore();const a=this.outline(scene,q),b=this.outline(options.next,parameters(options.next,0,false,.5));this.line(a.map((v,i)=>[mix(v[0],b[i][0],transition),mix(v[1],b[i][1],transition)]),C.gold,2,20);this.point(mix(a[0][0],b[0][0],transition),mix(a[0][1],b[0][1],transition),C.white,options.time,5);}
 return result;
 }
 outline(s,q){return Array.from({length:100},(_,i)=>{const t=i/99;if(['triangle','distance'].includes(s.kind)){const pts=s.kind==='triangle'?[[370,480],[790,480],[370,260],[370,480]]:[[340,470],[810,470],[810,255],[340,470]];const seg=Math.min(2,Math.floor(t*3)),u=t*3-seg;return[mix(pts[seg][0],pts[seg+1][0],u),mix(pts[seg][1],pts[seg+1][1],u)]}if(['circle','unit','trig','intro','network'].includes(s.kind)){const a=t*TAU,r=s.kind==='unit'?140*q.radius:170;return[600+r*Math.cos(a),365-r*Math.sin(a)]}return[240+t*710,370-115*Math.sin(t*TAU)];});}
 draw(s,q,o){const g=this.g,pulse=o.time*3.8,reveal=clamp(q.t*3+.03),point=(x,y,col=C.gold)=>this.point(x,y,col,pulse),a=q.angle;let live='';
 if(s.kind==='intro'){
  const center=[600,355],names=['数学Ⅰ','数学A','数学Ⅱ','数学B','数学C'];names.forEach((name,i)=>{const ang=-Math.PI/2+i*TAU/5,x=600+255*Math.cos(ang),y=345+133*Math.sin(ang);const t=clamp(q.t*3-i*.2);this.line([[x,y],[mix(x,center[0],t),mix(y,center[1],t)]],i%2?C.blue:C.cyan,1.3,10);point(x,y,C.cyan);this.text(name,x,y-23,'#c8e0eb',23)});point(...center);this.text(q.t>.28?'数学Ⅲ':'高校数学',600,363,C.white,48);if(q.t>.4){['極限','微分','積分'].forEach((name,i)=>{const x=450+i*150;this.arrow([600,387],[x,470],C.gold,1);this.text(name,x,502,C.gold,25)})}
 }else if(s.kind==='triangle'||s.kind==='distance'){
  const height=140+q.t*100,A=[360,480],B=[800,480],D=[s.kind==='triangle'?360:800,480-height];if(s.kind==='distance')this.axes([-1,5],[-1,4],[270,245,940,520]);this.line([A,B,D,A],C.cyan,3,17);[A,B,D].forEach((p,i)=>{point(...p);this.text(['A','B','C'][i],p[0]+(i===1?20:-20),p[1]+22,C.white,21)});this.line([[D[0],480-20],[D[0]+(D[0]===360?20:-20),480-20],[D[0]+(D[0]===360?20:-20),480]],C.dim,2,0);this.text(s.kind==='triangle'?'a':'x₂ − x₁',580,510,C.gold,23);this.text(s.kind==='triangle'?'b':'y₂ − y₁',D[0]+(D[0]===360?-45:60),480-height/2,C.blue,23);this.text(s.kind==='triangle'?'c':'AB',590,440-height/2,C.cyan,23);live=s.kind==='triangle'?'直角三角形\n2辺の平方和 = 斜辺の平方':'距離 = 横の差と縦の差の平方和の平方根';
 }else if(['circle','unit','trig','sin','cos','trigDerivative'].includes(s.kind)){
  const wave=['sin','cos','trigDerivative'].includes(s.kind),cx=wave?345:590,cy=365,r=s.kind==='unit'?145*(1+.22*(q.radius-1)):145;this.line([[cx-r-35,cy],[cx+r+35,cy]],C.dim,1,0);this.line([[cx,cy-r-30],[cx,cy+r+30]],C.dim,1,0);this.circle(cx,cy,r,s.kind==='circle'?Math.max(.02,TAU*reveal):TAU);const px=cx+r*Math.cos(a),py=cy-r*Math.sin(a);this.line([[cx,cy],[px,py]],C.gold,2,10);point(px,py);if(['trig','sin','cos','trigDerivative'].includes(s.kind)){this.line([[px,py],[px,cy]],C.blue,1.5,5,true);this.line([[px,py],[cx,py]],C.green,1.5,5,true);this.circle(cx,cy,35,(a%TAU),C.gold);this.text('cos θ',cx+55,cy+28,C.blue,18);this.text('sin θ',cx-47,py-12,C.green,18);this.text('P',px+19,py-14,C.gold,20)}else this.text(`r = ${s.kind==='unit'?q.radius.toFixed(2):'r'}`,cx+30,cy-38,C.gold,24);
  if(wave){const l=555,rgt=1055,X=x=>l+x/(TAU*2)*(rgt-l),Y=y=>cy-y*145;this.arrow([l-15,cy],[rgt+10,cy],C.dim,1.5);this.text('4π',rgt,cy+28,'#8ca6b6',16);const fn=s.kind==='cos'?Math.cos:Math.sin,phase=a,pts=Array.from({length:150},(_,i)=>{const x=phase*i/149;return[X(x),Y(fn(x))]});this.line(pts,C.cyan,3,14);point(X(phase),Y(fn(phase)));const projected=s.kind==='cos'?[px,cy]:[cx,py];this.line([projected,[X(phase),Y(fn(phase))]],C.gold,1,8,true);if(s.kind==='cos'||s.kind==='trigDerivative'){const fn2=s.kind==='cos'?Math.sin:Math.cos;this.line(Array.from({length:150},(_,i)=>{const x=phase*i/149;return[X(x),Y(fn2(x))]}),C.blue,1.8,8);this.text(s.kind==='cos'?'sin：位相を比べる':'cos：sin の傾き',820,535,C.blue,18)}live=`θ = ${(a%TAU).toFixed(2)} rad\nsin θ = ${Math.sin(a).toFixed(3)}\ncos θ = ${Math.cos(a).toFixed(3)}`;}
 }else if(s.kind==='period'){
  const ax=this.axes([0,4*Math.PI],[-2.2,2.2],[220,260,1030,500]);this.curve(ax,x=>sine(x,q.amplitude,q.frequency,q.phase),C.cyan,reveal);const period=TAU/q.frequency,start=Math.max(0,-q.phase/q.frequency);if(start+period<4*Math.PI){this.arrow([ax.X(start),ax.Y(-1.95)],[ax.X(start+period),ax.Y(-1.95)],C.gold);this.text('1周期 T',ax.X(start+period/2),ax.Y(-1.95)+24,C.gold,18)}this.arrow([ax.X(.3),ax.Y(0)],[ax.X(.3),ax.Y(q.amplitude)],C.blue);live=`A = ${q.amplitude.toFixed(2)}\nω = ${q.frequency.toFixed(1)}\nφ = ${q.phase.toFixed(2)} rad\nT = ${(TAU/q.frequency).toFixed(3)}`;
 }else if(['sequence','limitSequence','convergence','e'].includes(s.kind)){
  const phase=s.kind==='convergence'?Math.min(2,Math.floor(q.t*3)):0,n=s.kind==='e'?q.eN:q.n,domain=[0,s.kind==='e'?Math.max(6,n):Math.max(15,n)],range=s.kind==='e'?[1.5,3.2]:phase===1?[0,Math.max(n+4,15)]:phase===2?[-1.5,1.5]:[1.3,3.4],ax=this.axes(domain,range,[240,255,990,510],['n','aₙ']);let L=s.kind==='e'?Math.E:2,fn=s.kind==='e'?eSequence:phase===1?i=>i:phase===2?i=>(-1)**i:converge;const count=Math.min(n,70),indices=Array.from({length:count},(_,i)=>Math.max(1,Math.round(mix(1,n,i/Math.max(count-1,1)))));if(!phase){this.line([[ax.X(0),ax.Y(L)],[ax.X(domain[1]),ax.Y(L)]],C.gold,1.6,8,true);this.text(s.kind==='e'?'e = 2.71828…':'L = 2',ax.X(domain[1])+5,ax.Y(L)-15,C.gold,18,'right')}for(const i of indices)point(ax.X(i),ax.Y(fn(i)),i===n?C.gold:C.cyan);if(!phase){this.arrow([ax.X(n),ax.Y(fn(n))],[ax.X(n),ax.Y(L)],C.gold,1);this.text(`差 = ${Math.abs(fn(n)-L).toFixed(5)}`,600,537,C.gold,20)}if(s.kind==='convergence')this.text(['収束：2 + 1/n','発散：n → +∞','振動：(−1)ⁿ'][phase],600,224,[C.cyan,C.red,C.blue][phase],23);live=`n = ${n}\naₙ = ${fn(n).toFixed(6)}`;
 }else if(s.kind==='functionLimit'||s.kind==='continuity'){
  const ax=this.axes([-.1,2.1],[-.2,4.5],[240,245,980,510]);if(s.kind==='functionLimit'){this.curve(ax,x=>x*x,C.cyan,1);const h=q.approach;for(const t of [1-h,1+h]){point(ax.X(t),ax.Y(t*t));this.line([[ax.X(t),ax.Y(0)],[ax.X(t),ax.Y(t*t)]],C.blue,1,4,true)}point(ax.X(1),ax.Y(1),C.white);live=`左：x = ${(1-h).toFixed(3)}\n右：x = ${(1+h).toFixed(3)}\nf(x) → 1`;}else{const broken=q.t>.5;const fn=x=>Math.sin(x)+1+(broken&&x>=1?1.2:0);const split=1;for(const [lo,hi] of [[-.1,split-.003],[split,2.1]]){const pts=Array.from({length:90},(_,i)=>{const x=mix(lo,hi,i/89);return[ax.X(x),ax.Y(fn(x))]});this.line(pts,C.cyan,3,12)}const x=-.1+2.2*(q.t*2%1);point(ax.X(x),ax.Y(fn(x)));if(broken){this.circle(ax.X(1),ax.Y(Math.sin(1)+1),6,TAU,C.gold);point(ax.X(1),ax.Y(Math.sin(1)+2.2),C.red)}this.text(broken?'不連続：左右の極限が異なる':'連続：極限とその点の値が一致',600,540,broken?C.red:C.green,20);}
 }else if(s.kind==='secant'||s.kind==='derivative'){
  const ax=this.axes([-1.5,2.2],[-.5,4.5],[245,240,950,510]),x=.5,h=s.kind==='secant'?.5+q.t:q.h,m=secantSlope(x,h),A=[ax.X(x),ax.Y(x*x)],B=[ax.X(x+h),ax.Y((x+h)**2)];this.curve(ax,t=>t*t,C.cyan,1);this.line([[ax.X(-.7),ax.Y(x*x+m*(-.7-x))],[ax.X(1.6),ax.Y(x*x+m*(1.6-x))]],C.gold,3,20);this.line([[ax.X(-.7),ax.Y(x*x+2*x*(-.7-x))],[ax.X(1.6),ax.Y(x*x+2*x*(1.6-x))]],'#547181',1,0,true);point(...A,C.white);point(...B,C.gold);this.arrow(A,[B[0],A[1]],C.blue);this.arrow([B[0],A[1]],B,C.green);this.text('A',A[0]-22,A[1]+25,C.white,20);this.text('B',B[0]+20,B[1]-12,C.gold,20);live=`a = 0.5\nh = ${h.toFixed(3)}\n割線の傾き = ${m.toFixed(3)}\nf′(a) = 1`;this.text(s.kind==='derivative'?'h → 0：平均から、瞬間へ':'Δy / Δx：区間の変化率',630,542,C.gold,20);
 }else if(['slope','monotonic','extrema'].includes(s.kind)){
  const trig=s.kind==='slope',fn=trig?Math.sin:cubic,df=trig?Math.cos:cubicDerivative,ax=this.axes(trig?[0,TAU]:[-2.1,2.1],[-1.3,1.3],[220,265,990,500]),x=trig?q.t*TAU:q.x,m=df(x),y=fn(x);this.curve(ax,fn,C.cyan,1,3,trig?null:df);this.line([[ax.X(x-.55),ax.Y(y-.55*m)],[ax.X(x+.55),ax.Y(y+.55*m)]],Math.abs(m)<.03?C.gold:m>0?C.green:C.red,3,15);point(ax.X(x),ax.Y(y),Math.abs(m)<.03?C.gold:C.white);if(s.kind==='extrema')for(const [x,name,col] of [[-1,'極大',C.gold],[1,'極小',C.blue]]){point(ax.X(x),ax.Y(fn(x)),col);this.text(name,ax.X(x),ax.Y(fn(x))+(x<0?-24:32),col,24);this.line([[ax.X(x-.25),ax.Y(fn(x))],[ax.X(x+.25),ax.Y(fn(x))]],col,2,13)}live=`x = ${x.toFixed(3)}\nf′(x) = ${m.toFixed(3)}\n${Math.abs(m)<.03?'傾きが0付近':m>0?'増加：＋':'減少：−'}`;
 }else if(s.kind==='exponential'){
  const inverse=smooth((q.t-.4)/.2),ax=this.axes([-2.2,4.7],[-2.2,5.2],[240,245,990,510]);
  const samples=Array.from({length:180},(_,i)=>{const u=-2+3.5*i/179,v=Math.exp(u);return[ax.X(mix(u,v,inverse)),ax.Y(mix(v,u,inverse))]});
  this.line(samples,inverse<.5?C.cyan:C.blue,3,15);
  if(inverse>0&&inverse<1){this.line([[ax.X(-2),ax.Y(-2)],[ax.X(4.5),ax.Y(4.5)]],C.dim,1,0,true);this.text('座標 (x, y) を (y, x) へ',600,540,C.gold,20)}
  const u=-2+3.5*clamp(q.t<.4?q.t/.4:q.t>.6?(q.t-.6)/.4:1),v=Math.exp(u),x=mix(u,v,inverse),y=mix(v,u,inverse),m=inverse===1?1/v:v;
  point(ax.X(x),ax.Y(y));if(inverse===0||inverse===1){this.line([[ax.X(x-.3),ax.Y(y-.3*m)],[ax.X(x+.3),ax.Y(y+.3*m)]],C.gold,2.5,15);live=`x = ${x.toFixed(3)}\ny = ${y.toFixed(3)}\n傾き = ${m.toFixed(3)}`;this.text(inverse===1?'自然対数 ln x（底 e）':'指数 eˣ',600,535,inverse===1?C.blue:C.cyan,24)}else live='逆関数へ：座標を入れ替える';
 }else if(s.kind==='position'||s.kind==='acceleration'){
  const t=q.time,m=motion(t),stage=s.kind==='position'&&q.t<.35?'object':'graph';if(stage==='object'){const blend=smooth((q.t-.15)/.2);g.save();g.globalAlpha=1-blend;this.line([[250,400],[1010,400]],C.dim,2);this.arrow([250+m.position/8*760,370],[250+m.position/8*760+40*m.velocity,370],C.cyan,2);g.restore();g.save();g.globalAlpha=blend;const ax=this.axes([0,4],[0,8.5],[240,260,1000,510],['t','x(t)']);this.curve(ax,x=>x*x/2,C.cyan,1);g.restore();point(mix(250+m.position/8*760,ax.X(t),blend),mix(390,ax.Y(m.position),blend));}else if(s.kind==='acceleration'){const x=260+t/4*650;for(const [i,label,value,col]of [[0,'位置 x(t)',m.position,C.gold],[1,'速度 v(t)',m.velocity,C.cyan],[2,'加速度 a(t)',m.acceleration,C.blue]]){const y=285+i*90;this.line([[260,y],[990,y]],C.dim,1);point(x,y,col);this.text(`${label} = ${value.toFixed(2)}`,240,y+5,col,20,'right');this.arrow([x,y],[x+value*18,y],col,2)}this.line([[x,270],[x,478]],C.white,1,8,true);}else{const ax=this.axes([0,4],[0,8.5],[240,260,1000,510],['t','x(t)']);this.curve(ax,x=>x*x/2,C.cyan,1);const y=m.position;point(ax.X(t),ax.Y(y));this.line([[ax.X(t-.5),ax.Y(y-.5*m.velocity)],[ax.X(t+.5),ax.Y(y+.5*m.velocity)]],C.gold,3,17);this.text('接線の傾き = 速度',650,535,C.gold,22)}live=`t = ${t.toFixed(2)} s\nx = ${m.position.toFixed(3)} m\nv = ${m.velocity.toFixed(3)} m/s\na = 1 m/s²`;
 }else if(['rectangles','integral','fundamental','work'].includes(s.kind)){
  const work=s.kind==='work',fundamental=s.kind==='fundamental',ax=this.axes([0,work?4:1.05],[0,work?4.5:1.15],[260,265,990,510],work?['t','v(t)']:['x','y']);const n=q.rectangles,dx=1/n,end=fundamental?q.integralX:work?q.time:1,fn=work?x=>x:x=>x*x;
  if(fundamental||work){const pts=[[ax.X(0),ax.Y(0)],...Array.from({length:90},(_,i)=>{const x=end*i/89;return[ax.X(x),ax.Y(fn(x))]}),[ax.X(end),ax.Y(0)]];g.save();g.beginPath();pts.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.fillStyle='#70e2f02c';g.fill();g.restore();this.line(pts.slice(1,-1),C.gold,2,10);point(ax.X(end),ax.Y(fn(end)));}
  else{for(let i=1;i<=n;i++){const x=i*dx,y=x*x,top=ax.Y(y),bottom=ax.Y(0),rise=clamp(reveal*2-i/n+.5);g.save();g.fillStyle=s.kind==='integral'?'#70e2f035':'#79aaff2b';g.strokeStyle='#70e2f077';g.lineWidth=.7;g.shadowColor=C.cyan;g.shadowBlur=this.low?0:3;g.fillRect(ax.X(x-dx),bottom-(bottom-top)*rise,ax.X(dx)-ax.X(0), (bottom-top)*rise);g.strokeRect(ax.X(x-dx),bottom-(bottom-top)*rise,ax.X(dx)-ax.X(0), (bottom-top)*rise);g.restore();}live=`n = ${n}\nΔx = ${dx.toFixed(5)}\nSₙ = ${rightRiemann(n).toFixed(6)}\n正確な面積 = 1/3\n誤差 = ${(rightRiemann(n)-1/3).toFixed(6)}`;}
  this.curve(ax,fn,C.cyan,1);if(work){live=`t = ${end.toFixed(2)} s\n変位 = ${(end*end/2).toFixed(3)} m\n加速度1の積分 = ${end.toFixed(3)} m/s`;this.text('速度 v(t)=t の面積 → 変位',640,542,C.gold,21)}else if(fundamental){live=`x = ${end.toFixed(3)}\nF(x) = ${(end**3/3).toFixed(5)}\nF′(x) = ${(end*end).toFixed(5)}`;this.text('面積の増え方 = 曲線の高さ',650,542,C.gold,21)}else this.text('右端の高さを使う長方形近似：上から 1/3 へ',650,540,C.gold,19);
 }else if(s.kind==='spring'){
  const h=harmonic(a,q.amplitude,q.frequency,q.phase),cx=360,cy=350,r=120;this.circle(cx,cy,r,TAU);const px=cx+r*Math.cos(q.frequency*a+q.phase),py=cy-r*Math.sin(q.frequency*a+q.phase);point(px,py);this.line([[cx,cy],[px,py]],C.gold,2,10);this.line([[px,py],[620,py]],C.gold,1,5,true);const proj=this.projector(o),body=proj(1.6,h.position,0);this.line(Array.from({length:80},(_,i)=>{const t=i/79;return proj(1.6-.16*Math.cos(t*TAU*10),2.5+(h.position-2.5)*t,.16*Math.sin(t*TAU*10))}),C.cyan,2.8,12);g.save();g.fillStyle='#ffd58a';g.shadowColor=C.gold;g.shadowBlur=16;g.fillRect(body[0]-15,body[1]-15,30,30);g.restore();this.arrow(body,[body[0],body[1]-h.velocity*28],C.blue,2);this.arrow([body[0]+30,body[1]],[body[0]+30,body[1]-h.acceleration*22],C.orange,2);this.line(Array.from({length:120},(_,i)=>{const x=i/119*3;return proj(1.9+x,Math.sin(q.frequency*a-2*x)*q.amplitude,-.8)}),C.blue,2,10);live=`x = ${h.position.toFixed(3)}\nv = ${h.velocity.toFixed(3)}\na = ${h.acceleration.toFixed(3)}\na = −ω²x`;
 }else if(s.kind==='network'){this.network(q,o);}
 return live;
 }
 projector(o){return(a,b,z)=>{const yaw=o.yaw,pitch=o.pitch,X=a*Math.cos(yaw)-z*Math.sin(yaw),Z=a*Math.sin(yaw)+z*Math.cos(yaw),Y=b*Math.cos(pitch)-Z*Math.sin(pitch),scale=75*o.zoom/(1+.035*Z);return[630+X*scale,360-Y*scale];};}
 network(q,o){const names=['三平方','座標','円','単位円','三角関数','数列','極限','e','指数','対数','平均変化率','接線','微分','増減','極値','区分求積','積分','速度','加速度','単振動','波動','仕事','エネルギー','ベクトル','媒介変数','複素数','2次曲線','無限級数','回転体','曲線長','合成関数','高次導関数','整数','ユークリッド','相似','方べき','正規分布'],proj=this.projector({...o,yaw:o.yaw+(o.explore?0:q.t*.6)}),positions=new Map();for(let i=0;i<names.length;i++){const a=i*2.399963,r=1.35+2.7*Math.sqrt(i/names.length),x=r*Math.cos(a),y=1.25*Math.sin(a),z=r*Math.sin(a)*.62;positions.set(names[i],proj(x,y,z));}const focused=o.focus||['極限','微分','積分'][Math.min(2,Math.floor(q.t*3))];for(const[a,b]of o.links){const A=positions.get(a),B=positions.get(b);if(A&&B)this.line([A,B],a===focused||b===focused?C.cyan:'#274257',a===focused||b===focused?1.6:.5,a===focused||b===focused?9:0)}const neighbors=new Set(o.links.filter(([a,b])=>a===focused||b===focused).flatMap(([a,b])=>[a,b]));for(const[name,p]of positions){const active=neighbors.has(name);this.point(...p,name===focused?C.gold:active?C.cyan:'#426375',o.time*3,active?5:2.5);if(active||!this.low){this.text(name,p[0],p[1]-15,name===focused?C.gold:active?'#d6edf2':'#6d899a',active?19:13)}this.nodes.push({name,x:p[0],y:p[1]});}this.text('数学Ⅲ',600,365,C.white,38);this.text('極限 · 微分 · 積分',600,397,C.gold,18);this.text(o.explore?'点をタップして関係を読む · ドラッグで回転 · ピンチで拡大':'知識は、ひとつの宇宙へ。',600,535,'#9bb4c4',17);}
}
