import { useEffect, useMemo, useState } from 'react'
import { Box, ChevronLeft, Compass, Lightbulb, LineChart, RotateCcw, Sigma } from 'lucide-react'
import Scene3D from './Scene3D'
import { CENTER, LEFT, RIGHT, distanceFromCenter, verdict, type Verdict } from './math'

type Mode = 'line'|'space'|'graph'|'formula'
const tabs: {id:Mode; label:string; icon:typeof Box}[] = [{id:'line',label:'数直線で見る',icon:Compass},{id:'space',label:'3Dで見る',icon:Box},{id:'graph',label:'グラフで見る',icon:LineChart},{id:'formula',label:'式で解く',icon:Sigma}]
const statusText: Record<Verdict,string> = {inside:'○ 条件を満たす',boundary:'△ 境界（含まない）',outside:'× 条件を満たさない'}
const px = (n:number) => `${((n+7)/14)*100}%`

function NumberLine({x,state}:{x:number;state:Verdict}) { return <div className="visual-card"><div className="card-label">DISTANCE ON A NUMBER LINE <span>距離 = {distanceFromCenter(x).toFixed(2)}</span></div><div className="numberline"><div className="solution-band" style={{left:px(LEFT),width:`${6/14*100}%`}}/><div className="distance-line" style={{left:px(Math.min(x,CENTER)),width:`${Math.abs(x-CENTER)/14*100}%`}}/>{[-6,-4,-2,0,2,4,6].map(n=><i className="tick" style={{left:px(n)}} key={n}><b>{n}</b></i>)}{[LEFT,RIGHT].map((n,i)=><i className="endpoint" style={{left:px(n)}} key={n}><b>{i?'3−√2':'−3−√2'}</b></i>)}<i className="center" style={{left:px(CENTER)}}><b>中心 −√2</b></i><i className={`xpoint ${state}`} style={{left:px(x)}}><b>x = {x.toFixed(2)}</b></i></div><p className="explain"><strong>|x + √2| = {distanceFromCenter(x).toFixed(2)}</strong><span>x と −√2 の間の距離</span></p></div> }

function Graph({x,state}:{x:number;state:Verdict}) { const mapX=(n:number)=>40+(n+7)/14*760, mapY=(n:number)=>290-n/8*250; const pts=Array.from({length:141},(_,i)=>-7+i/10); const path=(arr:number[])=>arr.map((n,i)=>`${i?'L':'M'}${mapX(n)},${mapY(Math.abs(n-CENTER))}`).join(' '); return <div className="visual-card graph"><div className="card-label">ABSOLUTE VALUE GRAPH <span>y = |x + √2|</span></div><svg viewBox="0 0 840 340" role="img" aria-label="絶対値関数とyイコール3のグラフ"><defs><filter id="glow"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><line x1="40" y1={mapY(0)} x2="800" y2={mapY(0)} className="axis"/><line x1="40" y1={mapY(3)} x2="800" y2={mapY(3)} className="limit"/><text x="52" y={mapY(3)-10}>y = 3</text><path d={path(pts)} className="vline"/><path d={path(pts.filter(n=>n>=LEFT&&n<=RIGHT))} className="vline gold" filter="url(#glow)"/><line x1={mapX(LEFT)} y1={mapY(0)} x2={mapX(RIGHT)} y2={mapY(0)} className="graph-answer"/><circle cx={mapX(CENTER)} cy={mapY(0)} r="8" className="vertex"/><circle cx={mapX(x)} cy={mapY(distanceFromCenter(x))} r="10" className={`graph-dot ${state}`}/><text x={mapX(CENTER)+8} y={mapY(0)-15}>頂点 (−√2, 0)</text><text x={mapX(LEFT)-25} y={mapY(3)-14}>−3−√2</text><text x={mapX(RIGHT)-16} y={mapY(3)-14}>3−√2</text></svg><p className="explain"><strong>金色のV字が y = 3 より下</strong><span>その真下の x が、答えの区間です。</span></p></div> }

const steps=[['|x + √2| < 3','まず、絶対値の中に注目しよう。'],['|x − (−√2)| < 3','x + √2 は、x − (−√2) と同じ。'],['−√2 からの距離が 3 未満','絶対値は、2点の「距離」を表します。'],['−3 < x + √2 < 3','距離が3未満なら、−3と3の間にあります。'],['−3 − √2 < x < 3 − √2','3つの項すべてから √2 を引きます。'],['−3 − √2 < x < 3 − √2','これが最終解。端点は含みません！']]
function Formula({step,setStep}:{step:number;setStep:(n:number)=>void}) { return <div className="formula-layout"><div className="steps">{steps.map(([formula,note],i)=><button className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)} key={i}><small>STEP {i+1}</small><strong>{formula}</strong><span>{note}</span></button>)}</div><div className="formula-focus"><span>いまのポイント</span><b>{steps[step][0]}</b><p>{steps[step][1]}</p>{step===5&&<div className="boxed">−3 − √2 &lt; x &lt; 3 − √2</div>}<button onClick={()=>setStep((step+1)%steps.length)}>{step===5?'最初から':'次のステップへ →'}</button></div></div> }

export default function App(){const [mode,setMode]=useState<Mode>('line');const [x,setX]=useState(0);const [step,setStep]=useState(0);const [hint,setHint]=useState(false);const [pulse,setPulse]=useState(0);const state=useMemo(()=>verdict(x),[x]);useEffect(()=>{if(state==='inside')setPulse(p=>p+1)},[state]);return <main className="app"><header><a href="../../" className="back"><ChevronLeft/>教材ライブラリ</a><div className="eyebrow">MATHEMATICS I ・ 数と式 / 不等式</div><h1>絶対値の不等式を<br/><em>3Dで理解する</em></h1><div className="hero-formula">|x + √2| &lt; 3</div><p>絶対値って何だろう？　これはどこからどこまでの範囲を表しているのだろう？</p></header><nav className="tabs">{tabs.map(t=><button onClick={()=>setMode(t.id)} className={mode===t.id?'active':''} key={t.id}><t.icon/>{t.label}</button>)}</nav><section className="lab"><div className="lab-head"><div><small>INTERACTIVE LAB</small><h2>{tabs.find(t=>t.id===mode)?.label}</h2></div><div className={`verdict ${state}`}>{statusText[state]}</div></div>{mode==='line'&&<NumberLine x={x} state={state}/>} {mode==='space'&&<Scene3D x={x} state={state} pulse={pulse}/>} {mode==='graph'&&<Graph x={x} state={state}/>} {mode==='formula'&&<Formula step={step} setStep={setStep}/>}<div className="controller"><div className={`live-dot ${state}`}>x</div><label><span>点 x を動かそう <output>{x.toFixed(2)}</output></span><input type="range" min="-7" max="7" step="0.01" value={x} onChange={e=>setX(+e.target.value)}/><div><small>−7</small><button onClick={()=>setX(LEFT)}>左境界</button><button onClick={()=>setX(CENTER)}>中心</button><button onClick={()=>setX(RIGHT)}>右境界</button><small>7</small></div></label></div><div className="metrics"><div><small>中心</small><b>−√2 ≈ {CENTER.toFixed(2)}</b></div><div><small>距離 |x+√2|</small><b>{distanceFromCenter(x).toFixed(2)}</b></div><div><small>解の区間</small><b>−3−√2 &lt; x &lt; 3−√2</b></div></div></section><section className="insight"><div><Lightbulb/><h2>発見のヒント</h2><p>絶対値は、0からの距離だけではありません。<b>|x − a|</b> は「x と a の距離」。だから |x + √2| は x と −√2 の距離です。</p><button onClick={()=>setHint(!hint)}>ヒントを{hint?'閉じる':'見る'}</button>{hint&&<aside>半径3の光の中に x を入れてみよう。壁の上は距離がちょうど3。「&lt;」なので、そこは答えに入りません。</aside>}</div><div><RotateCcw/><h2>似た問題に挑戦</h2><p>中心と半径を頭に描いてみよう。</p><ul><li>|x − 2| &lt; 4</li><li>|x + 1| ≤ 2</li><li>|x − 3| &gt; 1</li></ul><button onClick={()=>{setX(-7);setTimeout(()=>setX(0),250);setMode('line')}}>もう一度アニメーション</button></div></section><footer><b>ABSOLUTE VALUE EXPLORER</b><span>距離が見えたら、不等式が動き出す。</span></footer></main>}
