const NS='http://www.w3.org/2000/svg';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function typeset(nodes){if(window.MathJax?.typesetPromise) window.MathJax.typesetPromise(nodes).catch(()=>{});}
$$('.tabs button').forEach(b=>b.onclick=()=>{ $$('.tabs button').forEach(x=>x.classList.toggle('active',x===b)); $$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab)); if(b.dataset.tab==='space') drawTerrain(); });
const bounds={xmin:-5,xmax:5,ymin:-3.3,ymax:3.3}, W=720,H=450;
function X(x){return (x-bounds.xmin)/(bounds.xmax-bounds.xmin)*W} function Y(y){return H-(y-bounds.ymin)/(bounds.ymax-bounds.ymin)*H}
function el(name,attrs={}){const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
function line(svg,x1,y1,x2,y2,cls){svg.append(el('line',{x1:X(x1),y1:Y(y1),x2:X(x2),y2:Y(y2),class:cls}))}
function path(svg,points,cls='curve-line'){svg.append(el('path',{d:points.map((p,i)=>`${i?'L':'M'} ${X(p[0])} ${Y(p[1])}`).join(' '),class:cls}))}
function label(svg,x,y,text,cls='svg-label'){const t=el('text',{x:X(x),y:Y(y),class:cls});t.textContent=text;svg.append(t)}
function base(svg){svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML='';for(let x=-4;x<=4;x++){line(svg,x,bounds.ymin,x,bounds.ymax,x===0?'axis':'gridline')}for(let y=-3;y<=3;y++){line(svg,bounds.xmin,y,bounds.xmax,y,y===0?'axis':'gridline')}label(svg,4.72,-.16,'x');label(svg,.1,3.05,'y')}
function point(svg,x,y,name='A',extra=''){svg.append(el('circle',{cx:X(x),cy:Y(y),r:7,class:`point ${extra}`}));label(svg,x+.16,y+.22,name)}
function tangent(svg,x,y,m){if(!Number.isFinite(m)){line(svg,x,bounds.ymin,x,bounds.ymax,'tangent-line');return}let x1=bounds.xmin,x2=bounds.xmax;line(svg,x1,y+m*(x1-x),x2,y+m*(x2-x),'tangent-line')}
function ellipsePts(a=Math.sqrt(12),b=2){return Array.from({length:181},(_,i)=>{const t=i/180*Math.PI*2;return[a*Math.cos(t),b*Math.sin(t)]})}
function bubble(svg,x,y,text){const g=el('g');const r=el('rect',{x:X(x)-42,y:Y(y)-37,width:84,height:27,rx:8,class:'slope-bubble'});const t=el('text',{x:X(x),y:Y(y)-19,'text-anchor':'middle',class:'svg-label'});t.textContent=text;g.append(r,t);svg.append(g)}
function drawEllipse(svg,x=3,y=1,showBubble=true){base(svg);path(svg,ellipsePts());tangent(svg,x,y,-x/(3*y));point(svg,x,y);if(showBubble)bubble(svg,x,y,`傾き ${(-x/(3*y)).toFixed(2)}`)}
// Introduction: secant tends to tangent on y=x²/3.
function drawIntro(){const svg=$('#introGraph');base(svg);const f=x=>x*x/3-1;path(svg,Array.from({length:151},(_,i)=>{let x=-4.5+i*.06;return[x,f(x)]}));const ax=1,ay=f(1),d=+$('#secantRange').value,bx=ax+d,by=f(bx);const m=(by-ay)/d;line(svg,-4.5,ay+m*(-4.5-ax),4.5,ay+m*(4.5-ax),'secant-line');tangent(svg,ax,ay,2/3);point(svg,ax,ay,'A');svg.append(el('circle',{cx:X(bx),cy:Y(by),r:6,class:'point-b'}));label(svg,bx+.12,by+.2,'B');$('#secantOut').value=d.toFixed(2)}
$('#secantRange').oninput=drawIntro;drawIntro();drawEllipse($('#exampleGraph'));
const steps=[
 ['STEP 1｜元の式','\\[\\frac{x^2}{12}+\\frac{y^2}{4}=1\\]'],
 ['STEP 2｜両辺を x で微分','\\[\\frac{2x}{12}+\\frac{2y}{4}y\' =0\\]'],
 ["STEP 3｜y' を解く",'\\[\\frac{x}{6}+\\frac{y}{2}y\'=0\\qquad y\'=-\\frac{x}{3y}\\]'],
 ['STEP 4｜A(3,1) を代入','\\[y\'=-\\frac{3}{3\\cdot1}\\]'],
 ['STEP 5｜傾きを決定','\\[m=-1\\]'],
 ['STEP 6｜点傾き式','\\[y-1=-1(x-3)\\]'],
 ['STEP 7｜完成','\\[\\boxed{y=-x+4}\\]']
];
let step=0;const stepBox=$('#steps');stepBox.innerHTML=steps.map((s,i)=>`<div class="math-step" data-i="${i}"><small>${s[0]}</small>${s[1]}</div>`).join('');
function showStep(){ $$('.math-step').forEach((n,i)=>{n.classList.toggle('visible',i<=step);n.classList.toggle('current',i===step)});$('#stepCount').textContent=`STEP ${step+1} / 7`;$('#stepBar').style.width=`${(step+1)/7*100}%`;$('#prevStep').disabled=step===0;$('#nextStep').textContent=step===6?'最初から ↺':'次へ →';$('#stepHint').textContent=step<3?'紫の曲線の式を微分して、接線の傾きを準備します。':step<5?'金色の点 A の座標を代入します。':'シアンの接線の式が完成します。';typeset([stepBox])}
$('#nextStep').onclick=()=>{step=step===6?0:step+1;showStep()};$('#prevStep').onclick=()=>{step=Math.max(0,step-1);showStep()};showStep();
$('#modeButton').onclick=()=>{$('[data-tab="explore"]').click()};
function fmt(n){if(Math.abs(n)<.005)return'0.00';return n.toFixed(2)}
function drawExplore(){const t=+$('#tRange').value,x=Math.sqrt(12)*Math.cos(t),y=2*Math.sin(t),m=-x/(3*y);drawEllipse($('#exploreGraph'),x,y);$('#tOut').value=`${t.toFixed(2)} rad`;$('#dynamicValues').innerHTML=`<div><small>接点 A</small><b>(${fmt(x)}, ${fmt(y)})</b></div><div><small>傾き m</small><b>${Number.isFinite(m)?fmt(m):'定義なし（垂直）'}</b></div>`;$('#dynamicEquation').innerHTML=Number.isFinite(m)?`\\[y-${fmt(y)}=${fmt(m)}(x-${fmt(x)})\\]`:`\\[x=${fmt(x)}\\]`;typeset([$('#dynamicEquation')])}
$('#tRange').oninput=drawExplore;$('#snapExample').onclick=()=>{$('#tRange').value=Math.atan2(.5,3/Math.sqrt(12));drawExplore()};drawExplore();
const cases={ellipse:{title:'(1) 楕円',feature:'閉じた曲線。上下の位置によって接線の傾きが変わります。',curve:()=>ellipsePts(Math.sqrt(8),Math.sqrt(2)),p:[2,-1],m:2/2,math:['\\[\\frac{x^2}{8}+\\frac{y^2}{2}=1\\]','\\[\\frac{x}{4}+yy\'=0\\Rightarrow y\'=-\\frac{x}{4y}\\]','\\[A(2,-1)\\Rightarrow m=\\frac12\\]','\\[\\boxed{y=\\frac12x-2}\\]']},hyperbola:{title:'(2) 双曲線',feature:'2本の枝をもつ曲線。接線は漸近線とは異なります。',curve:()=>{let a=[],b=[];for(let y=-3;y<=3;y+=.04){a.push([Math.sqrt(1+y*y),y]);b.push([-Math.sqrt(1+y*y),y])}return[a,b]},p:[Math.SQRT2,1],m:Math.SQRT2,math:['\\[x^2-y^2=1\\]','\\[2x-2yy\'=0\\Rightarrow y\'=\\frac{x}{y}\\]','\\[A(\\sqrt2,1)\\Rightarrow m=\\sqrt2\\]','\\[\\boxed{y=\\sqrt2x-1}\\]']},parabola:{title:'(3) 放物線',feature:'1方向へ開く曲線。軸上の頂点では接線が垂直です。',curve:()=>Array.from({length:151},(_,i)=>{let y=-3+i*.04;return[y*y/4,y]}),p:[1,2],m:1,math:['\\[y^2=4x\\]','\\[2yy\'=4\\Rightarrow y\'=\\frac{2}{y}\\]','\\[A(1,2)\\Rightarrow m=1\\]','\\[\\boxed{y=x+1}\\]']}};
function drawPractice(key){const c=cases[key],svg=$('#practiceGraph');base(svg);const curves=c.curve();if(Array.isArray(curves[0][0]))curves.forEach(q=>path(svg,q));else path(svg,curves);tangent(svg,...c.p,c.m);point(svg,...c.p);bubble(svg,...c.p,`m=${c.m.toFixed(2)}`);$('#practiceTitle').textContent=c.title;$('#practiceFeature').textContent=c.feature;$('#practiceMath').innerHTML=c.math.map((x,i)=>`<div><small>STEP ${i+1}</small>${x}</div>`).join('');typeset([$('#practiceMath')])}
$$('#practicePicks button').forEach(b=>b.onclick=()=>{$$('#practicePicks button').forEach(x=>x.classList.toggle('active',x===b));drawPractice(b.dataset.case)});drawPractice('ellipse');
const quiz=[{q:'楕円の A(3,1) での傾きは？',a:['1','−1','−3'],ok:1,why:"y'=-x/(3y) に (3,1) を代入します。"},{q:'傾き −1、点 (3,1) を通る接線は？',a:['y = −x + 4','y = x − 2','y = −x + 2'],ok:0,why:'点傾き式 y−1=−1(x−3) を整理します。'},{q:'座標 (x,y) を代入するのはどこ？',a:['微分する前だけ','導いた y\' の式','最後の答えだけ'],ok:1,why:"まず一般の点で y' を導き、その後に接点の座標を代入します。"}];let answers={};$('#quizList').innerHTML=quiz.map((q,i)=>`<article class="quiz-card"><h3>${i+1}. ${q.q}</h3>${q.a.map((a,j)=>`<button data-q="${i}" data-a="${j}">${a}</button>`).join('')}<p class="feedback"></p></article>`).join('');$$('.quiz-card button').forEach(b=>b.onclick=()=>{const i=+b.dataset.q,j=+b.dataset.a;answers[i]=j;const card=b.closest('.quiz-card');card.querySelectorAll('button').forEach((x,k)=>{x.classList.toggle('correct',k===quiz[i].ok);x.classList.toggle('wrong',k===j&&j!==quiz[i].ok)});card.querySelector('.feedback').textContent=(j===quiz[i].ok?'正解！ ':'もう一度確認。 ')+quiz[i].why;$('#score').textContent=`${Object.entries(answers).filter(([i,a])=>quiz[i].ok===a).length} / 3`});
// Lightweight projected wireframe terrain.
const canvas=$('#terrain'),ctx=canvas.getContext('2d');let yaw=-.65,pitch=.55,drag=null;
function proj(x,y,z,w,h){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);let X=x*cy-y*sy,Y=x*sy+y*cy;return[w/2+X*38,h*.72+(Y*sp-z*cp)*42]}
function drawTerrain(){const d=devicePixelRatio||1,w=canvas.clientWidth||600,h=w*.625;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.lineWidth=1;for(let y=-3;y<=3;y+=.5){ctx.beginPath();for(let x=-4;x<=4;x+=.12){let p=proj(x,y,x*x/12+y*y/4,w,h);x===-4?ctx.moveTo(...p):ctx.lineTo(...p)}ctx.strokeStyle='#24516d';ctx.stroke()}for(let x=-4;x<=4;x+=.5){ctx.beginPath();for(let y=-3;y<=3;y+=.12){let p=proj(x,y,x*x/12+y*y/4,w,h);y===-3?ctx.moveTo(...p):ctx.lineTo(...p)}ctx.strokeStyle='#1a435e';ctx.stroke()}ctx.lineWidth=3;ctx.strokeStyle='#9a77ff';ctx.beginPath();ellipsePts().forEach(([x,y],i)=>{let p=proj(x,y,1,w,h);i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.stroke();const A=proj(3,1,1,w,h),p1=proj(-1,5,1,w,h),p2=proj(5,-1,1,w,h);ctx.strokeStyle='#43e5da';ctx.beginPath();ctx.moveTo(...p1);ctx.lineTo(...p2);ctx.stroke();ctx.fillStyle='#ffd166';ctx.shadowBlur=16;ctx.shadowColor='#ffd166';ctx.beginPath();ctx.arc(...A,7,0,7);ctx.fill();ctx.shadowBlur=0}
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.008;pitch=Math.max(.15,Math.min(1.2,pitch+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY];drawTerrain()};canvas.onpointerup=()=>drag=null;window.addEventListener('resize',drawTerrain);drawTerrain();
window.addEventListener('load',()=>typeset(document.body));
