import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
// 円と座標は同じ平面に配置し、カメラだけを動かす。元のSVGは2Dの基準図として保持。
export function createPlaneView(stage,svg){
 let active=false,renderer,scene,camera,controls,texture,mesh,raf=0,pending=false,dirty=true,imageURL=null;
 const help=document.createElement('p');help.className='orbit-help';help.textContent='ドラッグ：回転 ／ ホイール・ピンチ：拡大 ／ 右ドラッグ・2本指：移動';help.hidden=true;stage.after(help);
 const reset=document.createElement('button');reset.textContent='視点を初期位置に戻す';reset.hidden=true;help.after(reset);
 function home(){camera.position.set(1.5,-3,7.2);camera.up.set(0,1,0);controls.target.set(0,0,0);controls.update();}reset.onclick=home;
 function init(){renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0b1422,1);stage.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,1,.1,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=18;controls.maxPolarAngle=Math.PI*.94;
 texture=new THREE.CanvasTexture(document.createElement('canvas'));texture.colorSpace=THREE.SRGBColorSpace;mesh=new THREE.Mesh(new THREE.PlaneGeometry(6.4,6.4*Number(svg.viewBox.baseVal.height)/640),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide,transparent:true}));scene.add(mesh);
 const border=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0x506e89}));scene.add(border);home();}
 // SVGの計算済みスタイルをテクスチャに保持し、ビルド後のCSSファイル名に依存しない。
 function updateTexture(){if(pending||!dirty)return;dirty=false;pending=true;const clone=svg.cloneNode(true);const originals=[svg,...svg.querySelectorAll('*')],copies=[clone,...clone.querySelectorAll('*')];originals.forEach((node,i)=>{const style=getComputedStyle(node);for(const key of ['fill','stroke','stroke-width','stroke-dasharray','font-family','font-size','font-weight','paint-order','opacity','stroke-linecap','stroke-linejoin'])copies[i].style.setProperty(key,style.getPropertyValue(key));copies[i].style.animation='none';copies[i].style.transform='none';});clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','1280');clone.setAttribute('height',String(svg.viewBox.baseVal.height*2));clone.style.transform='none';clone.style.visibility='visible';clone.style.position='static';clone.style.width='1280px';clone.style.height=String(svg.viewBox.baseVal.height*2)+'px';
 const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));imageURL=url;const img=new Image();img.onload=()=>{const canvas=texture.image;canvas.width=1280;canvas.height=svg.viewBox.baseVal.height*2;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0);texture.needsUpdate=true;URL.revokeObjectURL(url);imageURL=null;pending=false;};img.onerror=()=>{URL.revokeObjectURL(url);imageURL=null;pending=false;};img.src=url;}
 function render(){if(!active)return;const w=stage.clientWidth,h=w*svg.viewBox.baseVal.height/640;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();updateTexture();controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(render);}
 new MutationObserver(()=>{dirty=true;}).observe(svg,{childList:true,subtree:true});
 return {set(value){active=value;help.hidden=!value;reset.hidden=!value;if(value){try{if(!renderer)init();svg.style.transform='none';svg.style.position='absolute';svg.style.visibility='hidden';svg.style.pointerEvents='none';renderer.domElement.hidden=false;dirty=true;cancelAnimationFrame(raf);render();return true;}catch(error){active=false;help.textContent='この環境ではWebGLが使えません。2D図で操作できます。';reset.hidden=true;svg.style.position='';svg.style.visibility='';svg.style.pointerEvents='';if(renderer)renderer.domElement.hidden=true;return false;}}cancelAnimationFrame(raf);svg.style.position='';svg.style.visibility='';svg.style.pointerEvents='';svg.style.transform='none';if(renderer)renderer.domElement.hidden=true;return true;}};
}
