import {Canvas} from '@react-three/fiber'
import {Grid,Html,Line,OrbitControls} from '@react-three/drei'
import {useEffect,useMemo,useRef,useState} from 'react'
import {BookOpen,ChevronRight,Home,Maximize2,Pause,Play,RotateCcw,Search,SkipForward,ZoomIn,ZoomOut} from 'lucide-react'
import type {OrbitControls as OrbitControlsImpl} from 'three-stdlib'
import {formatValue,nSteps,problems,type Problem} from './core'

const colors=['#ff5267','#3aa9ff','#ffd45c']
const N=()=> <mi>n</mi>, Pow=({power}:{power:number})=><msup><N/><mn>{power}</mn></msup>
const Limit=()=> <munder><mo>lim</mo><mrow><N/><mo>→</mo><mi>∞</mi></mrow></munder>
const FracM=({children}:{children:[React.ReactNode,React.ReactNode]})=><mfrac><mrow>{children[0]}</mrow><mrow>{children[1]}</mrow></mfrac>
function Expression({p}:{p:Problem}){
 const n=<N/>, n2=<Pow power={2}/>, n3=<Pow power={3}/>
 const expressions:Record<string,React.ReactNode>={
  '2-1':<FracM>{[<mn>1</mn>,<>{n2}<mo>+</mo><mn>1</mn></>]}</FracM>,
  '2-2':<mrow><mo>(</mo>{n3}<mo>+</mo><mn>4</mn>{n2}<mo>)</mo></mrow>,
  '2-3':<FracM>{[<>{n}<mo>−</mo><mn>5</mn></>,<><mn>2</mn>{n}<mo>+</mo><mn>1</mn></>]}</FracM>,
  '2-4':<FracM>{[<>{n}<mo>+</mo><mn>2</mn></>,<>{n2}<mo>−</mo><mn>2</mn></>]}</FracM>,
  '2-5':<FracM>{[<>{n2}<mo>+</mo><mn>5</mn>{n}<mo>+</mo><mn>4</mn></>,<><mn>3</mn><mo>−</mo><mn>2</mn>{n2}</>]}</FracM>,
  '2-6':<mrow><mo>(</mo><mn>2</mn><mo>−</mo><FracM>{[<>{n}<mo>+</mo><mn>1</mn></>,<><mn>3</mn>{n}<mo>−</mo><mn>1</mn></>]}</FracM><mo>)</mo></mrow>,
 }
 return <>{expressions[p.id]}</>
}
function Answer({answer}:{answer:string}){if(answer==='1/2'||answer==='−1/2'||answer==='5/3'){const neg=answer.startsWith('−');const [a,b]=(neg?answer.slice(1):answer).split('/');return <>{neg&&<mo>−</mo>}<FracM>{[<mn>{a}</mn>,<mn>{b}</mn>]}</FracM></>}return answer==='∞'?<mi>∞</mi>:<mn>{answer}</mn>}
function Formula({p,answer=false}:{p:Problem,answer?:boolean}){return <math className={`formula ${answer?'answered':''}`} display="inline" aria-label={`${p.label} の極限${answer?`は${p.answer}`:''}`}><mrow><Limit/><Expression p={p}/>{answer&&<><mo>=</mo><Answer answer={p.answer}/></>}</mrow></math>}
function TransformFormula({p}:{p:Problem}){const n=<N/>,n2=<Pow power={2}/>;const map:Record<string,React.ReactNode>={
 '2-1':<><FracM>{[<FracM>{[<mn>1</mn>,n2]}</FracM>,<><mn>1</mn><mo>+</mo><FracM>{[<mn>1</mn>,n2]}</FracM></>]}</FracM><mo>→</mo><FracM>{[<mn>0</mn>,<><mn>1</mn><mo>+</mo><mn>0</mn></>]}</FracM></>,
 '2-2':<>{n2}<mo>(</mo>{n}<mo>+</mo><mn>4</mn><mo>)</mo><mo>→</mo><mi>∞</mi></>,
 '2-3':<><FracM>{[<><mn>1</mn><mo>−</mo><FracM>{[<mn>5</mn>,n]}</FracM></>,<><mn>2</mn><mo>+</mo><FracM>{[<mn>1</mn>,n]}</FracM></>]}</FracM><mo>→</mo><FracM>{[<mn>1</mn>,<mn>2</mn>]}</FracM></>,
 '2-4':<><FracM>{[<><FracM>{[<mn>1</mn>,n]}</FracM><mo>+</mo><FracM>{[<mn>2</mn>,n2]}</FracM></>,<><mn>1</mn><mo>−</mo><FracM>{[<mn>2</mn>,n2]}</FracM></>]}</FracM><mo>→</mo><mn>0</mn></>,
 '2-5':<><FracM>{[<><mn>1</mn><mo>+</mo><FracM>{[<mn>5</mn>,n]}</FracM><mo>+</mo><FracM>{[<mn>4</mn>,n2]}</FracM></>,<><FracM>{[<mn>3</mn>,n2]}</FracM><mo>−</mo><mn>2</mn></>]}</FracM><mo>→</mo><mo>−</mo><FracM>{[<mn>1</mn>,<mn>2</mn>]}</FracM></>,
 '2-6':<><mn>2</mn><mo>−</mo><FracM>{[<><mn>1</mn><mo>+</mo><FracM>{[<mn>1</mn>,n]}</FracM></>,<><mn>3</mn><mo>−</mo><FracM>{[<mn>1</mn>,n]}</FracM></>]}</FracM><mo>→</mo><mn>2</mn><mo>−</mo><FracM>{[<mn>1</mn>,<mn>3</mn>]}</FracM><mo>=</mo><FracM>{[<mn>5</mn>,<mn>3</mn>]}</FracM></>};return <math className="transform-formula" display="block"><mrow>{map[p.id]}</mrow></math>}
const scaled=(v:number)=>Math.sign(v)*Math.log10(Math.abs(v)+1)*1.5
function Axes3D(){const ticks=[-4,-2,0,2,4];return <group name="coordinate-axes">
 <Line points={[[-4,0,0],[6.7,0,0]]} color="#d8ecff" lineWidth={2.5}/>
 <mesh position={[6.78,0,0]} rotation={[0,0,-Math.PI/2]}><coneGeometry args={[.13,.38,16]}/><meshBasicMaterial color="#d8ecff" toneMapped={false}/></mesh>
 <Line points={[[ -4,-5.2,0],[-4,5.5,0]]} color="#76c7ff" lineWidth={4}/>
 <mesh position={[-4,5.68,0]}><coneGeometry args={[.16,.42,18]}/><meshBasicMaterial color="#76c7ff" toneMapped={false}/></mesh>
 {ticks.map(y=><group key={y}><Line points={[[ -4.16,y,0],[-3.84,y,0]]} color="#bde5ff" lineWidth={2}/>{y!==0&&<Html center position={[-4.4,y,0]}><span className="axis3d-tick">{y}</span></Html>}</group>)}
 <Html center position={[-4.05,5.95,0]}><strong className="axis3d-label y">y（値）</strong></Html>
 <Html center position={[-4.3,-.35,0]}><strong className="axis3d-label">0</strong></Html>
 <Html center position={[7.05,-.3,0]}><strong className="axis3d-label">n</strong></Html>
 </group>}
function Scene({p,n,controlsRef}:{p:Problem,n:number,controlsRef:React.RefObject<OrbitControlsImpl|null>}){
 const samples=useMemo(()=>nSteps.filter(x=>x<=n),[n]); const index=nSteps.indexOf(n); const xOf=(x:number)=>Math.log10(x)*3.1-4
 return <Canvas camera={{position:[10,8,12],fov:42}} dpr={[1,1.7]} gl={{antialias:true}}><color attach="background" args={['#050914']}/><ambientLight intensity={.65}/><pointLight position={[2,8,4]} intensity={25} color="#9bcfff"/><Grid args={[16,16]} position={[0,-.02,0]} cellColor="#152944" sectionColor="#28466b" fadeDistance={24}/><Axes3D/>
 {p.parts.map((label,lane)=>{const pts=samples.map(s=>[xOf(s),scaled(p.values(s)[lane]),(lane-1)*3] as [number,number,number]);const current=pts.at(-1)??[xOf(n),scaled(p.values(n)[lane]),(lane-1)*3];return <group key={label}><Line points={pts.length>1?pts:[current,current]} color={colors[lane]} lineWidth={lane===2?3:2} transparent opacity={.8}/>{pts.map((v,i)=><mesh position={v} key={i}><sphereGeometry args={[i===pts.length-1?.18:.09,18,18]}/><meshStandardMaterial color={colors[lane]} emissive={colors[lane]} emissiveIntensity={i===pts.length-1?4:1}/></mesh>)}<Html center position={[6.4,.4,(lane-1)*3]}><span className="lane3d-label" style={{color:colors[lane]}}>{label}</span></Html></group>})}
 <Line points={[[-4,0,-4],[6.6,0,-4]]} color="#ffe9a6" transparent opacity={.55}/><Html center position={[6.2,-.4,-4]}><span className="zero3d-label">y = 0</span></Html><Html center position={[6.2,.05,1.2]}><span className="n3d-label">n →（対数目盛）</span></Html>
 <OrbitControls ref={controlsRef} enableDamping dampingFactor={.08} minDistance={6} maxDistance={28} target={[1,2,0]}/></Canvas>
}
function Graph2D({p,n,nearZero}:{p:Problem,n:number,nearZero:boolean}){const xs=nSteps.filter(x=>x<=n);const values=xs.map(x=>p.values(x)[2]);const max=nearZero?Math.max(...values.map(Math.abs),.001):Math.max(...xs.flatMap(x=>p.values(x).map(Math.abs)),1);const zeroY=210;const xPos=(i:number)=>72+i*(642/Math.max(xs.length-1,1));return <svg className="graph2d" viewBox="0 0 760 420" role="img" aria-label="横軸n、縦軸y（値）の座標平面。自然数nにおける数列の値"><defs><filter id="axisGlow"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g className="grid-lines">{[-150,-75,75,150].map(y=><line key={y} x1="58" y1={zeroY+y} x2="724" y2={zeroY+y}/>)}</g><g className="axes" filter="url(#axisGlow)"><line className="x-axis" x1="58" y1={zeroY} x2="735" y2={zeroY}/><line className="y-axis" x1="58" y1="22" x2="58" y2="390"/><path d="M735 210l-10-5v10zM58 22l-5 10h10z"/></g><g className="axis-labels"><text x="724" y="198">n</text><text x="70" y="33">y（値）</text><text x="40" y="228">0</text>{[-1,-.5,.5,1].map(t=><g key={t}><line x1="53" x2="63" y1={zeroY-t*175} y2={zeroY-t*175}/><text x="48" y={zeroY-t*175+4} textAnchor="end">{t===1?'最大':t===-1?'−最大':t}</text></g>)}</g>{p.parts.map((_,lane)=>{const pts=xs.map((x,i)=>{const val=nearZero&&lane!==2?0:p.values(x)[lane];return `${xPos(i)},${zeroY-val/max*175}`}).join(' ');return nearZero&&lane!==2?null:<g key={lane}><polyline points={pts} style={{stroke:colors[lane]}}/>{pts.split(' ').map((pt,i)=>{const[a,b]=pt.split(',');return <g key={i}><circle cx={a} cy={b} r="5" style={{fill:colors[lane]}}/><text className="n-tick" x={a} y="232" textAnchor="middle">{xs[i]}</text></g>})}</g>})}<text className="sequence-note" x="72" y="400">● 実際の数列は整数 n の点（線は変化を見るための補助）</text></svg>}

const quiz=[{q:'nを大きくしても、分子1はどうなっていますか？',a:['大きくなる','小さくなる','変わらない'],ok:2},{q:'分母 n²+1 はどうなっていますか？',a:['大きくなる','小さくなる','ほぼ変わらない'],ok:0},{q:'1を、とても大きな数で割ると、値はどこへ近づきそうですか？',a:['0','1','∞','−∞'],ok:0}]
function Inquiry({onComplete}:{onComplete:()=>void}){const[step,setStep]=useState(0);const[result,setResult]=useState('');const q=quiz[step];return <section className="inquiry"><small>THINK FIRST · {step+1}/3</small><h3>{q.q}</h3><div>{q.a.map((a,i)=><button key={a} onClick={()=>{if(i===q.ok){setResult('正解です。グラフの変化と一致しています。');setTimeout(()=>{if(step<2){setStep(step+1);setResult('')}else onComplete()},500)}else setResult('もう一度、色の軌跡を観察してみよう。')}}>{a}</button>)}</div><output>{result}</output></section>}
function Derivation({p}:{p:Problem}){const[answer,setAnswer]=useState(false);return <section className="derivation"><div><small>FROM GRAPH TO FORMULA</small><h2>数式で確かめる</h2></div><details className="formula-reveal"><summary className="gold-button">数式で確かめる <ChevronRight/></summary><div className="math-steps"><Formula p={p}/><span className="arrow">↓</span><p>{p.id==='2-2'?<><math><Pow power={2}/></math> でくくり出す</>:p.id==='2-6'?'分数部分を最高次 n で割る':'分子・分母を最高次の n で割る'}</p><TransformFormula p={p}/><button onClick={()=>setAnswer(true)} disabled={answer}>解答を表示</button>{answer&&<><Formula p={p} answer/><p>{p.insight}</p></>}</div></details></section>}

export default function App(){const[pIndex,setPIndex]=useState(0),p=problems[pIndex];const[nIndex,setNIndex]=useState(0),n=nSteps[nIndex];const[playing,setPlaying]=useState(false),[view,setView]=useState<'3d'|'2d'>('3d'),[nearZero,setNearZero]=useState(false),[mode,setMode]=useState('探究モード'),[quizDone,setQuizDone]=useState(false);const controls=useRef<OrbitControlsImpl|null>(null)
 useEffect(()=>{if(!playing)return;const id=setTimeout(()=>setNIndex(i=>{if(i>=nSteps.length-1){setPlaying(false);return i}return i+1}),nIndex<5?850:420);return()=>clearTimeout(id)},[playing,nIndex])
 useEffect(()=>{setNIndex(0);setPlaying(false);setQuizDone(false);setNearZero(false)},[pIndex]);const vals=p.values(n)
 const resetView=()=>controls.current?.reset(); const zoom=(d:number)=>{const c=controls.current;if(c){const cam=c.object;cam.position.multiplyScalar(d);c.update()}}
 return <div className="app"><header><a href="../../" className="brand"><Home/>教材一覧</a><div><small>MATHEMATICS III · SEQUENCE LIMIT</small><b>LIMIT <i>SCOPE</i></b></div><nav>{['探究モード','解説モード','自由操作モード'].map(x=><button className={mode===x?'active':''} onClick={()=>setMode(x)} key={x}>{x}</button>)}</nav></header>
 <section className="problem-bar"><span><b>01</b> 問題を選ぶ</span><div>{problems.map((x,i)=><button className={i===pIndex?'active':''} onClick={()=>setPIndex(i)} key={x.id}>{x.label}</button>)}</div><button className="examples"><BookOpen/>解説：例8(1)(2)<span>3n+2 / n+1 → 3　・　(n+1)/(2n²−n−3) → 0</span></button></section>
 <main><section className="hero-formula"><div><small>CURRENT PROBLEM</small><Formula p={p}/></div><p>まずグラフと数値から、極限を予想しよう。</p></section>
 <div className="workspace"><section className="visual"><div className="visual-head"><div className="switch"><button className={view==='2d'?'active':''} onClick={()=>setView('2d')}>2D</button><button className={view==='3d'?'active':''} onClick={()=>setView('3d')}>3D</button></div><div className="legend">{p.parts.map((x,i)=><span style={{color:colors[i]}} key={x}>● {x}</span>)}</div><button className={nearZero?'active':''} onClick={()=>{setNearZero(x=>!x);setView('2d')}}><Search/>0付近を拡大</button></div><div className="viewport">{view==='3d'?<Scene p={p} n={n} controlsRef={controls}/>:<Graph2D p={p} n={n} nearZero={nearZero}/>}<div className="view-tools"><button onClick={()=>zoom(.82)} title="拡大"><ZoomIn/></button><button onClick={()=>zoom(1.2)} title="縮小"><ZoomOut/></button><button onClick={resetView} title="視点リセット"><RotateCcw/></button></div><p className="gesture"><Maximize2/>ドラッグ / 1本指：3D回転　・　ホイール / ピンチ：拡大縮小</p></div>
 <div className="timeline"><div className="n-now">現在 <b>n = {n}</b>{nIndex===nSteps.length-1&&<em>この先も n → ∞</em>}</div><input aria-label="nスライダー" type="range" min="0" max={nSteps.length-1} step="1" value={nIndex} onChange={e=>setNIndex(+e.target.value)}/><div className="ticks"><span>1</span><span>5</span><span>100</span><span>1000 → ∞</span></div><div className="play-controls"><button onClick={()=>setNIndex(0)}><RotateCcw/>最初に戻る</button><button className="primary" onClick={()=>setPlaying(x=>!x)}>{playing?<><Pause/>一時停止</>:<><Play/>再生</>}</button><button onClick={()=>setNIndex(i=>Math.min(i+1,nSteps.length-1))}><SkipForward/>1ステップ進む</button><button onClick={()=>setNIndex(i=>Math.min(i+1,nSteps.length-1))}>nを大きくする <ChevronRight/></button></div></div></section>
 <aside><section className="values"><small>LIVE VALUES</small><h2>現在 n = {n}</h2>{p.parts.map((x,i)=><div className={`value v${i}`} key={x}><span>{x}</span><b>{i===0&&p.id==='2-1'?'1':i===1&&p.id==='2-1'?<math><mrow><msup><mn>{n}</mn><mn>2</mn></msup><mo>+</mo><mn>1</mn><mo>=</mo><mn>{vals[i]}</mn></mrow></math>:formatValue(vals[i])}</b>{i===2&&p.denominator&&<small><math className="value-fraction"><mfrac><mtext>{p.numerator.replaceAll('n',String(n))}</mtext><mtext>{p.denominator.replaceAll('n',String(n))}</mtext></mfrac><mo>≈</mo><mn>{formatValue(vals[i])}</mn></math></small>}</div>)}</section><section className="infinity"><b>∞ は数ではありません</b><p>nをどこまでも大きくしていく状態を表します。「n = ∞」を代入するのではありません。</p></section><section className="insight"><b>観察ポイント</b><p>{p.insight}</p>{p.id==='2-1'&&<p>金色の点は0に近づいていますが、有限のnでは0ではありません。</p>}</section></aside></div>
 {(mode==='探究モード'&&!quizDone&&p.id==='2-1')?<Inquiry onComplete={()=>setQuizDone(true)}/>:<section className="prediction"><span>極限値を予想できましたか？</span><Formula p={p}/><button onClick={()=>setQuizDone(true)}>予想を決める</button></section>}
 {(quizDone||mode==='解説モード')&&<Derivation p={p}/>}<section className="notes"><h2>極限で気をつけること</h2><div><p><b>∞ / ∞</b> は答えではなく「不定形」。問2(3)のように最高次で割って比べます。</p><p><b>∞ − ∞</b> もそのままでは判断できません。式を整理して増え方を比較します。</p></div></section></main><footer>グラフを見る → nを大きくする → 値を比較 → 予想 → 数式で確認</footer></div>
}
