import {Canvas} from '@react-three/fiber'
import {Billboard,Grid,Line,OrbitControls,Text} from '@react-three/drei'
import {useEffect,useMemo,useRef,useState} from 'react'
import katex from 'katex'
import 'katex/dist/katex.min.css'
import {BookOpen,ChevronRight,Home,Maximize2,Pause,Play,RotateCcw,Search,SkipForward,ZoomIn,ZoomOut} from 'lucide-react'
import type {OrbitControls as OrbitControlsImpl} from 'three-stdlib'
import {formatValue,nSteps,problems,type Problem} from './core'

const colors=['#ff5267','#3aa9ff','#ffd45c']
function Frac({top,bottom}:{top:string,bottom:string}){return <span className="frac"><span>{top}</span><span>{bottom}</span></span>}
function MathFormula({latex,className=''}:{latex:string,className?:string}){return <span className={`katex-formula ${className}`} role="math" aria-label={latex} dangerouslySetInnerHTML={{__html:katex.renderToString(latex,{throwOnError:false,displayMode:false,output:'html'})}}/>}
function Formula({p,answer=false}:{p:Problem,answer?:boolean}){
 const result=p.answer==='1/2'?'\\frac12':p.answer==='−1/2'?'-\\frac12':p.answer==='5/3'?'\\frac53':p.answer
 return <MathFormula className={`formula ${answer?'answered':''}`} latex={`${p.formulaLatex}${answer?`=${result}`:''}`}/>
}
const scaled=(v:number)=>Math.sign(v)*Math.log10(Math.abs(v)+1)*1.5
function Scene({p,n,controlsRef}:{p:Problem,n:number,controlsRef:React.RefObject<OrbitControlsImpl|null>}){
 const samples=useMemo(()=>nSteps.filter(x=>x<=n),[n]); const xOf=(x:number)=>Math.log10(x)*3.1-4; const yTicks=[-4,-2,0,2,4,6]
 return <Canvas camera={{position:[10,8,12],fov:42}} dpr={[1,1.7]} gl={{antialias:true}}><color attach="background" args={['#050914']}/><ambientLight intensity={.65}/><pointLight position={[2,8,4]} intensity={25} color="#9bcfff"/><Grid args={[16,16]} position={[0,-.02,0]} cellColor="#152944" sectionColor="#28466b" fadeDistance={24}/>
 {p.parts.map((label,lane)=>{const pts=samples.map(s=>[xOf(s),scaled(p.values(s)[lane]),(lane-1)*3] as [number,number,number]);const current=pts.at(-1)??[xOf(n),scaled(p.values(n)[lane]),(lane-1)*3];return <group key={label}><Line points={pts.length>1?pts:[current,current]} color={colors[lane]} lineWidth={lane===2?3:2} transparent opacity={.8}/>{pts.map((v,i)=><mesh position={v} key={i}><sphereGeometry args={[i===pts.length-1?.18:.09,18,18]}/><meshStandardMaterial color={colors[lane]} emissive={colors[lane]} emissiveIntensity={i===pts.length-1?4:1}/></mesh>)}<Billboard position={[6.4,.4,(lane-1)*3]}><Text fontSize={.35} color={colors[lane]} anchorX="right">{label}</Text></Billboard></group>})}
 <Line points={[[ -4,-4,0],[-4,6.5,0]]} color="#f8fbff" lineWidth={4} depthTest={false}/>
 {yTicks.map(y=><group key={y}><Line points={[[ -4.18,y,0],[-3.82,y,0]]} color={y===0?'#ffd45c':'#f8fbff'} lineWidth={y===0?4:2} depthTest={false}/><Billboard position={[-4.45,y,0]}><Text fontSize={.25} color={y===0?'#ffd45c':'#f8fbff'} anchorX="right">{y}</Text></Billboard></group>)}
 <Line points={[[ -4,0,-4],[6.6,0,-4]]} color="#ffd45c" lineWidth={3} depthTest={false}/><Line points={[[ -4,0,0],[6.6,0,0]]} color="#ffd45c" lineWidth={2.5} depthTest={false}/><Billboard position={[5.9,.35,-4]}><Text fontSize={.31} color="#ffd45c">y = 0</Text></Billboard><Billboard position={[-4,6.2,0]}><Text fontSize={.38} color="#ffffff">y（値）</Text></Billboard><Text rotation={[-Math.PI/2,0,0]} position={[6.2,.05,1.2]} fontSize={.32} color="#aec9e8">n →（対数目盛）</Text>
 <OrbitControls ref={controlsRef} enableDamping dampingFactor={.08} minDistance={6} maxDistance={28} target={[1,2,0]}/></Canvas>
}
function Graph2D({p,n,nearZero}:{p:Problem,n:number,nearZero:boolean}){const xs=nSteps.filter(x=>x<=n); const values=xs.map(x=>p.values(x)[2]);const max=nearZero?Math.max(...values.map(Math.abs),.001):Math.max(...xs.flatMap(x=>p.values(x).map(Math.abs)),1);return <svg className="graph2d" viewBox="0 0 760 420" role="img" aria-label="自然数nにおける数列の値"><path d="M55 210H735M55 20V395"/><text x="720" y="202">n</text><text x="20" y="30">値</text>{p.parts.map((_,lane)=>{const pts=xs.map((x,i)=>{const val=nearZero&&lane!==2?0:p.values(x)[lane];return `${55+i*(655/Math.max(xs.length-1,1))},${210-val/max*175}`}).join(' ');return nearZero&&lane!==2?null:<g key={lane}><polyline points={pts} style={{stroke:colors[lane]}}/>{pts.split(' ').map((pt,i)=>{const[a,b]=pt.split(',');return <circle key={i} cx={a} cy={b} r="5" style={{fill:colors[lane]}}/>})}</g>})}<text x="70" y="385">● 実際の数列は整数 n の点（線は変化を見るための補助）</text></svg>}

const quiz=[{q:'nを大きくしても、分子1はどうなっていますか？',a:['大きくなる','小さくなる','変わらない'],ok:2},{q:'分母 n²+1 はどうなっていますか？',a:['大きくなる','小さくなる','ほぼ変わらない'],ok:0},{q:'1を、とても大きな数で割ると、値はどこへ近づきそうですか？',a:['0','1','∞','−∞'],ok:0}]
function Inquiry({onComplete}:{onComplete:()=>void}){const[step,setStep]=useState(0);const[result,setResult]=useState('');const q=quiz[step];return <section className="inquiry"><small>THINK FIRST · {step+1}/3</small><h3>{q.q}</h3><div>{q.a.map((a,i)=><button key={a} onClick={()=>{if(i===q.ok){setResult('正解です。グラフの変化と一致しています。');setTimeout(()=>{if(step<2){setStep(step+1);setResult('')}else onComplete()},500)}else setResult('もう一度、色の軌跡を観察してみよう。')}}>{a}</button>)}</div><output>{result}</output></section>}
function Derivation({p,n}:{p:Problem,n:number}){
 const[stage,setStage]=useState(-1)
 useEffect(()=>setStage(-1),[p.id])
 const step=stage>=0?p.derivation[stage]:null
 return <section className="derivation"><div><small>FROM GRAPH TO FORMULA</small><h2>数式で確かめる</h2></div>{!step?<button className="gold-button" onClick={()=>setStage(0)}>数式で確かめる <ChevronRight/></button>:<div className="math-steps"><small className="step-label">{step.label}</small>{step.note&&<p>{step.note}</p>}<div className={`formula-card ${step.emphasis?'emphasis':''} ${step.final?'final':''}`}><MathFormula latex={step.latex}/></div>{p.id==='2-1'&&stage>=2&&<div className="numeric-proof"><MathFormula latex={`n=${n}\\quad\\frac{1}{n^2}=${formatValue(1/(n*n))}`}/><span>nを大きくすると 1/n² は0に近づく</span><b>したがって 1/(n²+1) も0に近づく</b></div>}{stage<p.derivation.length-1?<button onClick={()=>setStage(x=>x+1)}>次のステップ <ChevronRight/></button>:<p className="derivation-insight">{p.insight}</p>}<div className="step-dots" aria-label={`${stage+1}/${p.derivation.length}`}>{p.derivation.map((_,i)=><button key={i} aria-label={`STEP ${i+1}`} className={i===stage?'active':''} onClick={()=>setStage(i)}/>)}</div></div>}</section>
}

export default function App(){const[pIndex,setPIndex]=useState(0),p=problems[pIndex];const[nIndex,setNIndex]=useState(0),n=nSteps[nIndex];const[playing,setPlaying]=useState(false),[view,setView]=useState<'3d'|'2d'>('3d'),[nearZero,setNearZero]=useState(false),[mode,setMode]=useState('探究モード'),[quizDone,setQuizDone]=useState(false);const controls=useRef<OrbitControlsImpl|null>(null)
 useEffect(()=>{if(!playing)return;const id=setTimeout(()=>setNIndex(i=>{if(i>=nSteps.length-1){setPlaying(false);return i}return i+1}),nIndex<5?850:420);return()=>clearTimeout(id)},[playing,nIndex])
 useEffect(()=>{setNIndex(0);setPlaying(false);setQuizDone(false);setNearZero(false)},[pIndex]);const vals=p.values(n)
 const resetView=()=>controls.current?.reset(); const zoom=(d:number)=>{const c=controls.current;if(c){const cam=c.object;cam.position.multiplyScalar(d);c.update()}}
 return <div className="app"><header><a href="../../" className="brand"><Home/>教材一覧</a><div><small>MATHEMATICS III · SEQUENCE LIMIT</small><b>LIMIT <i>SCOPE</i></b></div><nav>{['探究モード','解説モード','自由操作モード'].map(x=><button className={mode===x?'active':''} onClick={()=>setMode(x)} key={x}>{x}</button>)}</nav></header>
 <section className="problem-bar"><span><b>01</b> 問題を選ぶ</span><div>{problems.map((x,i)=><button className={i===pIndex?'active':''} onClick={()=>setPIndex(i)} key={x.id}>{x.label}</button>)}</div><button className="examples"><BookOpen/>解説：例8(1)(2)<span>3n+2 / n+1 → 3　・　(n+1)/(2n²−n−3) → 0</span></button></section>
 <main><section className="hero-formula"><div><small>CURRENT PROBLEM</small><Formula p={p}/></div><p>まずグラフと数値から、極限を予想しよう。</p></section>
 <div className="workspace"><section className="visual"><div className="visual-head"><div className="switch"><button className={view==='2d'?'active':''} onClick={()=>setView('2d')}>2D</button><button className={view==='3d'?'active':''} onClick={()=>setView('3d')}>3D</button></div><div className="legend">{p.parts.map((x,i)=><span style={{color:colors[i]}} key={x}>● {x}</span>)}</div><button className={nearZero?'active':''} onClick={()=>{setNearZero(x=>!x);setView('2d')}}><Search/>0付近を拡大</button></div><div className="viewport">{view==='3d'?<Scene p={p} n={n} controlsRef={controls}/>:<Graph2D p={p} n={n} nearZero={nearZero}/>}<div className="view-tools"><button onClick={()=>zoom(.82)} title="拡大"><ZoomIn/></button><button onClick={()=>zoom(1.2)} title="縮小"><ZoomOut/></button><button onClick={resetView} title="視点リセット"><RotateCcw/></button></div><p className="gesture"><Maximize2/>ドラッグ / 1本指：3D回転　・　ホイール / ピンチ：拡大縮小</p></div>
 <div className="timeline"><div className="n-now">現在 <b>n = {n}</b>{nIndex===nSteps.length-1&&<em>この先も n → ∞</em>}</div><input aria-label="nスライダー" type="range" min="0" max={nSteps.length-1} step="1" value={nIndex} onChange={e=>setNIndex(+e.target.value)}/><div className="ticks"><span>1</span><span>5</span><span>100</span><span>1000 → ∞</span></div><div className="play-controls"><button onClick={()=>setNIndex(0)}><RotateCcw/>最初に戻る</button><button className="primary" onClick={()=>setPlaying(x=>!x)}>{playing?<><Pause/>一時停止</>:<><Play/>再生</>}</button><button onClick={()=>setNIndex(i=>Math.min(i+1,nSteps.length-1))}><SkipForward/>1ステップ進む</button><button onClick={()=>setNIndex(i=>Math.min(i+1,nSteps.length-1))}>nを大きくする <ChevronRight/></button></div></div></section>
 <aside><section className="values"><small>LIVE VALUES</small><h2>現在 n = {n}</h2>{p.parts.map((x,i)=><div className={`value v${i}`} key={x}><span>{x}</span><b>{i===0&&p.id==='2-1'?'1':i===1&&p.id==='2-1'?<>{n}² + 1 = {vals[i]}</>:formatValue(vals[i])}</b>{i===2&&p.denominator&&<small><Frac top={p.numerator.replaceAll('n',String(n))} bottom={p.denominator.replaceAll('n',String(n))}/> ≈ {formatValue(vals[i])}</small>}</div>)}{p.id==='2-1'&&<div className="live-convergence"><MathFormula latex={`\\frac{1}{n^2}=${formatValue(1/(n*n))}`}/><span>↓ n を大きくすると 0 に近づく</span><MathFormula latex={`\\frac{1}{n^2+1}=${formatValue(vals[2])}`}/></div>}</section><section className="infinity"><b>∞ は数ではありません</b><p>nをどこまでも大きくしていく状態を表します。「n = ∞」を代入するのではありません。</p></section><section className="insight"><b>観察ポイント</b><p>{p.insight}</p>{p.id==='2-1'&&<p>金色の点は0に近づいていますが、有限のnでは0ではありません。</p>}</section></aside></div>
 {(mode==='探究モード'&&!quizDone&&p.id==='2-1')?<Inquiry onComplete={()=>setQuizDone(true)}/>:<section className="prediction"><span>極限値を予想できましたか？</span><Formula p={p}/><button onClick={()=>setQuizDone(true)}>予想を決める</button></section>}
 {(quizDone||mode==='解説モード')&&<Derivation p={p} n={n}/>}<section className="notes"><h2>極限で気をつけること</h2><div><p><b>∞ / ∞</b> は答えではなく「不定形」。問2(3)のように最高次で割って比べます。</p><p><b>∞ − ∞</b> もそのままでは判断できません。式を整理して増え方を比較します。</p></div></section></main><footer>グラフを見る → nを大きくする → 値を比較 → 予想 → 数式で確認</footer></div>
}
