import{lazy,Suspense,useMemo,useState}from'react';import TicketTowerLab from'./TicketTowerLab';import AomoriMap from'./AomoriMap';import katex from'katex';import{jumboData}from'./data/yearEndJumbo';import{aomoriWins,allJumbo,source}from'./data/aomoriHighWins';import{atLeast,expectedValue,highCount,money}from'./core';const Landscape=lazy(()=>import('./Landscape3D'));const tabs=['宝くじを数学で見る','2,000万分の1を体感','2020～2025年度比較','当せん確率を求める','期待値とは？','900円で3枚買ったら？','高額当せんの確率','10枚・100枚・1万枚なら？','モンテカルロ実験','同じ期待値・違う分布','青森県 高額当せんマップ','3D確率ランドスケープ','自由探究','確認問題'];const F=({x}:{x:string})=><span className="formula" dangerouslySetInnerHTML={{__html:katex.renderToString(x,{throwOnError:false})}}/>;const Ticket=()=> <div className="ticket"><small>YEAR-END MATH</small><b>¥300</b><span>確率を考える券</span></div>;const Pyramid=({d}:{d:typeof jumboData[number]})=><div className="pyramid">{d.prizes.map((p,i)=><div key={p.label} className={'p p'+i} style={{width:`${28+70*Math.log10(p.count)/Math.log10(46e6)}%`}}><b>{p.label}</b><span>{money(p.amount)}円 × {money(p.count)}本</span></div>)}</div>;
function Sim({d,initial=1000}:{d:typeof jumboData[number];initial?:number}){const[n,setN]=useState(initial),[run,setRun]=useState(0);const res=useMemo(()=>{if(!run)return null;let total=0,pts:number[]=[];const ps=d.prizes.map(x=>x.count/d.totalTickets);for(let i=1;i<=n;i++){let r=Math.random(),c=0,w=0;for(let j=0;j<ps.length;j++){c+=ps[j];if(r<c){w=d.prizes[j].amount;break}}total+=w;if(i%Math.max(1,Math.floor(n/40))===0)pts.push(total/i)}return{total,pts}},[run,n,d]);return <><div className="simulation-stream" aria-hidden="true">{Array.from({length:48},(_,i)=><i key={i} className={i%13===0?'win':''}/>)}</div><div className="choices">{[10,100,1000,10000,100000].map(x=><button key={x} onClick={()=>{setN(x);setRun(v=>v+1)}}>{money(x)}回</button>)}</div>{res&&<><div className="metrics"><b>累積購入額<em>{money(n*300)}円</em></b><b>累積払戻額<em>{money(res.total)}円</em></b><b>1枚平均<em>{money(res.total/n,2)}円</em></b></div><svg className="chart" viewBox="0 0 600 220"><line x1="0" y1="145" x2="600" y2="145"/><polyline points={res.pts.map((v,i)=>`${i*600/(res.pts.length-1)},${Math.max(5,Math.min(215,205-v*.4))}`).join(' ')}/><text x="8" y="139">理論値 約150円</text></svg></>}<aside>教育用確率モデル：公式の賞金本数をカテゴリ確率に使用。当せん番号間の関係は完全再現しません。</aside><h3>大数の法則</h3><p>少数回は大きくばらつき、回数を増やすと標本平均は理論値へ近づきます。10回だけで判断してよいでしょうか？</p></>}
const quiz=[['2,000万枚に1本の確率は？','1/20,000,000（0.000005%）'],['7億円×1/2,000万は？','期待値への寄与は35円。'],['期待値150円は次に150円当たる意味？','いいえ。多数回の1枚あたり平均です。'],['3枚900円の期待払戻額は？','約449.985円。'],['2023年と2025年の違いは？','平均は同じでも賞金分布が違います。'],['当たった売り場は次も有利？','その実績だけでは根拠になりません。'],['試行回数が増えると平均は？','理論的期待値へ近づきます。'],['確率と実績の違いは？','確率はモデル上の起こりやすさ、実績は観測結果です。']];
export default function App(){const[t,setT]=useState(0),[year,setYear]=useState(2025),[th,setTh]=useState(1e6),[n,setN]=useState(3),[ans,setAns]=useState(-1),[sources,setSources]=useState(false),[simCount,setSimCount]=useState(1000);const d=jumboData.find(x=>x.year===year)!;const ev=expectedValue(d),hc=th===0?d.prizes[0].count:highCount(d,th),hp=hc/d.totalTickets;return <div><header><a href="../../">← 教材一覧</a><div><small>MATHEMATICS A × I</small><h1>宝くじの確率、期待値</h1></div><button onClick={()=>setSources(true)}>データ出典</button></header><aside className="warn">この教材は宝くじの購入を推奨するものではありません。公開されたデータを利用して確率・期待値を学ぶ数学教材です。</aside><nav>{tabs.map((x,i)=><button key={x} className={t===i?'on':''} onClick={()=>setT(i)}><i>{i+1}</i>{x}</button>)}</nav><main><p className="eyebrow">探究 {t+1}</p><h2>{tabs[t]}</h2>
{t===0&&<div className="split"><section className="center"><Ticket/><h3>この300円には、数学的には<br/>どのくらいの価値がある？</h3></section><article><h3>{year}年・第{d.issueNumber}回</h3><strong className="hero">約 {ev.toFixed(3)}円</strong><p>必ず返る金額ではなく、多数回の1枚あたり平均です。</p><Year v={year} set={setYear}/></article></div>}
{t===1&&<><strong className="hero">1 / 20,000,000</strong><div className="zoom">{['200組','↓','1組10万枚','↓','100000～199999','↓','★ その中の1枚'].map((x,i)=><span key={i}>{x}</span>)}</div><p>2,000万要素は生成せず、階層に縮約して表現しています。</p></>}
{t===2&&<div className="split"><Pyramid d={d}/><article><h3>{year}年 第{d.issueNumber}回</h3><p>高さ順＝賞金額、横幅＝本数。年度で分布が変わります。</p><Year v={year} set={setYear}/></article></div>}
{t===3&&<article><F x={'P(A)=\\frac{n(A)}{n(U)}'}/><p>①全体を決める → ②有利な場合を数える → ③割る</p><F x={'P(\\text{1等})=\\frac1{20{,}000{,}000}'}/><F x={'P(\\text{100万円以上})=\\frac{\\text{該当賞の本数}}{\\text{発売予定枚数}}'}/></article>}
{t===4&&<article><F x={'E(X)=\\sum_i x_iP(X=x_i)'}/><div className="contrib">{d.prizes.map(p=><div key={p.label}><b>{p.label}</b><span>{money(p.amount)} × {p.count}/{money(d.totalTickets)}</span><em>{(p.amount*p.count/d.totalTickets).toFixed(3)}円</em></div>)}</div><strong className="hero">合計 {ev.toFixed(3)}円</strong><p>1等は35円、7等は30円。なぜ寄与が意外に近いのでしょう？</p></article>}
{t===5&&<><div className="three"><Ticket/>＋<Ticket/>＋<Ticket/>＝900円</div><div className="balance"><b>購入額<strong>900円</strong></b><i>⚖</i><b>期待払戻額<strong>449.985円</strong></b></div><aside>期待損益 −450.015円。「3枚で450円程度当たる」意味ではなく、未来の予言でもありません。</aside><F x={'E(X_1+X_2+X_3)=3E(X)'}/><p>1等は独立購入と近似すると <b>1-(1-1/20,000,000)³ ≒ 0.000015%</b>、約666万7千回に1回です。</p></>}
{t===6&&<><div className="choices">{[['100万円以上',1e6],['1,000万円以上',1e7],['1億円以上',1e8],['1等のみ',0]].map(([x,v])=><button key={String(x)} className={th===v?'on':''} onClick={()=>setTh(+v)}>{x}</button>)}</div><Year v={year} set={setYear}/><div className="metrics"><b>本数<em>{money(hc)}本</em></b><b>1枚<em>約1/{money(Math.round(1/hp))}</em></b><b>3枚で1枚以上<em>約1/{money(Math.round(1/atLeast(hp,3)))}</em></b></div><div className="dots">{Array.from({length:180},(_,i)=><i key={i} className={i<Math.max(1,Math.round(hp*2e4))?'hot':''}/>)}</div><h3>期待値は同じなのに、2023・24年はなぜ100万円以上が多い？</h3><p>本数：2020・21=1,034、2022=1,081、2023・24=9,453、2025=1,104。3枚では順に約1/141,844、1/16,221、1/138,889。</p></>}
{t===7&&<TicketTowerLab count={n} setCount={setN} expected={ev} onExperiment={()=>{setSimCount(n);setT(8)}}/>}
{t===8&&<Sim key={simCount} d={d} initial={simCount}/>} {t===9&&<><div className="compare">{[2023,2025].map(y=>{const x=jumboData.find(d=>d.year===y)!;return <article key={y}><h3>{y}</h3><Pyramid d={x}/><b>期待値 {expectedValue(x).toFixed(3)}円</b><p>{y===2023?'100万円級を厚く配分':'2等1億円など高額側へ配分'}</p></article>})}</div><h3>平均が同じでも、結果のばらつき方は違う。</h3><p>平均・分布・散らばり・リスクを合わせて分析しましょう。</p></>}
{t===10&&<AomoriMap/>}
{t===11&&<Suspense fallback={<p>3Dを遅延読み込み中…</p>}><Landscape/></Suspense>}{t===12&&<Designer/>}{t===13&&<div className="quiz">{quiz.map((q,i)=><article key={i}><h3>Q{i+1}　{q[0]}</h3><button onClick={()=>setAns(ans===i?-1:i)}>ヒント・答え合わせ</button>{ans===i&&<p>{q[1]}</p>}</article>)}</div>}</main><footer>確率・期待値・実績を区別して考える数学教材</footer>{sources&&<div className="modal"><section><button onClick={()=>setSources(false)}>× 閉じる</button><h2>データ出典</h2><p>賞金・本数・発売予定枚数：宝くじ公式サイト。ミニは基本計算に含めません。</p>{jumboData.map(x=><a key={x.year} href={x.sourceUrl}><b>{x.year}年 第{x.issueNumber}回</b>　公開日 {x.sourcePublishedDate}／確認日 {x.verifiedDate}</a>)}<a href={source}>2023年度 高額当せん情報／確認日 2026-10-05</a><aside>「記録を確認できない」と「当せんがなかった」は同じではありません。</aside></section></div>}</div>}
function Year({v,set}:{v:number;set:(n:number)=>void}){return <label>年度<input type="range" min="2020" max="2025" value={v} onChange={e=>set(+e.target.value)}/><b>{v}</b></label>}function Designer(){const[a,setA]=useState(7e8),[c,setC]=useState(1),[total,setTotal]=useState(2e7),[price,setPrice]=useState(300);const ev=a*c/total;return <div className="split"><article><h3>仮想宝くじを設計</h3>{[['1等賞金',a,setA],['1等本数',c,setC],['発売枚数',total,setTotal],['価格',price,setPrice]].map(([x,v,s])=><label key={String(x)}>{String(x)}<input type="number" value={v as number} onChange={e=>(s as Function)(+e.target.value)}/></label>)}</article><div className="metrics"><b>確率<em>{c}/{money(total)}</em></b><b>期待値<em>{money(ev,3)}円</em></b><b>回収率<em>{money(ev/price*100,2)}%</em></b></div><p>期待値150円のまま当たりやすくできる？ 高額賞を増やすなら何を減らす？</p></div>}
