import './style.css'
import katex from 'katex'

const $$=(s,r=document)=>[...r.querySelectorAll(s)], $=(s,r=document)=>r.querySelector(s)
const state={a:4,x:-2,b:2,angle:-.55,tilt:.52,zoom:1,clue:0}
const f=(x,b=2)=>x*x+b/x, df=(x,b=2)=>2*x-b/(x*x)
const fmt=n=>Math.abs(n)<.0005?'0':n.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')

function roots(a,b=2){ // x^3-a*x+b=0; interval bisection preserves the double root boundary.
 const critical=Math.cbrt(b/2), min=f(critical,b), out=[]
 const bisect=(lo,hi)=>{let fl=f(lo,b)-a;for(let i=0;i<70;i++){const m=(lo+hi)/2, fm=f(m,b)-a;if(fl*fm<=0)hi=m;else{lo=m;fl=fm}}return(lo+hi)/2}
 out.push(bisect(-Math.max(10,Math.sqrt(Math.abs(a))+3),-.000001))
 if(Math.abs(a-min)<1e-8) out.push(critical)
 else if(a>min){out.push(bisect(.000001,critical));out.push(bisect(critical,Math.max(10,Math.sqrt(a)+3)))}
 return out
}
function setupCanvas(c){const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);return{g,w,h}}
function drawGraph(c,{a=state.a,b=2,tangent=false,progress=10}={}){const{g,w,h}=setupCanvas(c),xMin=-5,xMax=5,yMin=-6,yMax=12,X=x=>(x-xMin)/(xMax-xMin)*w,Y=y=>h-(y-yMin)/(yMax-yMin)*h;g.clearRect(0,0,w,h);g.strokeStyle='#193758';g.lineWidth=1;for(let x=-5;x<=5;x++){g.beginPath();g.moveTo(X(x),0);g.lineTo(X(x),h);g.stroke()}for(let y=-6;y<=12;y+=3){g.beginPath();g.moveTo(0,Y(y));g.lineTo(w,Y(y));g.stroke()}g.strokeStyle='#66809e';g.beginPath();g.moveTo(0,Y(0));g.lineTo(w,Y(0));g.moveTo(X(0),0);g.lineTo(X(0),h);g.stroke();g.setLineDash([7,6]);g.strokeStyle='#ff9f55';g.lineWidth=2;g.beginPath();g.moveTo(X(0),0);g.lineTo(X(0),h);g.stroke();g.setLineDash([]);g.fillStyle='#ffb070';g.fillText('x=0  定義されない',X(0)+7,18)
 const curve=(lo,hi)=>{g.beginPath();let started=false;for(let x=lo;x<=hi;x+=.012){const y=f(x,b);if(y<yMin-5||y>yMax+5){started=false;continue}if(!started){g.moveTo(X(x),Y(y));started=true}else g.lineTo(X(x),Y(y))}g.stroke()};g.strokeStyle='#70d9ff';g.lineWidth=3;g.shadowColor='#55cfff';g.shadowBlur=8;if(progress>=9)curve(-5,-.035);if(progress>=10)curve(.035,5);g.shadowBlur=0
 if(progress>=4){g.fillStyle='#bc98ff';g.shadowColor='#b899ff';g.shadowBlur=15;g.beginPath();g.arc(X(Math.cbrt(b/2)),Y(f(Math.cbrt(b/2),b)),7,0,7);g.fill();g.shadowBlur=0;g.fillStyle='#d7c8ff';g.fillText('極小点',X(Math.cbrt(b/2))+10,Y(f(Math.cbrt(b/2),b))-10)}
 if(a!=null){g.strokeStyle='#ffca55';g.lineWidth=3;g.shadowColor='#ffca55';g.shadowBlur=9;g.beginPath();g.moveTo(0,Y(a));g.lineTo(w,Y(a));g.stroke();g.shadowBlur=0;g.fillStyle='#ffdc83';g.fillText(`y = ${a.toFixed(1)}`,8,Y(a)-8);for(const x of roots(a,b)){g.fillStyle='#ffd45f';g.shadowColor='#ffd45f';g.shadowBlur=18;g.beginPath();g.arc(X(x),Y(a),7,0,7);g.fill()}g.shadowBlur=0}
 if(tangent&&Math.abs(state.x)>.001){const px=state.x,py=f(px),m=df(px);g.strokeStyle=m<-.001?'#ff7180':m>.001?'#54dfa0':'#ffca55';g.lineWidth=2;g.beginPath();g.moveTo(X(px-2),Y(py-2*m));g.lineTo(X(px+2),Y(py+2*m));g.stroke();g.fillStyle='#fff';g.beginPath();g.arc(X(px),Y(py),6,0,7);g.fill();g.fillText('P',X(px)+9,Y(py)-8)}
 g.fillStyle='#9bb1cb';g.font='12px system-ui';g.fillText('x',w-13,Y(0)-7);g.fillText('y',X(0)+8,12)
}
function render(){ $$('.graph').forEach(c=>drawGraph(c,{tangent:c.classList.contains('tangent')}));drawGraph($('#buildGraph'),{a:null,progress:state.clue});drawGraph($('#bGraph'),{a:state.a,b:state.b});$$('.a-value b').forEach(o=>o.textContent=state.a.toFixed(1));$$('.a-range').forEach(r=>{if(+r.value!==state.a)r.value=state.a});const rs=roots(state.a),count=rs.length;$$('.counter strong').forEach(x=>x.textContent=count);$$('.roots').forEach(x=>x.innerHTML=`<b>現在の異なる実数解</b><br>${rs.map((r,i)=>`x<sub>${i+1}</sub> = ${fmt(r)}`).join('<br>')}`);$$('.case').forEach(x=>{const eq=Math.abs(state.a-3)<.001;x.classList.toggle('touch',eq);x.innerHTML=state.a>3?'<b>a &gt; 3</b>：左側1個 ＋ 右側2個 ＝ 合計3個':eq?'<b>a = 3</b>：左側1個 ＋ 右側1個 ＝ 合計2個<br>右側は (1,3) で<b>接している</b>。f′(1)=0':'<b>a &lt; 3</b>：左側1個のみ ＝ 合計1個'});renderX();render3D()}
function renderX(){let x=state.x;if(Math.abs(x)<.05)x=.1;const y=f(x),d=df(x),kind=Math.abs(d)<.001?'水平（f′=0）':d<0?'減少（f′<0）':'増加（f′>0）';$('#xOut').textContent=x.toFixed(1);$('#liveValues').innerHTML=`<span>x<br><b>${x.toFixed(1)}</b></span><span>f(x)<br><b>${fmt(y)}</b></span><span class="${d<0?'dec':d>0?'inc':''}">f′(x)<br><b>${fmt(d)}</b><br>${kind}</span>`;$$('.variation .current').forEach(x=>x.classList.remove('current'));const cells=$$('.variation>div');(x<0?[1,6,11]:x<1?[3,8,13]:[4,9,14]).forEach(i=>cells[i]?.classList.add('current'))}
function renderMath(){$$('.formula,.math-steps,.insight,.limits,.answer-table span,.mapping span,#three h2,#advanced h2,#quiz h2').forEach(el=>{el.innerHTML=el.innerHTML.replace(/\\\((.*?)\\\)/gs,(_,v)=>katex.renderToString(v,{throwOnError:false}))})}

$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');requestAnimationFrame(render)})
$$('.a-range').forEach(r=>r.oninput=e=>{state.a=+e.target.value;render()});$('#xRange').oninput=e=>{let v=+e.target.value;if(Math.abs(v)<.05){v=.1;e.target.value=.1}state.x=v;render()}
const clues=['① 定義域 x≠0','② x<0で減少','③ 0<x<1で減少','④ x=1で極小','⑤ x>1で増加','⑥ x→0− で −∞','⑦ x→0+ で +∞','⑧ x→±∞で +∞','⑨ 左側の枝','⑩ 右側の枝'];$('#nextClue').onclick=()=>{if(state.clue<10){state.clue++;$('#clues').innerHTML=clues.slice(0,state.clue).map(x=>`<li>${x}</li>`).join('');$('#buildStatus').textContent=state.clue===10?'完成：y = x² + 2/x':'手がかり '+state.clue+' / 10'}render()};$('#resetClue').onclick=()=>{state.clue=0;$('#clues').innerHTML='';render()}
$('#predict').onclick=()=>{$('#feedback').textContent='予想を選択して、理由を言葉にしてみよう。'};$('#check').onclick=()=>{let ok=true;$$('select[data-answer]').forEach(s=>{const yes=s.value===s.dataset.answer;s.className=yes?'correct':'wrong';ok&&=yes});$('#feedback').className=ok?'ok':'bad';$('#feedback').textContent=ok?'正解！ 極小値3を境に右側の交点数が変わります。':'もう一度グラフを動かし、左右の枝を別々に数えよう。'}
$('#bRange').oninput=e=>{state.b=+e.target.value;$('#bOut').textContent=state.b.toFixed(1);$('#bFacts').hidden=true;render()};$('#revealB').onclick=()=>{const c=Math.cbrt(state.b/2),m=3*c*c;$('#bFacts').hidden=false;$('#bFacts').innerHTML=`極小点：(${fmt(c)}, ${fmt(m)})<br>境界となる極小値：${fmt(m)}<br>導関数：f′<sub>b</sub>(x)=2x−b/x²`}
const quiz=[['① 関数として見る','f(x)=x³/(x−1) とおく。'],['② 定義域','分母に注目する。'],['③ 導関数','商の微分を使う。'],['④ 増減','導関数を因数分解し、符号を調べる。'],['⑤ 極値','停留点での関数値を計算する。'],['⑥ 極限・漸近線','x→1± と x→±∞ を調べる。'],['⑦ グラフ','x=1の左右を結ばずに描く。'],['⑧ 水平線 y=a','上下に動かす場面を想像する。'],['⑨ 共有点数','各枝との交点を数える。'],['⑩ aで分類','境界値を含む場合に注意する。']];let qi=0;function showQ(){$('#quizStep').innerHTML=`<h3>${quiz[qi][0]}</h3><p>ステップ ${qi+1} / 10</p>`;$('#quizHelp').textContent=''}showQ();$('#hint').onclick=()=>$('#quizHelp').textContent=quiz[qi][1];$('#quizNext').onclick=()=>{qi=Math.min(9,qi+1);showQ()};$('#quizAnswer').onclick=()=>$('#quizHelp').innerHTML='<b>解答の骨格：</b> f′(x)=x²(2x−3)/(x−1)²。x=0は停留点ですが符号は変わらず、極小は f(3/2)=27/4。x=1は定義外。したがって a&lt;27/4:1個、a=27/4:2個、a&gt;27/4:3個。'

function render3D(){const c=$('#surface');if(!c)return;const{g,w,h}=setupCanvas(c);g.clearRect(0,0,w,h);const ca=Math.cos(state.angle),sa=Math.sin(state.angle),ct=Math.cos(state.tilt),st=Math.sin(state.tilt),project=(x,a,z)=>{x*=38*state.zoom;a=(a-2.5)*22*state.zoom;z=Math.max(-10,Math.min(10,z))*18*state.zoom;const X=x*ca-a*sa,Y=x*sa+a*ca;return[w/2+X,h*.53+Y*st-z*ct]};const line=(pts,color,width=1)=>{g.strokeStyle=color;g.lineWidth=width;g.beginPath();pts.forEach((p,i)=>{const q=project(...p);i?g.lineTo(...q):g.moveTo(...q)});g.stroke()};for(let a=-3;a<=8;a+=1)for(const side of [[-4,-.25],[.25,4]]){const p=[];for(let x=side[0];x<=side[1];x+=.13)p.push([x,a,f(x)-a]);line(p,'#2a7793aa')};for(let x=-4;x<=4;x+=.5){if(Math.abs(x)<.2)continue;const p=[];for(let a=-3;a<=8;a+=.25)p.push([x,a,f(x)-a]);line(p,'#225b78aa')};const plane=[[-4,-3,0],[4,-3,0],[4,8,0],[-4,8,0]].map(p=>project(...p));g.fillStyle='#ffca5520';g.beginPath();plane.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.fill();line([[-4,state.a,0],[4,state.a,0]],'#ffca55',3);for(const x of roots(state.a)){const p=project(x,state.a,0);g.fillStyle='#ffd45f';g.shadowColor='#ffd45f';g.shadowBlur=14;g.beginPath();g.arc(...p,6,0,7);g.fill()}g.shadowBlur=0;line([[-4,-3,0],[4,-3,0]],'#b8d0e7',2);line([[0,-3,0],[0,8,0]],'#b8d0e7',2);line([[0,-3,-8],[0,-3,8]],'#b8d0e7',2);g.fillStyle='#d9e8f8';g.fillText('x',...project(4.2,-3,0));g.fillText('a',...project(0,8.4,0));g.fillText('z = F(x,a)',...project(0,-3,8.5))}
let drag=null;$('#surface').onpointerdown=e=>{drag=[e.clientX,e.clientY];e.target.setPointerCapture(e.pointerId)};$('#surface').onpointermove=e=>{if(!drag)return;state.angle+=(e.clientX-drag[0])*.01;state.tilt=Math.max(.1,Math.min(1.3,state.tilt+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];render3D()};$('#surface').onpointerup=()=>drag=null;$('#surface').onwheel=e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(1.7,state.zoom*(e.deltaY>0?.9:1.1)));render3D()}
new ResizeObserver(()=>render()).observe(document.body);renderMath();render()
