import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import katex from 'katex'
import 'katex/dist/katex.min.css'
import './style.css'
import { averageVelocity, motions, signs, type Motion } from './math'

const tabs=[['motion','1. まず動きを見る'],['average','2. 平均速度'],['instant','3. 瞬間速度'],['accel','4. 加速度'],['sync','5. 位置・速度・加速度'],['example','6. 例題21'],['throw','7. 鉛直投げ上げ'],['three','8. 3D解析'],['world','9. 現実世界'],['quiz','10. 確認問題']]
const fmt=(n:number)=>Math.abs(n)<.005?'0.00':n.toFixed(2)
function MathText({tex,block=false}:{tex:string,block?:boolean}){return <span className={block?'math block':'math'} dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{throwOnError:false,displayMode:block})}}/>}

function usePlayer(max:number,initial=1){ const [t,setT]=useState(Math.min(initial,max)); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); useEffect(()=>{if(!playing)return; let last=performance.now(),id=0; const go=(now:number)=>{setT(old=>{const n=old+(now-last)/1000*speed; return n>=max?0:n});last=now;id=requestAnimationFrame(go)};id=requestAnimationFrame(go);return()=>cancelAnimationFrame(id)},[playing,max,speed]); return {t,setT,playing,setPlaying,speed,setSpeed} }
function Controls({p,max}:{p:ReturnType<typeof usePlayer>,max:number}){return <div className="controls"><button onClick={()=>p.setPlaying(true)}>▶ 再生</button><button onClick={()=>p.setPlaying(false)}>⏸ 一時停止</button><button onClick={()=>{p.setPlaying(false);p.setT(0)}}>↺ 最初に戻る</button><label>速度倍率 <select value={p.speed} onChange={e=>p.setSpeed(+e.target.value)}>{[.25,.5,1,2].map(x=><option key={x} value={x}>{x}倍</option>)}</select></label><label className="range">時刻 t = <b>{p.t.toFixed(2)} s</b><input aria-label="時刻 t" type="range" min="0" max={max} step=".01" value={p.t} onChange={e=>p.setT(+e.target.value)}/></label></div>}

function Values({m,t,label='位置'}:{m:Motion,t:number,label?:string}){const s=signs(m.v(t),m.a(t));return <div className="values"><div><small>時刻</small><b>{fmt(t)} <i>s</i></b></div><div className="position"><small>{label}</small><b>{fmt(m.x(t))} <i>m</i></b></div><div className="velocity"><small>速度</small><b>{fmt(m.v(t))} <i>m/s</i></b></div><div className="acceleration"><small>加速度</small><b>{fmt(m.a(t))} <i>m/s²</i></b></div><p className={m.v(t)>=0?'positive':'negative'}>{s.direction} {m.v(t)>0?'＋ →':m.v(t)<0?'− ←':'＝ ●'} ／ {s.speed}</p></div>}
function NumberLine({m,t,second}:{m:Motion,t:number,second?:number}){const vals=Array.from({length:121},(_,i)=>m.x(m.duration*i/120)); const lo=Math.min(...vals)-1,hi=Math.max(...vals)+1; const pos=(x:number)=>6+88*(x-lo)/(hi-lo); const v=m.v(t),a=m.a(t); const arrow=(n:number,y:number,cl:string,name:string)=><g className={cl}><line x1={pos(m.x(t))} y1={y} x2={Math.max(4,Math.min(96,pos(m.x(t))+Math.sign(n)*Math.min(20,Math.abs(n)*2+3)))} y2={y}/><text x={pos(m.x(t))} y={y-3}>{name} {n>=0?'→':'←'}</text></g>;return <svg className="numberline" viewBox="0 0 100 42" role="img" aria-label="点Pが動く数直線"><line className="axis" x1="4" y1="24" x2="96" y2="24"/><path className="axis" d="M96 24l-3-2m3 2l-3 2"/>{Array.from({length:9},(_,i)=><line className="tick" key={i} x1={8+i*11} y1="22" x2={8+i*11} y2="26"/>)}<circle className="p" cx={pos(m.x(t))} cy="24" r="3"/><text x={pos(m.x(t))} y="34" textAnchor="middle">P(t)</text>{second!==undefined&&<><circle className="q" cx={pos(m.x(second))} cy="24" r="2.5"/><text x={pos(m.x(second))} y="40" textAnchor="middle">P(t+Δt)</text><line className="delta" x1={pos(m.x(t))} y1="15" x2={pos(m.x(second))} y2="15"/><text x={(pos(m.x(t))+pos(m.x(second)))/2} y="12" textAnchor="middle">Δx</text></>}{second===undefined&&<>{arrow(v,13,'v-arrow','v')}{arrow(a,5,'a-arrow','a')}</>}</svg>}

function Graph({m,t,kind='x',secant}:{m:Motion,t:number,kind?:'x'|'v'|'a',secant?:number}){const fn=kind==='x'?m.x:kind==='v'?m.v:m.a; const points=Array.from({length:101},(_,i)=>[m.duration*i/100,fn(m.duration*i/100)]);let ys=points.map(p=>p[1]); if(Math.max(...ys)-Math.min(...ys)<1)ys=ys.map(y=>y+(y===0?1:Math.abs(y)*.15)); const lo=Math.min(...ys),hi=Math.max(...ys),x=(q:number)=>42+500*q/m.duration,y=(q:number)=>112-88*(q-lo)/(hi-lo); const path=points.map((p,i)=>`${i?'L':'M'}${x(p[0])},${y(p[1])}`).join(' ');return <svg className={`graph ${kind}`} viewBox="0 0 560 130" role="img" aria-label={`${kind}と時刻のグラフ`}><line className="grid" x1="42" y1="112" x2="548" y2="112"/><line className="grid" x1="42" y1="8" x2="42" y2="116"/><text x="4" y="15">{kind==='x'?'x (m)':kind==='v'?'v (m/s)':'a (m/s²)'}</text><text x="516" y="127">t (s)</text><path className="curve" d={path}/><line className="now" x1={x(t)} y1="8" x2={x(t)} y2="115"/><circle className="current" cx={x(t)} cy={y(fn(t))} r="5"/><text className="read" x={Math.min(485,x(t)+8)} y={Math.max(15,y(fn(t))-7)}>{fmt(fn(t))}</text>{secant&&kind==='x'&&<line className="secant" x1={x(t)} y1={y(fn(t))} x2={x(Math.min(m.duration,t+secant))} y2={y(fn(Math.min(m.duration,t+secant)))}/>}</svg>}
function GraphStack({m,t}:{m:Motion,t:number}){return <div className="stack"><Graph m={m} t={t}/><Graph m={m} t={t} kind="v"/><Graph m={m} t={t} kind="a"/></div>}
function FormulaFlow(){return <div className="formula-flow"><span><small>位置</small><MathText tex="x=f(t)"/></span><b>時間変化 ↓</b><span className="velocity"><small>速度</small><MathText tex={String.raw`v=\frac{dx}{dt}=f'(t)`}/></span><b>時間変化 ↓</b><span className="acceleration"><small>加速度</small><MathText tex={String.raw`a=\frac{dv}{dt}=\frac{d^2x}{dt^2}=f''(t)`}/></span></div>}

function Basic({mode}:{mode:'motion'|'average'|'instant'|'accel'|'sync'}){const [id,setId]=useState('ex21'),m=motions[id],p=usePlayer(m.duration,1),[dt,setDt]=useState(1); const avg=averageVelocity(m,Math.min(p.t,m.duration-dt),dt); return <><div className="intro"><span className="tag">{mode==='motion'?'まず動きを見る':mode==='average'?'変化量を時間で割る':mode==='instant'?'割線から接線へ':mode==='accel'?'速度の変化を見る':'完全同期'}</span><h2>{mode==='average'?'平均速度 Δx / Δt':mode==='instant'?'瞬間速度は接線の傾き':mode==='accel'?'速度グラフの傾きが加速度':'位置 → 速度 → 加速度'}</h2>{mode==='sync'&&<FormulaFlow/>}</div><div className="lab"><section className="panel"><label>自由に試す：位置関数 <select value={id} onChange={e=>{setId(e.target.value);p.setT(0)}}>{['linear','square','ex21','p39'].map(k=><option key={k} value={k}>{motions[k].label}</option>)}</select></label><NumberLine m={m} t={p.t} second={mode==='average'?Math.min(m.duration,p.t+dt):undefined}/>{mode==='motion'&&<p className="question">位置が増えていれば速度は必ず正？ 時刻を前後に動かして調べよう。</p>}{mode==='average'&&<><label className="range">Δt = <b>{dt.toFixed(2)} s</b><input aria-label="デルタ t" type="range" min=".01" max="2" step=".01" value={dt} onChange={e=>setDt(+e.target.value)}/></label><MathText block tex={String.raw`\frac{\Delta x}{\Delta t}=\frac{f(t+\Delta t)-f(t)}{\Delta t}=${fmt(avg)}\ \mathrm{m/s}`}/></>}</section><section className="panel">{mode==='motion'?<Graph m={m} t={p.t}/>:mode==='average'||mode==='instant'?<><Graph m={m} t={p.t} secant={dt}/><p>平均 {fmt(avg)} → 瞬間 {fmt(m.v(p.t))} m/s　差 {fmt(Math.abs(avg-m.v(p.t)))}</p>{mode==='instant'&&<button onClick={()=>setDt(Math.max(.01,dt/2))}>Δt → 0（半分にする）</button>}</>:mode==='accel'?<><Graph m={m} t={p.t} kind="v"/><p>速度グラフの接線の傾き = a = {fmt(m.a(p.t))} m/s²</p><p className="question">速度グラフの傾きから加速度を予想できる？</p></>:<GraphStack m={m} t={p.t}/>}</section></div><Values m={m} t={p.t}/><Controls p={p} max={m.duration}/></>}

function Example(){const [id,setId]=useState('ex21'),m=motions[id],p=usePlayer(m.duration,id==='p39'?2:1);return <><div className="intro"><span className="tag">例題21 ＋ 練習39</span><h2>速度と加速度の矢印を分けて読む</h2><div className="switch"><button className={id==='ex21'?'active':''} onClick={()=>{setId('ex21');p.setT(1)}}>例題21</button><button className={id==='p39'?'active':''} onClick={()=>{setId('p39');p.setT(2)}}>練習39</button><button onClick={()=>p.setT(id==='p39'?2:1)}>★ 指定時刻へ</button></div></div><div className="lab"><section className="panel"><MathText block tex={id==='ex21'?String.raw`x=t^2-3t,\quad v=2t-3,\quad a=2`:String.raw`x=t^3-8t+4,\quad v=3t^2-8,\quad a=6t`}/><NumberLine m={m} t={p.t}/><p className="legend"><i className="blue"/> 速度ベクトル v　<i className="orange"/> 加速度ベクトル a</p>{id==='ex21'&&Math.abs(p.t-1)<.03&&<p className="callout">速度は左向き（−1）だが、加速度は右向き（＋2）。今は減速し、やがて向きを変えます。</p>}</section><section className="panel"><GraphStack m={m} t={p.t}/></section></div><Values m={m} t={p.t}/><Controls p={p} max={m.duration}/></>}
function Throw(){const [id,setId]=useState('throw245'),m=motions[id],p=usePlayer(m.duration,id==='throw245'?2.5:0),[revealed,setRevealed]=useState(false);const apex=id==='throw245'?2.5:2;return <><div className="intro"><span className="tag">例題19 ＋ 練習40</span><h2>鉛直投げ上げ</h2><div className="switch"><button className={id==='throw245'?'active':''} onClick={()=>{setId('throw245');p.setT(0)}}>例題19：初速度24.5 m/s</button><button className={id==='throw196'?'active':''} onClick={()=>{setId('throw196');p.setT(0);setRevealed(false)}}>練習40：初速度19.6 m/s</button></div></div><div className="lab"><section className="panel throw-scene"><div className="height-label">高さ {Math.max(0,m.x(p.t)).toFixed(1)} m</div><div className="tower"><div className="marks">30 m<br/><br/>20 m<br/><br/>10 m<br/><br/>0 m</div><div className="ball" style={{bottom:`${8+Math.max(0,m.x(p.t))/32*78}%`}}>●<span className="ball-v">v {m.v(p.t)>0?'↑':m.v(p.t)<0?'↓':'= 0'}</span><span className="ball-a">a ↓</span></div></div><p>地面</p><MathText block tex={String.raw`${m.formula},\quad ${m.velocity},\quad ${m.acceleration}`}/><p className="note">−9.8 m/s² ＝ 1秒ごとに速度が9.8 m/sずつ下向きに変化する。</p></section><section className="panel"><GraphStack m={m} t={p.t}/></section></div><Values m={m} t={p.t} label="高さ"/><div className="question"><b>速度が0なら加速度も0なのか？</b>{id==='throw245'?<><button onClick={()=>p.setT(apex)}>最高点 t=2.5 s を見る</button>{Math.abs(p.t-apex)<.03&&<p>いいえ。最高点では速度 = 0 でも、重力加速度 = −9.8 m/s² は働き続けています。</p>}</>:<><p>v = 0 となる時刻を自分で求めよう。</p><button onClick={()=>setRevealed(true)}>解答を確認</button>{revealed&&<p>19.6 − 9.8t = 0 より、最高点は t = 2.0 s。</p>}</>}</div><Controls p={p} max={m.duration}/></>}

function ThreeD(){const [mode,setMode]=useState<'txv'|'tva'|'throw'>('txv'),p=usePlayer(mode==='throw'?5:4,1),canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=canvas.current;if(!c)return;const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');if(!ctx)return;ctx.scale(dpr,dpr);ctx.fillStyle='#07182c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#46617f';ctx.lineWidth=1;const O=[w*.18,h*.76],axes=[[w*.68,0],[-w*.08,-h*.52],[w*.25,-h*.16]];for(const [dx,dy] of axes){ctx.beginPath();ctx.moveTo(...O);ctx.lineTo(O[0]+dx,O[1]+dy);ctx.stroke()}ctx.fillStyle='#9fb1c6';ctx.fillText('t',w*.87,h*.8);ctx.fillText(mode==='txv'?'x':'v',w*.08,h*.19);ctx.fillText(mode==='throw'?'現実空間':mode==='txv'?'v':'a',w*.43,h*.57);const m=mode==='throw'?motions.throw245:motions.ex21,project=(t:number)=>{const X=t/m.duration,Y=mode==='txv'?m.x(t)/5:m.v(t)/6,Z=mode==='txv'?m.v(t)/5:m.a(t)/5;return[O[0]+axes[0][0]*X+axes[2][0]*Z,O[1]+axes[1][1]*(Y*.55+.2)+axes[2][1]*Z]};ctx.strokeStyle='#48a8ff';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=100;i++){const q=project(m.duration*i/100);i?ctx.lineTo(...q):ctx.moveTo(...q)}ctx.stroke();const q=project(p.t);ctx.shadowBlur=18;ctx.shadowColor='#f7c948';ctx.fillStyle='#f7c948';ctx.beginPath();ctx.arc(q[0],q[1],7,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillText('現在点',q[0]+12,q[1]-9)},[mode,p.t]);return <><div className="intro"><span className="tag">状態空間表示</span><h2>位置・速度・加速度を3Dで同時に見る</h2><div className="switch"><button onClick={()=>setMode('txv')} className={mode==='txv'?'active':''}>A (t, x, v)</button><button onClick={()=>setMode('tva')} className={mode==='tva'?'active':''}>B (t, v, a)</button><button onClick={()=>setMode('throw')} className={mode==='throw'?'active':''}>鉛直投げ上げ3D</button></div></div><section className="panel three-d"><canvas ref={canvas} aria-label="状態空間3Dグラフ"/><p>青い曲線を3軸へ投影して読み、金色の点を時刻スライダーで動かします。描画は常に背景と軸を先に描くため、ブラックアウトしません。</p>{mode==='throw'&&<p className="callout">上昇中：v ↑ / a ↓　｜　最高点：v = 0 / a ↓　｜　下降中：v ↓ / a ↓</p>}</section><Controls p={p} max={mode==='throw'?5:4}/></>}

const worldModels={car:{name:'自動車',max:8,fn:(t:number)=>({x:Math.min(t,4)**2+(t>4?(t-4)*8-(t-4)**2:0),v:t<4?2*t:Math.max(0,16-2*t),a:t<4?2:-2}),desc:'教材用の模式例です。アクセルで正の加速度、ブレーキで速度と逆向きの加速度になります。'},elevator:{name:'エレベーター',max:8,fn:(t:number)=>{const a=t<2?1:t<5?0:t<7?-1:0,v=t<2?t:t<5?2:t<7?7-t:0,x=t<2?t*t/2:t<5?2+2*(t-2):t<7?8+2*(t-5)-(t-5)**2/2:10;return{x,v,a}},desc:'上昇開始 → 加速 → 一定速度 → 減速 → 停止。減速中は速度 ↑ でも加速度 ↓ です。'},throw:{name:'鉛直投げ上げ',max:5,fn:(t:number)=>({x:motions.throw245.x(t),v:motions.throw245.v(t),a:-9.8}),desc:'例題19。最高点でも重力加速度は下向きに働き続けます。'}}
function World(){const [id,setId]=useState<keyof typeof worldModels>('car'),w=worldModels[id],p=usePlayer(w.max,0),d=w.fn(p.t),m:Motion={id,label:w.name,formula:'',velocity:'',acceleration:'',duration:w.max,x:t=>w.fn(t).x,v:t=>w.fn(t).v,a:t=>w.fn(t).a};return <><div className="intro"><span className="tag">現実世界</span><h2>同じ微分の関係を、3つの現象で探る</h2><div className="switch">{Object.entries(worldModels).map(([k,v])=><button className={id===k?'active':''} onClick={()=>{setId(k as keyof typeof worldModels);p.setT(0)}} key={k}>{v.name}</button>)}</div></div><div className="lab"><section className="panel world-scene"><div className={id==='elevator'?'elevator':id==='throw'?'world-ball':'car'} style={id==='elevator'||id==='throw'?{bottom:`${8+Math.max(0,d.x)/(id==='throw'?32:10)*75}%`}:{left:`${5+Math.max(0,d.x)/32*80}%`}}>{id==='car'?'🚙':id==='elevator'?'▣':'●'}</div><div className="ground"/><p>{w.desc}</p><p className="arrows">速度 {d.v>0?'＋ ↑/→':d.v<0?'− ↓/←':'0 ●'}　 加速度 {d.a>0?'＋ ↑/→':d.a<0?'− ↓/←':'0 ●'}</p></section><section className="panel"><GraphStack m={m} t={p.t}/></section></div><Values m={m} t={p.t} label={id==='throw'?'高さ':'位置'}/><Controls p={p} max={w.max}/></>}
function Quiz(){const qs=[['x=t²−3t の t=2 における速度 v と加速度 a は？','v = 1, a = 2'],['x=t³−8t+4 の t=2 における速度 v と加速度 a は？','v = 4, a = 12'],['y=19.6t−4.9t² が最高点に達する時刻は？','t = 2秒'],['x=t²−3t の t=1。速度と加速度の符号は？','v は負（左向き）、a は正（右向き）']];const [open,setOpen]=useState<number[]>([]);return <><div className="intro"><span className="tag">CHECK</span><h2>確認問題</h2><p>予想してから答えを開きましょう。</p></div><div className="quiz-list">{qs.map((q,i)=><article className="panel" key={i}><b>第{i+1}問</b><h3>{q[0]}</h3><button onClick={()=>setOpen(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}>{open.includes(i)?'答えを隠す':'答えを見る'}</button>{open.includes(i)&&<p className="answer">{q[1]}</p>}</article>)}</div><div className="question">さらに考えよう：加速度が一定なら速度グラフはどんな形？ 速度が一次関数なら位置はどんな関数？</div></>}
function App(){const [tab,setTab]=useState('motion');return <><header><a href="../../">← 教材一覧</a><div><span>MATHEMATICS III · DIFFERENTIAL CALCULUS</span><h1>数学Ⅲ｜速度と加速度</h1><p>位置・速度・加速度を動きとグラフで理解する</p></div><MathText tex={String.raw`x\xrightarrow{\ d/dt\ }v\xrightarrow{\ d/dt\ }a`}/></header><nav className="tabs" aria-label="教材の章">{tabs.map(([id,name])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{name}</button>)}</nav><main>{tab==='motion'&&<Basic mode="motion"/>}{tab==='average'&&<Basic mode="average"/>}{tab==='instant'&&<Basic mode="instant"/>}{tab==='accel'&&<Basic mode="accel"/>}{tab==='sync'&&<Basic mode="sync"/>}{tab==='example'&&<Example/>}{tab==='throw'&&<Throw/>}{tab==='three'&&<ThreeD/>}{tab==='world'&&<World/>}{tab==='quiz'&&<Quiz/>}</main><footer><a href="../../">数学教材ポータルへ戻る</a><span>位置を微分 → 速度を微分 → 加速度</span></footer></>}
createRoot(document.getElementById('root')!).render(<App/>)
