import katex from 'katex'

const tabs=['平面上を動く点','ベクトルとは','速度ベクトル','速さ','加速度ベクトル','例22','成分分解','現実世界','3D解析','自由探究','確認問題']
const motions={
 A:{label:'A 直線',range:5,f:t=>[t,t,1,1,0,0],eq:String.raw`x=t,\ y=t`},
 B:{label:'B 放物線',range:3,f:t=>[t,t*t,1,2*t,0,2],eq:String.raw`x=t,\ y=t^2`},
 C:{label:'C 例22',range:5,f:t=>[2*t,t*t-t,2,2*t-1,0,2],eq:String.raw`x=2t,\ y=t^2-t`},
 D:{label:'D 円運動',range:6.28,f:t=>[Math.cos(t),Math.sin(t),-Math.sin(t),Math.cos(t),-Math.cos(t),-Math.sin(t)],eq:String.raw`x=\cos t,\ y=\sin t`},
 E:{label:'E だ円運動',range:6.28,f:t=>[3*Math.cos(t),2*Math.sin(t),-3*Math.sin(t),2*Math.cos(t),-3*Math.cos(t),-2*Math.sin(t)],eq:String.raw`x=3\cos t,\ y=2\sin t`}
}
let motion=motions.C,t=1.5,playing=false,last=0,showComponents=true,tab=0,quiz=0,angleX=.55,angleY=-.65,zoom=1
const $=s=>document.querySelector(s),canvas=$('#plane'),ctx=canvas.getContext('2d'),time=$('#time')
const tex=(el,s,display=true)=>katex.render(s,el,{displayMode:display,throwOnError:false})
const fmt=n=>Math.abs(n)<.005?'0':n.toFixed(2)
tabs.forEach((name,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${name}`;b.onclick=()=>selectTab(i);$('#tabs').append(b)})

function resize(c=canvas){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(c.width!==r.width*d||c.height!==r.height*d){c.width=r.width*d;c.height=r.height*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}}
function arrow(c,x1,y1,x2,y2,color,label,dash=[]){const a=Math.atan2(y2-y1,x2-x1);c.save();c.strokeStyle=color;c.fillStyle=color;c.lineWidth=3;c.shadowColor=color;c.shadowBlur=8;c.setLineDash(dash);c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.setLineDash([]);c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-11*Math.cos(a-.45),y2-11*Math.sin(a-.45));c.lineTo(x2-11*Math.cos(a+.45),y2-11*Math.sin(a+.45));c.fill();c.shadowBlur=0;c.font='bold 13px sans-serif';c.fillText(label,x2+7,y2-7);c.restore()}
function draw(){resize();const w=canvas.clientWidth,h=canvas.clientHeight,[x,y,vx,vy,ax,ay]=motion.f(t);const vals=[];for(let i=0;i<=motion.range;i+=motion.range/80){const q=motion.f(i);vals.push(q[0],q[1])}const xmin=Math.min(-1,...vals.filter((_,i)=>i%2===0)),xmax=Math.max(2,...vals.filter((_,i)=>i%2===0)),ymin=Math.min(-2,...vals.filter((_,i)=>i%2)),ymax=Math.max(2,...vals.filter((_,i)=>i%2));const pad=42,s=Math.min((w-2*pad)/(xmax-xmin),(h-2*pad)/(ymax-ymin)),X=n=>pad+(n-xmin)*s,Y=n=>h-pad-(n-ymin)*s;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#183650';ctx.lineWidth=1;for(let n=Math.ceil(xmin);n<=xmax;n++){ctx.beginPath();ctx.moveTo(X(n),pad);ctx.lineTo(X(n),h-pad);ctx.stroke()}for(let n=Math.ceil(ymin);n<=ymax;n++){ctx.beginPath();ctx.moveTo(pad,Y(n));ctx.lineTo(w-pad,Y(n));ctx.stroke()}arrow(ctx,X(xmin),Y(0),X(xmax),Y(0),'#61809c','x');arrow(ctx,X(0),Y(ymin),X(0),Y(ymax),'#61809c','y');ctx.strokeStyle='#56a8d4';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<=t;i+=motion.range/100){const q=motion.f(i);i?ctx.lineTo(X(q[0]),Y(q[1])):ctx.moveTo(X(q[0]),Y(q[1]))}ctx.stroke();ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#829bb1';ctx.beginPath();ctx.moveTo(X(x),Y(y));ctx.lineTo(X(x),Y(0));ctx.moveTo(X(x),Y(y));ctx.lineTo(X(0),Y(y));ctx.stroke();ctx.restore();ctx.fillStyle='#cad7e2';ctx.fillText('Q',X(x)+5,Y(0)+17);ctx.fillText('R',X(0)+7,Y(y)-7);const scale=Math.min(s*.65,36);if(showComponents){arrow(ctx,X(x),Y(y),X(x)+vx*scale,Y(y),'#57e3ef','vₓ');arrow(ctx,X(x)+vx*scale,Y(y),X(x)+vx*scale,Y(y)-vy*scale,'#b394ff','vᵧ')}arrow(ctx,X(x),Y(y),X(x)+vx*scale,Y(y)-vy*scale,'#45b8ff','v');arrow(ctx,X(x),Y(y),X(x)+ax*scale,Y(y)-ay*scale,'#ff9b4a','a');if($('#tangent').checked){const k=80/Math.hypot(vx,vy);ctx.strokeStyle='#9ce9ff';ctx.setLineDash([9,5]);ctx.beginPath();ctx.moveTo(X(x)-vx*k,Y(y)+vy*k);ctx.lineTo(X(x)+vx*k,Y(y)-vy*k);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle='#ffd85e';ctx.shadowColor='#ffd85e';ctx.shadowBlur=26;ctx.beginPath();ctx.arc(X(x),Y(y),7+Math.sin(performance.now()/430)*1.5,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff1a6';ctx.font='bold 14px sans-serif';ctx.fillText(`P (${fmt(x)}, ${fmt(y)})`,X(x)+12,Y(y)-12);if(tab===8)draw3D();requestAnimationFrame(draw)}
function update(){const [x,y,vx,vy,ax,ay]=motion.f(t),sp=Math.hypot(vx,vy),am=Math.hypot(ax,ay);time.value=t;$('#tOut').value=t.toFixed(2);$('#pos').textContent=`P (${fmt(x)}, ${fmt(y)})`;tex($('#xChain'),motion===motions.C?String.raw`x=2t=${fmt(x)}\\ \frac{dx}{dt}=2\\ \frac{d^2x}{dt^2}=0`:String.raw`x=${fmt(x)}\\ \frac{dx}{dt}=${fmt(vx)}\\ \frac{d^2x}{dt^2}=${fmt(ax)}`);tex($('#yChain'),motion===motions.C?String.raw`y=t^2-t=${fmt(y)}\\ \frac{dy}{dt}=2t-1=${fmt(vy)}\\ \frac{d^2y}{dt^2}=2`:String.raw`y=${fmt(y)}\\ \frac{dy}{dt}=${fmt(vy)}\\ \frac{d^2y}{dt^2}=${fmt(ay)}`);tex($('#vFormula'),String.raw`\vec v=\left(\frac{dx}{dt},\frac{dy}{dt}\right)=(${fmt(vx)},${fmt(vy)})`);tex($('#aFormula'),String.raw`\vec a=\left(\frac{d^2x}{dt^2},\frac{d^2y}{dt^2}\right)=(${fmt(ax)},${fmt(ay)})`);tex($('#speed'),String.raw`|\vec v|=\sqrt{(${fmt(vx)})^2+(${fmt(vy)})^2}=${fmt(sp)}`,false);tex($('#accMag'),String.raw`|\vec a|=\sqrt{(${fmt(ax)})^2+(${fmt(ay)})^2}=${fmt(am)}`,false)}
function selectTab(i){tab=i;[...$('#tabs').children].forEach((b,j)=>b.classList.toggle('active',i===j));const L=$('#lesson');const common={0:['時刻から軌跡へ','スライダーを動かし、P と x 軸上の Q、y 軸上の R が同期する様子を観察しよう。','時刻 t → 座標 → 点P → 軌跡'],1:['ベクトルとは','ベクトルは「大きさ」と「向き」をもつ量。位置の変化を矢印で比べよう。','成分は横と縦の移動量'],2:['速度ベクトル','水色の x 成分と紫の y 成分を合成すると、青い速度ベクトルになる。','速度は軌跡の接線方向'],3:['速さ','速度の「大きさ」が速さ。横・縦・斜辺の直角三角形を探そう。','なぜ平方根が現れる？'],4:['加速度ベクトル','加速度は速度ベクトルの変化。運動方向と同じとは限らない。','速度と加速度の向きが違うと？'],5:['例22','x=2t、y=t²−t。t=3 ボタンで教科書の値を図と結びつけよう。','P=(6,6), v=(2,5), a=(0,2)'],6:['成分分解','t=3 では (2,0)+(0,5)=(2,5)。a=(0,2) なので横方向には速度変化なし。','数字 2 と 5 は図のどこ？']}[i];if(common){L.innerHTML=`<h2>${common[0]}</h2><div class="lesson-grid"><div class="mini"><h3>観察</h3><p>${common[1]}</p></div><div class="mini"><h3>つながり</h3><p>${common[2]}</p></div><div class="mini"><h3>探究</h3><p>${$('#insight').textContent}</p></div></div>`}else if(i===7){L.innerHTML=`<h2>現実世界の模式モデル</h2><div class="lesson-grid"><div class="mini"><h3>🚁 ドローン</h3><p>上空から見た位置と進行方向（速度）、速度の変化（加速度）。</p></div><div class="mini"><h3>🤖 自動運転・ロボット</h3><p>曲線コースでは速度と加速度が異なる方向を向く。</p></div><div class="mini"><h3>🏀 スポーツ</h3><p>選手が方向転換するときの位置・速度・加速度。</p></div></div><p>※ 理解のための数学的な模式モデルであり、実際の空気抵抗等は省略しています。</p>`}else if(i===8){L.innerHTML='<h2>時間を高さにした 3D 解析</h2><p>横 x・奥行 y・高さ t の空間曲線 <b>(x(t), y(t), t)</b>。ドラッグで回転、ホイール／ピンチで拡大縮小できます。</p><canvas id="space3d" aria-label="時間を第3軸にした空間曲線"></canvas>'}else if(i===9){L.innerHTML=`<h2>自由探究</h2><p>運動を切り替えて、軌跡・速度・加速度を比較しよう。円運動では青は接線方向、オレンジは中心方向になる。</p><div class="motion-picker">${Object.entries(motions).map(([k,m])=>`<button data-motion="${k}">${m.label}: \(${m.eq}\)</button>`).join('')}</div><div class="question">円運動では、速度と加速度はどのような角度になる？</div>`;L.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>setMotion(b.dataset.motion));renderInline()}else quizRender();update()}
function renderInline(){$('#lesson').querySelectorAll('button').forEach(b=>{const m=b.textContent.match(/(.*): \\?\((.*)\\?\)/);if(m){b.textContent=m[1]+': ';const s=document.createElement('span');b.append(s);tex(s,m[2],false)}})}
const qs=[['速度ベクトルを求めよ：x=2t, y=t²−t','各成分を t で1回微分。','\\vec v=(2,2t-1)'],['加速度ベクトルを求めよ。','速度の各成分をもう1回微分。','\\vec a=(0,2)'],['t=3 での速さは？','v=(2,5) の大きさ。','|\\vec v|=\\sqrt{29}'],['v=(3,4) のとき速さは？','直角三角形を思い出そう。','5'],['円運動の速度と加速度の向きは？','青とオレンジの角度を観察。','互いに垂直（加速度は中心向き）']]
function quizRender(){const q=qs[quiz];$('#lesson').innerHTML=`<h2>確認問題 ${quiz+1} / 5</h2><div class="mini"><h3>${q[0]}</h3><p id="quizText">自分の言葉・式で考えてから確認しよう。</p><div class="quiz-actions"><button id="hint">ヒント</button><button id="answer">解答を見る</button><button id="next">次へ</button></div></div>`;$('#hint').onclick=()=>$('#quizText').textContent=q[1];$('#answer').onclick=()=>tex($('#quizText'),q[2]);$('#next').onclick=()=>{quiz=(quiz+1)%qs.length;quizRender()}}
function setMotion(k){motion=motions[k];time.max=motion.range;t=Math.min(t,motion.range);update()}
time.addEventListener('input',e=>{t=+e.target.value;playing=false;update()});$('#play').onclick=()=>playing=true;$('#pause').onclick=()=>playing=false;$('#reset').onclick=()=>{playing=false;t=0;update()};$('#jump').onclick=()=>{motion=motions.C;time.max=5;const from=t,start=performance.now();const go=now=>{t=from+(3-from)*Math.min(1,(now-start)/650);update();if(now-start<650)requestAnimationFrame(go);else{$('.stage').classList.add('flash');setTimeout(()=>$('.stage').classList.remove('flash'),1000)}};requestAnimationFrame(go)};$('#components').onclick=()=>{showComponents=!showComponents;$('#components').setAttribute('aria-pressed',showComponents)};$('#compose').onclick=()=>{$('.stage').classList.add('compose');showComponents=true;setTimeout(()=>$('.stage').classList.remove('compose'),850)}
function draw3D(){const c=$('#space3d');if(!c)return;resize(c);const g=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight;g.clearRect(0,0,w,h);const proj=(x,y,z)=>{let X=x*Math.cos(angleY)-y*Math.sin(angleY),Y=x*Math.sin(angleY)+y*Math.cos(angleY),Z=z;const yy=Y*Math.cos(angleX)-Z*Math.sin(angleX);return[w/2+X*24*zoom,h*.78+yy*20*zoom]};g.strokeStyle='#25415e';for(let i=-4;i<=4;i++){let a=proj(i,-4,0),b=proj(i,4,0);g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke();a=proj(-4,i,0);b=proj(4,i,0);g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke()}g.strokeStyle='#57e3ef';g.lineWidth=3;g.beginPath();for(let u=0;u<=motion.range;u+=motion.range/90){const q=motion.f(u),p=proj(q[0],q[1],u);u?g.lineTo(...p):g.moveTo(...p)}g.stroke();const q=motion.f(t),p=proj(q[0],q[1],t),pv=proj(q[0]+q[2]*.4,q[1]+q[3]*.4,t+.4);arrow(g,...p,...pv,'#45b8ff','v');g.fillStyle='#ffd85e';g.shadowColor='#ffd85e';g.shadowBlur=24;g.beginPath();g.arc(...p,7,0,7);g.fill();g.shadowBlur=0;g.fillText('P(x(t), y(t), t)',p[0]+10,p[1]-10)}
document.addEventListener('pointerdown',e=>{if(e.target.id==='space3d'){e.target.setPointerCapture(e.pointerId);e.target._p=[e.clientX,e.clientY]}});document.addEventListener('pointermove',e=>{const c=$('#space3d');if(c?._p){angleY+=(e.clientX-c._p[0])*.008;angleX+=(e.clientY-c._p[1])*.008;c._p=[e.clientX,e.clientY]}});document.addEventListener('pointerup',()=>{const c=$('#space3d');if(c)c._p=null});document.addEventListener('wheel',e=>{if(e.target.id==='space3d'){e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom-e.deltaY*.001))}},{passive:false})
function loop(now){if(playing){t+=(now-last)/1000*+$('#rate').value;if(t>motion.range)t=0;update()}last=now;requestAnimationFrame(loop)}
selectTab(0);update();requestAnimationFrame(loop);requestAnimationFrame(draw)
