import {useEffect,useMemo,useRef} from 'react'
import {Canvas,useFrame,useThree} from '@react-three/fiber'
import {Html,Line,OrbitControls} from '@react-three/drei'
import * as THREE from 'three'
import {FontLoader} from 'three/examples/jsm/loaders/FontLoader.js'
import {TextGeometry} from 'three/examples/jsm/geometries/TextGeometry.js'
import fontData from './e-font.json'
import {compound,convergencePoints,graphPoints,logA,secant,derivative,limitExperiment,type Parameters,type Vec3} from './model'
const cyan='#69d7dc',gold='#e8bc73',red='#ee8a93'
type Props={chapter:number;p:Parameters;time:number;movie:boolean;flat:boolean;reveal:boolean;highlight:string;effects:boolean;node:string}
function Pulse({position,color=gold,time,effects}:{position:Vec3;color?:string;time:number;effects:boolean}){const pulse=effects?1+.16*Math.sin(time*4):1;return <group position={position}><mesh scale={pulse}><sphereGeometry args={[.07,16,12]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={3}/></mesh><mesh scale={pulse}><sphereGeometry args={[.17,12,12]}/><meshBasicMaterial color={color} transparent opacity={.12} depthWrite={false}/></mesh></group>}
function Camera({movie,flat,time,chapter}:{movie:boolean;flat:boolean;time:number;chapter:number}){const {camera}=useThree();const controls=useRef<any>(null);useEffect(()=>{camera.position.set(flat?2:7,flat?1.2:4,flat?12:11);controls.current?.target.set(2,1.2,0);controls.current?.update()},[flat,movie,camera]);useFrame(()=>{if(movie){const z=chapter===3?8.8:12;camera.position.set(3.1+Math.sin(time*.1)*2.2,2.6+Math.cos(time*.13)*1.1,z);camera.lookAt(2.6,1.4,0)}});return <OrbitControls ref={controls} enabled={!movie} enableRotate={!flat} enableDamping minDistance={3} maxDistance={28} target={[2,1.2,0]}/>}
function World(props:Props){const {chapter,p,time,movie,flat,reveal,highlight,effects,node}=props
 const line=useMemo(()=>graphPoints(p.a),[p.a]),inverse=useMemo(()=>graphPoints(p.a,true),[p.a]);const eg=useMemo(()=>{const font=new FontLoader().parse(fontData);const g=new TextGeometry('e',{font,size:2.4,depth:.28,curveSegments:20,bevelEnabled:true,bevelThickness:.04,bevelSize:.04,bevelSegments:3});g.center();return g},[]);useEffect(()=>()=>eg.dispose(),[eg]);
 const h=p.h,x=p.x,y=logA(x,p.a),valid=x+h>0&&h!==0,s=secant(x,h,p.a),d=derivative(x,p.a),glow=(id:string)=>highlight===id?5:2
 const boxes=Array.from({length:36},(_,i)=>{const u=i/35;const v=Math.exp(Math.log1p(1/p.n)*p.n*u);return {x:-2+(i%9)*.75,z:-1-Math.floor(i/9)*.9,h:v*(.3+(i%5)*.12)}})
 return <><color attach="background" args={['#080e18']}/><fog attach="fog" args={['#080e18',20,45]}/><ambientLight intensity={.65}/><directionalLight position={[5,7,6]} intensity={2.5} color="#d6e9f4"/><pointLight position={[2,4,3]} intensity={55} color={gold}/><pointLight position={[-3,1,2]} intensity={40} color={cyan}/><Camera {...{movie,flat,time,chapter}}/><gridHelper args={[26,26,'#283c4b','#14232f']} position={[2,-1.5,-2]} rotation={[0,0,0]}/>
 {chapter===0&&<group>{boxes.map((b,i)=><group key={i} position={[b.x,-1.5,b.z]}><mesh position={[0,b.h/2,0]}><boxGeometry args={[.42,b.h,.48]}/><meshStandardMaterial metalness={.5} roughness={.25} color={i%3===0?gold:'#2c5968'} emissive={i%3===0?gold:cyan} emissiveIntensity={.15}/></mesh><Pulse position={[0,b.h+.05,0]} time={time+i} effects={effects}/></group>)}<Line points={Array.from({length:100},(_,i)=>{const u=i/99;return [-2+u*7,Math.exp(p.n*Math.log1p(1/p.n)*u)-1.5,1] as Vec3})} color={cyan} lineWidth={3}/></group>}
 {chapter===1&&<><Line points={[[0,0,0],[6,0,0]]} color="#758a9a" lineWidth={2}/><Line points={convergencePoints()} color={cyan} lineWidth={3}/><Line points={convergencePoints(true)} color={red} lineWidth={3}/>{[1,-1].map(sign=>{const q=sign*Math.abs(h);return <Pulse key={sign} position={[-Math.log10(Math.abs(q))-1,(limitExperiment(q)-2.5)*10,sign*.55]} color={sign>0?cyan:red} time={time} effects={effects}/>})}{reveal&&<Line points={[[0,(Math.E-2.5)*10,0],[6,(Math.E-2.5)*10,0]]} color={gold} dashed dashSize={.1} gapSize={.1}/>}</>}
 {chapter>=2&&line.length>1&&<><Html position={[7,0,0]} center><span className='axis-label'>x</span></Html><Html position={[0,5,0]} center><span className='axis-label'>y</span></Html><Html position={[0,0,-3]} center><span className='axis-label'>z</span></Html><Html position={[1,-.3,0]} center><span className='axis-label'>1</span></Html><Html position={[-.3,1,0]} center><span className='axis-label'>1</span></Html><Line points={[[-1,0,0],[7,0,0]]} color="#8195a5" lineWidth={1.5}/><Line points={[[0,-3,0],[0,5,0]]} color="#8195a5" lineWidth={1.5}/><Line points={[[0,0,-3],[0,0,3]]} color="#334858" dashed dashSize={.15} gapSize={.15}/><Line points={line} color={cyan} lineWidth={highlight==='curve'?5:3}/>{(chapter===2||node==='exp')&&<><Line points={inverse} color={gold} lineWidth={3}/><Line points={[[-1,-1,0],[5,5,0]]} color="#6a7c8e" dashed dashSize={.1} gapSize={.1}/></>}
 {chapter>=3&&<><Pulse position={[x,y,0]} time={time} effects={effects}/>{valid&&<><Pulse position={[x+h,logA(x+h,p.a),0]} time={time+.5} effects={effects} color={red}/><Line points={[[Math.max(.08,x-1),y+s*(Math.max(.08,x-1)-x),0],[x+1.3,y+s*1.3,0]]} color={red} lineWidth={highlight==='h'?5:2}/><Line points={[[x,y,0],[x+h,y,0],[x+h,logA(x+h,p.a),0]]} color="#b59c9f" dashed dashSize={.08} gapSize={.06}/></>}<Line points={[[Math.max(.08,x-1),y+d*(Math.max(.08,x-1)-x),.01],[x+1.4,y+d*1.4,.01]]} color={gold} lineWidth={highlight==='slope'?5:3}/></>}
 {chapter===5&&node==='integral'&&<group>{Array.from({length:36},(_,i)=>{const q=1+(x-1)*(i+.5)/36,height=1/q;return <mesh key={i} position={[q,height/2,-.08]}><boxGeometry args={[Math.max(.01,Math.abs(x-1)/36),height,.05]}/><meshStandardMaterial color={x>=1?gold:red} transparent opacity={.5}/></mesh>})}<Line points={Array.from({length:100},(_,i)=>{const q=.2+i/99*5.8;return [q,1/q,-.08] as Vec3})} color={red} lineWidth={3}/></group>}
 </>}
 {chapter===4&&reveal&&(!movie||p.a===Math.E)&&<mesh geometry={eg} position={[4,2.7,.8]} rotation={[0,-.15+Math.sin(time*.2)*.08,0]} scale={effects?1+.035*Math.sin(time*3):1}><meshStandardMaterial color={gold} emissive={gold} emissiveIntensity={glow('e')*.25} metalness={.8} roughness={.22}/></mesh>}
 <points rotation={[0,0,effects?time*.015:0]}><bufferGeometry><bufferAttribute attach="attributes-position" args={[new Float32Array(Array.from({length:56},(_,i)=>{const angle=i*2.399;return [Math.cos(angle)*(3+i*.045)+2,Math.sin(angle)*(2+i*.035)+1,-2-i%5]}).flat()),3]}/></bufferGeometry><pointsMaterial color={cyan} size={.025} transparent opacity={.5} sizeAttenuation/></points></>
}
export function Scene(props:Props){return <Canvas frameloop={props.movie?'demand':'always'} dpr={props.movie?.75:[1,1.5]} camera={{fov:42,near:.1,far:100,position:[7,4,11]}} gl={{antialias:true,preserveDrawingBuffer:true}}><World {...props}/></Canvas>}
