const tabs=['接線とは','接線の方程式','例：y=log x','外部点からの接線','例：y=eˣ と原点','練習22・23','現実世界','3D発展','自由に試す','確認問題'];
const app=document.querySelector('#app'), nav=document.querySelector('#tabs');
let tab=0, a=1, h=1.5, step=0, freeFn='square', mode='point', animation;

nav.innerHTML=tabs.map((x,i)=>`<button data-tab="${i}" class="${i===0?'active':''}"><span>${i+1}</span>${x}</button>`).join('');
nav.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=+b.dataset.tab;step=0;render();nav.querySelectorAll('button').forEach((x,i)=>x.classList.toggle('active',i===tab));scrollTo({top:120,behavior:'smooth'})});
document.querySelector('#guideBtn').onclick=()=>document.querySelector('#guide').showModal();
document.querySelectorAll('.close').forEach(x=>x.onclick=()=>document.querySelector('#guide').close());

const funcs={square:{label:'y=x²',f:x=>x*x,d:x=>2*x,domain:[-3,3]},cube:{label:'y=x³',f:x=>x**3,d:x=>3*x*x,domain:[-2.1,2.1]},log:{label:'y=log x',f:Math.log,d:x=>1/x,domain:[.12,5.2]},exp:{label:'y=eˣ',f:Math.exp,d:Math.exp,domain:[-2.5,2.2]},sqrt:{label:'y=√x',f:Math.sqrt,d:x=>1/(2*Math.sqrt(x)),domain:[.04,5]},sin:{label:'y=sin x',f:Math.sin,d:Math.cos,domain:[-4,4]}};
const fmt=n=>Math.abs(n)<.0001?'0':Math.abs(n-Math.round(n))<.001?String(Math.round(n)):n.toFixed(2);
const head=(n,title,desc)=>`<header class="chapter-head"><span class="num">CH.${String(n).padStart(2,'0')}</span><div><h2>${title}</h2><p>${desc}</p></div></header>`;
const graphPanel=(badge,control='')=>`<section class="panel"><div class="panel-title"><span>GRAPH VIEW</span><span class="legend"><i><span class="dot" style="background:#ffc84a"></span>接点 A</i><i><span class="dot" style="background:#18c89b"></span>接線</i><i><span class="dot" style="background:#ff8a3d"></span>割線</i></span></div><div class="graph-wrap"><canvas id="graph"></canvas><span class="graph-badge">${badge}</span><div id="match"></div></div>${control?`<div class="controls">${control}</div>`:''}</section>`;
const range=(id,label,value,min,max,stepv)=>`<label class="range" for="${id}">${label}：<strong id="${id}Out">${fmt(value)}</strong><input id="${id}" type="range" value="${value}" min="${min}" max="${max}" step="${stepv}"><span class="range-row"><span>${min}</span><span>${max}</span></span></label>`;
const question=t=>`<aside class="question"><b>THINK!</b><p>${t}</p></aside>`;

function standardPage(kind='square'){
 const fn=funcs[kind], external=tab===3, title=tab===0?'接線は「近づけた割線」の行き先':tab===1?'1点と傾きから、直線を組み立てる':'外部点を通る条件が、接点を決める';
 const desc=tab===0?'BをAへ近づけ、2点を通る割線が接線へ変わる瞬間を見よう。':tab===1?'接点を動かすと、座標・微分係数・方程式がひとつながりに更新されます。':'接点候補を動かし、接線が外部点Pを通る場所を探そう。';
 app.innerHTML=head(tab+1,title,desc)+`<div class="workspace">${graphPanel(fn.label,`${range('a',external?'接点候補 a':'接点 a',a,-2.4,2.4,.02)}${tab===0?range('h','AからBまでの距離 h',h,.02,2,.02):''}`)}<section class="panel math-panel"><p class="eyebrow">LIVE EQUATION</p><h3>図と式をつなぐ</h3><div class="stats"><div class="stat">接点 A<b>(${fmt(a)}, ${fmt(fn.f(a))})</b></div><div class="stat">傾き m<b>${fmt(fn.d(a))}</b></div></div><div class="step-list"><div class="step active"><b>POINT</b>A (${fmt(a)}, ${fmt(fn.f(a))})</div><div class="step ${tab>0?'active':''}"><b>SLOPE</b>m = f′(a) = ${fmt(fn.d(a))}</div><div class="step active"><b>POINT–SLOPE FORM</b>y − ${fmt(fn.f(a))} = ${fmt(fn.d(a))}(x − ${fmt(a)})</div></div><div class="formula-big">\\(y-f(a)=f'(a)(x-a)\\)</div>${question(external?'なぜ、未知の接点を A(a, f(a)) とおくとよいのだろう？':'接線とは本当に「曲線と1点だけで交わる直線」だろうか？')}</section></div>`;
 bindRange('a',v=>a=v);if(tab===0)bindRange('h',v=>h=v);startGraph({fn,secant:tab===0,external});
}

const lessonData={2:{title:'例：y=log x',desc:'A(e, 1) における接線を、微分から1段ずつ導こう。',fn:'log',a:Math.E,steps:['f(x)=\\log x',"f'(x)=\\dfrac1x","f'(e)=\\dfrac1e",'y-1=\\dfrac1e(x-e)','y=\\dfrac1e x']},4:{title:'例：y=eˣ と原点',desc:'候補を動かし、「原点を通る」という条件から a=1 を発見しよう。',fn:'exp',a:1,steps:['A(a,e^a) とおく','傾きは e^a','y-e^a=e^a(x-a)','y=e^ax+e^a(1-a)','0=e^a(1-a)','e^a\\ne0 より a=1','接点は (1,e)','y=ex']}};
function examplePage(which){const d=lessonData[which],fn=funcs[d.fn],isExp=which===4;if(!isExp)a=d.a; const shownA=isExp?a:d.a;const matched=isExp&&Math.abs(a-1)<.035;
 app.innerHTML=head(which+1,d.title,d.desc)+`<div class="workspace">${graphPanel(fn.label,`${isExp?range('a','接点候補 a',a,-1,2,.01):'<p><span class="glow-sample"></span> 接点 A(e, 1) を固定して観察</p>'}`)}<section class="panel math-panel"><p class="eyebrow">STEP BY STEP</p><div class="step-list">${d.steps.map((x,i)=>`<div class="step ${i===step?'active':''}"><b>STEP ${i+1}</b>\\(${x}\\)</div>`).join('')}</div><div class="step-controls"><button id="prev" class="secondary">← 戻る</button><button id="next" class="primary">次の式へ →</button></div>${matched?'<div class="formula-big">条件成立！ ここが接点 A(1, e)</div>':''}${question(isExp?'「原点を通る条件」は、式のどこに使われている？':'なぜ最後の式は原点を通ると分かる？')}</section></div>`;
 if(isExp)bindRange('a',v=>a=v);document.querySelector('#prev').onclick=()=>{step=Math.max(0,step-1);examplePage(which)};document.querySelector('#next').onclick=()=>{step=Math.min(d.steps.length-1,step+1);examplePage(which)};startGraph({fn,a:shownA,external:isExp,origin:true,matched,thick:true});
}
function practice(){const ps=[['練習22 (1)','y=x²/4−1/2, A(2,1)','f′(2)=1 より y=x−1'],['練習22 (2)','y=x³, A(0,0)','f′(0)=0 より y=0'],['練習23 (1)','y=log x, P(0,0)','a=e、接線 y=x/e'],['練習23 (2)','y=√x, P(0,1)','a=4、接線 y=x/4+1']];app.innerHTML=head(6,'練習22・23','まず自分で考える「問題モード」と、接点まで確認する「解説モード」。')+`<div class="practice-grid">${ps.map((p,i)=>`<article class="problem"><p class="eyebrow">${p[0]}</p><h3>\\(${p[1]}\\)</h3><button class="secondary reveal">ヒント・解説を見る</button><div class="answer"><b>解説</b><p>\\(${p[2]}\\)</p><p>接点と傾きを点傾き形式へ代入しよう。</p></div></article>`).join('')}</div>${question('答えを開く前に、接点の x 座標を a とおいた式を作れる？')}`;document.querySelectorAll('.reveal').forEach(b=>b.onclick=()=>b.closest('.problem').classList.toggle('open'));typeset()}
function realWorld(){app.innerHTML=head(7,'現実世界の「その瞬間の向き」','接線は計算の道具だけでなく、動いているものの今の向きを表します。')+`<div class="cards"><article class="info-card"><p class="eyebrow">A / ROAD</p><h3>曲がった道と車</h3><p>車の前方はいつも進行方向、つまり道路の接線方向を向きます。</p><div class="road"><span class="car" aria-label="右向きの車">🚙</span><span class="direction">接線方向 →</span></div></article><article class="info-card"><p class="eyebrow">B / SLOPE</p><h3>コースター</h3><p>小球が曲線上を移動する瞬間、その進む向きは接線の矢印です。</p><div class="road"><span class="car">●</span><span class="direction">瞬間の向き →</span></div></article><article class="info-card"><p class="eyebrow">C / LIGHT</p><h3>ライトと反射</h3><p>曲面の「その場の向き」を接線で捉えることが、反射を考える入口になります。</p><div class="formula-big">曲線 → 接点 → その場の向き</div></article></div>${question('道のカーブが急になると、接線の向きはどのように変わる？')}`}
function threeD(){app.innerHTML=head(8,'3D発展：接線から接平面へ','2Dの考えを少し浮かせて眺めよう。主役は緑の接線方向です。')+`<div class="workspace"><section class="panel"><div class="panel-title">3D VIEW <span>ドラッグ不要・安定表示</span></div><div class="three-d"><div class="surface"></div><div class="three-line"></div><span class="glow-sample pulse3d"></span></div></section><section class="panel math-panel"><p class="eyebrow">EXTENSION</p><h3>曲線を空間に置く</h3><div class="formula-big">\\((x,y,z)=(x,f(x),0)\\)</div><p>金色の点での緑の線が接線方向。曲面 \\(z=f(x,y)\\) では、2方向の傾きを合わせた<strong>接平面</strong>へ考えが広がります。</p>${question('1本の接線から、面に接する「平面」へは何が必要だろう？')}</section></div>`;typeset()}
function free(){const fn=funcs[freeFn];app.innerHTML=head(9,'自由に試す','関数とモードを選び、自分だけの予想を図で確かめよう。')+`<div class="selector" id="fnSelect">${Object.entries(funcs).map(([k,v])=>`<button data-fn="${k}" class="${k===freeFn?'active':''}">${v.label}</button>`).join('')}</div><div class="selector"><button id="pointMode" class="${mode==='point'?'active':''}">曲線上の点</button><button id="externalMode" class="${mode==='external'?'active':''}">外部点から</button></div><div class="workspace">${graphPanel(fn.label,range('a','接点 a',a,fn.domain[0],fn.domain[1],.02))}<section class="panel math-panel"><p class="eyebrow">YOUR LAB</p><div class="stats"><div class="stat">接点<b>(${fmt(a)}, ${fmt(fn.f(a))})</b></div><div class="stat">f′(a)<b>${fmt(fn.d(a))}</b></div></div><div class="formula-big">y − ${fmt(fn.f(a))} = ${fmt(fn.d(a))}(x − ${fmt(a)})</div>${question('関数を変えると、傾きの変わり方にはどんな違いがある？')}</section></div>`;bindRange('a',v=>a=v);document.querySelector('#fnSelect').onclick=e=>{if(e.target.dataset.fn){freeFn=e.target.dataset.fn;a=freeFn==='log'||freeFn==='sqrt'?1:0.7;free()}};document.querySelector('#pointMode').onclick=()=>{mode='point';free()};document.querySelector('#externalMode').onclick=()=>{mode='external';free()};startGraph({fn,external:mode==='external',origin:mode==='external'})}
function quiz(){const qs=[['第1問','y=x² の x=1 における接線','ヒント：f′(1)=2','y=2x−1'],['第2問','y=log x の x=e における接線','ヒント：f′(e)=1/e','y=x/e'],['第3問','y=eˣ に原点から引いた接線','ヒント：0=eᵃ(1−a)','接点 (1,e)、y=ex'],['第4問','右下がりの曲線上で、接線の傾きの符号は？','右へ進んだときの y の変化を見る','負'],['第5問','接点を (a,f(a)) とおく意味は？','曲線上の点が満たす関係に注目','未知の接点が必ず曲線上にあることを表す']];app.innerHTML=head(10,'確認問題','ヒント → 答えの順に開き、理解を確かめよう。')+`<div class="practice-grid">${qs.map(q=>`<article class="problem"><p class="eyebrow">${q[0]}</p><h3>${q[1]}</h3><div class="quiz-actions"><button class="secondary hint">ヒント</button><button class="primary reveal">答え</button></div><p class="hintText" hidden>${q[2]}</p><div class="answer"><b>ANSWER</b><p>${q[3]}</p></div></article>`).join('')}</div>`;document.querySelectorAll('.hint').forEach(b=>b.onclick=()=>b.closest('.problem').querySelector('.hintText').hidden=false);document.querySelectorAll('.reveal').forEach(b=>b.onclick=()=>b.closest('.problem').classList.toggle('open'))}

function bindRange(id,callback){document.querySelector(`#${id}`).addEventListener('input',e=>{callback(+e.target.value);render()})}
function render(){cancelAnimationFrame(animation);if(tab<=1||tab===3)standardPage();else if(tab===2||tab===4)examplePage(tab);else if(tab===5)practice();else if(tab===6)realWorld();else if(tab===7)threeD();else if(tab===8)free();else quiz();typeset()}
function typeset(){if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([app]).catch(()=>{})}

function startGraph(o){const canvas=document.querySelector('#graph');if(!canvas)return;const ctx=canvas.getContext('2d'),fn=o.fn;let t=0;function draw(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(canvas.width!==rect.width*dpr||canvas.height!==rect.height*dpr){canvas.width=rect.width*dpr;canvas.height=rect.height*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,hg=rect.height;ctx.clearRect(0,0,w,hg);const xMin=fn.domain[0],xMax=fn.domain[1];let samples=[];for(let i=0;i<=250;i++){let x=xMin+(xMax-xMin)*i/250,y=fn.f(x);if(Number.isFinite(y)&&Math.abs(y)<30)samples.push([x,y])}let ys=samples.map(p=>p[1]);let yMin=Math.min(...ys,0),yMax=Math.max(...ys,0);let pad=(yMax-yMin)*.18+.3;yMin-=pad;yMax+=pad;const X=x=>40+(x-xMin)/(xMax-xMin)*(w-65),Y=y=>hg-32-(y-yMin)/(yMax-yMin)*(hg-55);ctx.strokeStyle='#dfe7ef';ctx.lineWidth=1;for(let i=0;i<7;i++){let x=40+i*(w-65)/6;ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,hg-32);ctx.stroke()}for(let i=0;i<6;i++){let y=15+i*(hg-47)/5;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-25,y);ctx.stroke()}ctx.strokeStyle='#7d8b9d';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(40,Y(0));ctx.lineTo(w-25,Y(0));ctx.moveTo(X(0),15);ctx.lineTo(X(0),hg-32);ctx.stroke();ctx.strokeStyle='#2387d8';ctx.lineWidth=3;ctx.beginPath();samples.forEach((p,i)=>i?ctx.lineTo(X(p[0]),Y(p[1])):ctx.moveTo(X(p[0]),Y(p[1])));ctx.stroke();let aa=o.a??a;if(aa<xMin)aa=xMin;if(aa>xMax)aa=xMax;const ay=fn.f(aa),slope=fn.d(aa);line(aa,ay,slope,'#18c89b',5,o.matched);if(o.secant){let bx=Math.min(xMax,aa+h),by=fn.f(bx),m=(by-ay)/(bx-aa);line(aa,ay,m,`rgb(255,${Math.round(138+(1-Math.min(h/2,1))*62)},${Math.round(61+(1-Math.min(h/2,1))*90)})`,3);point(bx,by,'B','#ff8a3d',false)}if(o.external||o.origin){point(0,0,o.origin?'O':'P','#ff5d62',false)}point(aa,ay,'A','#ffc84a',true);if(o.matched){document.querySelector('#match').innerHTML='<span class="match">✦ 条件成立・ここが接点！</span>'}function line(px,py,m,c,l,glow){let x1=xMin,x2=xMax;ctx.save();ctx.strokeStyle=c;ctx.lineWidth=l;ctx.shadowBlur=glow?22:8;ctx.shadowColor=c;ctx.beginPath();ctx.moveTo(X(x1),Y(py+m*(x1-px)));ctx.lineTo(X(x2),Y(py+m*(x2-px)));ctx.stroke();ctx.restore()}function point(x,y,label,c,pulse){let r=(pulse?7+Math.sin(t)*2:6);ctx.save();ctx.fillStyle=c;ctx.shadowBlur=pulse?20:12;ctx.shadowColor=c;ctx.beginPath();ctx.arc(X(x),Y(y),r,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#10243d';ctx.font='700 12px sans-serif';ctx.fillText(label,X(x)+11,Y(y)-10);ctx.restore()}t+=.08;animation=requestAnimationFrame(draw)}draw()}
render();
