import {tourIds,sceneSeconds,routeBetween,demoState} from './tour.js';
import './style.css';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import {concepts,byId,connections,chapters,subjects,relations} from './data.js';
import {Universe,SolidModel} from './universe.js';
import {createModelState,modelNames,modelControls,renderModel,toss,sample,morphContour} from './models.js';
const $=(s)=>document.querySelector(s);
const math=(latex)=>katex.renderToString(latex,{throwOnError:false,strict:false,output:'html',displayMode:true});
const icon=(name)=>({play:'▷',pause:'Ⅱ',prev:'←',next:'→',map:'✦',expand:'⛶',search:'⌕'}[name]);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let modelStart=0,frozenModelTime=0,activeMorph=null,effectsTime=0,focusPart='all',lastInteraction=-10;
let pulseEnabled=!matchMedia('(prefers-reduced-motion: reduce)').matches;
let touring=false,tourIndex=0,tourElapsed=0;
let selected=null,chapter=0,step=0,playing=false,motion=!reduced,time=0,chapterElapsed=0,last=0,modelState=createModelState(),model='circle',manual=false,showFormula=true,showExplanation=true,mode='explore',model3d=false,lastModel=0,lastMath='',quiz=false,quizTarget=null,sequenceTimers=[];
$('#app').innerHTML=`
<header class="header"><a class="brand" href="#" aria-label="全体マップへ"><span class="brand-mark">✳</span><span>MATHEMATICS <small>GENEALOGY</small></span></a><nav class="mode-switch" aria-label="教材モード"><button data-mode="explore" class="active">自由探索</button><button data-mode="cinema">自動再生</button><button data-mode="inquiry">探究</button></nav><a class="library-link" href="../../">← 教材一覧</a><button id="help" class="quiet-button">使い方 <span>?</span></button></header>
<main>
<section class="intro"><div><div class="eyebrow">A CONSTELLATION OF IDEAS <span class="mini-line"></span></div><h1>高校数学の<span>系譜</span></h1><p>すべての数学は、つながっている。</p></div><div class="intro-note"><span class="live-dot"></span> KNOWLEDGE UNIVERSE<br><strong id="counts"></strong><small>一つの考えから、次の数学へ。</small></div></section>
<div class="workspace">
<section class="map-section" aria-label="3D数学系譜MAP"><div class="map-top"><span class="map-label">数学系譜 MAP <small id="map-status">3D EXPLORATION</small></span><div class="map-actions"><button id="dimension" class="small-button active" aria-pressed="true">3D</button><button id="auto-rotate" class="small-button" aria-pressed="false">自動回転</button><button id="map-reset" class="small-button" title="全体MAPへ戻る">全体へ ↗</button></div></div>
<div id="universe"><div class="orbit-ring orbit-one"></div><div class="orbit-ring orbit-two"></div></div><div id="cinema-overlay" hidden><div class="cinema-eyebrow">PROLOGUE</div><h2>数学の宇宙</h2><p>数、式、図形から、ひとつの体系へ。</p></div>
<div class="map-bottom"><span><span class="mouse-hint">↔</span> ドラッグで回転 · ピンチ／スクロールで拡大</span><div><button id="zoom-out" aria-label="縮小">−</button><button id="zoom-in" aria-label="拡大">＋</button><button id="fullscreen" aria-label="全画面">⛶</button></div></div>
</section>
<aside class="detail-panel" aria-label="概念の解説"><div class="panel-eyebrow"><span id="panel-tag">はじめの一歩</span><span id="subject-tag">EXPLORE</span></div><div id="panel-content"></div><div id="model-wrap"><div class="model-heading"><span id="model-title">円の動きが、波になる</span><button id="model-expand" aria-label="数学モデルを拡大">⛶</button></div><div id="math-model"></div><div id="solid-model" hidden></div><div id="model-caption" class="model-caption"></div><div id="model-formula" class="formula-box"></div><div id="model-controls"></div><div class="control-row"><button id="model-motion" class="quiet-button">動きを止める</button><button id="model-dimension" class="quiet-button" hidden>立体で見る</button></div></div><div id="relations-content"></div></aside>
</div>
<div class="legend" aria-label="科目フィルター"><button data-subject="all" class="active">すべて</button>${Object.entries(subjects).map(([id,s])=>`<button data-subject="${id}" style="--subject-color:${s.color}"><i></i>${s.name}</button>`).join('')}<span class="legend-note">色を越えて、考え方がつながる</span></div>
<section class="journeys"><div class="section-header"><div><div class="eyebrow">FOLLOW THE LIGHT</div><h2>ひとつの考えから、旅をする。</h2></div><button id="all-chapters" class="quiet-button">すべての章 <span>↗</span></button></div><div class="journey-grid">${[
[1,'01','三角形から、回転へ','三平方 → 三角比 → 内積','#55dce9','△'],[3,'02','解は、消えない','二次関数 → 判別式 → 複素数','#eb99c9','𝑖'],[7,'03','数えることから、予測へ','組合せ → 二項定理 → 分布','#82d5a1','Σ'],[5,'04','小さな和から、無限へ','数列 → 極限 → 微積分','#b59aef','∫']
].map(([c,n,title,sub,color,symbol])=>`<button class="journey" data-chapter="${c}" style="--journey-color:${color}"><span class="journey-number">${n}</span><span class="journey-symbol">${symbol}</span><span class="journey-text"><strong>${title}</strong><small>${sub}</small></span><span class="journey-arrow">↗</span></button>`).join('')}</div></section>
</main>
<footer class="transport"><div class="transport-title"><span class="chapter-count" id="chapter-number">00</span><div><strong id="chapter-title">数学の宇宙</strong><small id="chapter-subtitle">自由にノードを選んで、つながりを探索</small></div></div><div class="play-controls"><button id="prev" aria-label="前の場面">←</button><button id="play" class="play-button" aria-label="自動再生を開始">▷</button><button id="next" aria-label="次の場面">→</button><div class="timeline"><input id="progress" type="range" min="0" max="100" value="0" aria-label="章の再生位置"><span id="progress-label">00 / 13</span></div></div><div class="settings"><button id="settings" class="quiet-button">授業用設定 ⚙</button><select id="chapter-select" aria-label="章に移動">${chapters.map((c,i)=>`<option value="${i}">${String(i).padStart(2,'0')} ${c.title}</option>`).join('')}</select></div></footer>
<dialog id="settings-dialog"><div class="dialog-heading"><h2>授業用設定</h2><button data-close="settings-dialog" aria-label="閉じる">×</button></div><label class="toggle"><span>数式を表示</span><input id="formula-toggle" type="checkbox" checked></label><label class="toggle"><span>解説を表示</span><input id="explanation-toggle" type="checkbox" checked></label><label class="toggle"><span>関連線・光の粒子</span><input id="line-toggle" type="checkbox" checked></label><label class="toggle"><span>自動的な動き</span><input id="motion-toggle" type="checkbox" ${motion?'checked':''}></label><p class="hint">動きを減らす設定では、自動回転やモデルの連続運動を抑えます。スライダーや章移動はそのまま操作できます。</p></dialog>
<dialog id="help-dialog"><div class="dialog-heading"><h2>数学の宇宙を歩く</h2><button data-close="help-dialog" aria-label="閉じる">×</button></div><ol><li><strong>光るノードを選ぶ。</strong><p>前提と発展先が強く光り、数学モデルが現れます。</p></li><li><strong>つながりを選ぶ。</strong><p>光が相手へ届き、二つの概念を結ぶ理由を表示します。</p></li><li><strong>自分の手で変える。</strong><p>角度・定数・点・分割数を動かし、図と数式を確かめます。</p></li></ol><p>自動再生は下の再生ボタンから。停止・再開、章ジャンプ、場面移動ができます。探究では関連を予想して選びます。</p><div class="source-note">科目分類の基準：<a href="https://www.mext.go.jp/content/20230217-mxt_kyoiku02-100002620_05.pdf" target="_blank" rel="noopener">文部科学省 学習指導要領解説（数学編・理数編）</a><br>本図は歴史上の発見順や必修の履修順ではなく、数学的な構造の関連を表します。</div></dialog>
<dialog id="chapters-dialog"><div class="dialog-heading"><h2>数学の系譜をたどる</h2><button data-close="chapters-dialog" aria-label="閉じる">×</button></div><div class="chapter-list">${chapters.map((c,i)=>`<button data-chapter="${i}"><span>${String(i).padStart(2,'0')}</span><div><strong>${c.title}</strong><small>${c.subtitle}</small></div><span>→</span></button>`).join('')}</div></dialog>
<div id="toast" role="status" aria-live="polite"></div>
`;
// The mathematical laboratory is the main stage; genealogy stays compact below it.
const laboratory=document.createElement('section');laboratory.className='lab-stage';laboratory.setAttribute('aria-label','動かして確かめる数学ラボ');
laboratory.innerHTML=`<div class="lab-top"><div class="eyebrow"><span class="live-dot"></span> LIVE MATHEMATICS LAB</div><span class="lab-top-note">光る点をつかんで、数学を動かす</span></div><nav class="lab-selector" aria-label="可視化モデルを選択">${[['unit-circle','単位円と波'],['quadratic','二次関数と解'],['derivative','微分と接線'],['integral','積分と面積'],['dot','ベクトルと角度'],['correlation','散布図と相関'],['complex-plane','複素数と回転'],['normal','正規分布'],['e','e・自然対数'],['series','無限級数'],['euclid','互除法'],['riemann','区分求積'],['conic','二次曲線'],['power','方べき'],['volume','回転体']].map(([id,label])=>`<button data-node="${id}">${label}</button>`).join('')}</nav>`;
laboratory.insertAdjacentHTML('afterbegin',`<div class="tour-launch"><div><strong>高校数学を、一本の旅に。</strong><span>全73概念・約7分18秒／途中で止めて操作できます</span></div><button id="tour-start" class="primary-button">▶ 全単元を連続再生</button><button id="video-open" class="small-button">▶ MP4動画を見る</button></div>`);
$('.workspace').prepend(laboratory);laboratory.append($('#model-wrap'));
const visual=document.createElement('div');visual.className='lab-visual';const controls=document.createElement('div');controls.className='lab-controls';
const body=document.createElement('div');body.className='lab-body';$('#model-wrap').append(body);body.append(visual,controls);
['#math-model','#solid-model','#model-caption','#model-formula'].forEach(id=>visual.append($(id)));
controls.append($('#model-controls'),$('#model-motion').parentElement);
controls.insertAdjacentHTML('beforeend',`<button id="pulse-toggle" class="small-button ${pulseEnabled?'active':''}" aria-pressed="${pulseEnabled}">発光・鼓動 ${pulseEnabled?'ON':'OFF'}</button><div id="focus-controls"></div><p id="drag-hint" class="hint"></p><div id="live-insight" class="live-insight" aria-live="off"></div>`);
$('.map-label').firstChild.textContent='つながりをたどる · 系譜MAP ';
$('#fullscreen').setAttribute('aria-label','系譜マップを拡大');$('#fullscreen').title='系譜マップを拡大';
$('#counts').textContent=`${concepts.length} CONCEPTS / ${connections.length} CONNECTIONS`;
const universe=new Universe($('#universe'),selectConcept,chooseRelation);
const solid=new SolidModel($('#solid-model'));
function updateOverview(){selected=null;universe.overview();$('#panel-tag').textContent='はじめの一歩';$('#subject-tag').textContent='EXPLORE';$('#subject-tag').style.color='';$('#panel-content').innerHTML=`<h2>数学は、<br>どこへつながる？</h2><p class="description">一つの定理が、別の単元の言葉になる。<br>光る星を選び、その続きを見つけよう。</p><div class="search-box"><span>⌕</span><input id="search" aria-label="概念を検索" placeholder="概念を検索：微分、確率…" autocomplete="off"></div><div id="search-results"></div>`;$('#relations-content').innerHTML=`<button id="begin-journey" class="primary-button">三角形から旅をはじめる <span>→</span></button><p class="hint">まずは単位円を動かしてみよう。<br>円の動きと波の形は、同じ数学です。</p>`;setModel('circle');$('#begin-journey').onclick=()=>startChapter(1,false);$('#search').addEventListener('input',e=>{const q=e.target.value.trim();$('#search-results').innerHTML=q?concepts.filter(c=>c.title.includes(q)||subjects[c.subject].name.includes(q)).slice(0,10).map(c=>`<button data-node="${c.id}" class="search-result"><i style="background:${subjects[c.subject].color}"></i>${c.title}<small>${subjects[c.subject].name}</small></button>`).join(''):'';});applySettings();}
function selectConcept(id,keepPlay=false){if(!byId[id])return;if(!keepPlay){if(playing)pause();touring=false;}selected=id;quiz=false;quizTarget=null;const c=byId[id];universe.select(id);$('#panel-tag').textContent='CONCEPT / つながりを探る';$('#subject-tag').textContent=subjects[c.subject].name;$('#subject-tag').style.color=subjects[c.subject].color;$('#panel-content').innerHTML=`<h2>${c.title}</h2><p class="description">${c.description}</p><div class="concept-formula">${math(c.formula)}</div>`;universe.subject=null;document.querySelectorAll('[data-subject]').forEach(b=>b.classList.toggle('active',b.dataset.subject==='all'));setModel(c.model);renderRelations(id);applySettings();$('#cinema-overlay').hidden=true;}
function renderRelations(id){const before=connections.filter(e=>e.to===id),after=connections.filter(e=>e.from===id);const relButton=(e,from)=>`<button class="relation-button" data-edge="${e.id}"><i style="background:${subjects[byId[from?e.from:e.to].subject].color}"></i><span>${byId[from?e.from:e.to].title}<small>${relations[e.relation]}</small></span><b>${from?'←':'→'}</b></button>`;$('#relations-content').innerHTML=`<div class="connections-heading">どこから来て、どこへ行く？</div><div class="relation-columns"><div><h3>前提・起点</h3>${before.map(e=>relButton(e,true)).join('')||'<p class="hint">中学数学の出発点</p>'}</div><div><h3>発展・別の見方</h3>${after.map(e=>relButton(e,false)).join('')||'<p class="hint">関連を探す</p>'}</div></div><div id="edge-explanation" role="status"></div><button id="inquiry-start" class="inquiry-button">この数学はどこへつながる？ <span>✦</span></button>`;$('#inquiry-start').onclick=()=>beginQuiz(id);}
function chooseRelation(e){if(!playing&&mode!=='cinema')motion=!reduced;if(!selected)selectConcept(e.from);universe.shoot(e,time);activeMorph={e,start:time,progress:0};const box=$('#edge-explanation');if(box){box.innerHTML=`<div class="edge-tag">${relations[e.relation]}</div><h3>${byId[e.from].title} <span>→</span> ${byId[e.to].title}</h3><p>${e.explanation}</p><div class="contour-morph"><svg viewBox="0 0 290 180" role="img" aria-label="起点から発展先への図形の変形"><polyline id="contour-line" fill="none" stroke="#9cdae6" stroke-width="2" stroke-linejoin="round" points="${morphContour(byId[e.from].model,byId[e.to].model,0)}"/></svg><p id="morph-caption">光が届くと、表現が変わる。</p><small>途中の形は補間による演出です。</small></div><div class="morph-formulas"><div>${math(byId[e.from].formula)}</div><span>↓</span><div>${math(byId[e.to].formula)}</div></div><button data-node="${e.to}">発展先へ進む →</button>`;box.scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest'});}}
function setModel(m){model=m;focusPart='all';$('#math-model').dataset.focus='all';$('.lab-stage').dataset.model=m;modelStart=time;frozenModelTime=0;manual=false;model3d=false;modelState=createModelState();if(['integral','curve'].includes(m))modelState.x=1.5;if(['counting','binomial'].includes(m))modelState.n=4;if(m==='sequence')modelState.n=20;if(m==='volume')modelState.n=18;$('#model-title').textContent=modelNames[m]||'数学の構造';$('#model-controls').innerHTML=modelControls(m,modelState);$('#solid-model').hidden=true;$('#math-model').hidden=false;$('#model-dimension').hidden=!['volume','vector','complex','coordinate','curve','statistics','probability'].includes(m);$('#model-dimension').textContent='立体で見る';solid.set(m,modelState);setFocusControls(m);document.querySelectorAll('.lab-selector button').forEach(b=>b.classList.toggle('active',selected===b.dataset.node||(!selected&&b.dataset.node==='unit-circle')));lastMath='';renderCurrentModel();}
function renderCurrentModel(){const t=manual?frozenModelTime:time-modelStart;
if(motion&&!manual){
if(touring)Object.assign(modelState,demoState(model,tourElapsed));
if(!touring){
if(['circle','complex','triangle'].includes(model))modelState.theta=(35+t*12)%360;
if(model==='vector')modelState.theta=(45+t*9)%180;
if(model==='quadratic')modelState.c=1.8*Math.sin(t*.35);
if(model==='derivative'){modelState.x=1.7*Math.sin(t*.3);modelState.h=Math.max(.005,1-((t*.08)%1));}
if(model==='integral'){modelState.x=(t*.28)%4;modelState.n=[4,8,20,100][Math.floor(t/6)%4];}
if(model==='sequence')modelState.n=Math.min(100,4+Math.floor((t*3)%96));
if(model==='curve')modelState.x=(t*.45)%6.283;
if(model==='exponential')modelState.x=1.7*Math.sin(t*.25);
}
document.querySelectorAll('[data-param]').forEach(el=>{el.value=modelState[el.dataset.param];const output=document.querySelector(`[data-output="${el.dataset.param}"]`);if(output)output.textContent=Number(el.value).toFixed(el.dataset.param==='h'?3:2);});
document.querySelectorAll('[data-select]').forEach(el=>el.value=modelState[el.dataset.select]);
if(model3d&&['complex','vector','coordinate'].includes(model))solid.set(model,modelState);
}
const result=renderModel(model,modelState,touring?tourElapsed*2.8:t,false,{phase:pulseEnabled?effectsTime:0,pulse:pulseEnabled,focus:focusPart});$('#math-model').innerHTML=result.svg;$('#math-model').dataset.focus=focusPart;$('#live-insight').innerHTML=result.insight||'';$('#model-caption').textContent=model3d&&model==='curve'?'円錐の断面：楕円。半径 (2−y)/2 の円錐を平面 y = −0.5−0.4z で切った別モデル。':model3d&&model==='probability'?'3Dコインの投げ上げイメージ。試行結果と分布は「平面で見る」から確認。':result.caption;if(result.formula!==lastMath){$('#model-formula').innerHTML=math(result.formula);lastMath=result.formula;}}
function setFocusControls(m){
const parts={circle:[['point','点 P'],['cos','cos θ'],['sin','sin θ・波']],complex:[['point','回転する点']],quadratic:[['vertex','頂点'],['roots','解']],derivative:[['point','点 P・Q'],['secant','割線'],['tangent','接線']],integral:[['area','蓄積した面積'],['point','境界の点']],vector:[['point','ベクトルの先端']],scatter:[['point','データ点']]};
$('#focus-controls').innerHTML='<span class="control-caption">光で対応を確かめる</span><div class="focus-buttons">'+[['all','すべて'],...(parts[m]||[])].map(([id,label])=>`<button data-focus="${id}" class="${id==='all'?'active':''}">${label}</button>`).join('')+'</div>';
$('#drag-hint').textContent={circle:'点Pを円周に沿ってドラッグ。縦の長さと波の高さが同期します。',complex:'点をドラッグすると、偏角と累乗の位置が変わります。',quadratic:'頂点を上下にドラッグ。Dの符号と二つの解が変わります。',derivative:'Pを左右、QをPへ近づけてみよう。割線と接線を比較できます。',integral:'金色の境界点を左右にドラッグ。面積が光を伴って蓄積します。',vector:'ベクトルbの先端をドラッグ。90°で内積は0になります。',scatter:'各データ点を直接ドラッグ。相関係数が同時に変わります。'}[m]||'スライダーを動かし、図・数式・値の変化を確かめよう。';
}
function noteInteraction(){const fresh=effectsTime-lastInteraction>.2;lastInteraction=effectsTime;$('.lab-stage').classList.add('interacting');if(fresh){$('#model-caption').classList.remove('value-flash');void $('#model-caption').offsetWidth;$('#model-caption').classList.add('value-flash');}}
function syncModelInputs(){document.querySelectorAll('[data-param]').forEach(el=>{el.value=modelState[el.dataset.param];const output=document.querySelector(`[data-output="${el.dataset.param}"]`);if(output)output.textContent=Number(modelState[el.dataset.param]).toFixed(el.dataset.param==='h'?3:2);});}
function beginQuiz(id){pause();mode='inquiry';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const c=byId[id];if(selected!==id)selectConcept(id);quiz=true;const answers=connections.filter(e=>e.from===id||e.to===id),correct=answers[0];if(!correct)return;quizTarget=correct.from===id?correct.to:correct.from;const candidates=[quizTarget,...concepts.filter(c=>c.id!==id&&!answers.some(e=>e.from===c.id||e.to===c.id)).slice(3,6).map(c=>c.id)].sort((a,b)=>a.localeCompare(b));$('#relations-content').innerHTML=`<div class="quiz-card"><div class="eyebrow">MAKE A CONNECTION</div><h3>「${c.title}」と直接つながるのは？</h3><p>構造を想像して、光をつないでみよう。</p>${candidates.map(cid=>`<button data-quiz="${cid}">${byId[cid].title}<span>→</span></button>`).join('')}<p id="quiz-feedback" aria-live="polite"></p><button data-action="exit-quiz">関連をすべて見る</button></div>`;}
function answerQuiz(id){if(id===quizTarget){const e=connections.find(e=>(e.from===selected&&e.to===id)||(e.to===selected&&e.from===id));renderRelations(selected);chooseRelation(e);toast('つながった！ 同じ考え方を、別の形で使っています。');quiz=false;}else{$('#quiz-feedback').textContent='この図の直接の関連ではありません。式や図形の共通点を手がかりに、もう一度。';}}
function applySettings(){document.querySelectorAll('.concept-formula,.formula-box,.morph-formulas').forEach(el=>el.hidden=!showFormula);document.querySelectorAll('.description,#edge-explanation p').forEach(el=>el.hidden=!showExplanation);$('#model-motion').textContent=motion&&!manual?'動きを止める':'動きを再開';}
function startChapter(index,auto=false){touring=false;chapter=Math.max(0,Math.min(chapters.length-1,index));step=0;chapterElapsed=0;$('#chapter-select').value=chapter;$('#chapter-number').textContent=String(chapter).padStart(2,'0');$('#chapter-title').textContent=chapters[chapter].title;$('#chapter-subtitle').textContent=chapters[chapter].subtitle;document.querySelectorAll('dialog[open]').forEach(d=>d.close());if(chapter===0||chapter===13){updateOverview();showCinema();}else selectConcept(chapters[chapter].path[0],true);updateTimeline();if(auto){mode='cinema';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));playing=true;motion=!reduced;$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','一時停止');}else pause();}
function showCinema(){const c=chapters[chapter];const el=$('#cinema-overlay');el.hidden=false;el.querySelector('.cinema-eyebrow').textContent=chapter===0?'PROLOGUE':'EPILOGUE';el.querySelector('h2').textContent=chapter===0?'高校数学の系譜':'数学は、単元ではない。';el.querySelector('p').textContent=c.subtitle;universe.goalDistance=chapter===0?8:19;universe.birth=chapter===0?0:null;}
function updateTimeline(){if(touring){$('#progress').value=(tourIndex*sceneSeconds+tourElapsed)/(tourIds.length*sceneSeconds)*100;$('#progress-label').textContent=`${tourIndex+1} / ${tourIds.length}`;return;}const duration=chapter===0||chapter===13?18:chapters[chapter].path.length*9;$('#progress').value=chapterElapsed/duration*100;$('#progress-label').textContent=`${String(chapter).padStart(2,'0')} / 13`;}
function pause(){const wasPlaying=playing;playing=false;$('#play').textContent='▷';$('#play').setAttribute('aria-label','再生');if(wasPlaying||mode==='cinema'){motion=false;applySettings();}}
function play(){if(!selected&&!touring){startTour();return;}if(touring&&tourIndex===tourIds.length-1&&tourElapsed>=sceneSeconds){startTour();return;}if(chapter===13&&chapterElapsed>=18)startChapter(0,true);playing=true;motion=!reduced;mode='cinema';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','一時停止');if(!selected&&(chapter===0||chapter===13))showCinema();applySettings();}
function advance(direction){if(touring){pause();showTourScene(Math.max(0,Math.min(tourIds.length-1,tourIndex+direction)));return;}pause();const p=chapters[chapter].path;if(p.length&&step+direction>=0&&step+direction<p.length){step+=direction;chapterElapsed=step*9;selectConcept(p[step]);updateTimeline();}else startChapter(Math.max(0,Math.min(13,chapter+direction)),false);}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function reset(){touring=false;pause();mode='explore';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#cinema-overlay').hidden=true;updateOverview();}
document.addEventListener('click',e=>{const focus=e.target.closest('[data-focus]');if(focus){focusPart=focus.dataset.focus;document.querySelectorAll('[data-focus]').forEach(b=>b.classList.toggle('active',b===focus));noteInteraction();renderCurrentModel();}
const node=e.target.closest('[data-node]');if(node&&!node.closest('#universe'))selectConcept(node.dataset.node);const edge=e.target.closest('[data-edge]');if(edge)chooseRelation(connections.find(c=>c.id===edge.dataset.edge));const ch=e.target.closest('[data-chapter]');if(ch)startChapter(Number(ch.dataset.chapter),true);const close=e.target.closest('[data-close]');if(close)$(`#${close.dataset.close}`).close();const q=e.target.closest('[data-quiz]');if(q)answerQuiz(q.dataset.quiz);const view=e.target.closest('[data-view]');if(view){modelState.view=view.dataset.view;manual=true;$('#model-controls').innerHTML=modelControls(model,modelState);renderCurrentModel();}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='toss'){noteInteraction();manual=true;toss(modelState);renderCurrentModel();}if(action==='reset-toss'){modelState.trials=0;modelState.counts=[];renderCurrentModel();}if(action==='sample'){noteInteraction();manual=true;sample(modelState);solid.set('statistics',modelState);renderCurrentModel();}if(action==='population'){toggleSolid(true);}if(action==='reset-scatter'){modelState.scatter=createModelState().scatter;renderCurrentModel();}if(action==='exit-quiz')renderRelations(selected);});
document.addEventListener('input',e=>{const key=e.target.dataset.param;if(key){noteInteraction();modelState[key]=Number(e.target.value);manual=true;const output=document.querySelector(`[data-output="${key}"]`);if(output)output.textContent=Number(e.target.value).toFixed(key==='h'?3:2);renderCurrentModel();if(model3d)solid.set(model,modelState);applySettings();}});
document.addEventListener('change',e=>{const key=e.target.dataset.select;if(key){noteInteraction();modelState[key]=['n','tossN'].includes(key)?Number(e.target.value):e.target.value;manual=true;if(key==='tossN'){modelState.trials=0;modelState.counts=[];}renderCurrentModel();if(model3d)solid.set(model,modelState);applySettings();}});
$('#play').onclick=()=>playing?pause():play();$('#prev').onclick=()=>advance(-1);$('#next').onclick=()=>advance(1);$('#chapter-select').onchange=e=>startChapter(Number(e.target.value),playing);$('#progress').oninput=e=>{if(touring){const elapsed=tourIds.length*sceneSeconds*Number(e.target.value)/100;showTourScene(Math.min(tourIds.length-1,Math.floor(elapsed/sceneSeconds)));tourElapsed=elapsed%sceneSeconds;updateTimeline();return;}const duration=chapter===0||chapter===13?18:chapters[chapter].path.length*9;chapterElapsed=duration*Number(e.target.value)/100;const path=chapters[chapter].path;step=Math.min(path.length-1,Math.floor(chapterElapsed/9));if(path.length)selectConcept(path[Math.max(0,step)],true);updateTimeline();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));if(mode==='cinema'){startChapter(chapter,true);}else if(mode==='inquiry'){beginQuiz(selected||'cosine-law');}else reset();});
$('.brand').onclick=e=>{e.preventDefault();reset();};$('#map-reset').onclick=reset;$('#dimension').onclick=()=>{universe.is3d=!universe.is3d;$('#dimension').textContent=universe.is3d?'3D':'2D';$('#dimension').classList.toggle('active',universe.is3d);$('#dimension').setAttribute('aria-pressed',String(universe.is3d));$('#map-status').textContent=universe.is3d?'3D EXPLORATION':'2D EXPLORATION';};$('#auto-rotate').onclick=()=>{universe.rotate=!universe.rotate;if(universe.rotate)motion=true;$('#auto-rotate').classList.toggle('active',universe.rotate);$('#auto-rotate').setAttribute('aria-pressed',String(universe.rotate));};$('#zoom-in').onclick=()=>universe.goalDistance=Math.max(8,universe.goalDistance-3);$('#zoom-out').onclick=()=>universe.goalDistance=Math.min(40,universe.goalDistance+3);$('#fullscreen').onclick=()=>{const expanded=$('.map-section').classList.toggle('map-expanded');$('#fullscreen').textContent=expanded?'×':'⛶';$('#fullscreen').setAttribute('aria-label',expanded?'系譜マップの拡大を閉じる':'系譜マップを拡大');universe.resize();};$('#help').onclick=()=>$('#help-dialog').showModal();$('#settings').onclick=()=>$('#settings-dialog').showModal();$('#all-chapters').onclick=()=>$('#chapters-dialog').showModal();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));$('#formula-toggle').onchange=e=>{showFormula=e.target.checked;applySettings();};$('#explanation-toggle').onchange=e=>{showExplanation=e.target.checked;applySettings();};$('#line-toggle').onchange=e=>{universe.lines=e.target.checked;};$('#motion-toggle').onchange=e=>{motion=e.target.checked;manual=false;applySettings();};$('#model-motion').onclick=()=>{manual=!manual;if(manual)frozenModelTime=time-modelStart;else{motion=true;modelStart=time-frozenModelTime;}applySettings();};$('#model-expand').onclick=()=>{const expanded=$('.lab-stage').classList.toggle('expanded');$('#model-expand').textContent=expanded?'×':'⛶';$('#model-expand').setAttribute('aria-label',expanded?'モデル拡大を閉じる':'数学モデルを拡大');};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('.lab-stage').classList.remove('expanded');$('.map-section').classList.remove('map-expanded');$('#model-expand').textContent='⛶';$('#fullscreen').textContent='⛶';}if(e.target.matches('input,select,textarea'))return;if(e.code==='Space'&&!document.querySelector('dialog[open]')){e.preventDefault();playing?pause():play();}});
function toggleSolid(force){if(!solid.renderer){toast('WebGLが利用できないため、図形モデルで表示しています。');return;}model3d=force??!model3d;$('#solid-model').hidden=!model3d;$('#math-model').hidden=model3d;$('#model-dimension').textContent=model3d?'平面で見る':'立体で見る';solid.set(model,modelState);solid.resize();}
$('#model-dimension').onclick=()=>toggleSolid();
document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{universe.subject=b.dataset.subject==='all'?null:b.dataset.subject;document.querySelectorAll('[data-subject]').forEach(x=>x.classList.toggle('active',x===b));});
$('#pulse-toggle').onclick=()=>{pulseEnabled=!pulseEnabled;$('#pulse-toggle').classList.toggle('active',pulseEnabled);$('#pulse-toggle').setAttribute('aria-pressed',String(pulseEnabled));$('#pulse-toggle').textContent='発光・鼓動 '+(pulseEnabled?'ON':'OFF');renderCurrentModel();};
// Delegated pointer interaction survives animation frame redraws.
let drag=null;$('#math-model').addEventListener('pointerdown',e=>{const target=e.target.closest('[data-drag]');if(!target)return;manual=true;frozenModelTime=time-modelStart;noteInteraction();focusPart=({angle:'sin','quadratic-c':'vertex','derivative-p':'point','derivative-q':'point','integral-x':'area','vector-angle':'point',scatter:'point'})[target.dataset.drag]||'all';document.querySelectorAll('[data-focus]').forEach(b=>b.classList.toggle('active',b.dataset.focus===focusPart));drag={type:target.dataset.drag,index:Number(target.dataset.index)};$('#math-model').setPointerCapture(e.pointerId);e.preventDefault();});$('#math-model').addEventListener('pointermove',e=>{if(!drag)return;const svg=$('#math-model svg');if(!svg)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),x=point.x,y=point.y;noteInteraction();
if(drag.type==='angle')modelState.theta=(Math.atan2(145-y,x-140)*180/Math.PI+360)%360;
if(drag.type==='quadratic-c')modelState.c=Math.max(-2,Math.min(2,(192-y)/37));
if(drag.type==='derivative-p')modelState.x=Math.max(-1.8,Math.min(1.8,(x-225)/85));
if(drag.type==='derivative-q')modelState.h=Math.max(.001,Math.min(1,(x-225)/85-modelState.x));
if(drag.type==='integral-x')modelState.x=Math.max(0,Math.min(4,(x-60)/100));
if(drag.type==='vector-angle')modelState.theta=Math.max(0,Math.min(180,Math.atan2(Math.max(0,220-y),x-245)*180/Math.PI));if(drag.type==='scatter')modelState.scatter[drag.index]=[Math.max(-4.5,Math.min(4.5,(x-260)/47)),Math.max(-4,Math.min(4,(150-y)/28))];if(drag.type==='power-p'){modelState.px=Math.max(-3.7,Math.min(-1.9,(x-260)/58));modelState.py=Math.max(-.5,Math.min(.5,(160-y)/58));modelState.angle1=Math.atan2(-modelState.py,-modelState.px)+.08;modelState.angle2=Math.atan2(-modelState.py,-modelState.px)-.25;}if(drag.type==='power-angle'){const xx=(x-260)/58,yy=(160-y)/58,a=Math.atan2(yy-modelState.py,xx-modelState.px),center=Math.atan2(-modelState.py,-modelState.px),max=Math.asin(1.6/Math.hypot(modelState.px,modelState.py))*.95;modelState[drag.index?'angle2':'angle1']=Math.max(center-max,Math.min(center+max,a));}syncModelInputs();renderCurrentModel();if(model3d)solid.set(model,modelState);});$('#math-model').addEventListener('pointerup',()=>drag=null);$('#math-model').addEventListener('pointercancel',()=>drag=null);
updateOverview();
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.06,(now-last)/1000||0);last=now;if(document.hidden)return;if(motion)time+=dt;if(motion||drag||effectsTime-lastInteraction<1.4)effectsTime+=dt;if(effectsTime-lastInteraction>1.4)$('.lab-stage').classList.remove('interacting');if(playing&&touring){tourElapsed+=dt;if(tourElapsed>=sceneSeconds){if(tourIndex<tourIds.length-1)showTourScene(tourIndex+1);else pause();}updateTimeline();}
if(playing&&!touring){chapterElapsed+=dt;const ch=chapters[chapter],duration=chapter===0||chapter===13?18:ch.path.length*9;if(chapter===0){universe.birth=chapterElapsed;universe.goalDistance=8+16*Math.min(1,chapterElapsed/14);$('#cinema-overlay').style.opacity=Math.min(1,chapterElapsed/2);if(chapterElapsed>12)$('#cinema-overlay').hidden=true;}else if(chapter===13){universe.goalDistance=19+chapterElapsed*.35;const h=$('#cinema-overlay h2');h.textContent=chapterElapsed<6?'数学は、単元ではない。':chapterElapsed<12?'すべては、つながっている。':'MATHEMATICS';}else{const nextStep=Math.min(ch.path.length-1,Math.floor(chapterElapsed/9));if(nextStep!==step){const previous=ch.path[step];step=nextStep;const next=ch.path[step];selectConcept(next,true);const edge=connections.find(e=>e.from===previous&&e.to===next);if(edge){universe.shoot(edge,time);chooseRelation(edge);}}}if(chapterElapsed>=duration){if(chapter<13)startChapter(chapter+1,true);else{pause();chapterElapsed=18;}}updateTimeline();}
if(activeMorph&&$('#contour-line')){if(motion)activeMorph.progress=Math.max(0,Math.min(1,(time-activeMorph.start-2.1)/3));$('#contour-line').setAttribute('points',morphContour(byId[activeMorph.e.from].model,byId[activeMorph.e.to].model,activeMorph.progress));$('#morph-caption').textContent=activeMorph.progress<.5?byId[activeMorph.e.from].title:byId[activeMorph.e.to].title;}
universe.tick(time,dt,motion);solid.tick(time,motion&&!manual);if(now-lastModel>(window.innerWidth<700?50:33)){if(model==='probability'&&motion&&!manual&&playing&&Math.floor(now/1000)!==Math.floor(lastModel/1000)&&modelState.trials<1000)toss(modelState,10);renderCurrentModel();lastModel=now;}}
requestAnimationFrame(frame);

function showTourScene(index){const previous=tourIds[tourIndex];tourIndex=index;tourElapsed=0;selectConcept(tourIds[index],true);$('#cinema-overlay').hidden=true;$('#chapter-number').textContent=String(index+1).padStart(2,'0');$('#chapter-title').textContent='全単元を連続再生';$('#chapter-subtitle').textContent=byId[tourIds[index]].title;const route=routeBetween(index===0?null:previous,tourIds[index]);const box=$('#edge-explanation');if(box&&route.length>1){box.innerHTML=`<div class="edge-tag">関連をたどる · 逆向きは前提へ戻る</div><p>${route.map(id=>byId[id].title).join(' → ')}</p><p>${connections.find(e=>(e.from===route.at(-2)&&e.to===route.at(-1))||(e.to===route.at(-2)&&e.from===route.at(-1)))?.explanation||''}</p>`;const e=connections.find(e=>(e.from===route.at(-2)&&e.to===route.at(-1))||(e.to===route.at(-2)&&e.from===route.at(-1)));if(e)universe.shoot(e,time);}updateTimeline();}
function startTour(){pause();touring=true;mode='cinema';motion=true;manual=false;showTourScene(0);playing=true;$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','一時停止');applySettings();}
$('#tour-start').onclick=startTour;
document.body.insertAdjacentHTML('beforeend',`<dialog id="video-dialog"><div class="dialog-heading"><h2>高校数学の系譜 · 全単元の動画</h2><button id="video-close" aria-label="閉じる">×</button></div><video id="tour-video" controls playsinline preload="none" poster="https://mathematics-genealogy-universe.hakunou22hr.chatgpt.site/videos/poster.jpg" src="https://mathematics-genealogy-universe.hakunou22hr.chatgpt.site/videos/mathematics-genealogy.mp4"><track kind="captions" src="https://mathematics-genealogy-universe.hakunou22hr.chatgpt.site/videos/chapters.vtt" srclang="ja" label="日本語"></video><p>字幕付き・音声なし。教材と同じ数学モデルから生成した映像です。スライダーを操作する場合は、動画を閉じて連続再生をご利用ください。</p><a class="small-button" href="https://mathematics-genealogy-universe.hakunou22hr.chatgpt.site/videos/mathematics-genealogy.mp4" download>MP4をダウンロード</a></dialog>`);
$('#video-open').onclick=()=>{pause();$('#video-dialog').showModal();$('#tour-video').play().catch(()=>{});};$('#video-close').onclick=()=>{$('#tour-video').pause();$('#video-dialog').close();};$('#video-dialog').addEventListener('close',()=>$('#tour-video').pause());
