import {quadratic,f,df,integrand,area,midpoint,choose,binomial,correlation,secantCircle} from './math.js';
export const modelNames={natural:'eと自然対数',normal:'密度の面積が確率になる',series:'部分和の行き先',euclid:'余りを繰り返す',triangle:'長さから、角度へ',circle:'円の動きが、波になる',complex:'掛け算が、回転になる',quadratic:'解は消えない',derivative:'割線から、接線へ',integral:'面積を蓄積する関数',sequence:'無限に近づく',counting:'道を数える、式を展開する',binomial:'係数が受け継がれる',probability:'偶然が、分布になる',statistics:'標本から、母集団へ',scatter:'点群と相関',vector:'角度を、積で表す',coordinate:'同じ点、三つの言語',curve:'動く点が曲線になる',power:'変わらない二つの積',volume:'面積から、体積へ',language:'同じ構造を、式で表す',geometry:'形から、関係へ',exponential:'倍率と、その逆操作'};
export function createModelState(){return {mu:0,sd:1,k:1,r:.5,a:84,b:30,value:35,n:8,c:-1,theta:45,h:.8,x:.5,seq:'inverse',curve:'ellipse',view:'coordinate',px:-3.0,py:.15,angle1:0.05,angle2:-.28,scatter:Array.from({length:18},(_,i)=>[i/2-4.25,.6*(i/2-4.25)+Math.sin(i*2)*1.2]),trials:0,counts:[],tossN:20,p:.5,seed:12345,sample:[],population:Array.from({length:400},(_,i)=>50+9*Math.sin(i*1.723)+6*Math.cos(i*2.413))};}
let effectPhase=0,pulsing=true;
const part=(name,content)=>`<g data-part="${name}">${content}</g>`;
const metric=(label,value,color='#b9f0f0')=>`<div class="metric"><span>${label}</span><strong style="color:${color}">${value}</strong></div>`;
const fmt=(x,d=2)=>Number(x).toFixed(d);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
export function svgFrame(content){return `<svg viewBox="0 0 520 300" role="img" aria-label="操作に応じて変化する数学モデル"><defs><filter id="glow"><feGaussianBlur stdDeviation="3"/></filter><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#e7c56b" stop-opacity=".48"/><stop offset="1" stop-color="#e7c56b" stop-opacity=".08"/></linearGradient></defs>${content}</svg>`;}
const line=(x1,y1,x2,y2,color='#456075',width=1,dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
const text=(x,y,s,color='#adbacd',size=12)=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}" font-family="system-ui" text-anchor="middle">${esc(s)}</text>`;
const dot=(x,y,c='#55dce9',r=4,attrs='')=>{
const beat=pulsing?.5+.5*Math.sin(effectPhase*3.5):.25,ring=r*2.4+beat*6;
return `<g class="live-point"><circle cx="${x}" cy="${y}" r="${r*2.6+beat*3}" fill="${c}" opacity="${.18+beat*.12}" filter="url(#glow)"/><circle cx="${x}" cy="${y}" r="${ring}" fill="none" stroke="${c}" opacity="${.5-beat*.24}" stroke-width=".8"/><circle cx="${x}" cy="${y}" r="${r}" fill="${c}"/></g>`+(attrs?`<circle cx="${x}" cy="${y}" r="15" fill="transparent" ${attrs} />`:'');};
const path=(pts,c='#55dce9',w=2)=>{const d=pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');return `<path d="${d}" fill="none" stroke="${c}" stroke-width="${w+5}" opacity=".19" filter="url(#glow)"/><path d="${d}" fill="none" stroke="${c}" stroke-width="${w}" stroke-linejoin="round"/>`;};
function plot(fn,min=-2,max=2,c='#55dce9',Y=y=>150-y*45,X=x=>260+x*100){return path(Array.from({length:121},(_,i)=>{let x=min+(max-min)*i/120;return [X(x),Y(fn(x))]}),c);}
function axes(X=x=>260+x*100,Y=y=>150-y*45,min=-2,max=2){let s='';for(let x=Math.ceil(min);x<=max;x++){s+=line(X(x),25,X(x),260,'#172334');s+=text(X(x),Y(0)+18,x,'#65758a',10);}s+=line(35,Y(0),490,Y(0),'#425468')+line(X(0),25,X(0),265,'#425468');s+=text(494,Y(0)-8,'x')+text(X(0)+13,20,'y');return s;}
export function modelControls(model,s){const range=(label,key,min,max,step)=>`<label class="slider-label">${label}<output data-output="${key}">${fmt(s[key])}</output><input aria-label="${label}" type="range" data-param="${key}" min="${min}" max="${max}" step="${step}" value="${s[key]}"></label>`;
if(model==='normal')return range('平均 μ','mu',-2,2,.1)+range('標準偏差 σ','sd',.4,1.5,.05)+range('区間 μ ± kσ','k',.1,3,.1);
if(model==='series')return range('公比 r','r',-.9,1.1,.05)+range('項数 n','n',1,40,1);
if(model==='euclid')return range('整数 a','a',2,120,1)+range('整数 b','b',1,100,1);
if(model==='natural')return range('点の x 座標','x',-2,1.5,.01)+range('eの近似に使う n','n',1,200,1);
if(['circle','triangle','complex','vector'].includes(model))return range('角度 θ（度）','theta',0,model==='vector'?180:360,1);
if(model==='quadratic')return range('定数項 c','c',-2,2,.01);
if(model==='derivative')return range('点 P の x 座標','x',-1.8,1.8,.01)+range('二点の間隔 h','h',.001,1,.001);
if(model==='integral')return range('面積を蓄積する位置 x','x',0,4,.01)+`<label class="slider-label">長方形の数 n<select aria-label="長方形の数" data-select="n">${[4,8,20,100].map(n=>`<option ${s.n===n?'selected':''}>${n}</option>`).join('')}</select></label>`;
if(model==='sequence')return `<label class="slider-label">数列<select aria-label="数列の種類" data-select="seq"><option value="inverse">1 / n</option><option value="square">1 / n²</option><option value="geometric">(1 / 2)ⁿ</option></select></label>`+range('項数 n','n',4,100,1);
if(['binomial','counting'].includes(model))return range('展開の次数 n','n',1,7,1);
if(model==='probability')return `<label class="slider-label">1実験のコイン投数 n<select aria-label="コイン投数" data-select="tossN">${[4,10,20,50].map(n=>`<option ${s.tossN===n?'selected':''}>${n}</option>`).join('')}</select></label><div class="control-row"><button data-action="toss">100実験を追加</button><button data-action="reset-toss">リセット</button></div><p class="hint">公平なコイン。nを増やすと二項分布の正規近似が改善し、実験の反復を増やすと観測度数が理論値に近づきます。</p>`;
if(model==='statistics')return `<div class="control-row"><button data-action="sample">標本を抽出（n=30）</button><button data-action="population">母集団を3Dで見る</button></div><p class="hint">シミュレーション用の母集団から無作為抽出。標本平均は抽出ごとに変わります。</p>`;
if(model==='scatter')return `<p class="hint">光る点をドラッグして、相関係数を変えてみよう。相関は因果関係を示しません。</p><button data-action="reset-scatter">点群を戻す</button>`;
if(model==='power')return `<p class="hint">点Pと割線の交点A・Cをドラッグ。Pは円の外部を動きます。</p>`;
if(model==='coordinate')return `<div class="segmented">${[['coordinate','座標'],['vector','ベクトル'],['complex','複素数']].map(([k,v])=>`<button data-view="${k}" class="${s.view===k?'active':''}">${v}</button>`).join('')}</div>`;
if(model==='curve')return `<label class="slider-label">軌跡<select aria-label="曲線の種類" data-select="curve">${[['hyperbola','双曲線'],['ellipse','楕円'],['circle','円'],['parabola','放物線'],['cycloid','サイクロイド']].map(([k,v])=>`<option value="${k}" ${s.curve===k?'selected':''}>${v}</option>`).join('')}</select></label>`+range('媒介変数 t','x',0,6.283,.01);
if(model==='volume')return range('積み重ねる円板の数','n',4,40,1);
if(model==='exponential')return range('点の x 座標','x',-2,2,.01);
return `<p class="hint">図形の対応と数式の構造を、動く光でたどります。</p>`;
}
export function toss(s,count=100){s.counts=s.counts.length===s.tossN+1?s.counts:Array(s.tossN+1).fill(0);for(let j=0;j<count;j++){let k=0;for(let i=0;i<s.tossN;i++){s.seed=(s.seed*1664525+1013904223)>>>0;if(s.seed/4294967296<.5)k++;}s.counts[k]++;s.trials++;}}
export function sample(s){s.sample=[];for(let i=0;i<30;i++){s.seed=(s.seed*1664525+1013904223)>>>0;s.sample.push(s.population[Math.floor(s.seed/4294967296*s.population.length)]);}return s.sample;}
export function renderModel(model,s,t=0,autonomous=true,visual={}){effectPhase=visual.phase??t;pulsing=visual.pulse??true;let out='',caption='',formula='';const theta=(autonomous?(s.theta+t*12)%360:s.theta)*Math.PI/180;
if(model==='triangle'){
const a=115*Math.sin(Math.max(.16,Math.min(1.4,theta%(Math.PI/2)))),b=115*Math.cos(Math.max(.16,Math.min(1.4,theta%(Math.PI/2))));const ox=150,oy=210;
out=`<polygon points="${ox},${oy} ${ox+b},${oy} ${ox+b},${oy-a}" fill="#55dce912" stroke="#55dce9" stroke-width="2"/><polygon points="${ox},${oy} ${ox+b},${oy} ${ox+b},${oy+b} ${ox},${oy+b}" fill="#55dce917" stroke="#55dce966"/><polygon points="${ox+b},${oy} ${ox+b},${oy-a} ${ox+b+a},${oy-a} ${ox+b+a},${oy}" fill="#82d5a122" stroke="#82d5a1"/><polygon points="${ox},${oy} ${ox+b},${oy-a} ${ox+b-a},${oy-a-b} ${ox-a},${oy-b}" fill="#e7c56b18" stroke="#e7c56b"/>`;
out+=text(ox+b/2,oy+22,'b²','#55dce9')+text(ox+b+a/2,oy-a/2,'a²','#82d5a1')+text(ox+(b-a)/2,oy-(a+b)/2,'c²','#e7c56b');
for(let i=0;i<5;i++){const u=(t*.2+i/5)%1;out+=dot(ox+b+u*(80-b),oy-a/2-u*80,'#e7c56b',2);}
out+=text(410,108,'斜辺を1にすると', '#aabbd0',12)+text(410,141,'横 = cos θ','#55dce9',15)+text(410,173,'縦 = sin θ','#82d5a1',15);
caption='三つの正方形の面積：a² + b² = c²';formula='\\sin^2\\theta+\\cos^2\\theta=1';
}else if(['circle','complex'].includes(model)){
const cx=140,cy=145,r=83,px=cx+r*Math.cos(theta),py=cy-r*Math.sin(theta);out=line(35,cy,235,cy)+line(cx,35,cx,250)+`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#40566d"/>`+line(cx,cy,px,py,'#e7c56b',2)+part('cos',line(cx,cy,px,cy,'#55dce9',3))+part('sin',line(px,cy,px,py,'#82d5a1',3))+part('point',dot(px,py,'#e7c56b',5,'data-drag="angle" class="model-hit"'));
out+=text(140,276,model==='complex'?'実軸 Re / 虚軸 Im':'単位円・半径1');
if(model==='circle'){out+=line(270,cy,505,cy);const pts=Array.from({length:100},(_,i)=>[270+i*218/99,cy-83*Math.sin(theta-(99-i)*.055)]);out+=part('sin',path(pts,'#82d5a1',2.5)+line(px,py,488,cy-83*Math.sin(theta),'#82d5a1aa',1.5,'3 4')+dot(488,cy-83*Math.sin(theta),'#82d5a1',5))+text(140+(px-140)/2,cy+20,'cos θ','#55dce9',11)+text(380,276,'円運動 → sin 波');caption=`cos θ = ${fmt(Math.cos(theta))}　sin θ = ${fmt(Math.sin(theta))}`;formula='P=(\\cos\\theta,\\sin\\theta)';}
else {for(let n=2;n<=4;n++){const x=cx+r*Math.cos(n*theta),y=cy-r*Math.sin(n*theta);out+=line(cx,cy,x,y,'#eb99c966')+dot(x,y,'#eb99c9')+text(x+12,y-12,`z${['','','²','³','⁴'][n]}`,'#eb99c9');}out+=text(370,119,'掛け算で角度が加わる','#eb99c9',16)+text(370,150,'z → z² → z³', '#e7edf9',20)+text(370,184,'|z| = 1 のとき、円周を回転', '#aabbd0');caption=`偏角 θ = ${fmt(theta*180/Math.PI,1)}°`;formula='z^n=\\cos(n\\theta)+i\\sin(n\\theta)';}
}else if(model==='quadratic'){
const c=autonomous?1.8*Math.sin(t*.35):s.c;const q=quadratic(c),X=x=>130+x*48,Y=y=>192-y*37;out=axes(X,Y,-2,2)+plot(x=>x*x+c,-2,2,'#55dce9',Y,X);out+=line(320,145,498,145)+line(405,40,405,260)+text(493,135,'Re')+text(420,35,'Im')+text(402,281,'複素数平面');
out+=part('vertex',dot(X(0),Y(c),'#55dce9',6,'data-drag="quadratic-c" class="model-hit"')+text(X(0)+24,Y(c)-10,'頂点','#55dce9',10));for(const r of q.roots){if(!r.im)out+=part('roots',dot(X(r.re),Y(0),'#e7c56b',5));out+=part('roots',dot(405+r.re*45,145-r.im*55,'#eb99c9',5));}caption=`D = ${fmt(q.d)}　${q.d>0?'異なる2実数解':q.d===0?'重解':'共役な2虚数解'}`;formula=`x^2${c>=0?'+':''}${fmt(c)}=0`;out+=text(260,20,q.d<0?'実数の交点がなくても、解は消えない':'実数解は x 軸との交点','#e7edf9',13);
}else if(model==='derivative'){
const x=autonomous?1.7*Math.sin(t*.3):s.x,h=autonomous?Math.max(.005,1-((t*.08)%1)):s.h;const X=x=>225+x*85,Y=y=>110-y*22;out=axes(X,Y,-2,2.8)+plot(f,-2,-1,'#82d5a1',Y,X)+plot(f,-1,1,'#ef8090',Y,X)+plot(f,1,2.8,'#82d5a1',Y,X);const slope=(f(x+h)-f(x))/h;out+=part('tangent',line(X(x-.8),Y(f(x)-.8*df(x)),X(x+.8),Y(f(x)+.8*df(x)),'#55dce9',2.5,'5 3'))+part('secant',line(X(x-.8),Y(f(x)-.8*slope),X(x+.8),Y(f(x)+.8*slope),'#e7c56b',3))+part('point',dot(X(x),Y(f(x)),'#55dce9',5,'data-drag="derivative-p" class="model-hit"')+dot(X(x+h),Y(f(x+h)),'#e7c56b',5,'data-drag="derivative-q" class="model-hit"'))+text(X(x)-10,Y(f(x))-12,'P')+text(X(x+h)+10,Y(f(x+h))-12,'Q');const Y2=y=>270-y*14;out+=line(35,Y2(0),490,Y2(0)) + plot(df,-2,2,'#b59aef',Y2,X)+part('point',dot(X(x),Y2(df(x)),df(x)>0?'#82d5a1':df(x)<0?'#ef8090':'#e7c56b',5))+line(X(x),Y(f(x)),X(x),Y2(df(x)),'#65758a',1,'3 4')+text(460,210,'f′(x)');caption=`h = ${fmt(h,3)}　割線の傾き = ${fmt(slope,3)}　f′(x) = ${fmt(df(x),3)}`;formula='f(x)=x^3/3-x,\\quad f\prime(x)=x^2-1';
}else if(model==='integral'){
const x=autonomous?(t*.28)%4:s.x,n=autonomous?[4,8,20,100][Math.floor(t/6)%4]:Number(s.n),X=x=>60+x*100,Y=y=>250-y*40;out=axes(X,Y,0,4);for(let i=0;i<n;i++){const dx=4/n,xx=(i+.5)*dx;out+=`<rect x="${X(i*dx)}" y="${Y(integrand(xx))}" width="${100*dx}" height="${40*integrand(xx)}" fill="#b59aef18" stroke="#b59aef66" stroke-width=".6"/>`;}
const pts=[[X(0),Y(0)],...Array.from({length:80},(_,i)=>[X(x*i/79),Y(integrand(x*i/79))]),[X(x),Y(0)]];out+=part('area',`<polygon points="${pts.map(p=>p.join(',')).join(' ')}" fill="url(#areaFill)" opacity="${pulsing?.78+.18*Math.sin(effectPhase*2):1}"/><rect x="${X(x)-2}" y="${Y(integrand(x))}" width="4" height="${Y(0)-Y(integrand(x))}" fill="#e7c56b" opacity=".5" filter="url(#glow)"/>`)+plot(integrand,0,4,'#e7c56b',Y,X)+line(X(x),Y(0),X(x),Y(integrand(x)),'#e7c56b',2)+part('point',dot(X(x),Y(integrand(x)),'#e7c56b',5,'data-drag="integral-x" class="model-hit"'));caption=`n = ${n}　区分求積 ≈ ${fmt(midpoint(n),4)}　F(x) = ${fmt(area(x),4)}`;formula='F(x)=\\int_0^x(1+t^2/4)\\,dt=x+x^3/12';
}else if(model==='sequence'){
const n=autonomous?Math.min(100,4+Math.floor((t*3)%96)):Math.floor(s.n);const fn=k=>s.seq==='square'?1/k**2:s.seq==='geometric'?.5**k:1/k;out=line(50,250,490,250)+line(50,40,50,255)+text(490,276,'n')+text(32,45,'aₙ')+text(37,253,'0');for(let k=1;k<=n;k++){const x=50+k*430/n,y=250-fn(k)*195;out+=dot(x,y,k===n?'#e7c56b':'#b59aef',k===n?4:2);}out+=line(50,248,490,248,'#e7c56b66',1,'4 4');caption=`n = ${n}　aₙ = ${fn(n).toPrecision(4)}　限りなく 0 へ`;formula=s.seq==='square'?'a_n=1/n^2\\to0':s.seq==='geometric'?'a_n=(1/2)^n\\to0':'a_n=1/n\\to0';
}else if(['counting','binomial'].includes(model)){
const n=Math.min(7,Math.max(1,Math.round(s.n))),gap=27;for(let row=0;row<=n;row++){for(let k=0;k<=row;k++){const xx=136+(k-row/2)*gap,yy=33+row*29;if(row){out+=line(xx-gap/2,yy-29,xx,yy,'#82d5a133')+line(xx+gap/2,yy-29,xx,yy,'#82d5a133');}out+=text(xx,yy+4,choose(row,k),row===n?'#e7c56b':'#82d5a1',12);}}
for(let x=0;x<=4;x++)out+=line(305+x*36,72,305+x*36,180,'#284335');for(let y=0;y<=3;y++)out+=line(305,72+y*36,449,72+y*36,'#284335');const route=[[305,180],[341,180],[341,144],[377,144],[413,144],[413,108],[449,108],[449,72]];out+=path(route,'#82d5a1',2);let u=(t*.4)%7,k=Math.floor(u),p=u-k;out+=dot(route[k][0]*(1-p)+route[k+1][0]*p,route[k][1]*(1-p)+route[k+1][1]*p,'#e7c56b')+text(300,201,'S')+text(457,63,'G')+text(382,240,'右4・上3 → ₇C₃ = 35','#e7c56b');caption=`パスカルの第 ${n} 行：${Array.from({length:n+1},(_,k)=>choose(n,k)).join('  ')}`;formula=`(a+b)^${n}=`+Array.from({length:n+1},(_,k)=>`${choose(n,k)===1?'':choose(n,k)}${n-k?`a^{${n-k}}`:''}${k?`b^{${k}}`:''}`).join('+');
}else if(model==='probability'){
const n=s.tossN,probs=binomial(n),peak=Math.max(...probs)*1.3,X=k=>55+(k+.5)*410/(n+1),Y=p=>252-p/peak*190;out=line(48,252,475,252)+text(260,284,'表の回数 k')+text(60,27,`${s.trials} 回の実験`,'#e7edf9',14);
for(let k=0;k<=n;k++){const theory=probs[k],observed=s.trials?(s.counts[k]||0)/s.trials:0;out+=`<rect x="${X(k)-180/(n+1)}" y="${Y(theory)}" width="${360/(n+1)}" height="${252-Y(theory)}" fill="#ec9b6520" stroke="#ec9b6570"/><rect x="${X(k)-120/(n+1)}" y="${Y(observed)}" width="${240/(n+1)}" height="${252-Y(observed)}" fill="#82d5a1aa"/>`;if(k%(n>=20?5:1)===0)out+=text(X(k),270,k,'#8a99ac',10);}
const mu=n/2,sd=Math.sqrt(n/4),pts=Array.from({length:121},(_,i)=>{const k=-.5+(n+1)*i/120;return [X(k),Y(Math.exp(-.5*((k-mu)/sd)**2)/(sd*Math.sqrt(2*Math.PI)))]});out+=path(pts,'#e7c56b')+text(260,45,'緑：実験　橙：二項分布　金：正規近似','#acbace',11);caption=`n = ${n}　平均 = ${mu}　標準偏差 = ${fmt(sd)}　反復 = ${s.trials}`;formula=`X\\sim B(${n},1/2),\\quad E[X]=${mu}`;
}else if(model==='scatter'){
const X=x=>260+x*47,Y=y=>150-y*28;out=axes(X,Y,-4,4);s.scatter.forEach(([x,y],i)=>out+=part('point',dot(X(x),Y(y),'#55dce9',4,`data-drag="scatter" data-index="${i}" class="model-hit"`)));let r=correlation(s.scatter);caption=`相関係数 r = ${r===null?'定義できません':fmt(r,4)}`;formula='-1\\le r\\le1';
}else if(model==='statistics'){
const X=x=>65+(x-30)*10;for(let i=0;i<Math.min(160,s.population.length);i++){out+=dot(X(s.population[i]),45+(i%10)*13,'#55dce9',1.6);}
out+=text(260,24,'母集団（400個の観測値）','#93a8be',12);const mean=s.sample.length?s.sample.reduce((a,b)=>a+b,0)/s.sample.length:null;if(mean!==null){s.sample.forEach((v,i)=>out+=dot(X(v),220+(i%3)*13,'#e7c56b',3));out+=line(X(mean),205,X(mean),275,'#e7c56b',2)+text(260,193,'無作為に抽出した標本（n=30）','#e7c56b',12);}else out+=text(260,230,'「標本を抽出」で、母集団の一部を選ぶ','#e7c56b',14);caption=mean===null?'標本から母集団を推測する':`標本平均 = ${fmt(mean)}　母平均 = ${fmt(s.population.reduce((a,b)=>a+b,0)/400)}`;formula='\\bar X=\\frac1n\\sum_{i=1}^n X_i';
}else if(model==='vector'){
const angle=autonomous?(t*9+s.theta)%180:s.theta,rad=angle*Math.PI/180,ox=245,oy=220,px=ox+140*Math.cos(rad),py=oy-140*Math.sin(rad);const dp=6*Math.cos(rad),color=dp>1e-10?'#82d5a1':dp< -1e-10?'#ef8090':'#e7c56b';out=line(ox,oy,ox+150,oy,'#55dce9',3)+line(ox,oy,px,py,color,3)+part('point',dot(ox+150,oy)+dot(px,py,color,5,'data-drag="vector-angle" class="model-hit"'))+line(px,py,px,oy,'#65758a',1,'4 4')+text(ox+160,oy-10,'a','#55dce9',15)+text(px,py-12,'b',color,15)+text(255,50,`θ = ${fmt(angle,1)}°`,color,18)+text(260,280,'|a| = 2　|b| = 3');caption=`内積 = ${fmt(Math.abs(dp)<1e-10?0:dp,3)}　${Math.abs(dp)<1e-10?'垂直':dp>0?'鋭角 → 正':'鈍角 → 負'}`;formula='\\vec a\\cdot\\vec b=6\\cos\\theta';
}else if(model==='coordinate'){
const X=x=>190+x*65,Y=y=>220-y*60;out=axes(X,Y,0,4)+line(X(0),Y(0),X(2),Y(1),'#eb99c9',s.view==='vector'?3:1)+dot(X(2),Y(1),'#eb99c9',6)+line(X(2),Y(1),X(2),Y(0),'#456075',1,'3 4')+text(X(2),Y(1)-20,'P','#e7edf9',16);caption='点Pの位置は変わらない。表す言語だけが変わる。';formula=s.view==='complex'?'z=2+i':s.view==='vector'?'\\overrightarrow{OP}=(2,1)':'P=(2,1)';
}else if(model==='curve'){
const tt=autonomous?(t*.45)%6.283:s.x;const fn=u=>s.curve==='hyperbola'?[1.1*Math.cosh((u-3.1415)/2),.7*Math.sinh((u-3.1415)/2)]:s.curve==='circle'?[1.7*Math.cos(u),1.7*Math.sin(u)]:s.curve==='parabola'?[u/1.57-2,(u/1.57-2)**2/2-1]:s.curve==='cycloid'?[(u-Math.sin(u))/1.5-2,1-Math.cos(u)-1]:[2*Math.cos(u),1.2*Math.sin(u)];const X=x=>260+x*80,Y=y=>155-y*60;out=axes(X,Y)+path(Array.from({length:100},(_,i)=>{const p=fn(i/99*tt);return [X(p[0]),Y(p[1])]}),'#eb99c9');const [x,y]=fn(tt),[qx,qy]=fn(tt+.001),vx=(qx-x)/.001,vy=(qy-y)/.001,scale=.5/Math.max(1,Math.hypot(vx,vy));if(s.curve==='hyperbola')out+=path(Array.from({length:100},(_,i)=>{const [a,b]=fn(i/99*6.283);return [X(-a),Y(b)]}),'#eb99c9');out+=dot(X(x),Y(y),'#e7c56b')+line(X(x),Y(y),X(x+vx*scale),Y(y+vy*scale),'#82d5a1',2)+line(X(x-vx*scale),Y(y-vy*scale),X(x+vx*scale),Y(y+vy*scale),'#65758a',1,'4 4');caption=`t = ${fmt(tt)}　P = (${fmt(x)}, ${fmt(y)})　緑：速度ベクトル`;formula=s.curve==='hyperbola'?'x^2/1.21-y^2/0.49=1':s.curve==='ellipse'?'x=2\\cos t,\\quad y=1.2\\sin t':s.curve==='circle'?'x=1.7\\cos t,\\quad y=1.7\\sin t':s.curve==='cycloid'?'x=(t-\\sin t)/1.5-2,\\quad y=-\\cos t':'x=t/1.57-2,\\quad y=x^2/2-1';
}else if(model==='power'){
const one=secantCircle(s.px,s.py,s.angle1),two=secantCircle(s.px,s.py,s.angle2),X=x=>260+x*58,Y=y=>160-y*58;out=`<circle cx="260" cy="160" r="92.8" fill="#55dce907" stroke="#53677e"/>`+dot(X(s.px),Y(s.py),'#e7edf9',6,'data-drag="power-p" class="draggable"')+text(X(s.px)-12,Y(s.py)-13,'P','#e7edf9');[one,two].forEach((q,i)=>{if(!q)return;const color=i?'#82d5a1':'#e7c56b';out+=line(X(s.px),Y(s.py),X(q.B[0]),Y(q.B[1]),color,2)+dot(X(q.A[0]),Y(q.A[1]),color,5,`data-drag="power-angle" data-index="${i}" class="draggable"`)+dot(X(q.B[0]),Y(q.B[1]),color,4)+text(X(q.A[0]),Y(q.A[1])-12,i?'C':'A',color)+text(X(q.B[0]),Y(q.B[1])-12,i?'D':'B',color);});if(one&&two){caption=`PA×PB = ${fmt(one.product,4)}　PC×PD = ${fmt(two.product,4)}`;out+=`<rect x="40" y="260" width="${one.a*30}" height="${one.c*5}" fill="#e7c56b44"/><rect x="290" y="260" width="${two.a*30}" height="${two.c*5}" fill="#82d5a144"/>`;formula='PA\\cdot PB=PC\\cdot PD=PO^2-r^2';}else caption='円を横切る角度に割線を動かしてください。';
}else if(model==='normal'){
const mu=s.mu,sd=s.sd,k=s.k,X=x=>260+x*45,Y=y=>252-y*170,fn=x=>Math.exp(-.5*((x-mu)/sd)**2)/(sd*Math.sqrt(2*Math.PI)),a=mu-k*sd,b=mu+k*sd;
out=axes(X,Y,-5,5)+part('area',`<polygon points="${[[X(a),Y(0)],...Array.from({length:101},(_,i)=>{const x=a+(b-a)*i/100;return [X(x),Y(fn(x))]}),[X(b),Y(0)]].map(p=>p.join(',')).join(' ')}" fill="url(#areaFill)"/>`)+plot(fn,-5,5,'#e7c56b',Y,X)+dot(X(mu),Y(fn(mu)),'#e7c56b');let sum=0;for(let i=0;i<400;i++){const z=-k+(i+.5)*2*k/400;sum+=Math.exp(-z*z/2)/Math.sqrt(2*Math.PI)*2*k/400;}caption=`μ=${fmt(mu)} σ=${fmt(sd)} 区間の確率 ≈ ${fmt(sum*100,2)}%`;formula='f(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}';
}else if(model==='series'){
const n=autonomous?1+Math.floor(t*2)%40:Math.round(s.n),r=s.r,X=x=>55+x*10,Y=y=>240-y*35;let sum=0;out=line(50,240,480,240);for(let j=0;j<n;j++){sum+=r**j;out+=dot(X(j),Y(sum),'#b59aef',3);}if(Math.abs(r)<1)out+=line(50,Y(1/(1-r)),480,Y(1/(1-r)),'#e7c56b',2,'4 4');caption=`部分和 S${n}=${fmt(sum,4)}　${Math.abs(r)<1?'極限 '+fmt(1/(1-r),4):'この公比では収束しない'}`;formula='S_n=\\sum_{j=0}^{n-1}r^j';
}else if(model==='euclid'){
let a=Math.round(s.a),b=Math.round(s.b),steps=[];while(b){steps.push([a,b,Math.floor(a/b),a%b]);[a,b]=[b,a%b];}out=steps.map(([a,b,q,r],i)=>text(260,40+i*32,`${a} = ${b} × ${q} + ${r}`,i===Math.floor(t)%steps.length?'#e7c56b':'#aabbd0',18)).join('')+dot(65,35+(Math.floor(t)%steps.length)*32,'#e7c56b');caption=`最大公約数 = ${a}。余りが0になる直前の除数。`;formula='\\gcd(a,b)=\\gcd(b,a\\bmod b)';
}else if(model==='natural'){
const x=autonomous?1.4*Math.sin(t*.25):s.x,X=x=>260+x*65,Y=y=>210-y*40;out=axes(X,Y)+plot(Math.exp,-2,1.5,'#e7c56b',Y,X)+plot(Math.log,.1,3.5,'#55dce9',Y,X)+line(X(-2),Y(-2),X(3.5),Y(3.5),'#65758a',1,'4 4')+dot(X(x),Y(Math.exp(x)),'#e7c56b')+dot(X(Math.exp(x)),Y(x),'#55dce9');caption=`e ≈ ${fmt((1+1/s.n)**s.n,6)} (n=${s.n})　真値 ${fmt(Math.E,6)}`;formula='y=e^x\\quad\\longleftrightarrow\\quad y=\\ln x';
}else if(model==='exponential'){
const x=autonomous?1.7*Math.sin(t*.25):s.x,X=x=>260+x*70,Y=y=>200-y*45;out=axes(X,Y)+plot(x=>2**x,-2,2,'#e7c56b',Y,X)+plot(x=>Math.log2(x),.15,4,'#55dce9',Y,X)+line(X(-2),Y(-2),X(3.5),Y(3.5),'#65758a',1,'4 4')+dot(X(x),Y(2**x),'#e7c56b')+dot(X(2**x),Y(x),'#55dce9');caption=`指数関数 (${fmt(x)}, ${fmt(2**x)}) ↔ 対数関数 (${fmt(2**x)}, ${fmt(x)})`;formula='y=2^x\\quad\\longleftrightarrow\\quad y=\\log_2 x';
}else if(model==='volume'){
for(let k=0;k<s.n;k++){let x=4*(k+.5)/s.n,r=Math.sqrt(x)*47,cx=95+x*82;out+=`<ellipse cx="${cx}" cy="152" rx="${r*.32}" ry="${r}" fill="#b59aef0b" stroke="#b59aef88" stroke-width="1"/>`;}out+=line(65,152,460,152,'#e7c56b',2)+text(260,280,'半径 √x の円板を、x = 0 から 4 まで積む');caption=`V = π∫₀⁴ x dx = 8π ≈ ${fmt(8*Math.PI,4)}`;formula='V=\\pi\\int_0^4(\\sqrt x)^2\\,dx=8\\pi';
}else{
out=text(260,80,'展開 ↔ 因数分解','#55dce9',18)+text(260,136,'同じ関係を、違う形で表す','#aabbd0',14)+text(260,201,'a(b + c)  =  ab + ac','#e7edf9',23);for(let i=0;i<6;i++)out+=dot(90+((t*38+i*55)%340),235,'#55dce9',2);caption='数量・図形・条件を、式の構造としてつなぐ。';formula='a(b+c)=ab+ac';
}
let insight='';
if(model==='circle')insight=metric('横の長さ · cos θ',fmt(Math.cos(theta),3),'#55dce9')+metric('縦の長さ · sin θ',fmt(Math.sin(theta),3),'#82d5a1');
if(model==='complex')insight=metric('偏角 θ',fmt(theta*180/Math.PI,1)+'°','#eb99c9')+metric('絶対値 |z|','1.000');
if(model==='quadratic'){const c=autonomous?1.8*Math.sin(t*.35):s.c;insight=metric('判別式 D',fmt(-4*c,3),c>0?'#eb99c9':'#e7c56b')+metric('解の姿',c>0?'共役複素数':c===0?'重解':'二つの実数解');}
if(model==='derivative'){const x=autonomous?1.7*Math.sin(t*.3):s.x,h=autonomous?Math.max(.005,1-((t*.08)%1)):s.h;insight=metric('瞬間の傾き f′(x)',fmt(df(x),3),df(x)>=0?'#82d5a1':'#ef8090')+metric('割線との差',fmt(Math.abs((f(x+h)-f(x))/h-df(x)),4),'#e7c56b');}
if(model==='integral')insight=metric('ここまでの面積 F(x)',fmt(area(autonomous?(t*.28)%4:s.x),4),'#e7c56b')+metric('全区間 [0,4] の面積','28 / 3');
if(model==='vector')insight=metric('内積 a · b',fmt(6*Math.cos((autonomous?(t*9+s.theta)%180:s.theta)*Math.PI/180),3),Math.cos(theta)>=0?'#82d5a1':'#ef8090');
if(model==='scatter'){const r=correlation(s.scatter);insight=metric('相関係数 r',r===null?'未定義':fmt(r,4));}
return {svg:svgFrame(out),caption,formula,insight};}
// Equal-count contour samples permit continuous shape interpolation. Intermediate
// contours are presentation geometry, not an asserted mathematical graph.
export function conceptContour(model,s=createModelState(),count=100){
const poly=vertices=>Array.from({length:count},(_,i)=>{let u=i/(count-1)*(vertices.length-1),k=Math.min(vertices.length-2,Math.floor(u)),v=u-k;return [vertices[k][0]*(1-v)+vertices[k+1][0]*v,vertices[k][1]*(1-v)+vertices[k+1][1]*v];});
if(model==='triangle')return poly([[.1,.85],[.8,.85],[.8,.15],[.1,.85]]);
if(['circle','complex','coordinate'].includes(model))return Array.from({length:count},(_,i)=>{let a=i/(count-1)*Math.PI*2;return [.5+.35*Math.cos(a),.5-.35*Math.sin(a)];});
if(model==='vector')return poly([[.15,.75],[.85,.75],[.15,.75],[.65,.2]]);
if(['quadratic','curve'].includes(model))return Array.from({length:count},(_,i)=>{let x=-2+4*i/(count-1);return [.1+.8*i/(count-1),.82-.17*x*x];});
if(model==='derivative')return Array.from({length:count},(_,i)=>{let x=-1.8+3.6*i/(count-1);return [.1+.8*i/(count-1),.5-.18*(x*x*x/3-x)];});
if(['integral','volume'].includes(model))return poly([[.1,.9],...Array.from({length:30},(_,i)=>[.1+.8*i/29,.75-.55*(i/29)**2]),[.9,.9],[.1,.9]]);
if(model==='sequence')return Array.from({length:count},(_,i)=>[.1+.8*i/(count-1),.9-.8/(1+i*.13)]);
if(['probability','statistics','scatter'].includes(model))return Array.from({length:count},(_,i)=>{let x=-3+6*i/(count-1);return [.1+.8*i/(count-1),.85-.6*Math.exp(-x*x/2)];});
if(['counting','binomial'].includes(model))return poly([[.5,.1],[.9,.85],[.1,.85],[.5,.1]]);
if(model==='power')return Array.from({length:count},(_,i)=>{let a=i/(count-1)*Math.PI*2;return [.55+.3*Math.cos(a),.5-.3*Math.sin(a)];});
if(model==='exponential')return Array.from({length:count},(_,i)=>[.1+.8*i/(count-1),.88-.12*2**(i/(count-1)*2.5)]);
return poly([[.15,.8],[.4,.8],[.4,.5],[.65,.5],[.65,.2],[.85,.2]]);
}
export function morphContour(from,to,u){u=Math.max(0,Math.min(1,u));const ease=u*u*(3-2*u),a=conceptContour(from),b=conceptContour(to);return a.map((p,i)=>`${(25+(p[0]*(1-ease)+b[i][0]*ease)*240).toFixed(2)},${(8+(p[1]*(1-ease)+b[i][1]*ease)*150).toFixed(2)}`).join(' ');}
