import * as THREE from 'three';
import {concepts,connections,byId,subjects} from './data.js';
export class Universe{
constructor(host,onSelect,onLink){this.host=host;this.onSelect=onSelect;this.onLink=onLink;this.yaw=-.05;this.pitch=.08;this.distance=24;this.goalDistance=24;this.center=new THREE.Vector3(1,0,0);this.goalCenter=this.center.clone();this.is3d=true;this.rotate=false;this.lines=true;this.focus=null;this.activeEdge=null;this.subject=null;this.dragging=false;this.labels=new Map();this.positions=new Map();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(43,1,.1,100);this.camera.position.set(1,0,24);this.group=new THREE.Group();this.scene.add(this.group);
try{this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:window.innerWidth>700,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,window.innerWidth<700?1.3:1.8));this.renderer.setClearColor(0x050914,0);host.append(this.renderer.domElement);this.webgl=true;}catch{this.webgl=false;this.canvas=document.createElement('canvas');host.append(this.canvas);this.ctx=this.canvas.getContext('2d');}
this.labelLayer=document.createElement('div');this.labelLayer.className='node-labels';host.append(this.labelLayer);this.build();this.birth=null;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.bind();this.resize();}
glowTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const c=canvas.getContext('2d'),g=c.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.15,'rgba(255,255,255,.9)');g.addColorStop(.35,'rgba(255,255,255,.25)');g.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=g;c.fillRect(0,0,64,64);return new THREE.CanvasTexture(canvas);}
build(){const texture=this.glowTexture();this.nodes=[];for(const c of concepts){const material=new THREE.SpriteMaterial({map:texture,color:subjects[c.subject].color,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});const sprite=new THREE.Sprite(material);sprite.position.set(...c.position);sprite.scale.setScalar(.4);this.group.add(sprite);this.nodes.push({c,sprite});const b=document.createElement('button');b.className='node-label';b.style.setProperty('--node-color',subjects[c.subject].color);b.dataset.node=c.id;b.innerHTML=`<span class="node-dot"></span>${c.title}`;b.addEventListener('click',()=>this.onSelect(c.id));this.labelLayer.append(b);this.labels.set(c.id,b);}
this.edges=connections.map(e=>{const a=new THREE.Vector3(...byId[e.from].position),b=new THREE.Vector3(...byId[e.to].position);const geometry=new THREE.BufferGeometry().setFromPoints([a,b]);const material=new THREE.LineBasicMaterial({color:subjects[byId[e.to].subject].color,transparent:true,opacity:.14});const line=new THREE.Line(geometry,material);this.group.add(line);return {e,a,b,line};});
const starVertices=[];for(let i=0;i<(window.innerWidth<700?160:420);i++){const a=i*2.399,r=8+(i*17.3%17);starVertices.push(Math.cos(a)*r,Math.sin(a)*r,Math.sin(i*1.72)*9-5);}const stars=new THREE.BufferGeometry();stars.setAttribute('position',new THREE.Float32BufferAttribute(starVertices,3));this.scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0x8ba4c0,size:.025,transparent:true,opacity:.45})));
this.seed=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color:0xffffff,transparent:true,blending:THREE.AdditiveBlending}));this.seed.position.set(1,0,0);this.seed.scale.setScalar(.7);this.scene.add(this.seed);this.seed.visible=false;
this.particleCount=window.innerWidth<700?18:45;this.particlePositions=new Float32Array(this.particleCount*3);this.particleColors=new Float32Array(this.particleCount*3);const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(this.particlePositions,3));pg.setAttribute('color',new THREE.BufferAttribute(this.particleColors,3));this.particles=new THREE.Points(pg,new THREE.PointsMaterial({map:texture,size:.22,transparent:true,vertexColors:true,depthWrite:false,blending:THREE.AdditiveBlending}));this.group.add(this.particles);}
resize(){const wasCompact=this.compact;this.compact=!this.host.parentElement.classList.contains('map-expanded');this.group.scale.set(this.compact?2.1:1,this.compact?.42:1,this.compact?.5:1);if(wasCompact!==this.compact){if(this.focus){const p=byId[this.focus].position;this.goalCenter.set(p[0]*(this.compact?2.1:1),p[1]*(this.compact?.42:1),p[2]*(this.compact?.5:1));this.goalDistance=this.compact?10:15;}else{this.goalCenter.set(this.compact?2.1:1,0,0);this.goalDistance=this.compact?12:24;}}const {width,height}=this.host.getBoundingClientRect();this.w=Math.max(1,width);this.h=Math.max(1,height);this.camera.aspect=this.w/this.h;this.camera.updateProjectionMatrix();if(this.webgl)this.renderer.setSize(this.w,this.h);else{this.canvas.width=this.w;this.canvas.height=this.h;}}
bind(){let start=null,moved=false,pointers=new Map(),pinch=0;this.host.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);start=[e.clientX,e.clientY];moved=false;this.dragging=true;this.host.setPointerCapture(e.pointerId);});this.host.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);if(pinch)this.goalDistance=Math.max(8,Math.min(38,this.goalDistance*pinch/d));pinch=d;return;}const dx=e.clientX-old[0],dy=e.clientY-old[1];if(start&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>4)moved=true;if(this.is3d){this.yaw+=dx*.004;this.pitch=Math.max(-1,Math.min(1,this.pitch+dy*.004));}else{this.goalCenter.x-=dx*this.distance/this.w*.5;this.goalCenter.y+=dy*this.distance/this.h*.5;}});const end=e=>{pointers.delete(e.pointerId);this.dragging=false;pinch=0;if(!moved&&start){const [x,y]=start;let best=null,d=22;for(const[c,p]of this.positions){let dd=Math.hypot(p.x-(x-this.host.getBoundingClientRect().left),p.y-(y-this.host.getBoundingClientRect().top));if(dd<d){best=c;d=dd;}}if(best)this.onSelect(best);else if(this.lines){let found=null,min=8;const px=x-this.host.getBoundingClientRect().left,py=y-this.host.getBoundingClientRect().top;for(const{e}of this.edges){const a=this.positions.get(e.from),b=this.positions.get(e.to);if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,u=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/(dx*dx+dy*dy)));const dist=Math.hypot(px-a.x-u*dx,py-a.y-u*dy);if(dist<min){min=dist;found=e;}}if(found)this.onLink(found);}}start=null;};this.host.addEventListener('pointerup',end);this.host.addEventListener('pointercancel',()=>{pointers.clear();start=null;this.dragging=false;});this.host.addEventListener('wheel',e=>{e.preventDefault();this.goalDistance=Math.max(8,Math.min(40,this.goalDistance+e.deltaY*.012));},{passive:false});}
select(id){this.birth=null;this.focus=id;this.related=new Set([id,...connections.filter(e=>e.from===id||e.to===id).flatMap(e=>[e.from,e.to])]);const p=byId[id].position;this.goalCenter.set(p[0]*(this.compact?2.1:1),p[1]*(this.compact?.42:1),p[2]*(this.compact?.5:1));this.goalDistance=this.compact?10:15;this.yaw=0;this.pitch=.1;}
overview(){this.birth=null;this.focus=null;this.related=null;this.goalCenter.set(this.compact?2.1:1,0,0);this.goalDistance=this.compact?12:24;this.activeEdge=null;}
shoot(e,t){this.activeEdge={e,start:t};}
project(v){const p=v.clone().applyMatrix4(this.group.matrixWorld).project(this.camera);return{x:(p.x*.5+.5)*this.w,y:(-.5*p.y+.5)*this.h,z:p.z};}
tick(t,dt,motion=true){if(this.rotate&&this.is3d&&motion&&!this.dragging)this.yaw+=dt*.055;this.center.lerp(this.goalCenter,.08);this.distance+=(this.goalDistance-this.distance)*.08;this.group.rotation.y=this.is3d?this.yaw:0;this.group.rotation.x=this.is3d?this.pitch:0;this.camera.position.set(this.center.x,this.center.y,this.distance+this.center.z);this.camera.lookAt(this.center);this.group.updateMatrixWorld();this.camera.updateMatrixWorld();this.positions.clear();this.seed.visible=this.birth!==null&&this.birth<8;this.seed.scale.setScalar(this.birth!==null?.3+.4*Math.min(1,this.birth/2):.7);const born=c=>this.birth===null||this.birth>8+(concepts.indexOf(c)%12)*.3||(['number','expression','shape','function','chance','data'].includes(c.id)&&this.birth>2+concepts.indexOf(c)*.7);
const priority=new Set(['pythagorean','trig-ratio','cosine-law','vector','dot','complex-plane','quadratic','discriminant','complex','derivative','integral','limit','sequence','sigma','combination','binomial-theorem','binomial','normal','analysis','inference','trig','unit-circle','analytic-geometry','curves','number','geometry','probability','correlation','advanced-derivative','advanced-integral']);
for(const{c,sprite}of this.nodes){sprite.position.z=this.is3d?c.position[2]:0;const active=born(c)&&(!this.related||this.related.has(c.id))&&(!this.subject||this.subject===c.subject);sprite.material.opacity=born(c)?(active?1:.13):0;sprite.scale.setScalar(c.id===this.focus ? .65 : .36);const p=this.project(sprite.position);this.positions.set(c.id,p);const b=this.labels.get(c.id);const visible=p.z<1&&p.x>20&&p.x<this.w-20&&p.y>25&&p.y<this.h-30&&active&&(this.focus||(this.compact?new Set(['pythagorean','trig-ratio','cosine-law','dot','complex-plane','quadratic','derivative','integral','limit','sequence','combination','binomial-theorem','normal','analysis','inference','unit-circle']).has(c.id):priority.has(c.id)));b.hidden=!visible;b.style.transform=`translate(${p.x}px,${p.y}px)`;b.classList.toggle('selected',c.id===this.focus);}
for(const edge of this.edges){edge.a.z=this.is3d?byId[edge.e.from].position[2]:0;edge.b.z=this.is3d?byId[edge.e.to].position[2]:0;const arr=edge.line.geometry.attributes.position.array;arr.set(edge.a.toArray(),0);arr.set(edge.b.toArray(),3);edge.line.geometry.attributes.position.needsUpdate=true;edge.line.visible=this.lines&&born(byId[edge.e.from])&&born(byId[edge.e.to]);edge.line.material.opacity=this.focus?(edge.e.from===this.focus||edge.e.to===this.focus ? .6 : .025):.17;}
for(let i=0;i<this.particleCount;i++){const edge=this.edges[(i*7)%this.edges.length],p=((motion?t*.11:0)+i*.237)%1;const pos=edge.a.clone().lerp(edge.b,p);this.particlePositions.set(pos.toArray(),i*3);const col=new THREE.Color(subjects[byId[edge.e.to].subject].color);if(this.related&&!this.related.has(edge.e.from))col.multiplyScalar(.1);this.particleColors.set(col.toArray(),i*3);}
if(this.activeEdge){const edge=this.edges.find(x=>x.e.id===this.activeEdge.e.id);if(edge){const u=(t-this.activeEdge.start)/2.1,pos=edge.a.clone().lerp(edge.b,Math.min(1,u));this.particlePositions.set(pos.toArray(),0);this.particleColors.set([1,1,1],0);edge.line.material.opacity=.85;const target=this.nodes.find(n=>n.c.id===edge.e.to);if(u>=1&&u<2)target.sprite.scale.setScalar(.5+.3*Math.sin((u-1)*Math.PI));if(u>2)this.activeEdge=null;}}
this.particles.visible=this.lines&&(this.birth===null||this.birth>9);this.particles.geometry.attributes.position.needsUpdate=true;this.particles.geometry.attributes.color.needsUpdate=true;if(this.webgl)this.renderer.render(this.scene,this.camera);else this.drawFallback();}
drawFallback(){const ctx=this.ctx;ctx.clearRect(0,0,this.w,this.h);if(this.lines)for(const{e,line}of this.edges){if(!line.visible)continue;const a=this.positions.get(e.from),b=this.positions.get(e.to);ctx.globalAlpha=line.material.opacity;ctx.strokeStyle=subjects[byId[e.to].subject].color;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}for(const{c,sprite}of this.nodes){const p=this.positions.get(c.id);ctx.globalAlpha=sprite.material.opacity;ctx.fillStyle=subjects[c.subject].color;ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p.x,p.y,c.id===this.focus?5:3,0,Math.PI*2);ctx.fill();}if(this.seed.visible){ctx.fillStyle='#ffffff';ctx.shadowColor='#ffffff';ctx.shadowBlur=20;ctx.globalAlpha=1;ctx.beginPath();ctx.arc(this.w/2,this.h/2,4,0,Math.PI*2);ctx.fill();}ctx.shadowBlur=0;ctx.globalAlpha=1;}
}
export class SolidModel{
constructor(host){this.host=host;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(40,1,.1,100);this.camera.position.set(5,4,7);this.camera.lookAt(0,0,0);this.group=new THREE.Group();this.scene.add(this.group);try{this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.4));host.append(this.renderer.domElement);}catch{return;}this.scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(3,5,4);this.scene.add(light);const axes=new THREE.AxesHelper(3);this.group.add(axes);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.resize();}
resize(){if(!this.renderer)return;const r=this.host.getBoundingClientRect();this.renderer.setSize(Math.max(1,r.width),Math.max(1,r.height));this.camera.aspect=Math.max(.1,r.width/Math.max(1,r.height));this.camera.updateProjectionMatrix();}
set(model,s){if(!this.renderer)return;this.coin=null;for(const child of [...this.group.children]){if(child.type==='AxesHelper')continue;this.group.remove(child);child.geometry?.dispose();if(Array.isArray(child.material))child.material.forEach(m=>m.dispose());else child.material?.dispose();}const material=new THREE.MeshStandardMaterial({color:0xb59aef,transparent:true,opacity:.23,side:THREE.DoubleSide,roughness:.25,metalness:.2});
if(model==='volume'){const n=Math.min(40,s.n);for(let i=0;i<n;i++){const x=4*(i+.5)/n;const mesh=new THREE.Mesh(new THREE.CylinderGeometry(Math.sqrt(x),Math.sqrt(x),4/n*.85,36),material);mesh.rotation.z=Math.PI/2;mesh.position.x=x-2;this.group.add(mesh);}}
else if(model==='statistics'){const points=s.population.map((v,i)=>new THREE.Vector3((v-50)/7,Math.sin(i*2.399)*2,Math.cos(i*2.399)*2));const geo=new THREE.BufferGeometry().setFromPoints(points);this.group.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0x55dce9,size:.065,transparent:true,opacity:.6})));if(s.sample.length){const geo2=new THREE.BufferGeometry().setFromPoints(s.sample.map((v,i)=>new THREE.Vector3((v-50)/7,Math.sin(i*2.399)*2,Math.cos(i*2.399)*2)));this.group.add(new THREE.Points(geo2,new THREE.PointsMaterial({color:0xe7c56b,size:.14})));}}
else if(model==='vector'){this.group.add(new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(),2,0x55dce9,.22,.12));const r=s.theta*Math.PI/180;this.group.add(new THREE.ArrowHelper(new THREE.Vector3(Math.cos(r),Math.sin(r)*.8,Math.sin(r)*.6).normalize(),new THREE.Vector3(),3,0xeb99c9,.22,.12));}
else if(model==='complex'||model==='coordinate'){const circle=new THREE.BufferGeometry().setFromPoints(Array.from({length:101},(_,i)=>new THREE.Vector3(2*Math.cos(i/100*Math.PI*2),2*Math.sin(i/100*Math.PI*2),0)));this.group.add(new THREE.Line(circle,new THREE.LineBasicMaterial({color:0xeb99c9})));const r=s.theta*Math.PI/180;this.group.add(new THREE.ArrowHelper(new THREE.Vector3(Math.cos(r),Math.sin(r),0),new THREE.Vector3(),2,0xe7c56b,.2,.1));}
else if(model==='probability'){const coin=new THREE.Mesh(new THREE.CylinderGeometry(1.3,1.3,.12,48),new THREE.MeshStandardMaterial({color:0xe7c56b,roughness:.28,metalness:.7}));this.coin=coin;this.group.add(coin);}
else if(model==='curve'){const cone=new THREE.Mesh(new THREE.ConeGeometry(2,4,48,1,true),material);this.group.add(cone);const plane=new THREE.Mesh(new THREE.PlaneGeometry(5,5),new THREE.MeshBasicMaterial({color:0xeb99c9,transparent:true,opacity:.14,side:THREE.DoubleSide}));plane.rotation.x=Math.PI/2+Math.atan(.4);plane.position.y=-.5;this.group.add(plane);const ellipse=new THREE.BufferGeometry().setFromPoints(Array.from({length:101},(_,i)=>{const a=i/100*Math.PI*2;const r=1.25/(1-.2*Math.sin(a));return new THREE.Vector3(r*Math.cos(a),-.5-.4*r*Math.sin(a),r*Math.sin(a))}));this.group.add(new THREE.Line(ellipse,new THREE.LineBasicMaterial({color:0xe7c56b})));}
}
tick(t,motion=true){if(!this.renderer||this.host.hidden)return;this.group.rotation.y=motion?t*.13:.2;if(this.coin){this.coin.rotation.x=motion?t*7:.7;this.coin.position.y=motion?Math.abs(Math.sin(t*2))*1.5:0;}this.renderer.render(this.scene,this.camera);}
}
