import{useEffect,useMemo,useState}from'react';import{ChevronLeft,ChevronRight,Pause,Play,RotateCcw,Sparkles}from'lucide-react';import{choose3,diagonalKey,diagonals,isAdjacent,oneEdgeTriangles,sharedEdgeCount,sharedPolygonEdge,triangles,type Pair,type Triple}from'./math';import Polygon3D from'./Polygon3D'
type Mode='diag'|'tri'|'edge';type Speed='遅い'|'普通'|'速い';const names='ABCDEFGHIJKL';
const prompts={diag:['1つの頂点から、なぜ n−3 本なのだろう？','なぜ最後に2で割る必要がある？'],tri:['なぜ3つの頂点を選べば必ず三角形になる？','ABCとBCAは別の三角形だろうか？'],edge:['第3頂点として使えない頂点はどこだろう？','なぜ1辺につき n−4 個になる？','全部でなぜ n(n−4) 個になる？']};
const hints={diag:['自分自身と左右の隣には対角線を引けません。','両端のどちらからも同じ線を数えています。'],tri:['正多角形では3頂点が一直線上に並びません。','選ぶ順番が違っても、頂点の組は同じです。'],edge:['基準辺の外側に続く2つの隣接頂点に注目。','n−2個の候補から対象外の2個を引きます。','各三角形が共有する辺は1つなので重複しません。']};
const norm=(t:number[])=>[...t].sort((a,b)=>a-b).join('-');
function App(){const[n,setN]=useState(10);const[mode,setMode]=useState<Mode>('diag');const[index,setIndex]=useState(-1);const[showAll,setShowAll]=useState(false);const[completedDiagonalKeys,setCompletedDiagonalKeys]=useState(new Set<string>());const[answer,setAnswer]=useState(false);const[playing,setPlaying]=useState(false);const[speed,setSpeed]=useState<Speed>('普通');const[view3d,setView3d]=useState(false);const[tilt,setTilt]=useState(false);const[cameraReset,setCameraReset]=useState(0);const[hint,setHint]=useState(0);const[formula,setFormula]=useState<'double'|'choose'>('double');const[manual,setManual]=useState(false);const[base,setBase]=useState<Pair|null>(null);const[picked,setPicked]=useState<number[]>([]);const[found,setFound]=useState(new Set<string>());const[msg,setMsg]=useState('');
const ds=useMemo(()=>diagonals(n),[n]),ts=useMemo(()=>triangles(n),[n]),os=useMemo(()=>oneEdgeTriangles(n),[n]);const sequence=mode==='diag'?ds:mode==='tri'?ts:os;const current=index>=0?sequence[index%sequence.length]:null;
const reset=()=>{setIndex(-1);setShowAll(false);setCompletedDiagonalKeys(new Set());setPlaying(false);setPicked([]);setBase(null);setMsg('')};useEffect(()=>{reset();setAnswer(false);setHint(0);setFound(new Set())},[n,mode]);useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setIndex(i=>{const next=(i+1)%sequence.length;if(mode==='diag'){const pair=sequence[next] as Pair;setCompletedDiagonalKeys(keys=>new Set(keys).add(diagonalKey(...pair)))}return next}),speed==='遅い'?1800:speed==='普通'?1000:450);return()=>clearInterval(timer)},[playing,speed,sequence,mode]);
const activeTriangleVertices:number[]=mode==='tri'?(picked.length?[...picked].sort((a,b)=>a-b):current?.length===3?[...current]:[]):picked.length===3?[...picked].sort((a,b)=>a-b):current?.length===3?[...current]:[];const activeTriangle:Triple|null=activeTriangleVertices.length===3?activeTriangleVertices as Triple:null;const activePair:Pair|null=mode==='diag'&&current?current as Pair:mode==='edge'?(manual?base:activeTriangle?sharedPolygonEdge(activeTriangle,n):null):null;
function selectVertex(v:number){if(mode==='tri'){setPlaying(false);setPicked(p=>p.includes(v)?p.filter(x=>x!==v):p.length<3?[...p,v]:[v]);return}if(mode==='edge'&&manual&&base){if(base.includes(v))return;const t=[base[0],base[1],v].sort((a,b)=>a-b)as Triple;const count=sharedEdgeCount(t,n);if(count===1){const key=norm(t);setFound(f=>new Set(f).add(key));setMsg('✓ 正解　正多角形とちょうど1辺を共有しています');setPicked(t)}else{setMsg(`× この三角形は正多角形と${count}辺を共有しています`);setPicked(t)}}}
function selectEdge(a:number){if(mode!=='edge'||!manual)return;setBase([a,(a+1)%n]);setPicked([]);setMsg(`辺 ${names[a]}${names[(a+1)%n]} を選びました。第3頂点を選ぼう。`)}
const selectCompletedDiagonal=(pair:Pair)=>{const next=ds.findIndex(([a,b])=>diagonalKey(a,b)===diagonalKey(...pair));if(next<0)return;setPlaying(false);setIndex(next);setMsg(`✓ 生成済み\n${names[pair[0]]} ─ ${names[pair[1]]}\nこの対角線はすでに数えています（${next+1}本目に確認）`)};const advance=(d:number)=>{setPlaying(false);setPicked([]);setMsg('');setIndex(i=>{const next=Math.max(-1,Math.min(sequence.length-1,i+d));if(mode==='diag'&&next>=0){const pair=sequence[next] as Pair;setCompletedDiagonalKeys(keys=>new Set(keys).add(diagonalKey(...pair)))}return next})};const total=mode==='diag'?ds.length:mode==='tri'?ts.length:os.length;
return <div className="app"><header><a href="../../">← 教材一覧</a><div className="eyebrow"><Sparkles/> MATHEMATICS A · COUNTING</div><h1>正多角形 <b>カウント・ラボ</b></h1><p>光る図形をたどって、組合せのしくみを発見しよう。</p></header>
<main><section className="topbar"><div className="number"><label>何角形で調べますか？</label><div><button onClick={()=>setN(Math.max(5,n-1))}>−</button><input aria-label="頂点数" type="number" min="5" max="12" value={n} onChange={e=>setN(Math.min(12,Math.max(5,+e.target.value||5)))}/><button onClick={()=>setN(Math.min(12,n+1))}>＋</button><span>正{['','一','二','三','四','五','六','七','八','九','十','十一','十二'][n]}角形</span></div></div><div className="view"><button className={!view3d?'on':''} onClick={()=>setView3d(false)}>2D</button><button className={view3d?'on':''} onClick={()=>{setView3d(true);setCameraReset(x=>x+1)}}>3D</button><button disabled={!view3d} onClick={()=>{setTilt(false);setCameraReset(x=>x+1)}}>正面に戻す</button><button disabled={!view3d} onClick={()=>{setTilt(true);setCameraReset(x=>x+1)}}>少し傾ける</button></div></section>
<nav className="tabs">{([['diag','01','対角線'],['tri','02','三角形'],['edge','03','1辺だけ共有する三角形']]as const).map(([m,num,label])=><button className={mode===m?'active':''} onClick={()=>setMode(m)} key={m}><i>{num}</i>{label}</button>)}</nav>
<div className="workspace"><section className="stage"><div className="stage-label"><span>INTERACTIVE CANVAS</span><b>{view3d?'3D VIEW · 平面図形を空間から観察':'2D VIEW'}</b></div><Polygon n={n} mode={mode} current={current} activePair={activePair} activeTriangleVertices={activeTriangleVertices} showAll={showAll} completedDiagonalKeys={completedDiagonalKeys} manual={manual} base={base} view3d={view3d} tilt={tilt} cameraReset={cameraReset} onVertex={selectVertex} onEdge={selectEdge} onDiagonal={selectCompletedDiagonal}/><div className="legend"><span><i/>通常の辺</span><span><i/>選択中</span><span><i/>対象外</span></div></section>
<aside><div className="counter"><small>COUNT PROGRESS</small><strong>{index<0?0:index+1}<em> / {total}</em></strong><p>{mode==='diag'?'見つけた対角線':mode==='tri'?'現在の三角形':'条件を満たす三角形'}</p></div>{mode==='diag'&&<DiagonalHistory diagonals={ds} completed={completedDiagonalKeys} active={activePair} onSelect={selectCompletedDiagonal}/>}{mode==='edge'&&!manual&&<div className="step"><b>STEP {index<0?1:index%4+2}</b><p>{index<0?'まず、多角形の1辺 AB を選びます。':activeTriangle&&activePair?`共有辺 ${names[activePair[0]]}${names[activePair[1]]} ＋ 第3頂点 ${names[activeTriangle.find(v=>!activePair.includes(v))!]}`:'第3頂点を調べます。'}</p></div>}{mode==='tri'&&<p className="selection">選んだ頂点：{activeTriangleVertices.map(i=>names[i]).join('・')||'3つ選ぼう'}</p>}{msg&&<div className={'feedback '+(msg.startsWith('✓')?'good':'bad')}>{msg}</div>}
<div className="controls"><button onClick={()=>advance(-1)}><ChevronLeft/>前へ</button><button className="primary" onClick={()=>advance(1)}>次へ<ChevronRight/></button><button onClick={()=>{setPlaying(true);if(index<0){setIndex(0);if(mode==='diag')setCompletedDiagonalKeys(keys=>new Set(keys).add(diagonalKey(...ds[0])))}}}><Play/>自動再生</button><button onClick={()=>setPlaying(false)}><Pause/>一時停止</button><button onClick={reset}><RotateCcw/>最初に戻る</button><button className={showAll?'on':''} onClick={()=>setShowAll(value=>!value)}>{showAll?'通常表示':'すべて表示'}</button></div>{mode!=='diag'&&<div className="speed"><span>再生速度</span>{(['遅い','普通','速い']as Speed[]).map(s=><button className={s===speed?'on':''} onClick={()=>setSpeed(s)}>{s}</button>)}</div>}{mode==='edge'&&<button className={'manual '+(manual?'on':'')} onClick={()=>{setManual(!manual);reset()}}>◎ 自分で探す</button>}{manual&&<p className="found">見つけた数 <b>{found.size} / {os.length}</b></p>}
<button className="answer" onClick={()=>setAnswer(true)}>答えを確認</button>{answer&&<Answer mode={mode} n={n} formula={formula} setFormula={setFormula}/>}</aside></div>
<section className="think"><div><small>THINK ABOUT IT</small><h2>考えてみよう</h2></div><ul>{prompts[mode].map(x=><li>{x}</li>)}</ul><div><button onClick={()=>setHint(h=>Math.min(h+1,hints[mode].length))}>ヒント {hint}/{hints[mode].length}</button>{hints[mode].slice(0,hint).map((x,i)=><p><b>HINT {i+1}</b> {x}</p>)}</div></section>
<Results n={n} reveal={answer}/></main><footer>正多角形 COUNT LAB <span>数学A · 場合の数</span></footer></div>}

function Answer({mode,n,formula,setFormula}:{mode:Mode,n:number,formula:'double'|'choose',setFormula:(x:'double'|'choose')=>void}){return <div className="explain">{mode==='diag'?<><div className="switch"><button className={formula==='double'?'on':''} onClick={()=>setFormula('double')}>両端から数える</button><button className={formula==='choose'?'on':''} onClick={()=>setFormula('choose')}>組合せ</button></div>{formula==='double'?<p>1頂点から <b>n−3</b> 本。全頂点では n(n−3) 本ですが、同じ線を両端から2回数えるので2で割ります。</p>:<p>2頂点の選び方 <b>nC2</b> から、多角形の n 辺を除きます。</p>}<strong>{n}({n}−3)÷2 = {n*(n-3)/2}本</strong></>:mode==='tri'?<><p>n個の頂点から、異なる3個を選びます。順番は区別しません。</p><strong>{n}C3 = {choose3(n)}個</strong></>:<><p>第3頂点候補 n−2 個から、2辺を共有してしまう2頂点を除くので、1辺につき <b>n−4</b> 個です。</p><strong>{n}×({n}−4) = {n*(n-4)}個</strong></>}</div>}
function Results({n,reveal}:{n:number,reveal:boolean}){return <section className="results"><small>YOUR PREDICTION</small><h2>結果を予想しよう</h2><div className="table"><b>内容</b><b>自分の予想</b><b>実際の個数</b><b>考え方</b>{[['対角線',n*(n-3)/2,'n(n−3) / 2'],['三角形',choose3(n),'nC3'],['1辺だけ共有する三角形',n*(n-4),'n(n−4)']].map(([a,b,c])=><><span>{a}</span><input aria-label={`${a}の予想`} type="number" placeholder="？"/><strong>{reveal?`${b}個`:'•••'}</strong><code>{reveal?c:'LOCKED'}</code></>)}</div></section>}

export type PolygonProps={n:number,mode:Mode,current:Pair|Triple|null,activePair:Pair|null,activeTriangleVertices:number[],showAll:boolean,completedDiagonalKeys:Set<string>,manual:boolean,base:Pair|null,view3d:boolean,tilt:boolean,cameraReset:number,onVertex:(x:number)=>void,onEdge:(x:number)=>void,onDiagonal:(pair:Pair)=>void}

function DiagonalHistory({diagonals:lines,completed,active,onSelect}:{diagonals:Pair[],completed:Set<string>,active:Pair|null,onSelect:(pair:Pair)=>void}){
 const generated=lines.filter(([a,b])=>completed.has(diagonalKey(a,b)))
 return <section className="diagonal-history" aria-label="生成済み対角線"><div><b>生成済み対角線</b><span>{generated.length} / {lines.length}</span></div>{generated.length?<div className="history-chips">{generated.map(pair=>{const key=diagonalKey(...pair);const isActive=!!active&&diagonalKey(...active)===key;return <button key={key} className={isActive?'active':''} onClick={()=>onSelect(pair)} aria-pressed={isActive}>{names[pair[0]]}-{names[pair[1]]}</button>})}</div>:<p>「次へ」で確認した線がここに残ります。</p>}</section>
}

export function Polygon2D(p:Omit<PolygonProps,'view3d'|'tilt'|'cameraReset'>){
 const pts=Array.from({length:p.n},(_,i)=>{const a=-Math.PI/2+i*2*Math.PI/p.n;return{x:300+220*Math.cos(a),y:275+220*Math.sin(a)}})
 const act=new Set([...(p.activePair||[]),...p.activeTriangleVertices])
 const tri=p.activeTriangleVertices.length===3?p.activeTriangleVertices as Triple:null
 const all=p.mode==='diag'?diagonals(p.n):p.mode==='tri'?triangles(p.n):oneEdgeTriangles(p.n)
 const activeKey=p.activePair?diagonalKey(...p.activePair):null
 const completed=p.mode==='diag'?diagonals(p.n).filter(pair=>p.completedDiagonalKeys.has(diagonalKey(...pair))&&diagonalKey(...pair)!==activeKey):[]
 const backgroundDiagonals=p.showAll?all.filter((line):line is Pair=>line.length===2&&diagonalKey(...line)!==activeKey&&!p.completedDiagonalKeys.has(diagonalKey(...line))):[]
 return <div className="canvas"><svg viewBox="0 0 600 550" role="img" aria-label={`正${p.n}角形`}>
  <defs><filter id="glow" filterUnits="userSpaceOnUse" x="0" y="0" width="600" height="550"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><radialGradient id="fill"><stop stopColor="#68f8ff" stopOpacity=".38"/><stop offset="1" stopColor="#3b82f6" stopOpacity=".05"/></radialGradient></defs>
  {tri&&<polygon className={'triangle '+(sharedEdgeCount([...tri].sort((a,b)=>a-b)as Triple,p.n)!==1&&p.mode==='edge'?'invalid':'')} points={tri.map(i=>`${pts[i].x},${pts[i].y}`).join(' ')}/>}
  <g className="polygon-edge-layer" data-layer="polygon-edges">{pts.map((q,i)=>{const r=pts[(i+1)%p.n];const selected=p.activePair&&isAdjacent(p.activePair[0],p.activePair[1],p.n)&&p.activePair.includes(i)&&p.activePair.includes((i+1)%p.n);return <line onClick={()=>p.onEdge(i)} className={'side '+(selected?'selected':'')+(p.manual?' clickable':'')} x1={q.x} y1={q.y} x2={r.x} y2={r.y} key={'s'+i}/>})}</g>
  <g className="completed-diagonal-layer" data-layer="completed-diagonals">{backgroundDiagonals.map(pair=><line className="diagonal all" key={'all-'+diagonalKey(...pair)} x1={pts[pair[0]].x} y1={pts[pair[0]].y} x2={pts[pair[1]].x} y2={pts[pair[1]].y}/>)}{completed.map(pair=><line className="diagonal completed" data-diagonal={diagonalKey(...pair)} onClick={()=>p.onDiagonal(pair)} key={'done-'+diagonalKey(...pair)} x1={pts[pair[0]].x} y1={pts[pair[0]].y} x2={pts[pair[1]].x} y2={pts[pair[1]].y}/>)}</g>
  <g className="active-diagonal-layer" data-layer="active-diagonal">{p.mode==='diag'&&p.activePair&&<><line className="diagonal active-halo" data-diagonal={activeKey!} x1={pts[p.activePair[0]].x} y1={pts[p.activePair[0]].y} x2={pts[p.activePair[1]].x} y2={pts[p.activePair[1]].y}/><line className="diagonal active" data-diagonal={activeKey!} x1={pts[p.activePair[0]].x} y1={pts[p.activePair[0]].y} x2={pts[p.activePair[1]].x} y2={pts[p.activePair[1]].y}/></>}</g>
  <g className="vertex-layer" data-layer="vertices">{pts.map((q,i)=><g className={'vertex '+(act.has(i)?'active':'')} onClick={()=>p.onVertex(i)} key={i}><circle className="halo" cx={q.x} cy={q.y} r="22"/><circle cx={q.x} cy={q.y} r="9"/></g>)}</g>
  <g className="label-layer" data-layer="labels">{pts.map((q,i)=><text className={act.has(i)?'active':''} key={i} x={q.x+(q.x-300)*.13} y={q.y+(q.y-275)*.13+5}>{names[i]}</text>)}</g>
 </svg></div>
}

function Polygon(p:PolygonProps){if(p.view3d)return <Polygon3D {...p}/>;return <Polygon2D {...p}/>}
export default App
