'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const TAU=Math.PI*2, fmt=n=>Math.abs(n)>999?'∞':Math.abs(n)<1e-9?'0':Number(n.toFixed(2)).toString();
const cases={
 ex1:{title:'放物線を動く点',eq:'\\(x=2t+1,\\quad y=2t^2-3\\)',min:-2,max:2,step:.01,scale:40,fn:t=>({x:2*t+1,y:2*t*t-3,dx:2,dy:4*t}),steps:['\\(x=2t+1\\)　→　\\(dx/dt=2\\)','\\(y=2t^2-3\\)　→　\\(dy/dt=4t\\)','したがって　\\(\\displaystyle dy/dx=\\frac{4t}{2}=2t\\)'],q:'tを少し増やすと、Pはどちらへ動くだろう？'},
 circle:{title:'単位円を動く点',eq:'\\(x=\\cos t,\\quad y=\\sin t\\)',min:0,max:TAU,step:.005,scale:110,circle:1,fn:t=>({x:Math.cos(t),y:Math.sin(t),dx:-Math.sin(t),dy:Math.cos(t)}),steps:['\\(dx/dt=-\\sin t,\\quad dy/dt=\\cos t\\)','\\(\\displaystyle dy/dx=\\frac{\\cos t}{-\\sin t}=-\\frac{\\cos t}{\\sin t}\\)','\\(x^2+y^2=\\cos^2t+\\sin^2t=1\\)　半径1の円'],q:'半径ベクトルと速度ベクトルの角度は？'},
 free:{title:'自由に試す',eq:'<label>x(t) = <input id="freeX" value="cos(t)"></label><br><label>y(t) = <input id="freeY" value="sin(t)"></label><p class="feedback" id="freeError">t, t², sin(t), cos(t) と四則演算が使えます（eval不使用）。</p>',min:-TAU,max:TAU,step:.01,scale:70,fn:t=>freeFn(t),steps:['数式を安全なトークナイザーと再帰下降パーサーで解析します。','導関数は中央差分で近似し、軌跡・接線・速度を同期します。'],q:'式を変えると、どんな軌跡になるだろう？'}
};
let active=cases.ex1,t=0,playing=false,last=0,shownT=0,view={trace:true,tangent:true,velocity:true,xcomp:false,ycomp:false};
const conceptDef={min:-2,max:2,scale:70,fn:u=>({x:u,y:u*u,dx:1,dy:2*u})};
let conceptT=0,conceptPlaying=false,conceptLast=0,conceptStage='t';
const conceptMessages={
 t:'まず t を動かすと、x と y が同時に変化します。',
 x:'x=t なので、t が増えると横方向へ一定の速さで進みます。dx/dt=1 です。',
 y:'y=t² なので、縦方向の変化は位置によって変わります。dy/dt=2t です。',
 p:'x と y の変化が組み合わさり、点Pは放物線上を動きます。速度ベクトルの向きが接線方向です。'
};

function math(){window.MathJax?.typesetPromise?.().catch(()=>{})}
function setConceptStage(stage){
 conceptStage=stage;
 $$('[data-concept-stage]').forEach(b=>b.classList.toggle('active',b.dataset.conceptStage===stage));
 $('#conceptStageText').textContent=conceptMessages[stage]||conceptMessages.t;
}
function updateConcept(){
 const p=conceptDef.fn(conceptT),m=slope(p);
 $('#conceptTLabel').textContent=fmt(conceptT);
 $('#conceptValues').innerHTML=[['t',fmt(conceptT)],['x(t)',fmt(p.x)],['y(t)',fmt(p.y)],['dx/dt',fmt(p.dx)],['dy/dt',fmt(p.dy)],['dy/dx',isFinite(m)?fmt(m):'定義なし']].map(v=>`<div>${v[0]}<b>${v[1]}</b></div>`).join('');
 draw2d($('#conceptGraph'),conceptDef,conceptT,{trace:true,tangent:true,velocity:true,xcomp:conceptStage==='x',ycomp:conceptStage==='y'});
}
$('[data-concept-stage]').forEach(b=>b.onclick=()=>{setConceptStage(b.dataset.conceptStage);updateConcept()});
$('#conceptRange').oninput=e=>{conceptT=+e.target.value;conceptPlaying=false;$('#conceptPlay').textContent='▶ 再生';updateConcept()};
$('#conceptPlay').onclick=()=>{conceptPlaying=!conceptPlaying;$('#conceptPlay').textContent=conceptPlaying?'⏸ 一時停止':'▶ 再生'};
$('#conceptReset').onclick=()=>{conceptT=conceptDef.min;$('#conceptRange').value=conceptT;conceptPlaying=false;$('#conceptPlay').textContent='▶ 再生';setConceptStage('t');updateConcept()};

$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));resizeAll();math()});
$$('.subtabs button').forEach(b=>b.onclick=()=>{ $$('.subtabs button').forEach(x=>x.classList.toggle('active',x===b)); active=cases[b.dataset.case]; setupCase();});
function setupCase(){playing=false;$('#play').textContent='▶ 再生';t=active.min;shownT=t;$('#caseTitle').textContent=active.title;$('#equations').innerHTML=active.eq;$('#steps').innerHTML=active.steps.map((s,i)=>`<div><b>${i+1}</b> ${s}</div>`).join('');$('#caseQuestion').innerHTML='💡 <b>考えてみよう</b>　'+active.q;const r=$('#tRange');r.min=active.min;r.max=active.max;r.step=active.step;r.value=t;$('#ticks').innerHTML=active===cases.circle?'<span>0</span><span>π/2</span><span>π</span><span>3π/2</span><span>2π</span>':'<span>'+fmt(active.min)+'</span><span>0</span><span>'+fmt(active.max)+'</span>';if(active===cases.free)setTimeout(()=>{$$('#freeX,#freeY').forEach(x=>x.oninput=()=>update())},0);update();math()}
$('#tRange').oninput=e=>{t=+e.target.value;shownT=t;update()};$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'⏸ 一時停止':'▶ 再生'};$('#reset').onclick=()=>{t=active.min;shownT=t;$('#tRange').value=t;playing=false;$('#play').textContent='▶ 再生';update()};$$('[data-view]').forEach(c=>c.onchange=()=>{view[c.dataset.view]=c.checked;update()});
function slope(p){return Math.abs(p.dx)<1e-7?Infinity:p.dy/p.dx}
function update(){let p;try{p=active.fn(t);$('#freeError')?.replaceChildren(document.createTextNode('解析できました。スライダーで動きを確認してください。'))}catch(e){if($('#freeError'))$('#freeError').textContent='式を確認してください：'+e.message;return}const m=slope(p);$('#tLabel').textContent=active===cases.circle?piText(t):fmt(t);$('#values').innerHTML=[['t',piText(t)],['x',fmt(p.x)],['y',fmt(p.y)],['dx/dt',fmt(p.dx)],['dy/dt',fmt(p.dy)],['dy/dx',isFinite(m)?fmt(m):'定義なし（垂直接線）']].map(v=>`<div>${v[0]}<b>${v[1]}</b></div>`).join('');draw2d($('#graph'),active,t,view);}
function piText(v){if(Math.abs(v)<.005)return '0';for(const [n,s] of [[.5,'π/2'],[1,'π'],[1.5,'3π/2'],[2,'2π'],[-.5,'−π/2'],[-1,'−π'],[-2,'−2π']])if(Math.abs(v-n*Math.PI)<.005)return s;return fmt(v)}
function prep(c){const d=Math.min(devicePixelRatio||1,2),w=c.clientWidth||500,h=Math.max(c.clientHeight||380,320);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return{ctx,w,h}}
function arrow(ctx,x1,y1,x2,y2,color,width=3){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y1,x2-x1);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-10*Math.cos(a-.45),y2-10*Math.sin(a-.45));ctx.lineTo(x2-10*Math.cos(a+.45),y2-10*Math.sin(a+.45));ctx.fill()}
function draw2d(c,def,at,opt={trace:true,tangent:true,velocity:true}){const{ctx,w,h}=prep(c),cx=w/2,cy=h/2,sc=Math.min(def.scale,w/5.2,h/5.2);ctx.fillStyle='#08182a';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1a3551';ctx.lineWidth=1;for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(cx+i*sc,0);ctx.lineTo(cx+i*sc,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,cy+i*sc);ctx.lineTo(w,cy+i*sc);ctx.stroke()}arrow(ctx,8,cy,w-12,cy,'#829bb4',1.5);arrow(ctx,cx,h-8,cx,12,'#829bb4',1.5);ctx.fillStyle='#c4d2df';ctx.font='13px sans-serif';ctx.fillText('x',w-22,cy-8);ctx.fillText('y',cx+8,18);ctx.fillText('O',cx+6,cy+16);const X=x=>cx+x*sc,Y=y=>cy-y*sc;if(opt.trace){ctx.strokeStyle='#77a2c8';ctx.lineWidth=2.5;ctx.beginPath();let began=false;const end=Math.min(at,def.max),start=def.min;for(let i=0;i<=350;i++){const u=start+(end-start)*i/350;let q;try{q=def.fn(u)}catch{continue}if(!isFinite(q.x+q.y))continue;began?ctx.lineTo(X(q.x),Y(q.y)):ctx.moveTo(X(q.x),Y(q.y));began=true}ctx.stroke()}let p;try{p=def.fn(at)}catch{return}if(def.circle){ctx.strokeStyle='#446b8e';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(X(p.x),Y(p.y));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#dce7f0';ctx.fillText('半径 '+def.circle,cx+(p.x*sc)/2+5,cy-(p.y*sc)/2);ctx.fillText('O',cx+5,cy+14)}const px=X(p.x),py=Y(p.y),m=slope(p);if(opt.tangent){const len=90,n=Math.hypot(p.dx,p.dy)||1,ux=p.dx/n,uy=p.dy/n;ctx.strokeStyle=Math.abs(m)<.03?'#3da9fc':m>0?'#21b27a':'#ef5b67';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(px-ux*len,py+uy*len);ctx.lineTo(px+ux*len,py-uy*len);ctx.stroke()}if(opt.velocity){const n=Math.max(Math.hypot(p.dx,p.dy),1),f=55/n;arrow(ctx,px,py,px+p.dx*f,py-p.dy*f,'#3da9fc',3);if(opt.xcomp)arrow(ctx,px,py,px+p.dx*f,py,'#8bcdf8',2);if(opt.ycomp)arrow(ctx,px,py,px,py-p.dy*f,'#b7e0ff',2)}ctx.shadowBlur=18;ctx.shadowColor='#f5c95b';ctx.fillStyle='#f5c95b';ctx.beginPath();ctx.arc(px,py,8,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.fillText('P',px+12,py-10)}
// Safe expression parser: no Function/eval; restricted grammar and identifiers.
function tokenize(s){s=s.replaceAll('²','^2').replace(/\s/g,'');const out=[];for(let i=0;i<s.length;){const m=s.slice(i).match(/^(sin|cos|sqrt|t|pi|\d+(?:\.\d+)?|[()+\-*/^])/);if(!m)throw Error(`「${s[i]}」は使えません`);out.push(m[0]);i+=m[0].length}return out}
function parseExpr(src,tv){const a=tokenize(src);let i=0;function expr(){let v=term();while(a[i]=='+'||a[i]=='-'){const o=a[i++],r=term();v=o=='+'?v+r:v-r}return v}function term(){let v=power();while(a[i]=='*'||a[i]=='/'){const o=a[i++],r=power();v=o=='*'?v*r:v/r}return v}function power(){let v=atom();if(a[i]=='^'){i++;v=Math.pow(v,power())}return v}function atom(){const z=a[i++];if(z==='-')return-atom();if(z==='('){const v=expr();if(a[i++]!==')')throw Error('かっこを閉じてください');return v}if(z==='t')return tv;if(z==='pi')return Math.PI;if(['sin','cos','sqrt'].includes(z)){if(a[i++]!=='(')throw Error('関数には ( ) が必要です');const v=expr();if(a[i++]!==')')throw Error('かっこを閉じてください');return Math[z](v)}const n=+z;if(!isFinite(n))throw Error('式を確認してください');return n}const v=expr();if(i!==a.length)throw Error('演算記号を確認してください');return v}
function freeFn(u){const x=$('#freeX')?.value||'cos(t)',y=$('#freeY')?.value||'sin(t)',h=.0001;return{x:parseExpr(x,u),y:parseExpr(y,u),dx:(parseExpr(x,u+h)-parseExpr(x,u-h))/(2*h),dy:(parseExpr(y,u+h)-parseExpr(y,u-h))/(2*h)}}
const practices={p1:{eq:'\\(x=6t,\\ y=3t^2-1\\)',def:{min:-2,max:2,scale:40,fn:t=>({x:6*t,y:3*t*t-1,dx:6,dy:6*t})},work:['\\(dx/dt=6\\)','\\(dy/dt=6t\\)','\\(dy/dx=t\\)','\\(x=6t\\) より \\(t=x/6\\)。したがって \\(y=x^2/12-1\\)'],hint:'tの微分では、t² → 2t です。'},p2:{eq:'\\(x=2\\cos t,\\ y=2\\sin t\\)',def:{min:0,max:TAU,scale:80,circle:2,fn:t=>({x:2*Math.cos(t),y:2*Math.sin(t),dx:-2*Math.sin(t),dy:2*Math.cos(t)})},work:['\\(dx/dt=-2\\sin t\\)','\\(dy/dt=2\\cos t\\)','\\(dy/dx=-\\cos t/\\sin t\\)','\\(x/2=\\cos t,\\ y/2=\\sin t\\)<br>\\(x^2/4+y^2/4=1\\) → \\(x^2+y^2=4\\)：半径2の円'],hint:'cos²t + sin²t = 1 を使います。'},p3:{eq:'\\(x=3\\cos t,\\ y=2\\sin t\\)',def:{min:0,max:TAU,scale:65,fn:t=>({x:3*Math.cos(t),y:2*Math.sin(t),dx:-3*Math.sin(t),dy:2*Math.cos(t)})},work:['\\(dx/dt=-3\\sin t\\)','\\(dy/dt=2\\cos t\\)','\\(\\displaystyle dy/dx=-\\frac{2\\cos t}{3\\sin t}\\)','\\(x/3=\\cos t,\\ y/2=\\sin t\\)<br>両辺を2乗：\\(x^2/9=\\cos^2t,\\ y^2/4=\\sin^2t\\)<br>加えると \\(\\boxed{x^2/9+y^2/4=1}\\)<br>x方向半径 = 3、y方向半径 = 2'],hint:'xとyをそれぞれ係数で割ってから2乗します。'}};
let practice=practices.p1,pstep=0;$$('[data-practice]').forEach(b=>b.onclick=()=>{$$('[data-practice]').forEach(x=>x.classList.toggle('active',x===b));practice=practices[b.dataset.practice];pstep=0;renderPractice()});function renderPractice(){ $('#practiceEq').innerHTML=practice.eq;$('#practiceWork').innerHTML=practice.work.slice(0,pstep).map((x,i)=>`<div><b>${i+1}.</b> ${x}</div>`).join('')||'<p>まず x(t) を t で微分してみよう。</p>';$$('.progress span').forEach((x,i)=>x.classList.toggle('on',i===Math.min(pstep,3)));draw2d($('#practiceGraph'),practice.def,(practice.def.min+practice.def.max)*.37,{trace:true,tangent:true,velocity:true});$('#hintText').textContent='';math()}$('#hint').onclick=()=>$('#hintText').textContent=practice.hint;$('#next').onclick=()=>{pstep=Math.min(4,pstep+1);renderPractice()};$('#answer').onclick=()=>{pstep=4;renderPractice()};
function drawWheel(){const r=+$('#radius').value,def={min:0,max:TAU,scale:100,circle:1,fn:u=>({x:Math.cos(u),y:Math.sin(u),dx:-Math.sin(u),dy:Math.cos(u)})};draw2d($('#wheel'),def,shownT%TAU,{trace:true,tangent:true,velocity:true});const p=def.fn(shownT);$('#radiusOut').textContent=r;$('#wheelData').innerHTML=`横方向位置 <b>${fmt(r*p.x)} m</b>　現在の高さ <b>${fmt(r+r*p.y)} m</b><br>dx/dt = ${fmt(-r*Math.sin(shownT))}、dy/dt = ${fmt(r*Math.cos(shownT))}`;const runner=$('#runner');runner.style.transform=`translate(${Math.cos(shownT)*100}px,${Math.sin(shownT)*70}px)`}$('#radius').oninput=drawWheel;
let rotX=.55,rotY=-.65,zoom=62,drag=null,mode3=true;const c3=$('#graph3d');c3.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];c3.setPointerCapture(e.pointerId)});c3.addEventListener('pointermove',e=>{if(!drag)return;rotY+=(e.clientX-drag[0])*.008;rotX+=(e.clientY-drag[1])*.008;drag=[e.clientX,e.clientY];draw3d()});c3.addEventListener('pointerup',()=>drag=null);c3.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(30,Math.min(120,zoom-e.deltaY*.08));draw3d()},{passive:false});$('#mode2').onclick=()=>{mode3=false;$('#mode2').classList.add('active');$('#mode3').classList.remove('active');draw3d()};$('#mode3').onclick=()=>{mode3=true;$('#mode3').classList.add('active');$('#mode2').classList.remove('active');draw3d()};function draw3d(){try{if(!mode3){draw2d(c3,cases.circle,shownT%TAU,{trace:true,tangent:true,velocity:true});return}const{ctx,w,h}=prep(c3);ctx.fillStyle='#08182a';ctx.fillRect(0,0,w,h);const project=(x,y,z)=>{let X=x*Math.cos(rotY)+z*Math.sin(rotY),Z=-x*Math.sin(rotY)+z*Math.cos(rotY),Y=y*Math.cos(rotX)-Z*Math.sin(rotX);return[w/2+X*zoom,h*.68-Y*zoom]};const axes=[[2.3,0,0,'x','#ef5b67'],[0,2.3,0,'y','#21b27a'],[0,0,4,'t','#3da9fc']];for(const[a,b,z,n,col]of axes){const o=project(0,0,0),q=project(a,b,z);arrow(ctx,...o,...q,col,2);ctx.fillStyle=col;ctx.fillText(n,q[0]+5,q[1])}ctx.strokeStyle='#80b8e0';ctx.lineWidth=2.5;ctx.beginPath();for(let i=0;i<=250;i++){const u=TAU*2*i/250,q=project(Math.cos(u),Math.sin(u),u/Math.PI-2);i?ctx.lineTo(...q):ctx.moveTo(...q)}ctx.stroke();const u=(shownT%(TAU*2)),p=project(Math.cos(u),Math.sin(u),u/Math.PI-2),v=project(Math.cos(u)-Math.sin(u)*.45,Math.sin(u)+Math.cos(u)*.45,u/Math.PI-2+.45);arrow(ctx,...p,...v,'#3da9fc',3);ctx.shadowBlur=18;ctx.shadowColor='#f5c95b';ctx.fillStyle='#f5c95b';ctx.beginPath();ctx.arc(...p,8,0,TAU);ctx.fill();ctx.shadowBlur=0}catch{$('#fallback').hidden=false;mode3=false;draw2d(c3,cases.circle,shownT%TAU)}}
const quizzes=[{q:'第1問｜円：x=3cos t, y=3sin t',a:['-3sin(t)','3cos(t)','-cos(t)/sin(t)','x²+y²=9']},{q:'第2問｜楕円：x=4cos t, y=2sin t',a:['-4sin(t)','2cos(t)','-cos(t)/(2sin(t))','x²/16+y²/4=1']},{q:'第3問｜多項式：x=2t, y=t²',a:['2','2t','t','y=x²/4']}];$('#quizList').innerHTML=quizzes.map((q,i)=>`<article class="quiz"><h3>${q.q}</h3>${['dx/dt','dy/dt','dy/dx','軌跡'].map((l,j)=>`<label>${j+1}. ${l}<input data-answer="${q.a[j]}" aria-label="${l}"></label>`).join('')}<button data-check="${i}">段階ごとに確認</button><p class="feedback"></p></article>`).join('');$$('[data-check]').forEach(b=>b.onclick=()=>{const card=b.closest('.quiz'),ins=$$('input',card),ans=quizzes[+b.dataset.check].a;let first=-1;ins.forEach((x,i)=>{const norm=s=>s.replace(/[\s{}]/g,'').replaceAll('^2','²').toLowerCase();const ok=norm(x.value)===norm(ans[i]);x.style.borderColor=ok?'#21b27a':'#ef5b67';if(!ok&&first<0)first=i});const f=$('.feedback',card);f.className='feedback '+(first<0?'good':'bad');f.textContent=first<0?'全段階正解！軌跡と微分が結びつきました。':`${first+1}段階目（${['dx/dt','dy/dt','dy/dx','軌跡'][first]}）を見直そう。例：${ans[first]}`});
function resizeAll(){updateConcept();update();renderPractice();drawWheel();draw3d()}window.addEventListener('resize',resizeAll);function animate(now){if(conceptPlaying){const base=conceptLast?Math.min((now-conceptLast)/1000,.05):0;conceptT+=base*.9;if(conceptT>conceptDef.max)conceptT=conceptDef.min;$('#conceptRange').value=conceptT;if($('#concept').classList.contains('active'))updateConcept()}conceptLast=now;if(playing){const dt=Math.min((now-last)/1000,.05)*(+$('#speed').value);t+=dt;shownT=t;if(t>active.max)t=active.min;$('#tRange').value=t;update()}else shownT+=.006;drawWheel();draw3d();last=now;requestAnimationFrame(animate)}setConceptStage('t');updateConcept();setupCase();renderPractice();requestAnimationFrame(animate);
