import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, CircleHelp, GraduationCap, Lightbulb, Sparkles } from 'lucide-react'
import { polygonMetrics, displayAngle, specialResult, type Sides } from './polygonMath'

const tabs=['考え方','必要な公式','高さを求める','計算する','面積','別の解き方']
const choices=['外周の長さ','中心から辺までの高さ','対角線の本数','頂点の数']

export default function App(){
 const [n,setN]=useState<Sides>(8),[tab,setTab]=useState(0),[answered,setAnswered]=useState<number|null>(null),[step,setStep]=useState(0),[teacher,setTeacher]=useState(false),[why,setWhy]=useState(false),[compare,setCompare]=useState(false),[circle,setCircle]=useState(false)
 const m=useMemo(()=>polygonMetrics(n),[n]); const change=(v:number)=>{const x=Math.max(5,Math.min(10,Math.round(v))) as Sides;setN(x);setAnswered(null);setTab(0);setStep(0);setWhy(false)}
 const maxStep=8
 return <div className="app">
  <header><div className="eyebrow"><span>数学Ⅰ</span> 図形と計量・三角比</div><div className="header-row"><div><h1>1辺の長さが1の正多角形の面積を求めよう</h1><p>正5角形から正10角形まで <i/> 三角比・余弦定理・2次方程式を使って考える</p></div><label className="teacher"><GraduationCap/>教師モード<input type="checkbox" checked={teacher} onChange={e=>setTeacher(e.target.checked)}/><b/></label></div></header>
  <main>
   <section className="title-control"><div><small>CHALLENGE</small><h2>1辺の長さが1の正 <span>{n}</span> 角形</h2></div><div className="stepper"><button aria-label="辺を減らす" disabled={n===5} onClick={()=>change(n-1)}>−</button><input aria-label="辺の数" type="number" min="5" max="10" value={n} onChange={e=>change(+e.target.value)}/><button aria-label="辺を増やす" disabled={n===10} onClick={()=>change(n+1)}>＋</button><b>角形</b></div></section>
   <div className="workspace">
    <section className="visual-card"><Polygon n={n} split={answered===1||tab>0} focus={tab>0} why={why} finish={tab===4}/><div className="angle-stats"><div><small>中心角 ∠AOB</small><b>360° ÷ {n} = <em>{displayAngle(m.centralAngle)}°</em></b></div><div><small>半分の中心角 ∠AOM</small><b>180° ÷ {n} = <em>{displayAngle(m.halfAngle)}°</em></b></div></div>
     <div className="question"><small>まず、図を見て考えよう</small><h3>この正多角形の面積を求めるには、<br/>何が分かればよいだろう？</h3><div className="choices">{choices.map((x,i)=><button className={answered===i?(i===1?'correct':'wrong'):''} onClick={()=>setAnswered(i)} key={x}><span>{i+1}</span>{x}{answered===i&&<b>{i===1?'✓ 正解':'もう一度'}</b>}</button>)}</div>{answered===1&&<p className="success">正多角形を中心Oから三角形に分けると、同じ二等辺三角形が<strong>{n}個</strong>できます。</p>}</div>
    </section>
    <section className="lesson-card"><nav className="tabs">{tabs.map((x,i)=><button className={tab===i?'active':tab>i?'done':''} onClick={()=>setTab(i)} key={x}><span>{i+1}</span>{x}</button>)}</nav><Lesson tab={tab} n={n} step={step} why={why} setWhy={setWhy} teacher={teacher}/><div className="lesson-footer"><button disabled={tab===0} onClick={()=>setTab(v=>v-1)}><ChevronLeft/>前へ</button><span>{tab+1} / 6</span><button className="primary" onClick={()=>{if(tab===3&&step<maxStep)setStep(s=>s+1);else setTab(v=>Math.min(5,v+1))}}> {tab===3&&step<maxStep?'式を1段進める':'次へ'}<ChevronRight/></button></div></section>
   </div>
   <section className="formula-map"><div><small>FORMULA MAP</small><h2>この正{n}角形で使う数学</h2></div><FormulaChip name="三角比" state="必要" active/><FormulaChip name="面積公式" state="必要" active/><FormulaChip name="余弦定理" state={n===5||n===10?'別解で使用':'別解'} active={n===5||n===10}/><FormulaChip name="2次方程式" state={n===5||n===10?'発展で使用':'今回は不要'} active={n===5||n===10}/><FormulaChip name="有理化" state={n===8?'発展で使用':'今回は不要'} active={n===8}/></section>
   <section className="compare-nav"><div><b>ほかの正多角形も調べる</b>{([5,6,7,8,9,10] as Sides[]).map(x=><button className={n===x?'active':''} onClick={()=>change(x)} key={x}>{x}</button>)}</div><button onClick={()=>setCompare(v=>!v)}>面積を比較する <ChevronRight/></button></section>
   {compare&&<Comparison change={change}/>}<section className="summary"><Sparkles/><small>LEARNING SUMMARY</small><h2>正n角形を中心からn個の三角形に分けると考えると</h2><div className="big-formula">S = <span>n<i/>4 tan (180°/n)</span></div><p>辺の数 n を増やしていくと、正多角形はどんな図形に近づいていくだろう？</p><button onClick={()=>setCircle(v=>!v)}>{circle?'円に近づいていく！':'考えてみる'}</button>{circle&&<div className="circle-demo"/>}</section>
  </main>
 </div>
}

function Polygon({n,split,focus,why,finish}:{n:Sides;split:boolean;focus:boolean;why:boolean;finish:boolean}){const cx=260,cy=225,r=168;const pts=Array.from({length:n},(_,i)=>{const a=-Math.PI/2+(i+.5)*2*Math.PI/n;return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}});const A=pts[0],B=pts[n-1],M={x:(A.x+B.x)/2,y:(A.y+B.y)/2};return <svg className="polygon" viewBox="0 0 520 450" role="img" aria-label={`1辺が1の正${n}角形`}>
 <defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
 {finish&&pts.map((p,i)=><polygon className="area-triangle" style={{animationDelay:`${i*.12}s`}} points={`${cx},${cy} ${p.x},${p.y} ${pts[(i+1)%n].x},${pts[(i+1)%n].y}`}/>)}
 <polygon className="poly-fill" points={pts.map(p=>`${p.x},${p.y}`).join(' ')}/>{split&&pts.map((p,i)=><line className="split-line" style={{animationDelay:`${i*.07}s`}} key={i} x1={cx} y1={cy} x2={p.x} y2={p.y}/>)}
 {focus&&<polygon className="focus-triangle" points={`${cx},${cy} ${A.x},${A.y} ${B.x},${B.y}`}/>}<polygon className="poly-edge" points={pts.map(p=>`${p.x},${p.y}`).join(' ')}/>
 <line className="radius" x1={cx} y1={cy} x2={A.x} y2={A.y}/><line className="radius" x1={cx} y1={cy} x2={B.x} y2={B.y}/><line className={`height ${why?'blink':''}`} x1={cx} y1={cy} x2={M.x} y2={M.y}/><line className={`ab ${why?'blink-blue':''}`} x1={A.x} y1={A.y} x2={B.x} y2={B.y}/>
 <path className="angle" d={`M ${cx+34*Math.cos(-Math.PI/2+Math.PI/n)} ${cy+34*Math.sin(-Math.PI/2+Math.PI/n)} A 34 34 0 0 0 ${cx+34*Math.cos(-Math.PI/2-Math.PI/n)} ${cy+34*Math.sin(-Math.PI/2-Math.PI/n)}`}/>
 <g className="point"><circle cx={cx} cy={cy} r="5"/><text x={cx+10} y={cy+5}>O</text><circle cx={A.x} cy={A.y} r="4"/><text x={A.x+10} y={A.y+4}>A</text><circle cx={B.x} cy={B.y} r="4"/><text x={B.x+10} y={B.y+4}>B</text><circle cx={M.x} cy={M.y} r="4"/><text x={M.x+12} y={M.y+4}>M</text></g><text className="edge-label" x={M.x-12} y={M.y+28}>AB = 1</text><text className="height-label" x={M.x+12} y={(cy+M.y)/2}>OM</text><text className="angle-label" x={cx+45} y={cy-4}>∠AOM</text></svg>}

function Lesson({tab,n,step,why,setWhy,teacher}:{tab:number;n:Sides;step:number;why:boolean;setWhy:(x:boolean)=>void;teacher:boolean}){const m=polygonMetrics(n),a=displayAngle(m.halfAngle),special=specialResult(n);if(tab===0)return <div className="lesson"><Tag>STEP 01 — 考え方</Tag><h2>大きな図形を、<br/><em>知っている図形</em>に分けよう</h2><p>中心Oとすべての頂点を結ぶと、合同な二等辺三角形が <b>{n}個</b> できます。</p><div className="mini-flow"><b>正{n}角形</b><ChevronRight/><b>△OAB × {n}</b><ChevronRight/><b>直角三角形 × 2</b></div><div className="fact"><Lightbulb/><div><b>辺ABの中点をMとすると</b><span>AB = 1 だから　<strong>AM = 1/2</strong><br/>∠AOM = 180° ÷ {n} = <strong>{a}°</strong></span></div></div><p className="note">OMは辺ABに垂直。△OAMと△OMBは合同な直角三角形です。</p></div>;
 if(tab===1)return <div className="lesson"><Tag>STEP 02 — 必要な公式</Tag><h2>高さOMとAMを結ぶ<br/><em>tan</em> を選ぼう</h2><Formula title="三角比" why={()=>setWhy(!why)}><div className="equation">tan θ = <Frac top="対辺" bottom="隣辺"/></div><div className="equation blue">tan {a}° = <Frac top="AM" bottom="OM"/> = <Frac top="1/2" bottom="OM"/></div></Formula>{why&&<Why>分かっている対辺 <b>AM＝1/2</b> と、求めたい隣辺 <b>OM</b> を直接結びつける三角比だからtanを使います。図の青と赤の線を見比べよう。</Why>}<p>したがって　<strong>OM = 1 / {'{'}2 tan({a}°){'}'}</strong></p></div>;
 if(tab===2)return <div className="lesson"><Tag>STEP 03 — 高さを求める</Tag><h2>式を変形して、<em>OM</em>を求めよう</h2><div className="calc-stack"><p>tan {a}° = (1/2) ÷ OM</p><p>OM × tan {a}° = 1/2</p><p className="answer">OM = <Frac top="1" bottom={`2 tan ${a}°`}/><small>≈ {m.apothem.toFixed(5)}</small></p></div><Why>高さOMが分かれば、「底辺×高さ÷2」で三角形1個の面積が求められます。</Why></div>;
 if(tab===3){const lines=[`360° ÷ ${n} = ${displayAngle(m.centralAngle)}°`,`${displayAngle(m.centralAngle)}° ÷ 2 = ${a}°`,`AM = 1/2`,`tan ${a}° = (1/2) / OM`,`OM = 1 / {2 tan ${a}°}`,`△OAB = 1/2 × 1 × OM`,`S = ${n} × 1/2 × 1 × OM`,`${special.exact}　≈ ${m.area.toFixed(5)}`];return <div className="lesson"><Tag>STEP 04 — 計算する</Tag><h2>途中式を一段ずつ<br/><em>組み立てよう</em></h2><div className="steps">{lines.slice(0,teacher?8:Math.max(1,step)).map((x,i)=><div key={x}><span>STEP {i+1}</span><p>{x}</p></div>)}</div>{!teacher&&step===0&&<Why>「式を1段進める」を押して、考える順序を確認しましょう。</Why>}</div>}
 if(tab===4)return <div className="lesson"><Tag>STEP 05 — 面積</Tag><h2>三角形1個分を<br/><em>{n}倍</em>しよう</h2><div className="result"><small>正{n}角形の面積</small><b>{special.exact}</b><strong>≈ {m.area.toFixed(5)}</strong></div><p>△OAB = 1/2 × 1 × OM<br/>S = {n} × △OAB = <b>{n} / {'{'}4 tan({a}°){'}'}</b></p></div>;
 return <div className="lesson"><Tag>STEP 06 — 別の解き方</Tag><h2>{special.title}</h2><p>{special.note}</p>{(n===5||n===10)&&<><Formula title="余弦定理"><div className="equation">a² = b² + c² − 2bc cos A</div><p>2辺とその間の角から、残りの辺を求める公式です。</p></Formula><Formula title="2次方程式"><div className="equation">x² − x − 1 = 0</div><p>x = (1 ± √5)/2。長さなので正の解 <b>(1＋√5)/2</b> を採用します。</p></Formula></>}{n===8&&<Formula title="有理化"><div className="rational"><p>2 / (√2 − 1)</p><p>= 2(√2＋1) / {'{'}(√2−1)(√2＋1){'}'}</p><p>= 2(√2＋1)</p></div><p>分母にある根号をなくして、式を扱いやすくする操作を有理化といいます。</p></Formula>}{![5,8,10].includes(n)&&<Why>この正{n}角形では2次方程式は必要ありません。三角比による近似値が自然です。</Why>}</div>}

const Tag=({children}:{children:React.ReactNode})=><span className="tag">{children}</span>;const Frac=({top,bottom}:{top:string;bottom:string})=><span className="frac"><span>{top}</span><span>{bottom}</span></span>;const Why=({children}:{children:React.ReactNode})=><div className="why"><CircleHelp/><p>{children}</p></div>;function Formula({title,why,children}:{title:string;why?:()=>void;children:React.ReactNode}){return <div className="formula"><header><b>{title}</b>{why&&<button onClick={why}>なぜ？</button>}</header>{children}</div>};function FormulaChip({name,state,active}:{name:string;state:string;active?:boolean}){return <div className={active?'formula-chip active':'formula-chip'}><i/ ><span><b>{name}</b><small>{state}</small></span></div>}
function Comparison({change}:{change:(n:number)=>void}){return <section className="comparison"><small>AREA COMPARISON — すべて1辺＝1</small><h2>辺の長さが同じでも、辺の数が増えると面積はどうなる？</h2><div>{([5,6,7,8,9,10] as Sides[]).map(n=>{const m=polygonMetrics(n),pts=Array.from({length:n},(_,i)=>`${50+39*Math.cos(-Math.PI/2+i*2*Math.PI/n)},${50+39*Math.sin(-Math.PI/2+i*2*Math.PI/n)}`).join(' ');return <button onClick={()=>change(n)} key={n}><svg viewBox="0 0 100 100"><polygon points={pts}/></svg><b>正{n}角形</b><span>{m.area.toFixed(5)}</span></button>})}</div></section>}
