import { useEffect, useMemo, useRef, useState } from 'react'
import { Download, ZoomIn } from 'lucide-react'
import { PDFDocument, rgb } from 'pdf-lib'
import fontkit from '@pdf-lib/fontkit'
import * as pdfjs from 'pdfjs-dist'
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import fieldMap from './scoresheet-field-map.json'
import { foulSymbolRules, starterMark, type FoulKind } from './foul-symbols'
import type { GameEvent, Player, TeamId } from './core'
import { aggregate, buildRunningScore } from './core'

pdfjs.GlobalWorkerOptions.workerSrc=workerUrl
const TEMPLATE='./templates/official_scoresheet.pdf', FONT='./fonts/NotoSansJP-Regular.ttf'
type View='all'|'teamA'|'teamB'|'running'|'result'
type Props={events:GameEvent[];players:Player[];teamNames:Record<TeamId,string>}
const fetchRequired=async(url:string,label:string)=>{const r=await fetch(url);if(!r.ok)throw new Error(`${label}が見つかりません（${url} / HTTP ${r.status}）`);return r.arrayBuffer()}
function pos(f:{x:number;y:number;width?:number;height?:number;fontSize?:number}){return{left:`${f.x/fieldMap.page.width*100}%`,top:`${f.y/fieldMap.page.height*100}%`,width:f.width?`${f.width/fieldMap.page.width*100}%`:undefined,height:f.height?`${f.height/fieldMap.page.height*100}%`:undefined,fontSize:`${f.fontSize||7}px`}}
export default function OfficialScoresheet({events,players,teamNames}:Props){const canvas=useRef<HTMLCanvasElement>(null),[error,setError]=useState(''),[view,setView]=useState<View>('all'),debug=new URLSearchParams(location.search).get('debugScoresheet')==='true',totals=useMemo(()=>aggregate(events,players),[events,players]),running=useMemo(()=>buildRunningScore(events),[events])
 useEffect(()=>{let alive=true;(async()=>{try{const bytes=await fetchRequired(TEMPLATE,'公式スコアシートテンプレート');const pdf=await pdfjs.getDocument({data:bytes}).promise,page=await pdf.getPage(1),viewport=page.getViewport({scale:2});if(!alive||!canvas.current)return;canvas.current.width=viewport.width;canvas.current.height=viewport.height;await page.render({canvas:canvas.current,canvasContext:canvas.current.getContext('2d')!,viewport}).promise;setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}})();return()=>{alive=false}},[])
 const download=async()=>{try{const [template,fontBytes]=await Promise.all([fetchRequired(TEMPLATE,'公式スコアシートテンプレート'),fetchRequired(FONT,'日本語PDFフォント')]);const doc=await PDFDocument.load(template);doc.registerFontkit(fontkit);const font=await doc.embedFont(fontBytes,{subset:true}),page=doc.getPage(0),h=page.getHeight(),draw=(text:string,f:any,size=f.fontSize||7)=>page.drawText(text,{x:f.x,y:h-f.y-size,size,font,color:rgb(.03,.08,.16),maxWidth:f.width});draw('2026 AUTUMN CUP',fieldMap.fields.competition);draw(teamNames.A,fieldMap.fields.teamA.teamName);draw(teamNames.B,fieldMap.fields.teamB.teamName);(['A','B'] as TeamId[]).forEach(id=>{const team=fieldMap.fields[id==='A'?'teamA':'teamB'];players.filter(p=>p.id.startsWith(id.toLowerCase())).slice(0,team.players.count).forEach((p,i)=>{const y=team.players.y+i*team.players.rowHeight;draw(p.number,{x:team.players.numberX,y},7);draw(p.name,{x:team.players.nameX,y,width:team.players.nameWidth},p.name.length>10?5.5:7);if(p.starter)draw(starterMark,{x:team.players.starterX,y},8);events.filter(e=>!e.deletedAt&&e.playerId===p.id&&e.type==='FOUL').slice(0,5).forEach((e,j)=>draw(foulSymbolRules[(e.metadata?.foulType as FoulKind)||'Personal'],{x:team.players.foulX+j*team.players.foulGap,y},7))})});[0,1,2,3,4].forEach((q,i)=>{draw(String(totals.periods.A[i]),{x:fieldMap.fields.quarterScores.xA,y:fieldMap.fields.quarterScores.y+i*fieldMap.fields.quarterScores.rowGap},9);draw(String(totals.periods.B[i]),{x:fieldMap.fields.quarterScores.xB,y:fieldMap.fields.quarterScores.y+i*fieldMap.fields.quarterScores.rowGap},9)});draw(String(totals.score.A),{x:fieldMap.fields.finalScore.xA,y:fieldMap.fields.finalScore.y},10);draw(String(totals.score.B),{x:fieldMap.fields.finalScore.xB,y:fieldMap.fields.finalScore.y},10);if(totals.score.A!==totals.score.B)draw(totals.score.A>totals.score.B?teamNames.A:teamNames.B,fieldMap.fields.winningTeam);running.forEach(r=>{const m=fieldMap.fields.runningScore,col=Math.floor((r.score-1)/m.rows),row=(r.score-1)%m.rows,p=players.find(x=>x.id===r.playerId);draw(p?.number||'•',{x:m.x+col*m.columnWidth+(r.teamId==='A'?m.teamAX:m.teamBX),y:m.y+row*m.rowHeight},5.5)});const blob=new Blob([Uint8Array.from(await doc.save()).buffer],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='official-scoresheet.pdf';a.click();URL.revokeObjectURL(a.href);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const crop:Record<View,string>={all:'translate(0,0) scale(1)',teamA:'translate(17%,18%) scale(1.8)',teamB:'translate(17%,-27%) scale(1.8)',running:'translate(-27%,17%) scale(1.65)',result:'translate(-30%,-35%) scale(1.8)'}
 const teamFields=(id:TeamId)=>{const t=fieldMap.fields[id==='A'?'teamA':'teamB'];return players.filter(p=>p.id.startsWith(id.toLowerCase())).flatMap((p,i)=>{const y=t.players.y+i*t.players.rowHeight,fouls=events.filter(e=>!e.deletedAt&&e.playerId===p.id&&e.type==='FOUL');return [<span key={`${p.id}-lic`} className="pdf-field" style={pos({x:t.players.licenseX,y,width:43,height:t.players.rowHeight,fontSize:5.5})}>{p.licenseNo}</span>,<span key={`${p.id}-no`} className="pdf-field" style={pos({x:t.players.numberX,y,width:18,height:t.players.rowHeight,fontSize:7})}>{p.number}</span>,<span key={`${p.id}-name`} className="pdf-field" style={pos({x:t.players.nameX,y,width:t.players.nameWidth,height:t.players.rowHeight,fontSize:p.name.length>10?5.5:7})}>{p.name}</span>,p.starter&&<span key={`${p.id}-starter`} className="pdf-field mark" style={pos({x:t.players.starterX,y,width:11,height:11,fontSize:8})}>{starterMark}</span>,...fouls.slice(0,5).map((e,j)=><span key={e.id} className="pdf-field mark" style={pos({x:t.players.foulX+j*t.players.foulGap,y,width:11,height:11,fontSize:7})}>{foulSymbolRules[(e.metadata?.foulType as FoulKind)||'Personal']}</span>)]})}
 return <section className="official-preview"><div className="preview-tools">{([['all','全体表示'],['teamA','左上 Team A'],['teamB','左下 Team B'],['running','右上 Running Score'],['result','右下 最終結果']] as [View,string][]).map(([v,l])=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><ZoomIn/>{l}</button>)}<button className="download" onClick={download}><Download/>元PDFへ重ねて出力</button></div>{error&&<div className="template-error"><b>テンプレートを表示できません</b><p>{error}</p><small>提供されたPDFを public/templates/official_scoresheet.pdf に配置してください。代替帳票は生成しません。</small></div>}<div className="preview-viewport"><div className="pdf-page" style={{transform:crop[view]}}><canvas ref={canvas}/><div className={`pdf-overlay ${debug?'debug':''}`}>{teamFields('A')}{teamFields('B')}<span className="pdf-field" style={pos(fieldMap.fields.teamA.teamName)}>{teamNames.A}</span><span className="pdf-field" style={pos(fieldMap.fields.teamB.teamName)}>{teamNames.B}</span>{(['A','B'] as TeamId[]).flatMap(id=>{const t=fieldMap.fields[id==='A'?'teamA':'teamB'],timeouts=events.filter(e=>!e.deletedAt&&e.teamId===id&&e.type==='TIMEOUT');return [...timeouts.map((e,i)=><span key={e.id} className="pdf-field mark" style={pos({x:t.timeouts.x+i*t.timeouts.gap,y:t.timeouts.y,width:11,height:11,fontSize:7})}>×</span>),...[0,1,2,3].flatMap(q=>Array.from({length:Math.min(4,totals.fouls[id][q])},(_,i)=><span key={`${id}-${q}-${i}`} className="pdf-field mark" style={pos({x:t.teamFouls.x+q*t.teamFouls.quarterGap+i*t.teamFouls.markGap,y:t.teamFouls.y,width:10,height:10,fontSize:7})}>×</span>))]})}{running.map(r=>{const m=fieldMap.fields.runningScore,col=Math.floor((r.score-1)/m.rows),row=(r.score-1)%m.rows,p=players.find(x=>x.id===r.playerId);return <span key={r.eventId} className="pdf-field running-mark" style={pos({x:m.x+col*m.columnWidth+(r.teamId==='A'?m.teamAX:m.teamBX),y:m.y+row*m.rowHeight,width:13,height:10,fontSize:5.5})}>{p?.number}</span>})}{[0,1,2,3,4].flatMap(i=>(['A','B'] as TeamId[]).map(id=><span key={`${id}-q${i}`} className="pdf-field" style={pos({x:id==='A'?fieldMap.fields.quarterScores.xA:fieldMap.fields.quarterScores.xB,y:fieldMap.fields.quarterScores.y+i*fieldMap.fields.quarterScores.rowGap,width:24,height:13,fontSize:9})}>{totals.periods[id][i]}</span>))}<span className="pdf-field" style={pos({x:fieldMap.fields.finalScore.xA,y:fieldMap.fields.finalScore.y,width:24,height:13,fontSize:10})}>{totals.score.A}</span><span className="pdf-field" style={pos({x:fieldMap.fields.finalScore.xB,y:fieldMap.fields.finalScore.y,width:24,height:13,fontSize:10})}>{totals.score.B}</span>{debug&&Object.entries(fieldMap.fields).filter(([,v])=>'x'in v).map(([name,v])=><span key={name} className="debug-label" style={pos(v as any)}>{name} x:{(v as any).x} y:{(v as any).y}</span>)}</div></div></div></section>
}
