const PI=Math.PI, f=x=>Math.cos(x)*(1+Math.sin(x)), d=x=>(1+Math.sin(x))*(1-2*Math.sin(x));
let x=0, deriveStep=0, yaw=-.55, pitch=.42, zoom=1, dragging=false, last=[0,0], pinch=0;
const pointers=new Map();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function switchTab(id){$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));requestAnimationFrame(drawAll);scrollTo({top:Math.min(scrollY,$('#tabs').offsetTop),behavior:'smooth'})}
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
function resize(c){const r=c.getBoundingClientRect(),q=Math.min(devicePixelRatio,2);if(c.width!==r.width*q||c.height!==r.height*q){c.width=r.width*q;c.height=r.height*q}const g=c.getContext('2d');g.setTransform(q,0,0,q,0,0);return [g,r.width,r.height]}
function line(g,pts,color,w=2,glow=0){g.save();g.strokeStyle=color;g.lineWidth=w;g.shadowColor=color;g.shadowBlur=glow;g.beginPath();pts.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.stroke();g.restore()}
function graph(){const c=$('#graphCanvas');if(!c)return;const [g,w,h]=resize(c),pad=42,X=t=>pad+t/(2*PI)*(w-2*pad),Y=v=>h/2-v/3.3*(h-55);g.clearRect(0,0,w,h);g.strokeStyle='#233a57';g.lineWidth=1;for(let i=0;i<=4;i++){const xx=pad+i*(w-2*pad)/4;g.beginPath();g.moveTo(xx,20);g.lineTo(xx,h-25);g.stroke();g.fillStyle='#7890aa';g.font='10px sans-serif';g.fillText(['0','π/2','π','3π/2','2π'][i],xx-6,h-8)}line(g,[[pad,h/2],[w-pad,h/2]],'#526984');const pts=[];for(let t=0;t<=2*PI+.02;t+=.02)pts.push([X(t),Y(f(t))]);line(g,pts,'#65d9ef',4,10);[[PI/6,'#ffd66b'],[5*PI/6,'#61bdfc'],[3*PI/2,'#ffad62']].forEach(([t,col])=>{g.fillStyle=col;g.shadowColor=col;g.shadowBlur=18;g.beginPath();g.arc(X(t),Y(f(t)),5,0,7);g.fill()});if($('#tangent').checked){const slope=d(x),len=.7;line(g,[[X(Math.max(0,x-len)),Y(f(x)+slope*(Math.max(0,x-len)-x))],[X(Math.min(2*PI,x+len)),Y(f(x)+slope*(Math.min(2*PI,x+len)-x))]],'#ffdd73',2,8)}g.fillStyle='white';g.shadowColor='#fff';g.shadowBlur=18;g.beginPath();g.arc(X(x),Y(f(x)),6,0,7);g.fill()}
function drawBar(sel,fn){const c=$(sel),[g,w,h]=resize(c);g.clearRect(0,0,w,h);for(let i=0;i<w;i++){const t=i/w*2*PI,v=fn(t);g.fillStyle=Math.abs(v)<.025?'#ffe36e':v>0?'#31d99a':'#f05e79';g.fillRect(i,0,2,h)}[PI/6,5*PI/6,3*PI/2].forEach(t=>{const xx=t/(2*PI)*w;g.fillStyle='#fff';g.fillRect(xx-1,0,2,h)});g.fillStyle='#fff';g.shadowColor='#fff';g.shadowBlur=10;g.fillRect(x/(2*PI)*w-2,0,4,h)}
function zone(){if(x<PI/6)return 0;if(x<5*PI/6)return 1;if(x<3*PI/2)return 2;return 3}
function update(){const val=d(x),eps=.008;$('#xVal').textContent=x.toFixed(2);$('#fVal').textContent=f(x).toFixed(3);$('#dVal').textContent=val.toFixed(3);$('#fac1').textContent=(1+Math.sin(x)).toFixed(3);$('#fac2').textContent=(1-2*Math.sin(x)).toFixed(3);$('#facD').textContent=val.toFixed(3);const s=$('#status');s.className='status '+(Math.abs(val)<eps?'zero':val>0?'positive':'negative');s.textContent=Math.abs(val)<eps?'f′(x) = 0　• 停留点':val>0?'f′(x) > 0　↗ 増加中':'f′(x) < 0　↘ 減少中';$$('[data-zone]').forEach(e=>e.classList.toggle('lit',+e.dataset.zone===zone()));$$('input[type=range]').forEach(r=>{if(Math.abs(+r.value-x)>.001)r.value=x});drawAll()}
$$('input[type=range]').forEach(r=>r.addEventListener('input',e=>{x=+e.target.value;update()}));$('#tangent').addEventListener('change',graph);
const steps=[['f(x) = cos x(1 + sin x)','出発点。2つの関数の積に注目しよう。'],['積の微分法：(uv)′ = u′v + uv′','cos x と (1 + sin x) をそれぞれ微分します。'],["f′(x) = (−sin x)(1 + sin x) + cos x(cos x)",'2つの項を落とさず、積の微分法を適用します。'],["f′(x) = −sin x(1 + sin x) + cos²x",'同じ式を見やすく整理します。'],["f′(x) = cos²x − sin x − sin²x",'括弧を展開し、sin x の式へ近づけます。'],['cos²x = 1 − sin²x','三角関数の基本関係 sin²x + cos²x = 1 を使います。'],["f′(x) = 1 − sin x − 2sin²x",'sin x だけの2次式になりました。'],["f′(x) = (1 + sin x)(1 − 2sin x)",'因数分解すると、各因子から符号を読めます。これが探究のカギ！']];
$('#derivation').innerHTML=steps.map((s,i)=>`<div class="derive-line"><b>${s[0]}</b><p>${s[1]}</p></div>`).join('');function renderDerive(){$$('.derive-line').forEach((e,i)=>e.className='derive-line '+(i===deriveStep?'current':i<deriveStep?'done':''));$('#deriveCount').textContent=`${deriveStep+1} / ${steps.length}`;$('#prevDerive').disabled=deriveStep===0;$('#nextDerive').textContent=deriveStep===steps.length-1?'符号を調べる →':'次の変形 →'}$('#nextDerive').onclick=()=>deriveStep===steps.length-1?switchTab('sign'):(deriveStep++,renderDerive());$('#prevDerive').onclick=()=>{deriveStep=Math.max(0,deriveStep-1);renderDerive()};
function space(){const c=$('#spaceCanvas');if(!c)return;const [g,w,h]=resize(c);g.clearRect(0,0,w,h);const project=(a,b,z)=>{a=(a-PI)*.75;b*=1.2;z*=.75;let X=a*Math.cos(yaw)-z*Math.sin(yaw),Z=a*Math.sin(yaw)+z*Math.cos(yaw),Y=b*Math.cos(pitch)-Z*Math.sin(pitch);Z=b*Math.sin(pitch)+Z*Math.cos(pitch);const s=75*zoom/(1+Z*.055);return[w/2+X*s,h/2-Y*s,s]};const grid=[];for(let i=0;i<=8;i++){const a=i/8*2*PI;grid.push([project(a,-1.7,-2),project(a,-1.7,2)])}grid.forEach(p=>line(g,p.map(q=>q.slice(0,2)),'#1c3550'));for(let i=0;i<150;i++){const a=i/149*2*PI,b=(i+1)/149*2*PI,col=d((a+b)/2)>=0?'#32e5a0':'#ff5d78';line(g,[project(a,-1.7,0).slice(0,2),project(b,-1.7,0).slice(0,2)],col,5,9);line(g,[project(a,f(a),d(a)).slice(0,2),project(b,f(b),d(b)).slice(0,2)],col,3,6)}const p=project(x,f(x),d(x)),floor=project(x,-1.7,0);line(g,[p.slice(0,2),floor.slice(0,2)],'#ffe07d',2,10);g.fillStyle='#fff';g.shadowColor='#fff';g.shadowBlur=18;g.beginPath();g.arc(p[0],p[1],7,0,7);g.fill();[[PI/6,'#ffd66b'],[5*PI/6,'#69c7ff'],[3*PI/2,'#ffad62']].forEach(([t,col])=>{const q=project(t,f(t),d(t));g.fillStyle=col;g.beginPath();g.arc(q[0],q[1],5,0,7);g.fill()});g.shadowBlur=0;g.fillStyle='#8da4be';g.font='11px sans-serif';g.fillText('x →',w-45,h-25);g.fillText('高さ f(x) / 傾き f′(x)',15,22)}
const sc=$('#spaceCanvas'),distance=()=>{const p=[...pointers.values()];return p.length<2?0:Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1])};sc.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,[e.clientX,e.clientY]);dragging=true;last=[e.clientX,e.clientY];pinch=distance();sc.setPointerCapture(e.pointerId)});sc.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size>1){const next=distance();if(pinch)zoom=Math.max(.55,Math.min(1.8,zoom*next/pinch));pinch=next}else if(dragging){yaw+=(e.clientX-last[0])*.008;pitch=Math.max(-1,Math.min(1,pitch+(e.clientY-last[1])*.006));last=[e.clientX,e.clientY]}space()});const release=e=>{pointers.delete(e.pointerId);dragging=pointers.size>0;pinch=distance();if(dragging)last=[...pointers.values()][0]};sc.addEventListener('pointerup',release);sc.addEventListener('pointercancel',release);sc.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.55,Math.min(1.8,zoom*(e.deltaY>0?.92:1.08)));space()},{passive:false});
function drawAll(){graph();drawBar('#bar1',t=>1+Math.sin(t));drawBar('#bar2',t=>1-2*Math.sin(t));drawBar('#barD',d);space()}addEventListener('resize',drawAll);renderDerive();update();
