import {extractionPositions} from './motion.js';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { balls } from './math.js';
// 結果は数学モデルで先に選び、3個を同時に動かす。描画の物理挙動で抽選しない。
export function createBagScene(container){
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#101a29');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;container.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=14;controls.maxPolarAngle=Math.PI*.84;controls.target.set(0,1.6,0);camera.position.set(4.8,4.2,7.5);controls.update();
 const generator=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const environment=generator.fromScene(room);scene.environment=environment.texture;room.dispose();generator.dispose();
 scene.add(new THREE.HemisphereLight('#e6f5ff','#14223a',2));const light=new THREE.DirectionalLight('#ffffff',5);light.position.set(3,7,4);scene.add(light);
 const board=new THREE.Mesh(new THREE.CylinderGeometry(2.35,2.35,.12,80),new THREE.MeshStandardMaterial({color:'#1c3044',roughness:.45,metalness:.5}));board.position.y=-.08;scene.add(board);
 const profile=[[0,0],[.8,.08],[1.25,.3],[1.48,.75],[1.5,1.5],[1.38,2.2],[1.15,2.65]].map(([x,y])=>new THREE.Vector2(x,y));
 const bagMaterial=new THREE.MeshStandardMaterial({color:'#837764',roughness:.96,metalness:0,side:THREE.DoubleSide,transparent:true,opacity:.18,depthWrite:false});const bag=new THREE.Mesh(new THREE.LatheGeometry(profile,72),bagMaterial);bag.renderOrder=3;scene.add(bag);
 const wire=new THREE.LineSegments(new THREE.WireframeGeometry(new THREE.LatheGeometry(profile,24)),new THREE.LineBasicMaterial({color:'#7292a5',transparent:true,opacity:.12}));scene.add(wire);
 const mouth=new THREE.Mesh(new THREE.TorusGeometry(1.15,.065,10,90),new THREE.MeshStandardMaterial({color:'#ad9270',roughness:.7}));mouth.rotation.x=Math.PI/2;mouth.position.y=2.65;scene.add(mouth);
 // 縫い目と袋の口の紐で、開いた立体の袋の輪郭を読みやすくする。
 for(let i=0;i<3;i++){const t=i*Math.PI*2/3;const pts=profile.slice(1).map(p=>new THREE.Vector3(p.x*Math.cos(t),p.y,p.x*Math.sin(t)));const seam=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineDashedMaterial({color:'#b5a187',dashSize:.08,gapSize:.055,transparent:true,opacity:.5}));seam.computeLineDistances();scene.add(seam);}
 const mats={W:new THREE.MeshStandardMaterial({color:'#eeeef2',metalness:.9,roughness:.2}),R:new THREE.MeshStandardMaterial({color:'#bc152d',metalness:.82,roughness:.22}),B:new THREE.MeshStandardMaterial({color:'#182435',metalness:.85,roughness:.23})};
 const homes=balls.map((b,i)=>{const layer=i<4?0:i<9?1:2;const j=layer===0?i:layer===1?i-4:i-9;const n=[4,5,3][layer],t=j/n*Math.PI*2+.4*layer;return new THREE.Vector3(Math.cos(t)*[.75,.85,.65][layer],[.5,1.14,1.8][layer],Math.sin(t)*[.75,.85,.65][layer]);});
 const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d'),grad=ctx.createRadialGradient(64,64,0,64,64,64);grad.addColorStop(0,'rgba(255,255,255,.9)');grad.addColorStop(.3,'rgba(255,255,255,.35)');grad.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const glowTexture=new THREE.CanvasTexture(canvas);
 const meshes=balls.map((b,i)=>{const group=new THREE.Group(),sphere=new THREE.Mesh(new THREE.SphereGeometry(.29,32,24),mats[b.color].clone());group.add(sphere);const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:'#65e3e6',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));glow.scale.set(1.4,1.4,1);glow.visible=false;group.add(glow);group.position.copy(homes[i]);scene.add(group);return {group,sphere,glow};});
 let animation=null,selected=[],finish=null,paused=false,pauseAt=0;
 function returnAll(){animation=null;finish=null;selected=[];meshes.forEach((m,i)=>{m.group.position.copy(homes[i]);m.glow.visible=false;m.sphere.material.emissive.set('#000000');});}
 function take(ids,success,onComplete){returnAll();selected=ids.slice();finish=onComplete;const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0);animation={start:performance.now(),duration:2000,right:[right.x,0,right.z]};ids.forEach(id=>{meshes[id].glow.visible=true;meshes[id].glow.material.color.set(success?'#ff5d66':'#65e3e6');});}
 function render(now){const width=container.clientWidth,height=container.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();if(animation&&!paused){const t=Math.min(1,(now-animation.start)/animation.duration);const positions=extractionPositions(selected.map(id=>homes[id].toArray()),t,animation.right);selected.forEach((id,j)=>{const m=meshes[id];m.group.position.set(...positions[j]);m.glow.material.opacity=.45+.25*Math.sin(now/160);m.sphere.material.emissive.set('#201014');m.sphere.material.emissiveIntensity=.5;});if(t===1){animation=null;const callback=finish;finish=null;callback?.();}}else if(selected.length&&!paused)selected.forEach(id=>{meshes[id].glow.material.opacity=.45+.25*Math.sin(now/180);});controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}
 requestAnimationFrame(render);
 return {take,returnAll,setInside(value){bagMaterial.opacity=value?.18:.95;wire.visible=value;},resetView(){camera.position.set(4.8,4.2,7.5);controls.target.set(0,1.6,0);controls.update();},pause(value){if(value&&!paused)pauseAt=performance.now();if(!value&&paused&&animation)animation.start+=performance.now()-pauseAt;paused=value;}};
}
