const life=[
 {title:'自転車登校',p:'自転車で学校に来る',q:'自転車を持っている',why:'自転車で来たなら、その自転車を持っています。',reverse:'自転車を持っている人は、必ず自転車で登校する？',counter:'歩いて登校する人もいる。'},
 {title:'映画館',p:'映画館に入場できる',q:'有効なチケットを持っている',why:'この映画館への入場には有効なチケットが必要です。',reverse:'チケットを持っているだけで、必ず入場できる？',counter:'反例：上映日時が違うチケット。必要だが、それだけで十分とは限らない。'},
 {title:'部活動',p:'公式大会に選手として出場する',q:'その部活動に選手登録されている',why:'公式大会への出場には選手登録が必要です。',reverse:'選手登録されている人は全員大会に出場する？',counter:'出場しない部員もいる。'},
 {title:'スマートフォン',p:'スマートフォンの電源が入っている',q:'バッテリーが0％ではない',why:'電源が入るなら、使える電気が残っています。',reverse:'バッテリーが残っていれば、必ず電源が入っている？',counter:'バッテリーが50％あっても、電源を切っている場合がある。'},
 {title:'学校の教室',p:'現在この学校の1年1組の生徒である',q:'現在この学校の生徒である',why:'1年1組はこの学校のクラスの一つです。',reverse:'この学校の生徒なら全員1年1組？',counter:'2組や2年生、3年生もいる。'}];
const dailyQuiz=[
 ['P：雨が降っている／Q：空から水滴が落ちている','十分条件','雨なら水滴が落ちるが、水滴の原因は雨以外にもあります。'],
 ['P：18歳以上／Q：20歳以上','必要条件','20歳以上なら必ず18歳以上。逆向きだけが成り立ちます。'],
 ['P：今日が月曜日／Q：昨日が日曜日','必要十分条件','どちら向きも必ず成り立ちます。'],
 ['P：眼鏡をかける／Q：本を読む','どちらでもない','眼鏡でも本を読まない人、本を読むが眼鏡でない人がいます。'],
 ['P：東京にいる／Q：日本にいる','十分条件','東京にいれば日本にいます。逆は成り立ちません。']];
const math=[
 {title:'整数 x',p:'x は4の倍数',q:'x は偶数',pq:true,qp:false,counter:'反例：x = 2（偶数だが4の倍数ではない）',visual:''},
 {title:'実数 x',p:'x > 5',q:'x > 3',pq:true,qp:false,counter:'反例：x = 4',visual:'line'},
 {title:'実数 x',p:'x = 3',q:'x² = 9',pq:true,qp:false,counter:'x² = 9 なら x = 3, −3。反例：x = −3',visual:''},
 {title:'実数 x',p:'x = 2',q:'x − 2 = 0',pq:true,qp:true,counter:'両方向とも成立：P ⇔ Q　これは必要十分条件！',visual:''},
 {title:'三角形 ABC',p:'正三角形である',q:'二等辺三角形である',pq:true,qp:false,counter:'反例：2辺だけが等しい二等辺三角形',visual:'tri'}];
const finalQs=[
 ['P：12の倍数／Q：3の倍数','十分条件'],['P：x > 0／Q：x ≥ 0','十分条件'],['P：x² = 4／Q：x = 2','必要条件'],['P：x は偶数／Q：x は2の倍数','必要十分条件'],['P：x > 1／Q：x < 10','どちらでもない']];
let screen=0,lifeI=0,dailyI=0,mathI=0,finalI=0,score=0,state={};
const app=document.querySelector('#app'),prev=document.querySelector('#prev'),next=document.querySelector('#next');
const total=7;
function pqCards(p,q,arrow='→',glow=false){return `<div class="pq"><div class="pq-card"><div><b>P</b>${p}</div></div><div class="arrow ${glow?'glow':''}">${arrow}</div><div class="pq-card"><div><b>Q</b>${q}</div></div></div>`}
function panel(x){app.innerHTML=`<div class="panel">${x}</div>`;window.scrollTo({top:0,behavior:'smooth'})}
function conditionResult(){return `<div class="conditions"><div class="condition enough"><b>P は Q の十分条件</b>PがあればQまで行ける<br>「それだけでOK」</div><div class="condition need"><b>Q は P の必要条件</b>PになるためにはQが必要<br>「ないと困る」</div></div>`}
function render(){document.querySelector('#bar').style.width=`${(screen+1)/total*100}%`;document.querySelector('#stepLabel').textContent=screen===6?'FINAL CHECK':'STEP '+(screen+1);prev.disabled=screen===0;next.style.visibility=screen===6?'hidden':'visible';document.querySelector('#dots').textContent=`${screen+1} / ${total}`;
 if(screen===0)panel(`<p class="kicker">言葉の意味から始めよう</p><h1>「必要」と「十分」って、どういうこと？</h1><div class="meaning"><div class="need"><b>ないと困る？</b>→ 必要条件</div><span class="or">と</span><div class="enough"><b>それだけでOK？</b>→ 十分条件</div></div><p class="lead">いきなり公式を覚えなくて大丈夫。この2つの質問で考えていきます。</p>`);
 if(screen===1)renderLife();if(screen===2)renderDaily();if(screen===3)renderMath();if(screen===4)renderSet();if(screen===5)renderSummary();if(screen===6)renderFinal();}
function renderLife(){let x=life[lifeI];panel(`<span class="counter">生活例 ${lifeI+1} / 5</span><h2>${x.title}</h2><p class="lead">どちら向きに矢印が引ける？</p>${pqCards(x.p,x.q,'?')}<div class="choices"><button data-dir="pq">P → Q</button><button data-dir="qp">Q → P</button></div><div id="feedback"></div>`);document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>lifeAnswer(b.dataset.dir,x));}
function lifeAnswer(dir,x){let ok=dir==='pq',f=document.querySelector('#feedback');f.innerHTML=`<div class="result ${ok?'correct':'wrong'}">${ok?'○ 成り立つ！':'× 必ずそうなるとは限らない'}</div>${ok?`<button class="action" id="why">なぜ？</button>`:`<div class="reveal"><b>反例：</b>${x.counter}</div>`}`;if(ok)document.querySelector('#why').onclick=()=>{f.innerHTML+=`<div class="reveal">${x.why}<br><b>P → Q</b> です。<br><button class="action" id="reverse">逆は成り立つ？</button></div>`;document.querySelector('#why').remove();document.querySelector('#reverse').onclick=()=>{f.innerHTML+=`<div class="reveal"><b>${x.reverse}</b><p class="counterexample">${x.counter}</p></div>${conditionResult()}<div class="choices"><button id="lifeNext">${lifeI<4?'次の生活例へ':'STEP 3へ'}</button></div>`;document.querySelector('#reverse').remove();document.querySelector('#lifeNext').onclick=()=>{if(lifeI<4){lifeI++;renderLife()}else{screen++;render()}}}}}
function renderDaily(){let q=dailyQuiz[dailyI];panel(`<span class="counter">日常生活クイズ ${dailyI+1} / 5</span><h2>${q[0]}</h2><p class="big-question">PはQの何条件？</p><div class="quiz-grid choices">${['必要条件','十分条件','必要十分条件','どちらでもない'].map(a=>`<button data-a="${a}">${a}</button>`).join('')}</div><div id="feedback"></div>`);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{let ok=b.dataset.a===q[1],f=document.querySelector('#feedback');f.innerHTML=`<div class="result ${ok?'correct':'wrong'}">${ok?'○ 正解':'× もう一度考えよう'}</div>${ok?`<div class="reveal">${q[2]}</div><button class="action" id="quizNext">${dailyI<4?'次の問題':'数学へ進む'}</button>`:`<div class="choices"><button class="hint" id="h1">ヒント：PならQと言える？</button><button class="hint" id="h2">ヒント：QならPと言える？</button></div>`}`;if(ok)document.querySelector('#quizNext').onclick=()=>{dailyI<4?(dailyI++,renderDaily()):(screen++,render())};else document.querySelectorAll('.hint').forEach(h=>h.onclick=()=>h.textContent=h.id==='h1'?'具体例を1つ想像して確かめよう':'逆向きにも反例がないか探そう')})}
function renderMath(){let x=math[mathI],vis=x.visual==='line'?`<div class="numberline"><b>青：x &gt; 3　橙：x &gt; 5</b><div class="line"><i class="range q"></i><i class="range p"></i><i class="mark" style="left:28%"><span>3</span></i><i class="mark" style="left:55%"><span>5</span></i></div>小さい範囲（橙）は大きい範囲（青）に含まれます。</div>`:x.visual==='tri'?`<div class="triangles"><div><div class="tri"></div><p>正三角形</p></div><div><div class="tri iso"></div><p>二等辺三角形（反例）</p></div></div>`:'';panel(`<p class="kicker">生活の話と数学は同じ考え方です</p><span class="counter">数学問題 ${mathI+1} / 5</span><h2>${x.title}</h2>${pqCards(x.p,x.q)}${vis}<p class="lead">「必ず成り立つ」向きを1つずつ判定しよう。</p><div class="choices"><button data-m="pq">P → Q を判定</button><button data-m="qp">Q → P を判定</button></div><div id="feedback"></div>`);let answers={};document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{let d=b.dataset.m,val=d==='pq'?x.pq:x.qp;answers[d]=true;b.disabled=true;b.textContent+=(val?'：○ 成立':'：× 不成立');document.querySelector('#feedback').innerHTML=`<div class="result ${val?'correct':'wrong'}">${val?'○ 成り立つ！':'× 必ずそうなるとは限らない'}</div>${!val?`<div class="reveal counterexample">${x.counter}</div>`:''}`;if(answers.pq&&answers.qp)document.querySelector('#feedback').innerHTML+=`${x.pq&&!x.qp?conditionResult():`<div class="result correct">P ⇔ Q<br>これは必要十分条件</div>`}<button id="mathNext" class="action">${mathI<4?'次の数学問題':'集合との関係へ'}</button>`,document.querySelector('#mathNext').onclick=()=>{mathI<4?(mathI++,renderMath()):(screen++,render())}})}
function renderSet(){panel(`<p class="kicker">集合で見ると、もっとはっきり</p><h1>小さい集合 → 大きい集合</h1><div class="visual"><div class="venn"><span>Q：偶数</span><div class="inner">P：4の倍数<br>4, 8, 12…</div></div></div><p class="big-question">P ⊂ Q　ならば　P → Q</p><div class="reveal">4の倍数を1つ選ぶと、必ず外側の「偶数」の集合にも入っています。だから「4の倍数 → 偶数」です。</div>`)}
function renderSummary(){panel(`<p class="kicker">STEP 6　まとめ</p><h1>迷ったら、この2つを確認！</h1><div class="meaning"><div class="enough"><b>① PならQと言える？</b>成立ならPは十分条件</div><span class="or">⇄</span><div class="need"><b>② QならPと言える？</b>成立ならPは必要条件</div></div>${pqCards('Qの十分条件','Pの必要条件','→',true)}<div class="reveal"><b>必要条件：</b>それがないと成立しない<br><b>十分条件：</b>それだけあれば成立する<br><br><b>P → Q かつ Q → P</b> なら <b>P ⇔ Q</b>。PとQは「必要十分条件」です。</div>`)}
function renderFinal(){if(finalI>=5){let msg=score>=4?'よく理解できています！':score>=2?'矢印の向きをもう一度確認しよう':'生活の例からもう一度確認してみよう';return panel(`<p class="kicker">学習完了</p><div class="score">${score} / 5</div><h1 style="text-align:center">${msg}</h1><div class="choices"><button id="retry">もう一度挑戦する</button><button id="restart">最初から学習する</button></div>`),document.querySelector('#retry').onclick=()=>{finalI=score=0;renderFinal()},document.querySelector('#restart').onclick=()=>{screen=lifeI=dailyI=mathI=finalI=score=0;render()};}let q=finalQs[finalI];panel(`<span class="counter">最終確認 ${finalI+1} / 5</span><h2>${q[0]}</h2><p class="big-question">PはQの何条件？</p><div class="quiz-grid choices">${['必要条件','十分条件','必要十分条件','どちらでもない'].map(a=>`<button data-f="${a}">${a}</button>`).join('')}</div><div id="feedback"></div>`);document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{let ok=b.dataset.f===q[1];if(ok)score++;document.querySelectorAll('[data-f]').forEach(x=>x.disabled=true);document.querySelector('#feedback').innerHTML=`<div class="result ${ok?'correct':'wrong'}">${ok?'○ 正解':'× 正解は「'+q[1]+'」'}</div><button id="finalNext" class="action">${finalI===4?'結果を見る':'次の問題'}</button>`;document.querySelector('#finalNext').onclick=()=>{finalI++;renderFinal()}})}
prev.onclick=()=>{if(screen>0){screen--;render()}};next.onclick=()=>{if(screen<6){screen++;render()}};document.querySelector('#memo').onclick=e=>{let m=document.querySelector('#memory');m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',m.classList.contains('open'))};render();
