import { Canvas, useThree } from '@react-three/fiber'
import { Html, Line, OrbitControls } from '@react-three/drei'
import { Component, Suspense, useEffect, useMemo, useRef, useState, type ErrorInfo, type ReactNode } from 'react'
import katex from 'katex'
import { BookOpen, Eye, Home, Pause, Play, Settings2, Sparkles, X } from 'lucide-react'
import type { OrbitControls as OrbitControlsImpl } from 'three-stdlib'
import { polynomial, polynomialCritical, polynomialDerivative, polynomialSign, TAU, trigonometric, trigonometricCritical, getTrigonometricSnapshot, trigonometricDerivative, trigonometricIntervals, trigonometricSign, type DerivativeState, type TrigonometricSnapshot, type Sign } from './math'

const color = { positive: '#25e6b3', negative: '#ff5e72', gold: '#ffd166', ink: '#eaf6ff' }
const near = (a:number,b:number,e=.035)=>Math.abs(a-b)<e
const clamp = (n:number,a:number,b:number)=>Math.max(a,Math.min(b,n))
function MathText({children,block=false}:{children:string,block?:boolean}){return <span className="math" dangerouslySetInnerHTML={{__html:katex.renderToString(children,{throwOnError:false,displayMode:block})}}/>}
const signClass=(s:Sign)=>s==='＋'?'positive':s==='−'?'negative':'zero'

class LabErrorBoundary extends Component<{children:ReactNode,message:string},{hasError:boolean}> {
 state={hasError:false}
 static getDerivedStateFromError(){return{hasError:true}}
 componentDidCatch(error:Error,info:ErrorInfo){console.error(error,info.componentStack)}
 render(){return this.state.hasError?<section className="card error-fallback" role="alert"><h2>{this.props.message}</h2><button className="primary" onClick={()=>this.setState({hasError:false})}>再試行</button></section>:this.props.children}
}

function Plot({fn,df,x,range,yRange,label,onX,reveal=false,critical=[],state,segments=[],ticks=[]}:{fn:(x:number)=>number,df:(x:number)=>number,x:number,range:[number,number],yRange:[number,number],label:string,onX:(x:number)=>void,reveal?:boolean,critical?:readonly number[],state?:DerivativeState,segments?:readonly {start:number,end:number,state:DerivativeState}[],ticks?:{x:number,label:string}[]}){
 const [a,b]=range,[lo,hi]=yRange,W=640,H=300,pad=42; const sx=(v:number)=>pad+(v-a)/(b-a)*(W-pad*1.5),sy=(v:number)=>H-pad-(v-lo)/(hi-lo)*(H-pad*1.5)
 const samples=useMemo(()=>Array.from({length:241},(_,i)=>{const t=a+(b-a)*i/240;return{x:t,point:`${sx(t)},${sy(clamp(fn(t),lo-2,hi+2))}`}}),[fn,a,b,lo,hi]); const y=fn(x),d=df(x),visualState=state??(Math.abs(d)<.04?'zero':d>0?'positive':'negative'); const drag=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();onX(clamp(a+((e.clientX-r.left)/r.width)*(b-a),a,b));e.currentTarget.setPointerCapture(e.pointerId)}
 return <svg className="plot" viewBox={`0 0 ${W} ${H}`} onPointerDown={drag} onPointerMove={e=>e.buttons&&drag(e)} role="img" aria-label={`${label}の動的グラフ`}><path className="axis" d={`M${pad} ${sy(0)}H${W-16}M${sx(0)} 16V${H-pad}`}/>{critical.map(c=><line key={`guide-${c}`} className="critical-guide" x1={sx(c)} x2={sx(c)} y1="16" y2={H-pad}/>)}{segments.length?segments.map(({start,end,state:segmentState})=><polyline key={start} className={`curve segment ${segmentState}`} points={samples.filter(q=>q.x>=start-.001&&q.x<=end+.001).map(q=>q.point).join(' ')}/>):<polyline className="curve" points={samples.map(q=>q.point).join(' ')}/>} {reveal&&critical.map(c=><g key={c} className="extreme"><circle cx={sx(c)} cy={sy(fn(c))} r="10"/><circle cx={sx(c)} cy={sy(fn(c))} r="18" className="ring"/></g>)}{label==='f(x)'&&<line className={`tangent ${visualState}`} x1={sx(x-(b-a)*.09)} y1={sy(y-d*(b-a)*.09)} x2={sx(x+(b-a)*.09)} y2={sy(y+d*(b-a)*.09)}/>}<line className={`guide current-guide ${visualState}`} x1={sx(x)} x2={sx(x)} y1="16" y2={H-pad}/><circle className={`moving ${visualState}`} cx={sx(x)} cy={sy(y)} r="8"/><text x="12" y="24">{label}</text><text x={W-35} y={sy(0)-8}>x</text>{ticks.map(t=><g key={t.label}><line className="tick" x1={sx(t.x)} x2={sx(t.x)} y1={sy(0)-4} y2={sy(0)+4}/><text className="tick-label" x={sx(t.x)} y={H-14}>{t.label}</text></g>)}</svg>
}

function SignLine({type,x,onX,state}:{type:'poly'|'trig',x:number,onX:(x:number)=>void,state?:DerivativeState}){const poly=type==='poly',bounds=poly?[-3,-1,0,2,3]:[0,Math.PI/6,5*Math.PI/6,TAU], signs:Sign[]=poly?['−','＋','−','＋']:['＋','−','＋']; const labels=poly?['−3','−1','0','2','3']:['0','π/6','5π/6','2π'];return <div className="sign-line" aria-label="導関数の符号数直線">{signs.map((s,i)=><button key={i} className={signClass(s)} onClick={()=>onX((bounds[i]+bounds[i+1])/2)}><b>{s}</b><small>{s==='＋'?'増加':'減少'}</small></button>)}<i className={state} style={{left:`${(x-bounds[0])/(bounds.at(-1)!-bounds[0])*100}%`}}/>{labels.map((l,i)=><span key={l} style={{left:`${i/(labels.length-1)*100}%`}}>{l}</span>)}</div>}

function FillTable({type,onCorrect}:{type:'poly'|'trig',onCorrect:()=>void}){const answer:Sign[]=type==='poly'?['−','0','＋','0','−','0','＋']:['＋','0','−','0','＋'];const [cells,setCells]=useState<(Sign|'')[]>(answer.map(()=>''));const [pick,setPick]=useState<Sign>('＋');const good=cells.every((v,i)=>v===answer[i]);useEffect(()=>{if(good)onCorrect()},[good,onCorrect]);return <section className="card table-card"><div className="section-title"><span>TRY</span><h3>増減表を完成しよう</h3></div><p>記号を選び、空欄をタップ（記号はドラッグもできます）。</p><div className="tokens">{(['＋','−','0'] as Sign[]).map(s=><button key={s} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',s)} onClick={()=>setPick(s)} className={pick===s?'selected':''}>{s}</button>)}</div><div className="variation"><b>f′(x)</b>{cells.map((v,i)=><button key={i} onClick={()=>setCells(c=>c.map((q,j)=>j===i?pick:q))} onDrop={e=>{e.preventDefault();const s=e.dataTransfer.getData('text/plain') as Sign;setCells(c=>c.map((q,j)=>j===i?s:q))}} onDragOver={e=>e.preventDefault()}>{v||'?'}</button>)}</div><div className="flow">f(x)　{type==='poly'?'↘　極小　↗　極大　↘　極小　↗':'↗　極大　↘　極小　↗'}</div><output className={good?'success':''}>{good?'正解！ グラフの増減と符号がつながりました。':'導関数の符号を置いてみよう'}</output></section>}

function Derivation({type,reveal}:{type:'poly'|'trig',reveal:boolean}){return <section className="card derivation"><div className="section-title"><span>STEP 3</span><h3>項ごとに微分する</h3></div>{type==='poly'?<><div className="term-row"><MathText>{'3x^4\\;\\longrightarrow\\;12x^3'}</MathText><MathText>{'-4x^3\\;\\longrightarrow\\;-12x^2'}</MathText><MathText>{'-12x^2\\;\\longrightarrow\\;-24x'}</MathText><MathText>{'1\\;\\longrightarrow\\;0'}</MathText></div><div className="answer"><MathText block>{"f'(x)=12x^3-12x^2-24x=12x(x-2)(x+1)"}</MathText></div><MathText block>{"12x(x-2)(x+1)=0\\;\\Longrightarrow\\;x=-1,0,2"}</MathText><p className="question">この3点の前後で符号はどうなる？</p></>:<><div className="term-row"><MathText>{'x\\;\\longrightarrow\\;1'}</MathText><MathText>{'2\\cos x\\;\\longrightarrow\\;-2\\sin x'}</MathText></div><div className="answer"><MathText block>{"f'(x)=1-2\\sin x"}</MathText></div><MathText block>{"1-2\\sin x=0\\;\\Longrightarrow\\;\\sin x=\\frac12"}</MathText><p className="question">sin x = 1/2 は単位円のどこ？</p>{reveal&&<MathText block>{'x=\\frac{\\pi}{6},\\;\\frac{5\\pi}{6}'}</MathText>}</>}</section>}

function UnitCircle({x,onX,reveal,state}:{x:number,onX:(x:number)=>void,reveal:boolean,state:DerivativeState}){const cx=150,cy=145,r=105,qx=cx+r*Math.cos(x),qy=cy-r*Math.sin(x);const choose=(e:React.PointerEvent<SVGSVGElement>)=>{const b=e.currentTarget.getBoundingClientRect(),xx=(e.clientX-b.left)/b.width*320-cx,yy=cy-(e.clientY-b.top)/b.height*300;onX((Math.atan2(yy,xx)+TAU)%TAU)};return <div className="circle-box"><svg viewBox="0 0 320 300" onPointerDown={choose} role="img" aria-label="ドラッグできる単位円"><path className="circle-arc positive-stroke" d="M241 197.5 A105 105 0 0 1 241 92.5"/><path className="circle-arc negative-stroke" d="M241 92.5 A105 105 0 0 0 59 92.5"/><path className="circle-arc positive-stroke" d="M59 92.5 A105 105 0 1 0 241 197.5"/><path className="axis" d="M24 145H286M150 18V274"/><line className="half" x1="35" y1={cy-r/2} x2="266" y2={cy-r/2}/><line className="radius" x1={cx} y1={cy} x2={qx} y2={qy}/><line className="projection" x1={qx} y1={cy} x2={qx} y2={qy}/><line className={`sine-height ${state}`} x1={cx} y1={qy} x2={qx} y2={qy}/><text className="sine-label" x={cx+5} y={qy-7}>y = sin x</text><circle className={`moving ${state}`} cx={qx} cy={qy} r="9"/><text x={qx+9} y={qy-9}>Q</text><text x="270" y={cy-r/2-6}>y=1/2</text>{trigonometricCritical.map((a,i)=><g className="extreme" key={a}><circle cx={cx+r*Math.cos(a)} cy={cy-r*Math.sin(a)} r="8"/><circle className="ring" cx={cx+r*Math.cos(a)} cy={cy-r*Math.sin(a)} r="15"/>{reveal&&<text x={i?42:235} y="76">{i?'5π/6':'π/6'}</text>}</g>)}</svg><div className="live-values"><MathText>{`x=${x.toFixed(2)}`}</MathText><MathText>{`\\sin x=${Math.sin(x).toFixed(3)}`}</MathText><MathText>{`2\\sin x=${(2*Math.sin(x)).toFixed(3)}`}</MathText><MathText>{`f'(x)=${trigonometricDerivative(x).toFixed(3)}`}</MathText></div></div>}
function CameraRig({view}:{view:string}){const{camera}=useThree();useEffect(()=>{camera.position.set(...(view==='front'?[0,2,12]:view==='side'?[12,2,0]:[8,7,10]) as [number,number,number]);camera.lookAt(0,0,0)},[view,camera]);return null}
function Explore3D({type,x,state}:{type:'poly'|'trig',x:number,state?:DerivativeState}){const controls=useRef<OrbitControlsImpl>(null),[view,setView]=useState('angle');const poly=type==='poly',range=poly?[-3,3]:[0,TAU];const scaleX=(v:number)=>(v-range[0])/(range[1]-range[0])*7-3.5;const sample=(fn:(n:number)=>number,z:number,scale:number)=>Array.from({length:100},(_,i)=>{const a=range[0]+(range[1]-range[0])*i/99;return[scaleX(a),clamp(fn(a)*scale,-2.2,2.2),z] as [number,number,number]});const fn=poly?polynomial:trigonometric,df=poly?polynomialDerivative:trigonometricDerivative,crit=poly?polynomialCritical:trigonometricCritical;return <section className="card three"><div className="section-title"><span>3D</span><h3>同じ x を光で結ぶ</h3></div><div className="scene"><Suspense fallback={<div className="fallback">3Dを読み込み中…（2D教材は操作できます）</div>}><Canvas camera={{position:[8,7,10],fov:45}}><color attach="background" args={['#050b15']}/><ambientLight intensity={1.2}/><pointLight position={[2,5,4]} intensity={22}/><gridHelper args={[10,10,'#294861','#152637']} rotation={[Math.PI/2,0,0]}/><Line points={sample(fn,-2,poly?.05:.35)} color="#72a9ff" lineWidth={3}/><Line points={sample(df,0,poly?.018:.45)} color="#25e6b3" lineWidth={3}/><Line points={[[-3.5,0,2],[3.5,0,2]]} color="#dcecff" lineWidth={2}/><Line points={[[scaleX(x),-2.3,-2],[scaleX(x),2.3,2]]} color={state==='negative'?'#ff5e72':state==='positive'?'#25e6b3':'#ffd166'} lineWidth={3}/>{crit.map(c=><Line key={c} points={[[scaleX(c),-2.3,-2.4],[scaleX(c),2.3,2.4]]} color="#ffd166" lineWidth={2}/>)}<Html position={[-4,2,-2]}><span className="scene-label">f(x) / 手前</span></Html><Html position={[-4,2,0]}><span className="scene-label">f′(x) / 中央</span></Html><Html position={[-4,.5,2]}><span className="scene-label">{poly?'符号数直線 / 奥':'単位円・角度 / 奥'}</span></Html><OrbitControls ref={controls} enablePan={false}/><CameraRig view={view}/></Canvas></Suspense></div><div className="view-buttons"><button onClick={()=>setView('front')}>正面</button><button onClick={()=>setView('angle')}>斜め上</button><button onClick={()=>setView('side')}>真横</button><button onClick={()=>{setView('angle');controls.current?.reset()}}>リセット</button></div><p>ドラッグ／タッチで回転、ホイール／ピンチでズーム。光線が導関数・接線・元の関数を結びます。</p></section>}
function SafeExplore3D(props:Parameters<typeof Explore3D>[0]){return <LabErrorBoundary message="3D表示中にエラーが発生しました"><Explore3D {...props}/></LabErrorBoundary>}

const inquiries=['極値では接線は必ず水平になる？','f′(x)=0なら必ず極値？','f′(x)が正のとき、元の関数はどうなる？','f′(x)が負のときは？','＋→−では何が起こる？','−→＋では何が起こる？','問題2では、なぜ単位円を見るとf′(x)の符号が分かる？','|x|はx=0で微分できないのに、なぜ極小になる？']
function Inquiry(){return <section className="inquiry"><span>THINK</span><h2>探究問題</h2><div>{inquiries.map((q,i)=><details key={q}><summary>Q{i+1}　{q}</summary><p>{['いいえ。微分できない極値では水平な接線がないこともあります。','いいえ。前後で符号が変わるかを確かめます。','増加します。','減少します。','増加から減少へ変わり、極大が生まれます。','減少から増加へ変わり、極小が生まれます。','単位円上の高さ sin x と 1/2 を比べれば、1−2sin x の正負が分かるからです。','左で減少、右で増加し、0が周囲で最も小さいからです。'][i]}</p></details>)}</div></section>}

function Teacher({open,setOpen,reveal,setReveal,glow,setGlow,paused,setPaused,x,setX,range}:{open:boolean,setOpen:(v:boolean)=>void,reveal:boolean,setReveal:(v:boolean)=>void,glow:boolean,setGlow:(v:boolean)=>void,paused:boolean,setPaused:(v:boolean)=>void,x:number,setX:(v:number)=>void,range:[number,number]}){return <>{<button className="teacher-open" onClick={()=>setOpen(true)}><Settings2/>教師モード</button>}{open&&<aside className="teacher"><button className="close" onClick={()=>setOpen(false)} aria-label="閉じる"><X/></button><h2>教師モード</h2><p>授業中の表示を一括制御できます。</p><label><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/> 解答・増減表・極値・導関数・単位円・接線・符号を表示</label><label><input type="checkbox" checked={glow} onChange={e=>setGlow(e.target.checked)}/> 発光 ON</label><label><input type="checkbox" checked={paused} onChange={e=>setPaused(e.target.checked)}/> アニメーション停止</label><label>任意の x へ移動<input type="number" value={x.toFixed(2)} min={range[0]} max={range[1]} step=".05" onChange={e=>setX(clamp(Number(e.target.value),...range))}/></label><button className="answer-all" onClick={()=>setReveal(true)}><Eye/> 解答をすべて表示</button></aside>}</>}

function PolynomialLab({teacherReveal,setTeacherState}:{teacherReveal:boolean,setTeacherState:(v:{x:number,setX:(n:number)=>void,range:[number,number],play:()=>void})=>void}){const[x,setX]=useState(-2.5),[reveal,setReveal]=useState(false),[playing,setPlaying]=useState(false),[tableGlow,setTableGlow]=useState(false);useEffect(()=>setTeacherState({x,setX,range:[-3,3],play:()=>setPlaying(p=>!p)}),[x,setTeacherState]);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setX(v=>v>=3?(setPlaying(false),-3):v+.025),24);return()=>clearInterval(id)},[playing]);const d=polynomialDerivative(x),s=polynomialSign(x),at=polynomialCritical.find(c=>near(x,c,.04));return <><section className="hero-card"><div><span>PROBLEM 01 / POLYNOMIAL</span><h2>多項式の極値</h2><MathText block>{'f(x)=3x^4-4x^3-12x^2+1'}</MathText><p className="question">どこで増加と減少が入れ替わっていそう？</p></div><div className={`status ${signClass(s)}`}><small>いまの動き</small><b>{s==='＋'?'増加中 ↑':s==='−'?'減少中 ↓':'傾き 0'}</b><MathText>{`f'(x)=${d.toFixed(2)}`}</MathText></div></section><section className={`card graph-card ${tableGlow?'lit':''}`}><div className="section-title"><span>STEP 1–2</span><h3>動点 P と接線を動かす</h3></div><Plot fn={polynomial} df={polynomialDerivative} x={x} range={[-3,3]} yRange={[-36,30]} label="f(x)" onX={setX} reveal={reveal||teacherReveal} critical={polynomialCritical}/><input aria-label="多項式のx" type="range" min="-3" max="3" step=".005" value={x} onChange={e=>setX(+e.target.value)}/><div className="readout"><MathText>{`x=${x.toFixed(2)}`}</MathText><MathText>{`f(x)=${polynomial(x).toFixed(2)}`}</MathText><b className={signClass(s)}>符号 {s}</b></div><SignLine type="poly" x={x} onX={setX}/>{at!==undefined&&<div className="discovery"><Sparkles/><b>{at===0?'＋ → 0 → −　極大！':'− → 0 → ＋　極小！'}</b><span>({at}, {polynomial(at)})</span></div>}<button className="primary" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?'一時停止':'増減を再生'}</button></section><Derivation type="poly" reveal={reveal}/><section className="card sign-analysis"><div className="section-title"><span>STEP 4</span><h3>因数ごとの符号を調べる</h3></div><p>数直線の区間をタップすると、その区間の代表点へ移動します。</p><div className="factor-grid"><span>12x：{polynomialSign(x)==='0'?'0':x>0?'＋':'−'}</span><span>x−2：{near(x,2)?'0':x>2?'＋':'−'}</span><span>x＋1：{near(x,-1)?'0':x>-1?'＋':'−'}</span><b>したがって f′(x)：{s}</b></div></section><FillTable type="poly" onCorrect={()=>{setTableGlow(true);setReveal(true)}}/><button className="reveal" onClick={()=>setReveal(!reveal)}>{reveal?'極値を隠す':'極値を発見する'}</button><SafeExplore3D type="poly" x={x}/></>}
const trigTicks=[{x:0,label:'0'},{x:Math.PI/6,label:'π/6'},{x:Math.PI/2,label:'π/2'},{x:5*Math.PI/6,label:'5π/6'},{x:Math.PI,label:'π'},{x:3*Math.PI/2,label:'3π/2'},{x:TAU,label:'2π'}]
function CurrentValueCard({snapshot}:{snapshot:TrigonometricSnapshot}){const{x,sine,twiceSine,derivative,state,movement,comparison}=snapshot;return <aside className={`current-card ${state}`} aria-live="polite"><div><small>現在</small><b>x = {x.toFixed(2)}</b></div><div><span>sin x</span><b>{sine.toFixed(3)}</b></div><div><span>2 sin x</span><b>{twiceSine.toFixed(3)}</b></div><div><span>f′(x)</span><b>{derivative.toFixed(3)}</b></div><div className="current-conclusion"><b>f′(x) {state==='zero'?'＝':state==='positive'?'>':'<'} 0</b><strong>したがって f(x) は{movement}</strong></div><div className="logic-flow">{comparison==='equal'?<>sin x ＝ 1/2　→　f′(x) ＝ 0</>:comparison==='above'?<>sin x &gt; 1/2　→　2 sin x &gt; 1　→　1−2 sin x &lt; 0　→　f′(x)&lt;0　→　減少</>:<>sin x &lt; 1/2　→　f′(x)&gt;0　→　増加</>}</div></aside>}
function TrigLab({teacherReveal,setTeacherState}:{teacherReveal:boolean,setTeacherState:(v:{x:number,setX:(n:number)=>void,range:[number,number],play:()=>void})=>void}){
 const[x,setX]=useState(.15),[reveal,setReveal]=useState(false),[playing,setPlaying]=useState(false),[tableGlow,setTableGlow]=useState(false)
 useEffect(()=>setTeacherState({x,setX,range:[0,TAU],play:()=>setPlaying(p=>!p)}),[x,setTeacherState])
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setX(v=>v>=TAU?(setPlaying(false),0):v+.025),24);return()=>clearInterval(id)},[playing])
 const snapshot=getTrigonometricSnapshot(x),{derivative,state}=snapshot,s:Sign=state==='zero'?'0':state==='positive'?'＋':'−';const at=snapshot.extremum==='maximum'?trigonometricCritical[0]:snapshot.extremum==='minimum'?trigonometricCritical[1]:undefined
 return <><section className="hero-card"><div><span>PROBLEM 02 / TRIGONOMETRIC</span><h2>三角関数の極値</h2><MathText block>{'f(x)=x+2\\cos x\\quad(0\\leq x\\leq2\\pi)'}</MathText><p className="question">どのあたりで傾きが 0 になる？</p></div><div className={`status ${state}`}><small>導関数の符号</small><b>{s}　{state==='positive'?'増加':state==='negative'?'減少':'傾き0'}</b><MathText>{`f'(x)=${derivative.toFixed(3)}`}</MathText></div></section><Derivation type="trig" reveal={reveal||teacherReveal}/><section className={`card connection ${tableGlow?'lit':''}`}><div className="section-title"><span>SYNC MODE</span><h3>全部つなげて見る</h3></div><p>単位円 → sin x → f′(x) → 接線の傾き → f(x) の増減を、1本のスライダーと1つの数学的状態で同期します。</p><div className="triple"><div><h4>単位円</h4><UnitCircle x={x} onX={setX} reveal={reveal||teacherReveal} state={state}/></div><div><h4>導関数 y = 1 − 2 sin x</h4><Plot fn={trigonometricDerivative} df={()=>0} x={x} range={[0,TAU]} yRange={[-1.3,3.3]} label="f′(x)" onX={setX} reveal={reveal} critical={trigonometricCritical} state={state} segments={trigonometricIntervals} ticks={trigTicks}/></div><div><h4>元の関数と接線</h4><Plot fn={trigonometric} df={trigonometricDerivative} x={x} range={[0,TAU]} yRange={[-.2,7]} label="f(x)" onX={setX} reveal={reveal||teacherReveal} critical={trigonometricCritical} state={state} segments={trigonometricIntervals} ticks={trigTicks}/></div></div><CurrentValueCard snapshot={snapshot}/><input aria-label="角度x" type="range" min="0" max={TAU} step=".0005" value={x} onChange={e=>setX(+e.target.value)}/><SignLine type="trig" x={x} onX={setX} state={state}/>{at!==undefined&&<div className="discovery"><Sparkles/><b>{near(at,trigonometricCritical[0])?'f′(x)：＋ → 0 → −　増加 → 減少　極大！':'f′(x)：− → 0 → ＋　減少 → 増加　極小！'}</b><MathText>{near(at,trigonometricCritical[0])?'\\frac{\\pi}{6}+\\sqrt3':'\\frac{5\\pi}{6}-\\sqrt3'}</MathText></div>}<div className="actions"><button className="primary" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?'一時停止':'増減を再生'}</button><button onClick={()=>setReveal(!reveal)}><Eye/>{reveal?'角度名を隠す':'この角度は？'}</button></div></section><FillTable type="trig" onCorrect={()=>{setTableGlow(true);setReveal(true)}}/><section className="card result"><h3>符号変化から得た結論</h3><div><MathText block>{"x=\\frac{\\pi}{6}:\\quad +\\to0\\to-\\quad \\text{極大値 }\\frac{\\pi}{6}+\\sqrt3"}</MathText><MathText block>{"x=\\frac{5\\pi}{6}:\\quad -\\to0\\to+\\quad \\text{極小値 }\\frac{5\\pi}{6}-\\sqrt3"}</MathText></div></section><SafeExplore3D type="trig" x={x} state={state}/></>
}

function AbsoluteLab({setTeacherState}:{setTeacherState:(v:{x:number,setX:(n:number)=>void,range:[number,number],play:()=>void})=>void}){const[x,setX]=useState(-1.6);useEffect(()=>setTeacherState({x,setX,range:[-2,2],play:()=>{}}),[x,setTeacherState]);const at=near(x,0,.035),s=x<0?'−':x>0?'＋':'0';return <><section className="hero-card"><div><span>EXTENSION / NON-DIFFERENTIABLE</span><h2>微分できない極値</h2><MathText block>{'g(x)=|x|'}</MathText><p className="question">極値をとる点では必ず f′(x)=0 になる？</p></div><div className={`status ${at?'zero':x<0?'negative':'positive'}`}><small>点 P での傾き</small><b>{at?'微分不可':x<0?'−1　減少':'＋1　増加'}</b></div></section><section className="card graph-card"><Plot fn={Math.abs} df={(v)=>v<0?-1:v>0?1:0} x={x} range={[-2,2]} yRange={[-.5,2.3]} label="g(x)=|x|" onX={setX} reveal critical={[0]}/><input aria-label="絶対値のx" type="range" min="-2" max="2" step=".005" value={x} onChange={e=>setX(+e.target.value)}/><div className="split-slopes"><span>左側の傾き <b>−1（赤）</b> → 減少</span><span>右側の傾き <b>＋1（青緑）</b> → 増加</span></div>{at&&<div className="discovery"><Sparkles/><b>左側と右側の傾きが一致しない → 微分不可</b><span>それでも「減少 → 増加」なので x=0 で極小値 0</span></div>}</section><section className="core-message"><Sparkles/><h2>f′(x)=0 は極値を探す重要な手掛かり。<br/>しかし、極値かどうかは前後の増減を確認する。</h2><p>微分できない点でも極値になることがある</p></section></>}

export default function App(){const[tab,setTab]=useState<'poly'|'trig'|'abs'>('poly'),[teacherOpen,setTeacherOpen]=useState(false),[teacherReveal,setTeacherReveal]=useState(false),[glow,setGlow]=useState(true),[paused,setPaused]=useState(false),[teacherState,setTeacherState]=useState<{x:number,setX:(n:number)=>void,range:[number,number],play:()=>void}>({x:0,setX:()=>{},range:[-3,3],play:()=>{}});return <div className={`lab ${glow?'glow':'no-glow'} ${paused?'paused':''}`}><header><a href="../../" className="back"><Home/>教材一覧</a><div className="eyebrow"><BookOpen/> MATHEMATICS III / EXTREMA LAB</div><h1>極値はどこで生まれる？</h1><p>極値を「導関数の符号」から発見する</p><nav aria-label="問題を選ぶ">{([['poly','① 多項式の極値'],['trig','② 三角関数の極値'],['abs','③ 微分できない極値']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav></header><main>{tab==='poly'?<PolynomialLab teacherReveal={teacherReveal} setTeacherState={setTeacherState}/>:tab==='trig'?<LabErrorBoundary message="三角関数教材の表示中にエラーが発生しました"><TrigLab teacherReveal={teacherReveal} setTeacherState={setTeacherState}/></LabErrorBoundary>:<AbsoluteLab setTeacherState={setTeacherState}/>}<Inquiry/></main><Teacher open={teacherOpen} setOpen={setTeacherOpen} reveal={teacherReveal} setReveal={setTeacherReveal} glow={glow} setGlow={setGlow} paused={paused} setPaused={setPaused} {...teacherState}/><footer><b>極値の本質は「0」ではなく、前後の符号変化。</b><span>＋ → −：極大　/　− → ＋：極小</span></footer></div>}
