const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={x:-3,a:2,reveal:0}; let playing=false;
const f=(x,a=state.a)=>Math.exp(-a*x*x), fp=(x,a=state.a)=>-2*a*x*f(x,a), fpp=(x,a=state.a)=>2*a*(2*a*x*x-1)*f(x,a);
const fmt=n=>Math.abs(n)<.00005?'0.000':n.toFixed(3);
function setupCanvas(c){const d=devicePixelRatio||1,w=c.clientWidth,h=Math.max(235,c.clientHeight);c.width=w*d;c.height=h*d;const q=c.getContext('2d');q.scale(d,d);return{q,w,h}}
function axes(q,w,h,ymin=-.25,ymax=1.2){const X=x=>(x+3)/6*w,Y=y=>h-(y-ymin)/(ymax-ymin)*h;q.clearRect(0,0,w,h);q.fillStyle='#081827';q.fillRect(0,0,w,h);q.strokeStyle='#29445d';q.lineWidth=1;for(let x=-3;x<=3;x++){q.beginPath();q.moveTo(X(x),0);q.lineTo(X(x),h);q.stroke()}q.beginPath();for(let y=Math.ceil(ymin*2)/2;y<=ymax;y+=.5){q.moveTo(0,Y(y));q.lineTo(w,Y(y))}q.stroke();q.strokeStyle='#90a7bb';q.beginPath();q.moveTo(0,Y(0));q.lineTo(w,Y(0));q.moveTo(X(0),0);q.lineTo(X(0),h);q.stroke();q.fillStyle='#9db1c2';q.font='11px sans-serif';for(let x=-3;x<=3;x++)q.fillText(x,X(x)+3,Y(0)+14);return{X,Y}}
function curve(q,X,Y,fn,color,from=3){q.strokeStyle=color;q.lineWidth=3;q.beginPath();for(let i=0;i<=400;i++){const x=-3+6*i/400;if(x>from)break;const y=fn(x);i?q.lineTo(X(x),Y(y)):q.moveTo(X(x),Y(y))}q.stroke()}
function point(q,X,Y,x,y,color='#f2c75c',r=6){q.save();q.shadowBlur=16;q.shadowColor=color;q.fillStyle=color;q.beginPath();q.arc(X(x),Y(y),r,0,7);q.fill();q.restore()}
function drawMain(id,opts={}){const c=$('#'+id);if(!c)return;const {q,w,h}=setupCanvas(c),{X,Y}=axes(q,w,h,opts.ymin??-.18,opts.ymax??1.18);if(opts.bands){q.fillStyle='#399ee818';q.fillRect(0,Y(.05),X(-.5),18);q.fillRect(X(.5),Y(.05),w-X(.5),18);q.fillStyle='#e75b6420';q.fillRect(X(-.5),Y(.05),X(.5)-X(-.5),18)}curve(q,X,Y,opts.fn||f,opts.color||'#f1f5f9',opts.trace?state.x:3);if(opts.guides){[-.5,.5].forEach(x=>{q.setLineDash([5,5]);q.strokeStyle='#986fe2';q.beginPath();q.moveTo(X(x),0);q.lineTo(X(x),h);q.stroke();q.setLineDash([]);point(q,X,Y,x,f(x),'#986fe2')})}const y=(opts.fn||f)(state.x);q.strokeStyle='#63a3ce88';q.beginPath();q.moveTo(X(state.x),0);q.lineTo(X(state.x),h);q.stroke();point(q,X,Y,state.x,y,opts.color||'#f2c75c');if(opts.symmetry)point(q,X,Y,-state.x,f(-state.x),'#58cdf5',5);if(opts.tangent){const m=fp(state.x),col=Math.abs(m)<.015?'#f2c75c':m>0?'#20aa78':'#e75b64';q.strokeStyle=col;q.lineWidth=3;q.beginPath();q.moveTo(X(state.x-.65),Y(y-m*.65));q.lineTo(X(state.x+.65),Y(y+m*.65));q.stroke();point(q,X,Y,0,1,'#f2c75c',8)}if(opts.minitangents)[-.18,0,.18].forEach(dx=>{const x=state.x+dx,m=fp(x),y=f(x);q.strokeStyle='#72b8eb';q.lineWidth=2;q.beginPath();q.moveTo(X(x-.16),Y(y-m*.16));q.lineTo(X(x+.16),Y(y+m*.16));q.stroke()});if(opts.asymptote){q.strokeStyle='#f39a45';q.lineWidth=4;q.beginPath();q.moveTo(0,Y(0));q.lineTo(w,Y(0));q.stroke()}}
function drawSmall(id,fn,color,ymin,ymax){const c=$('#'+id);if(!c)return;const {q,w,h}=setupCanvas(c),{X,Y}=axes(q,w,h,ymin,ymax);curve(q,X,Y,fn,color);q.strokeStyle='#ffffff55';q.beginPath();q.moveTo(X(state.x),0);q.lineTo(X(state.x),h);q.stroke();point(q,X,Y,state.x,fn(state.x),color)}
function drawComplete(){drawMain('completeGraph',{guides:state.reveal>=5,asymptote:state.reveal>=6});const c=$('#completeGraph');if(!c)return;const {q,w,h}=setupCanvas(c),{X,Y}=axes(q,w,h,-.18,1.18);curve(q,X,Y,f,'#f1f5f9');if(state.reveal>=3)point(q,X,Y,0,1,'#f2c75c',8);if(state.reveal>=5)[-.5,.5].forEach(x=>point(q,X,Y,x,f(x),'#986fe2'));if(state.reveal>=6){q.strokeStyle='#f39a45';q.lineWidth=4;q.beginPath();q.moveTo(0,Y(0));q.lineTo(w,Y(0));q.stroke()}}
function render(){ $$('[data-out=x]').forEach(e=>e.textContent=state.x.toFixed(2));$$('[data-out=f]').forEach(e=>e.textContent=fmt(f(state.x)));$$('[data-out=fp]').forEach(e=>e.textContent=fmt(fp(state.x)));$$('[data-out=fpp]').forEach(e=>e.textContent=fmt(fpp(state.x)));$$('[data-out=move]').forEach(e=>e.textContent=Math.abs(state.x)<.01?'停留（極大）':state.x<0?'増加 ↗':'減少 ↘');$$('[data-out=concavity]').forEach(e=>e.textContent=Math.abs(fpp(state.x))<.01?'変曲':fpp(state.x)>0?'下に凸（y″>0）':'上に凸（y″<0）');$$('.x-range').forEach(e=>{if(document.activeElement!==e)e.value=state.x});const z=state.x<-.5?0:state.x<0?1:state.x<.5?2:3;$$('[data-zone]').forEach(e=>e.classList.toggle('active',+e.dataset.zone===z));drawMain('mainGraph',{trace:true,symmetry:true});drawMain('slopeGraph',{tangent:true});drawMain('curveGraph',{bands:true,guides:true,minitangents:true});drawSmall('fGraph',f,'#f2c75c',-.2,1.2);drawSmall('fpGraph',fp,'#20aa78',-1.8,1.8);drawSmall('fppGraph',fpp,'#399ee8',-4.4,2.2);drawComplete();const pct=(state.x+3)/6*100;$('#beam i').style.left=pct+'%';$('#diffusion').style.filter=`brightness(${.55+.65*f(state.x)})`}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));requestAnimationFrame(()=>{render();if(b.dataset.tab==='threeD')drawSurface()})});
$$('.x-range').forEach(r=>r.oninput=()=>{state.x=+r.value;render()});$$('[data-jump]').forEach(b=>b.onclick=()=>{state.x=+b.dataset.jump;render()});
$('#drawPlay').onclick=()=>{playing=!playing;state.x=-3;const tick=()=>{if(!playing)return;state.x=Math.min(3,state.x+.025);render();if(state.x<3)requestAnimationFrame(tick);else playing=false};tick()};
$('#limitPlay').onclick=()=>{let t=0;const tick=()=>{t+=.025;state.x=3*Math.sin(t);render();if(t<Math.PI*1.5)requestAnimationFrame(tick)};tick()};
$('#reveal').onclick=()=>{state.reveal=Math.min(6,state.reveal+1);$$('#revealList li').forEach((e,i)=>e.classList.toggle('complete-visible',i<state.reveal));drawComplete();$('#reveal').textContent=state.reveal===6?'完成！':'次の根拠を表示'};
$('#aRange').oninput=e=>{state.a=+e.target.value;$('#aOut').textContent=state.a.toFixed(2);$('#aFacts').innerHTML=`f′(x)=−${fmt(2*state.a)}xe<sup>−${state.a.toFixed(2)}x²</sup>　/　変曲点の x座標：±1/√(2a) ≈ ±${(1/Math.sqrt(2*state.a)).toFixed(3)}`;render()};
// Canvas 3D: dependency-free projection with rotation/zoom, and a guaranteed 2D fallback.
let rotX=-.55,rotZ=-.65,zoom=58,drag=null;
function drawSurface(){const c=$('#surface');if(!c)return;try{const {q,w,h}=setupCanvas(c),cx=w/2,cy=h*.62,s=+$('#slice').value;q.fillStyle='#081827';q.fillRect(0,0,w,h);const P=(x,y,z)=>{const X=x*Math.cos(rotZ)-y*Math.sin(rotZ),Y=x*Math.sin(rotZ)+y*Math.cos(rotZ);return[cx+X*zoom,cy+(Y*Math.cos(rotX)-z*2.2*Math.sin(rotX))*zoom]};for(let j=-16;j<=16;j++){q.beginPath();for(let i=-32;i<=32;i++){const x=i/10,y=j/10,z=f(Math.hypot(x,y));const p=P(x,y,z);i===-32?q.moveTo(...p):q.lineTo(...p)}q.strokeStyle=`rgba(57,158,232,${.2+f(Math.abs(j/10))*.45})`;q.stroke()}for(let i=-16;i<=16;i++){q.beginPath();for(let j=-32;j<=32;j++){const x=i/10,y=j/10,z=f(Math.hypot(x,y)),p=P(x,y,z);j===-32?q.moveTo(...p):q.lineTo(...p)}q.strokeStyle='#45b58d55';q.stroke()}if(s>.02){q.lineWidth=3;q.strokeStyle=`rgba(242,199,92,${s})`;q.beginPath();for(let i=-60;i<=60;i++){const x=i/20,p=P(x,0,f(x));i===-60?q.moveTo(...p):q.lineTo(...p)}q.stroke()}$('#fallback').hidden=true}catch(e){$('#fallback').hidden=false}}
$('#surface').onpointerdown=e=>{drag=[e.clientX,e.clientY];e.currentTarget.setPointerCapture(e.pointerId)};$('#surface').onpointermove=e=>{if(!drag)return;rotZ+=(e.clientX-drag[0])*.01;rotX+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];drawSurface()};$('#surface').onpointerup=()=>drag=null;$('#surface').onwheel=e=>{e.preventDefault();zoom=Math.max(30,Math.min(100,zoom-e.deltaY*.08));drawSurface()};$('#slice').oninput=drawSurface;
const quiz=[['1. y′を求める','合成関数の微分を使おう。','y′=−x e<sup>−x²/2</sup>'],['2. y′=0を解く','指数関数は常に正です。','x=0'],['3. 増減を判断','y′の符号を左右で調べよう。','x&lt;0 で増加、x&gt;0 で減少。極大点は (0,1)。'],['4. y″を求める','積の微分を使おう。','y″=(x²−1)e<sup>−x²/2</sup>'],['5. y″=0を解く','x²−1=0 を解こう。','x=±1'],['6. 凹凸を判断','x²−1の符号を区間ごとに調べよう。','|x|&gt;1 で y″&gt;0、|x|&lt;1 で y″&lt;0。変曲点は (±1,e<sup>−1/2</sup>)。'],['7. 極限を調べる','x²が大きくなると指数部は？','x→±∞ で y→0。水平漸近線は y=0。'],['8. グラフを完成','対称性・極大・変曲点・漸近線を重ねよう。','y軸対称で (0,1) が極大。変曲点 (±1,1/√e) を通り、両側で y=0 に近づく。']];let qi=0;function showQuiz(){const q=quiz[qi];$('#quizTitle').textContent=q[0];$('#quizPrompt').textContent='まず自分の言葉・式で考えてから、ヒントや解答を開こう。';$('#quizAnswer').innerHTML='';$('#quizFeedback').textContent='';$$('#quizSteps li').forEach((e,i)=>e.classList.toggle('active',i===qi))}$('#hint').onclick=()=>$('#quizFeedback').textContent=quiz[qi][1];$('#showAnswer').onclick=()=>$('#quizAnswer').innerHTML=quiz[qi][2];$('#quizNext').onclick=()=>{qi=Math.min(7,qi+1);showQuiz()};
addEventListener('resize',()=>{render();drawSurface()});showQuiz();render();
